### ISSUE TITLE
The release scripts of master branch can not work normally

### ISSUE THREAD

**Issue by huangyuqi** [kubernetes/release#1001]
when running `make build-rpms` , some error occurs: 

```
docker run --interactive --tty --rm -v /Users/yuqihuang/Documents/code/src/github.com/kubernetes/release/_output/rpms:/home/builder/rpmbuild/RPMS rpm-builder:200108214554
Building RPM's for amd64.....
sed: can't read /home/builder/workspace/SOURCES/x86_64/kubelet.spec: No such file or directory
make: *** [build-rpms] Error 2
```

Maybe, the path of  file`kubelet.spec` is not set correctly in [script](https://github.com/kubernetes/release/blob/master/build/rpms/build.sh#L45);
When modified  `cp -r "${BUILD_DIR}/SPECS"/* "${SRC_PATH}"` to  `cp -r "${BUILD_DIR}/SPECS"/templates/latest/kubelet/* "${SRC_PATH}"`
we got another error `error: line 2: Tag takes single token only: Version: {{ .Version }}`; 

Need some logic to render the file [`kubelet.spec`](https://github.com/kubernetes/release/blob/master/build/rpms/templates/latest/kubelet/kubelet.spec#L2)?

The release scripts of master branch can not work normally,  is there any plan to fix this or some steps is not declared in readme? 

Thanks ^^

**Comment by justaugustus** [comment]
@huangyuqi -- Thanks for filing this!

The `build-*` make targets are currently broken and the script that they call will not work as intended.
We're in the midst of developing a new go tool, `kubepkg`, which will template spec files and then produce debs or rpms based on the flags you provide.

The initial work for that was recently merged:
- https://github.com/kubernetes/release/pull/935
- https://github.com/kubernetes/release/pull/998

Right now, the only functionality the rpm side provides is templating rpm specs.
From there, you would need to move the specs to the correct locations and run the `rpmbuild` steps yourself.

If that suits your needs for the time being, here's the workflow:

```
Check out kubernetes/release from master
go install ./cmd/kubepkg/...
kubepkg rpms --template-dir build/rpms/templates/latest --spec-only # builds the specs
```

`kubepkg --help` will provide details on the flags you can use.

I can provide usage documentation next week.
In the meantime, if you have questions or feature requests for the tool, please let us know.

/assign
/milestone v1.18
/priority important-soon
/kind bug

**Comment by huangyuqi** [comment]
@justaugustus thanks so much, i will try the new release tools `kubepkg`.
