### ISSUE TITLE
Evaluate mdtoc as replacement for our implementation

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/release#1010]
I recently found out that there is already a markdown TOC generator used in k/enhancements: https://github.com/kubernetes-sigs/mdtoc

We should check if this fits our needs and eventually replace the implementation we currently have.

Any volunteers? :innocent:  (If not I'll do it in the next weeks.)

**Comment by onlydole** [comment]
I'd love to pair on this, if you have time next week or beyond! 
/assign @onlydole

**Comment by justaugustus** [comment]
@tallclair -- There's some buzz for your markdown TOC generator.
Would you have interest in migrating that in as a Kubernetes community project?

**Comment by tallclair** [comment]
Sure! I mostly didn't put it in the Kubernetes org because I couldn't think of a good place for it. Do you have somewhere in mind?

**Comment by justaugustus** [comment]
@tallclair -- we could do k-sigs/mdtoc.

Better yet, k/repo-infra --> https://github.com/kubernetes/repo-infra

**Comment by tallclair** [comment]
OK, I can look into one of those options. I'd sort of prefer a separate repo from repo-infra so it's more easily used outside the k8s project.

In the interim, the tool isn't factored to be useable as a library. If anyone wants to separate out the TOC generation bits from the command portion, please feel free to open a PR against github.com/tallclair/mdtoc

**Comment by xmudrii** [comment]
@saschagrunert @onlydole Are you still interested to work on this issue? Is this issue still relevant?

**Comment by onlydole** [comment]
I’m still interested, @saschagrunert and @xmudrii  🙌🏼

**Comment by xmudrii** [comment]
@onlydole Sounds great. I'll go ahead and remove the `good first issue` and `help-wanted` labels.

/remove-good-first-issue
/remove-help-wanted

**Comment by xmudrii** [comment]
`/remove-help-wanted` didn't work :eyes:

/help-wanted remove

**Comment by xmudrii** [comment]
Will try it for one more time.

/remove-help

**Comment by puerco** [comment]
I can help with this one too

**Comment by saschagrunert** [comment]
I'm wondering where we should move the source code.

**Comment by justaugustus** [comment]
> I'm wondering where we should move the source code.

kubernetes-sigs (ref: https://github.com/kubernetes/release/issues/1010#issuecomment-577459044) --> https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-repo&template=repo-create.md&title=

**Comment by saschagrunert** [comment]
Created the migration request: https://github.com/kubernetes/org/issues/1875

I'm quite not sure about the set of permissions, so feel free to suggest anything :)

**Comment by LappleApple** [comment]
/ good first issue

**Comment by tallclair** [comment]
Note that the repo has been migrated to kubernetes-sigs: https://github.com/kubernetes-sigs/mdtoc

**Comment by saschagrunert** [comment]
@puerco are you working on this one? I'd love to see this issue closed :innocent:

**Comment by puerco** [comment]
Yes im planning on having this closed this weekend
