### ISSUE TITLE
Refactor document rendering code

### ISSUE THREAD

**Issue by j0n3lson** [kubernetes/release#1016]
@hoegaarden pointed an opportunity to refactor in the blow PR:

https://github.com/kubernetes/release/pull/1008#pullrequestreview-341104346

As per that suggestion I think this issue/fix should also cover complete rendering of the document

**Comment by j0n3lson** [comment]
If it's okay I'll be glad to take this up.

**Comment by j0n3lson** [comment]
@saschagrunert  Can you assign this one to me as well.

I'm pretty much almost done with this. In addition to the two PRs above, I have a few pending that will expand test coverage and simplify the rendering code. Once #1019 lands I'll consider this work as done.

Relevant PRs:
https://github.com/kubernetes/release/pull/1154
https://github.com/kubernetes/release/pull/1159
https://github.com/kubernetes/release/pull/1148

**Comment by saschagrunert** [comment]
Alright :)
/assign @j0n3lson

**Comment by saschagrunert** [comment]
We still have some TODO's in the source code left, but I guess we can close this since the markdown rendering is now the standard.

/close
