### ISSUE TITLE
Use templates for changelog (e.g. PR#1008)

### ISSUE THREAD

**Issue by j0n3lson** [kubernetes/release#1019]
Opening this here to discuss whether k/release/cmd/krel should use the same approach as in PR#1008 (e.g. use go-templates).

Both tools do similar things with respect to notes generation/markdown. It would present a common interface for users of either tool

@saschagrunert What do you think?

**Comment by j0n3lson** [comment]
Assuming #1016 move forward, k/release/cmd/krel changelog can take advantage of the new Renderer machinery.

**Comment by j0n3lson** [comment]
@saschagrunert Can you assign this to me please?

**Comment by saschagrunert** [comment]
I thin so:
/assign @j0n3lson

**Comment by saschagrunert** [comment]
/close

This seems to be resolved already.
