### ISSUE TITLE
[krel] Allow krel to interpret an arbitrary k/release git reference instead of just branches (TOOL_BRANCH)

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#1028]
While debugging https://github.com/kubernetes/kubernetes/issues/86182 and https://github.com/kubernetes/release/issues/1020, we ran a few mock stages and releases targeting anago against forks of k/release.

I noticed that it might've been nice to have more information available which fork and commit we were using at any one time, so a few suggestions:

- Allow krel to interpret a git ref (instead of just branch) for use as the release tools repo to checkout (changes to both krel and the `gcb/{stage,release}` configs)
~- Surface the release tool repo org, name, branch (if chosen), and git ref at the time of run as part of the anago session values~

@tpepper -- Thoughts?

/help
/milestone v1.18
/sig release
/area release-eng
/priority important-soon

**Comment by justaugustus** [comment]
Let's consider this an eventual feature request for `krel anago`, not the shell-based tool.
/remove-lifecycle rotten
/milestone clear

**Comment by tpepper** [comment]
This could be emitting more info like `git status` and `cat .git/config` at anago runtime.

**Comment by saschagrunert** [comment]
@justaugustus is this something we still need? We drastically changed the logging approach in krel stage/release. For example the `--log-level=debug` output will implicitly increase the git verbosity output, too.

**Comment by justaugustus** [comment]
@saschagrunert -- I think this might still be useful:

> Allow anago to interpret a git ref (instead of just branch) for use as the release tools repo to checkout (changes to both anago and the gcb/{stage,release} configs)

s/`anago`/`krel`

AND

s/`TOOL_BRANCH`/`TOOL_REF`

thoughts?

**Comment by saschagrunert** [comment]
> thoughts?

Yes, this seems straight forward to implement.

**Comment by justaugustus** [comment]
updated the issue title
