### ISSUE TITLE
testgridshot is snapshotting incorrect pages

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#1029]
Noticed in https://github.com/kubernetes/sig-release/issues/958#issuecomment-575405731, testgridshot no longer snapshots the correct dashboards.

I think this should be a quick fix, if someone wants to take it up.
It likely has to do with the new testgrid updates mentioned here: https://groups.google.com/d/topic/kubernetes-dev/DbV4MpQ3TZg/discussion

cc: @hoegaarden @kubernetes/release-engineering 
/help
/milestone v1.18
/sig release
/area release-eng
/priority important-soon

**Comment by xmudrii** [comment]
It seems like this issue is resolved by #1033. Should we close it?

**Comment by cpanato** [comment]
yep, it is fixed now
/close
