### ISSUE TITLE
[krel] Generate JSON release notes

### ISSUE THREAD

**Issue by JamesLaverack** [kubernetes/release#1061]
Currently the release notes team members on the Kubernetes Release team execute `cmd/release-notes` directly to generate JSON release notes, and pull request them into github.com/kubernetes-sigs/release-notes. ([See the handbook for full details](https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/release-notes/patch-notes.md).)

We would like to roll this generation into the existing tooling for Kubernetes releases, and ultimately into CI.

**Comment by justaugustus** [comment]
cc: @saschagrunert @jeefy 
/assign @JamesLaverack @puerco

**Comment by cartyc** [comment]
We had briefly discussed doing this in the following thread in the`[ #release-notes](https://kubernetes.slack.com/archives/CN1KH4K9A/p1580050487002000)` channel on slack. 

For this we would need to put together a bucket that relnotes members would have access to but it would also need global read access for the site to be able to pick things up. 

Agreed that moving this function into CI would be an awesome move :)

**Comment by cartyc** [comment]
Wanted to link to the issue Sascha just opened, https://github.com/kubernetes/release/issues/1087
