### ISSUE TITLE
Enable release notes to be gathered for k/release releases

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#1065]
**What would you like to be added**:
Support release notes in k/release, by enabling the Prow plugin and adding templates to the repo.

**Why is this needed**:
As we iterate over the content of this repo faster and external repos start to depend on us, we need to be able to [cut releases](https://github.com/kubernetes/release/issues/857) which contain detailed release notes, without having to manually collate them.

We can do this via our own tooling; we just need to ensure the repo has:
- [x] (https://github.com/kubernetes/release/pull/1063) PR templates which contain a `release-note` code block
- [x] (https://github.com/kubernetes/test-infra/pull/16161) We enable Prow plugins to enforce release notes for PRs moving forward

cc: @tpepper @saschagrunert

**Comment by saschagrunert** [comment]
https://github.com/kubernetes/release/issues/857 seems to be related with respect to the release cadence :)

**Comment by justaugustus** [comment]
Yep, yep, I linked it in the issue description. :)

**Comment by justaugustus** [comment]
PRs are merged and we now generate release notes for each release.
See https://github.com/kubernetes/release/releases/tag/v0.2.7 as an example.

/close
