### ISSUE TITLE
Build release notes for alpha.0 and beta.0 releases

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/release#1119]
We should build the release notes for both `alpha.0` and `beta.0` releases as well which is currently not the case. This is also the reason why anago still removes the unnecessary `CHANGELOG/CHANGELOG-x.y.md` files from the release branch on its creation:

https://github.com/kubernetes/release/blob/3c232618dbe74484be327c396a64aece87747454/anago#L561-L573

This :point_up: code part should not be done by anago but the `krel changelog` command invocation to have a single point of responsibilities inside our tooling.

I suggest in keeping this issue open and address it after/during the migration of anago to krel.

Refers to https://github.com/kubernetes/release/issues/918

**Comment by xmudrii** [comment]
@saschagrunert What is the status of this issue? Should we move it away from the v1.18 milestone? Are you still interested to work on this one or should we reassign it?

**Comment by saschagrunert** [comment]
> @saschagrunert What is the status of this issue? Should we move it away from the v1.18 milestone? Are you still interested to work on this one or should we reassign it?

The work has not started yet. I guess we can tackle that issue when we're moving to a krel based anago version, which has been started in https://github.com/kubernetes/release/pull/1106

**Comment by xmudrii** [comment]
Thanks for the update! I'll move this issue to the v1.19 milestone for now.
/milestone v1.19

**Comment by saschagrunert** [comment]
I think it is intended to not create release notes for those .0 alphas and betas. We only create them with the first alpha, because then we would actually have something to diff to.
