### ISSUE TITLE
Deprecate k8s-staging-release-test and k8s-infra-sig-release-prototype GCP projects

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#1161]
- [x] (https://github.com/kubernetes/test-infra/pull/16679, https://github.com/kubernetes/release/pull/1162) Move image building and image references to `k8s-staging-releng`
- [x] (https://github.com/kubernetes/k8s.io/pull/742) Remove IAM groups
- [ ] Delete GCP projects

---

Details to follow. Opening this so I don't lose the thread.
ref: https://kubernetes.slack.com/archives/CCK68P2Q2/p1583537568133300?thread_ts=1583278896.067700&cid=CCK68P2Q2, https://github.com/kubernetes/k8s.io/pull/624, https://github.com/kubernetes/release/issues/911

cc: @thockin

**Comment by justaugustus** [comment]
Assigning Aaron for the last-mile (project deletions).
/assign @spiffxp 
ref: https://github.com/kubernetes/k8s.io/pull/947

**Comment by spiffxp** [comment]
/close
deleted k8s-staging-release-test (ref: https://github.com/kubernetes/k8s.io/pull/947#issuecomment-642843634)

deleted k8s-sig-release-prototype
```
$ gcloud projects delete k8s-sig-release-prototype
Deleted [https://cloudresourcemanager.googleapis.com/v1/projects/k8s-sig-release-prototype].

You can undo this operation for a limited period by running the command below.
    $ gcloud projects undelete k8s-sig-release-prototype
```
