### ISSUE TITLE
release notes and changelog all TBD on official release

### ISSUE THREAD

**Issue by ixdy** [kubernetes/release#118]
Not sure what happened, but the official announcement for 1.4.0 had a bunch of TBDs/TODOs - see [the email](https://groups.google.com/d/msg/kubernetes-dev/EaBh47mzpVk/5mXeXHYeGgAJ) and [CHANGELOG](https://github.com/kubernetes/kubernetes/blob/0e22d072a3de75429a19edc196999b33bc71d05b/CHANGELOG.md#v140).

@pwittrock has the `anago.log` and will upload it somewhere so we can analyze.

**Comment by david-mcmahon** [comment]
WAI.  dup of #119
