### ISSUE TITLE
[1.18] Freeze merges until Kubernetes 1.18.0 is released

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#1212]
We should block merges on k/release until 1.18.0 has been released.

AFAIK, this is the first time we've done this in this repo, so let's try it out.
@cpanato @saschagrunert -- You're authorized to close this issue if there are release-blocking changes you need to make to the tooling.

cc: @kubernetes/release-engineering 
/milestone v1.18

Analogous to https://github.com/kubernetes/website/issues/19809 (https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/docs/README.md).
ref: https://github.com/kubernetes/test-infra/blob/e86e60c9c133773a78093ce5e6eafa16c5edb6ff/config/prow/config.yaml#L497

**Comment by justaugustus** [comment]
Applied the `tide/merge-blocker` label.
Branch Managers to close this issue once the release is complete.
/assign @cpanato @saschagrunert

**Comment by saschagrunert** [comment]
Sounds good to me. The other way around we could stick to certain releases in the next cycle, so we would not have a need for a merge freeze. WDYT?

**Comment by cpanato** [comment]
1.18.0 released, closing this issue

/close

**Comment by justaugustus** [comment]
> Sounds good to me. The other way around we could stick to certain releases in the next cycle, so we would not have a need for a merge freeze. WDYT?

@saschagrunert -- That's what I had in mind as well, but it's a process change in a few places, so we need to think through a little bit e.g., Release Managers need to check out k/release@<tag> and images need to be versioned against the tag, which means they to be rebuilt at the tag cut and then promoted.

Let's discuss some of this here --> https://github.com/kubernetes/release/issues/857
