### ISSUE TITLE
Stopped publishing /bin folders of CI builds

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [kubernetes/release#1227]
#### What happened:
"/bin" folder is not published in CI builds. This broke all the kubeadm master jobs.

https://testgrid.k8s.io/sig-release-master-informing#kubeadm-kinder-master

#### What you expected to happen:
The CI builds published should contain bin folder with the executables.

#### How to reproduce it (as minimally and precisely as possible):
Look for bin folder in 
https://console.cloud.google.com/storage/browser/kubernetes-release-dev/ci/v1.19.0-alpha.1.247%2B2fd8debe9b913f

#### Environment:

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by justaugustus** [comment]
FYI @kubernetes/ci-signal @kubernetes/release-engineering 
ref: https://kubernetes.slack.com/archives/C2C40FMNF/p1585845311247000

**Comment by justaugustus** [comment]
This could be related to yesterday's change to lib/releaselib.sh in https://github.com/kubernetes/release/pull/1199, which would affect the push-build.sh script (which sources that library). push-build.sh pushes the build results of the `ci-kubernetes-build*` jobs, which are the artifacts that are pulled in several of our e2e tests.

I don't have time to look at this at the moment, but that (^^) should give people some places to start looking at and I'll sync up with the team later.

**Comment by justaugustus** [comment]
Potentially this line

https://github.com/kubernetes/release/blob/01df93c1059eb698b126e9fe5d2029dacfd6174a/lib/releaselib.sh#L749
