### ISSUE TITLE
kubelet.service not waiting for network-online.target

### ISSUE THREAD

**Issue by rosti** [kubernetes/release#1248]
Whenever kubeadm detects a system that has `systemd-resolved` running, it would provision the kubelet on the local node with a resolv.conf overwrite - `/run/systemd/resolve/resolv.conf`.

However, some kubeadm users have discovered an issue during system boot. The kubelet can end up in a race with the `systemd-resolved` service and actually startup loads with empty or incorrect resolve.conf files.

The race is caused by the fact that the `kubelet.service` file does not indicate dependence on the `network-online.target`.

xref kubernetes/kubeadm#2111

/kind bug
/assign

**Comment by neolit123** [comment]
/priority important-longterm
cc @BenTheElder @aojea

**Comment by BenTheElder** [comment]
Thanks for the heads up, the resolv.conf in kind isn't systemd managed though.

I could definitely see this being an issue in prod systems 😬

**Comment by justaugustus** [comment]
Closed via https://github.com/kubernetes/release/pull/1250.
/close
