### ISSUE TITLE
Update release branches to go1.13.12

### ISSUE THREAD

**Issue by markyjackson-taulia** [kubernetes/release#1257]
### What would you like to be added

Update release branches to go1.13.12

- [ ] (@Verolop) kube-cross bump:
- [ ] (@Verolop) kube-cross image promotion:
- [ ] (@Verolop) k/release/k8s-cloud-builder bump:
- [ ] (@markyjackson-taulia) k/k bump:
- [ ] (@Verolop) Cherry pick `master` go1.13.12 upgrade:
  - [ ] `release-1.18`:
  - [ ] `release-1.17`:
  - [ ] `release-1.16`:
- [ ] (@markyjackson-taulia) kubekins/krte variants bump:
- [ ] (@markyjackson-taulia) publishing-bot bump:

/assign @Verolop @markyjackson-taulia
/priority important-soon
Cc: @kubernetes/release-engineering

**Comment by justaugustus** [comment]
This is a patch release bump; it needs to get done, but isn't "urgent" per se.
/remove-priority critical-urgent
/priority important-soon
/milestone v1.19
/retitle Update release branches to go1.13.10

**Comment by markyjackson-taulia** [comment]
Thank you @justaugustus 🙂

**Comment by justaugustus** [comment]
np!

@markyjackson-taulia @Verolop -- I cleaned up the list, but you'll have to redistribute the work a bit (since there's less of it) :stuck_out_tongue: 
/area dependency

**Comment by xmudrii** [comment]
If you folks need any help with this, I'd be happy to help as well :D

**Comment by justaugustus** [comment]
Before you get started, I need to refactor kube-cross a little to fix the release for 1.15: https://github.com/kubernetes/sig-release/issues/1051

I'll check in later to give a progress update.
I should be able to fix that up today.

**Comment by justaugustus** [comment]
@markyjackson-taulia @Verolop -- I'm currently testing a fix for kube-cross image building here: https://github.com/kubernetes/release/pull/1258

**Comment by justaugustus** [comment]
Updated the description to reflect go.1.13.11 and redistributed the tasks.

**Comment by justaugustus** [comment]
FYI: k/repo-infra@v0.0.5 bump needs to merge ahead of doing the k/k bumps -- https://github.com/kubernetes/kubernetes/pull/91312

**Comment by justaugustus** [comment]
Update this to reflect go1.13.12, now that it's been released: https://golang.org/doc/devel/release.html#go1.13.minor

@Verolop @markyjackson-taulia -- please start on this work this week.

**Comment by markyjackson-taulia** [comment]
@Verolop let me know if you would like to do this in tandem

**Comment by justaugustus** [comment]
Superseded by the security updates happening in https://github.com/kubernetes/release/issues/1408.
/close
