### ISSUE TITLE
Latest release tag on github is wrong

### ISSUE THREAD

**Issue by ixdy** [kubernetes/release#128]
Looking at https://github.com/kubernetes/kubernetes/releases, the current "latest release" is v1.3.8, which was built 21h ago, rather than v1.4.0, which was built 2 days ago.

I'm guessing this is because v1.3.8 is newer, and the "latest" tag is automatically applied by GitHub? Is there any way to fix this?

cc @pwittrock @fabioy

**Comment by david-mcmahon** [comment]
v1.3.8 is the latest chronologically.  Maybe this is WAI?  I can't seem to find guidance on what the "latest release" label is supposed to indicate.

**Comment by zmerlynn** [comment]
I'm pretty sure this is WAI, without altering the date on the annotated tag: http://stackoverflow.com/questions/22822586/swap-latest-release-on-github

**Comment by ixdy** [comment]
it might be working-as-implemented, but as a user trying to download the latest version of Kubernetes, it's unhelpful.
