### ISSUE TITLE
Make PRs, *don't* push directly to master during release process

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/release#13]
It really confuses the build cop and could interfere with what they're doing at the moment.

**Comment by david-mcmahon** [comment]
We talked offline about this some:
* infra errors/gotchas by their nature have more impact than bugs in the product
* Release velocity would be significantly reduced by inserting unecessary roadblocks into the process 
* Non-atomic (some changes to branch now and some to master later) changes could introduce unforeseen issues
* Continuous integration / testing of release is on the releng roadmap.  This will help mitigate most issues
* In general we should vet and test *code* that that does the Right Thing and then allow those automated process to do their job (with non-human checks)
* Inserting humans into processes more often causes delays and non-determinism.  Those are not things you want in a release cycle
* Solve problems and enforce policy through code, not (more) doc or tribal knowledge.
* Use this issue to identify short and long term resolutions here

**Comment by lavalamp** [comment]
And as I said:
* Build cop needs to be aware this script is being run and that it is going to push commits to master. The human running the script should not run the script if the build cop is putting out a fire.
* The submit queue's current test is technically invalidated by this push to master.

**Comment by david-mcmahon** [comment]
Identifying the things pushed to master during a release
* [mungedocs](https://github.com/kubernetes/release/blob/master/anago#L722)
* [update the base.go file](https://github.com/kubernetes/release/blob/master/anago#L239)
* [CHANGELOG.md](https://github.com/kubernetes/release/blob/master/anago#L269)
* [tags](https://github.com/kubernetes/release/blob/master/anago#L379)

**Comment by david-mcmahon** [comment]
Concerns over the release process and pushing to master should be discussed in this issue.
These actions are currently expressed in code and should be addressed there as well.

Releases happen at least every 2 weeks and push tags and minimal changes to up the master as part of it.  Lets get any concerns addressed and fixed in the code.

This [comment](https://github.com/kubernetes/release/issues/13#issuecomment-226315006) points to the places were master is updated.  Please take a look and make suggestions, either here or in the form of a PR.

**Comment by david-mcmahon** [comment]
Note: There are releases coming up at least one a week for the next few weeks.  If we want to do something to address this, let's do it sooner than later.

**Comment by lavalamp** [comment]
Unfortunately I really don't have time to wrap my head around that bash-- I'm doing too many things.

@fabioy is the next build cop. Fabio, do you have time to look at this?

@david-mcmahon more thoughts:

* I glanced at the code and didn't see any verify scripts getting called, but I probably missed it. I also don't trust running the scripts locally to be a good proxy for whether they will fail in jenkins and block the queue for everyone.
* I don't think it's right that the release script makes changes which don't get the same level of checking as other changes. I take your point that the release script always needs to work. But I am not convinced that sufficient safeguards are taken against bitrot-- changes to the repo that invalidate the release script's assumptions.
* I *do* think we should make an exception for making the tag. That should be in its own commit, and I think that should be safe to push and should never screw anything up (knock on wood)
* However I think the safest thing is for the other things the script does to get dumped into a P0 retest-not-required PR.

**Comment by fabioy** [comment]
@lavalamp Yeah, I can take a look at this. I'll try to get the context from this issue, else I'll ping David... :)

**Comment by david-mcmahon** [comment]
Let's look more closely at each commit to master:
* [mungedocs](https://github.com/kubernetes/release/blob/master/anago#L722) - Dependent .go sources updated and update-munge-docs.sh run to handle the generated files
* [update the base.go file](https://github.com/kubernetes/release/blob/master/anago#L239) - gitMajor, gitMinor values tied closely to the tag that is pushed at the same time.  These should be atomic changes.
* [CHANGELOG.md](https://github.com/kubernetes/release/blob/master/anago#L269) - The release notes published at the time of the release.  I've gotten pings and email from people in the past before this process was streamlined as to "Why aren't the release notes available yet".  We don't want to go back to those dark times.  Release notes published at release time is correct.
* [tags](https://github.com/kubernetes/release/blob/master/anago#L379) - Self explanatory.

These are small release (infra) related changes that accompany the state of the tree through a release. 

The right direction here might be looking at how to avoid changing files on master at all (except for tags):
* There is a [P3 Issue to get rid of base.go](https://github.com/kubernetes/kubernetes/issues/16815) changes, but I don't know how feasible that is.  Brian said at the time at least it was not possible.
* The whole mungedocs thing seems silly to me and I know that's in some kind of flux, but maybe we can do away with changes to master there in the future. 
* CHANGELOG.md - We probably want to keep this one.  update-munge.docs.sh is the only dependency that I'm aware of.

**Comment by david-mcmahon** [comment]
Another thought on the CHANGELOG.md.  While it's certainly customary and desirable to have a CHANGELOG in the root directory that reflects release notes/changes, we could go back to publishing those solely on the github releases page or in another repo altogether (kubernetes.github.io? @johndmulhausen)
My concerns there are discoverability, inconvenience, release note public/process churn and related community blowback.  Then again, maybe noone cares that much.

**Comment by lavalamp** [comment]
I can buy that the base.go change is necessary and safe in addition to the
tags change.

.md file changes are scarier on account of our mungers...
