### ISSUE TITLE
kubepkg does not respect flags

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#1331]
#### What happened:

While working on https://github.com/kubernetes/release/pull/1330, I noticed that `kubepkg` doesn't actually respect user-supplied flags, instead running with the defaults specified in `pkg/kubepkg/options.go` (`options.New()`): https://github.com/kubernetes/release/blob/d992507a0aa386a1b2cd57319b7c891a0f6a126b/pkg/kubepkg/options/options.go#L73-L82

/assign @saschagrunert

**Comment by saschagrunert** [comment]
Confirmed, preparing a fix…
