### ISSUE TITLE
Add a few retries around failure points in release scripting

### ISSUE THREAD

**Issue by Verolop** [kubernetes/release#1353]
#### What would you like to be added:
Adding some retries around failure points in release scripting before failing completely. Eg:

 * docker pull commands on the code for Mock Release (Issue #1102 )
 * "Step #1: PUSH GIT OBJECTS  (11/14)" (Issue #933 )
 * audit past year's "HACK" and "revert" commits on anago/gcbmgr/lib shell to other points which would benefit from a basic sleep/retry loop

#### Why is this needed:
In case of failure, often we just need to hack workaround and attempt to re-run the release process, which is very time and resource consuming. Adding retries will allow these attempts to take place on the same run.

**Comment by Verolop** [comment]
sounds good, I agree!

**Comment by tpepper** [comment]
@Verolop we've just discussed that there are a number of issues that are relatively similar to this, so I've tweaked the description slightly to cover the more abstracted case.  There's max half a dozen points where a minimal additional retry loop in the shell script could make us much more likely to survive these random transient failures and save tonnes of release time and effort.

**Comment by tpepper** [comment]
(ie: rather than close a bunch of issues and create new one...just re-using/re-focusing this one for broad impact)

**Comment by saschagrunert** [comment]
An idea which came into my mind: What if we add a krel subcommand for pushing the git objects? Seems fairly straight forward and we could remove the bash bits from anago. Then I'd like to enhance the logging via logrus and maybe add some pre-checks: For example making the call fail only in some certain cases and assume that "everything is ok" if the tag is already present remotely. WDYT?

**Comment by tpepper** [comment]
> An idea which came into my mind: What if we add a krel subcommand for pushing the git objects? Seems fairly straight forward and we could remove the bash bits from anago. Then I'd like to enhance the logging via logrus and maybe add some pre-checks: For example making the call fail only in some certain cases and assume that "everything is ok" if the tag is already present remotely. WDYT?

This is the type of decomposition we need.  The anago bash bits doing that push can be removed to instead have anago call a more robust pusher.

**Comment by tpepper** [comment]
Related on the topic of fail/retry/continue resilience:
https://github.com/kubernetes/test-infra/issues/18808

**Comment by Verolop** [comment]
Does it still make sense to introduce the retries at this point, or should we just go ahead with @saschagrunert 's idea?

**Comment by tpepper** [comment]
We definitely need some retries still in anago too.

**Comment by puerco** [comment]
/remove-lifecycle stale

This was mostly addressed in https://github.com/kubernetes/release/pull/1595

unless there are more suggestions and/or comments I think we can close this one

**Comment by cpanato** [comment]
Agree, if more things come up we can create a new issue

/close
