### ISSUE TITLE
dont error out at end when there is no permission to push to the branch

### ISSUE THREAD

**Issue by jessfraz** [kubernetes/release#136]
example:

```
anago::push_git_objects(): git push origin release-1.4
remote: error: GH006: Protected branch update failed for refs/heads/release-1.4.        
remote: error: You're not authorized to push to this branch. Visit https://help.github.com/articles/about-protected-branches/ for more information.        
To git@github.com:kubernetes/kubernetes
 ! [remote rejected] release-1.4 -> release-1.4 (protected branch hook declined)
error: failed to push some refs to 'git@github.com:kubernetes/kubernetes'
```

**Comment by david-mcmahon** [comment]
Thanks for the report.  What was the original command line?

**Comment by jessfraz** [comment]
anago release-1.4 --buildversion=v1.4.1-beta.0.63+90a2226c1bc505 --nomock

**Comment by david-mcmahon** [comment]
Try running without the --nomock flag to make sure you can get through a run.  

I added you to the auth page for the branch to allow pushes.

I'll send a fix for this issue shortly that checks the correct auth.

**Comment by jessfraz** [comment]
ya I did and that worked

**Comment by jessfraz** [comment]
Thanks!!!

**Comment by david-mcmahon** [comment]
@jessfraz you did what?  Were you able to complete a non-mock run?  You should also have hit the auth issue in mock mode (up until a few minutes ago when I added you to administrators for that branch).

**Comment by jessfraz** [comment]
I was able to complete a non-mock run because it used --dry-run, it all
looked good

**Comment by jessfraz** [comment]
Sorry I just meant it worked without the flag `--nomock`

**Comment by david-mcmahon** [comment]
Very troubling that --dry-run would behave differently when pushing.  That means we have no way to validate auth/perms before we allow the release to happen.  I'm going to remove you from the branch again.  Can you send me the output of this?

```
$ git push --dry-run origin release-1.4
```

**Comment by jessfraz** [comment]
```
$ git push --dry-run origin release-1.4
To git@github.com:kubernetes/kubernetes.git
   6fb175e..4b5e85d  release-1.4 -> release-1.4
```

**Comment by david-mcmahon** [comment]
Addressing the specific issue of [branch auth based on repo admin, that has been resolved](https://github.com/kubernetes/release/blob/master/lib/gitlib.sh#L84).
