### ISSUE TITLE
release artifact consumers tracking policy (or disable tracking?)

### ISSUE THREAD

**Issue by tpepper** [kubernetes/release#1365]
#### What happened:

While setting up a sendgrid account to do `krel announce` I noticed various tracking settings enabled by default.  Looking at our recent notifications (eg: https://groups.google.com/g/kubernetes-dev/c/PSacPKC46tc/m/8Y9G-FqSBgAJ) you can see that instead of directly linking to our artifacts they are wrapped in ct.sendgrid.net redirected links.  There is also a snippet of tracking html to note if a send email is opened.

These are arguably interesting stats for us to collect as we are largely unaware of the reach and usage of our artifacts.

#### What you expected to happen:

If we're going to collect these stats, it should be documented that we are doing so and affirm the overall project is OK with that.  Additionally we'd need to confirm that no PII is collected and stored.

#### How to reproduce it (as minimally and precisely as possible):

View urls and html in a release announcement created since moving to sendgrid, eg: https://groups.google.com/g/kubernetes-dev/c/PSacPKC46tc/m/8Y9G-FqSBgAJ

For each SIG Release Branch Manager, view your tracking settings at https://app.sendgrid.com/settings/tracking

**Comment by tpepper** [comment]
/priority important-soon
also partly
/kind documentation

**Comment by saschagrunert** [comment]
Hm, yeah I think a proper documentation would be enough in our case, right? The changelogs should never contain any sensitive information.

**Comment by tpepper** [comment]
https://github.com/kubernetes/kubernetes/pull/94044 also references a tracker.

**Comment by puerco** [comment]
This is still a valid concern
/reopen
