### ISSUE TITLE
Integration of Release Notes automatic tools into the release process

### ISSUE THREAD

**Issue by puerco** [kubernetes/release#1370]
After some months of building and testing the release notes tools in `krel`, the 1.19 Release Notes Team would like to propose the final integration of the release notes automation into the release process. The release notes tooling in krel is by now fairly well tested and has proven to handle the most common problems we've encountered well. Therefore, we would like to propose the following actions to finalize the integration:

- [ ] Modify `krel release-notes` to honor the _mock/no-mock_ flag and match the behavior in other releng tools.
- [ ] Adding to `krel release-notes` the capability to prepare for a speedier generation by preloading PR data during the release staging phase
- [ ] Adding new flags to the `release-notes` subcommand to only perform the tests and environment checks for use during a mock run
- [ ] Write the necessary functions in `anago` to call the `release-notes` subcommand with the proper flags.
- [ ] Work with someone with access to expand the scope of the GitHub token being used when cutting a release to enable it to create PR
- [ ] Update the Branch Manager handbook with the new procedures
- [ ] Update the krel documentation to reflect new changes

We would love to hear any comments or guidance from the leads and branch managers before starting to work on these.

Thanks in advance for your feedback :)

/cc @kubernetes/release-engineering 
/cc @AGMETEOR @JamesLaverack @reylejano-rxm @wilsonehusin

**Comment by saschagrunert** [comment]
Thank you for the tracking issue!

> * [ ]  Modify `krel` to implement the _mock/no-mock_ behavior other releng tools have

I think we already have this in `krel, right?

**Comment by puerco** [comment]
oops yes you are right. I meant modifying `krel release-notes`. I've changed the wording to reflect that.

**Comment by saschagrunert** [comment]
@puerco has this been closed unintentionally or do we move the work to other issues?
