### ISSUE TITLE
kubelet-1.18.4-0 cannot be installed alongside cri-o on fedora 32

### ISSUE THREAD

**Issue by davemac30** [kubernetes/release#1371]
#### What happened:
Tried to install kubelet-1.18.4-0 RPM on a Fedora 32 box which had cri-o installed. Got the following error:

```
Error:
 Problem: problem with installed package containernetworking-plugins-0.8.6-1.fc32.x86_64
  - package kubelet-1.18.4-0.x86_64 conflicts with kubernetes-cni provided by containernetworking-plugins-0.8.6-1.fc32.x86_64
  - package kubelet-1.18.4-0.x86_64 conflicts with kubernetes-cni provided by containernetworking-plugins-0.8.5-1.1.gitf5c3d1b.fc32.x86_64
  - conflicting requests
```

#### What you expected to happen:

As with previous versions of kubelet RPM (e.g. 1.18.3-0), I expected kubelet-1.18.4-0 to install without errors.

#### How to reproduce it (as minimally and precisely as possible):

On a clean, new vagrant box based on `fedora/32-cloud-base`, run the following:

```
sudo dnf -y module enable cri-o:1.18
sudo dnf -y install cri-o
sudo dnf config-manager --add-repo https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
sudo rpmkeys --import https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
sudo dnf -y install kubelet-1.18.4-0
```

#### Environment:

Vagrant 2.2.9, VirtualBox 6.1.10, MacOS 10.15.5

Vagrantfile

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "fedora/32-cloud-base"

  config.vm.provider :virtualbox do |virtualbox|
    virtualbox.linked_clone = true
    virtualbox.customize ["modifyvm", :id, "--audio", "none"]
    virtualbox.memory = 1024
  end

end
```

**Comment by saschagrunert** [comment]
Hey @davemac30 👋, with the release of Kubernetes 1.18.4 we removed packaging `kubernetes-cni`, which means we probably can fix this error with https://github.com/kubernetes/release/pull/1367, too.

**Comment by saschagrunert** [comment]
Alright https://github.com/kubernetes/release/pull/1367#discussion_r443145331 clarifies that the solution is not as trivial as initially thought.

Calling for @dougsland 👋 do you have a suggested way how we can use both, the Fedora module and the packages on yum.k8s.io together?

cc @lsm5 @haircommander

**Comment by haircommander** [comment]
Cc @lsm5

**Comment by dougsland** [comment]
> Alright [#1367 (comment)](https://github.com/kubernetes/release/pull/1367#discussion_r443145331) clarifies that the solution is not as trivial as initially thought.
> 
> Calling for @dougsland  do you have a suggested way how we can use both, the Fedora module and the packages on yum.k8s.io together?
> 
> cc @lsm5 @haircommander

I think it's hard to keep a statement that both repos will work 100% all the time without conflicts (as independent repos).

**Comment by justaugustus** [comment]
Potential fix being discussed here: https://github.com/kubernetes/release/pull/1375

**Comment by justaugustus** [comment]
@davemac30 -- We've published new packages. Can you try again w/ `1.18.4-1`?

**Comment by davemac30** [comment]
Seems to work fine - cri-o and kubelet installed together no problem:

```
[vagrant@localhost ~]$ sudo rpm -qa cri-o kubelet
cri-o-1.18.1-2.module_f32+9078+15f1cda4.x86_64
kubelet-1.18.4-1.x86_64
```

Thanks all for the speedy resolution!

**Comment by jlpettersson** [comment]
This still seem to be a problem.

I tried to install kubelet and cni-tools.

```
Error:
 Problem: conflicting requests
  - package kubelet-1.28.0-150500.1.1.aarch64 from kubernetes requires kubernetes-cni >= 1.2.0, but none of the providers can be installed
```

and if I let `kubernetes-cni` be installed when I have `cni-tools` I get:

```
Error: Transaction test error:
  file /opt/cni/bin/bandwidth from install of kubernetes-cni-1.2.0-150500.2.1.aarch64 conflicts with file from package cni-plugins-1.2.0-1.amzn2023.0.3.aarch64
```

The binaries are installed from https://pkgs.k8s.io/core:/stable:/v1.28/rpm/

**Comment by haircommander** [comment]
`cni-plugins-1.2.0-1.amzn2023.0.3.aarch64` I think this may be something to take-up with the folks that put together your distro. is it Amazon Linux?

**Comment by jlpettersson** [comment]
@haircommander yes, it is Amazon Linux 2003.

But I will workaround by using `curl` instead of the yum repositories, it seems not to be a good way to install the kube binaries.

**Comment by xmudrii** [comment]
/reopen
/assign
I'll take a look into this

**Comment by xmudrii** [comment]
I'm not working on this at the moment.
/unassign
