### ISSUE TITLE
Provide links to k8s control plane images

### ISSUE THREAD

**Issue by b10s** [kubernetes/release#1384]
#### What would you like to be added:
Would be great to add links to images with official k8s control plane binaries to [release notes/changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#v1185)

#### Why is this needed:
Some users do deploy k8s using their own way without kubeadm.

They'd better have link to images instead using binaries to stick to best practice:
binary kubelet + other control plane parts as containers

**Comment by saschagrunert** [comment]
From a technical perspective I think we  could add a new flag to `krel changelog` to provide the release `--images` path. This path can be used to implement something like:
https://github.com/kubernetes/release/blob/8c711b57abe96ddcb0a41a331d4e451b0d0d8c92/lib/releaselib.sh#L1052-L1078

The same logic would be needed when converting parts of anago to a golang based version.

**Comment by puerco** [comment]
I can take it @saschagrunert unless you want to for some particular reason

**Comment by saschagrunert** [comment]
> I can take it @saschagrunert unless you want to for some particular reason

Sounds good, thank you @puerco!

**Comment by saschagrunert** [comment]
@puerco I assume that this will be resolved with #1837 now.

**Comment by puerco** [comment]
Yes, it's one of the tasks that should get resolved as a byproduct of the BOM :)
