### ISSUE TITLE
Golang security updates (go1.14.5 and go1.13.13)

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#1408]
#### What would you like to be added:

kubernetes/kubernetes should support go1.14.5 and go1.13.13

#### Why is this needed:

go1.14.5 and go1.13.13 are security releases that were made available earlier today.
Announcement here: https://groups.google.com/d/topic/golang-announce/XZNfaiwgt2w/discussion

#sig-release Slack thread here: https://kubernetes.slack.com/archives/C2C40FMNF/p1594746089427800

##### Both versions 

- [x] kube-cross bump: https://github.com/kubernetes/release/pull/1406
- [x] image promotion: https://github.com/kubernetes/k8s.io/pull/1021
- [x] k/release/k8s-cloud-builder bump: https://github.com/kubernetes/release/pull/1407
- [x] k/k bump (`master`): https://github.com/kubernetes/kubernetes/pull/93088
- [x] k/repo-infra bump: https://github.com/kubernetes/repo-infra/pull/194
- [x] k/repo-infra release cut: https://github.com/kubernetes/repo-infra/releases/tag/v0.0.7
- [x] k/k bazel rules_go: https://github.com/kubernetes/kubernetes/pull/93088
- [ ] k/k bazel rules_go cherry picks:
  - [ ] 1.18: https://github.com/kubernetes/kubernetes/pull/91348 (needs update)
  - [ ] 1.17: 
  - [ ] 1.16: 
- [x] kubekins/krte variants bump: https://github.com/kubernetes/test-infra/pull/18328
- [ ] publishing-bot bump: https://github.com/kubernetes/kubernetes/pull/93138

##### go1.13.13-specific items

- [ ] k/k bump (`release-1.18`):
- [ ] Cherry picks:
  - [ ] 1.17:
  - [ ] 1.16: 

/assign
/priority critical-urgent
cc: @kubernetes/release-engineering

**Comment by mkumatag** [comment]
Golang `1.14.6` is released today with an additional cherry-picks contains one of the mandatory fix for the ppc64e platform, I'm creating a separate issue to update the same.

**Comment by justaugustus** [comment]
I'm considering this complete. k/k `master`/`release-1.19` branches are on go1.14.5.
This release was determined to be low impact/severity by the PSC, so we'll carry forward the next go1.14 and go1.13 updates in https://github.com/kubernetes/release/issues/1410.

/close
