### ISSUE TITLE
[krel] Introduce krel subcommand for pushing git objects

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/release#1446]
There are multiple issues with pushing the git references inside anago, which makes the overall process not idempotent. For example network flakes can abort the push, even if specified as dry-run. If the remote tag already exists due to another issue in anago, then we're not able to skip this step accordingly.

I would like to solve that issue inside a dedicated krel subcommand for pushing the git objects. This means that we would replace this complete part in anago:
https://github.com/kubernetes/release/blob/6e2777630e320ff4e3c7ee8bcabf96aea8c3692d/anago#L807-L851

Additionally, we should enhance the implementation to:
- retry pushing on network failures
- check if the remote tag already exists and do not fail if so
- enhance testing around the common error cases

Refers to https://github.com/kubernetes/release/issues/1353
/priority important-soon

**Comment by puerco** [comment]
+1 If we are going to add more checks to the process, I think it's best to do it in go and strip anago as much as we can.

**Comment by saschagrunert** [comment]
@kubernetes/release-managers anyone wants to take this? :)
