### ISSUE TITLE
Reduce curl hits to github API

### ISSUE THREAD

**Issue by david-mcmahon** [kubernetes/release#146]
Ivan Žužak <support@github.com> said:

> For example, I need to search for PRs between tag v1.0..v2.0 and find
> specific labels in PRs merged within that range.
>
> Today I'm getting the list of PRs to look up with:
>
> git log $range --format="%s" --grep="Merge pull"
>
> And then curl'ing each one to see if it has the label I need.
>
> Is there a way to do this with some api to github so I don't have to make
> hundreds of curl execs?

No, there's no GitHub API that allows you to do exactly what you want, but there's still a way you can help yourself and both speed things up + reduce the number of API calls. Instead of hitting the API over and over again, add a webhook to the project which notifies you when a label has been added or removed from an issue or pull request: http://developer.github.com/webhooks/. That webhook would be pointed at the same system that's doing the API calls right now and that system would store that information locally so that when it needs to know if a pull request has a label -- it doesn't need to make the API call because it already has all the information it needs. In short, you'd cache the information you need locally instead of hitting the API. That should be both faster and reduce the number of API requests.

An alternative to this would be to do what I suggested before -- I think that suggestion is still valid. If you know which label you're looking for, then you can fetch the list of pull requests with that label via the API (by not fetching them individually, but by fetching 100 at a time, which will be 100 times more efficient than what you're doing now). If you then locally do an intersection of that list with the list of pull requests you compiled with the git log command you shared -- that should give you the list of pull requests you need (pull requests that are between some tags AND have label X). Even if you have multiple labels you need to check for -- this approach should still help you significantly reduce the number of API calls you need to make (you could do additional filtering locally, for example, because the list of pull requests you'd get from the API would include the full list of labels, so no need to hit the API again). Does that make sense for your use-case
 ? If not, can you share more details so that we can understand why it doesn't?

**Comment by mattymo** [comment]
I will take this on. Can you assign me?
