### ISSUE TITLE
Cut k/release v0.4.0

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/release#1466]
The last release was long long time ago and we added some features which are valuable to dependent projects. What do you think about releasing v0.4.0?

**Comment by puerco** [comment]
I'd like to have #1467 included in a release before the release cycle is out.

v0.4.0 is a nice round number that we can use to know from which point the release notes maps where added and it would certainly be nice to the feature in that one, but what I'm really interested in is to have it in a release before the Release Notes team for 1.20 takes over.

**Comment by saschagrunert** [comment]
> I'd like to have #1467 included in a release before the release cycle is out.
> 
> v0.4.0 is a nice round number that we can use to know from which point the release notes maps where added and it would certainly be nice to the feature in that one, but what I'm really interested in is to have it in a release before the Release Notes team for 1.20 takes over.

Sounds good, let's hold for #1467

**Comment by justaugustus** [comment]
/assign
I'll plan to release this on Monday.
If https://github.com/kubernetes/release/pull/1467 lands before then, we'll include it.
If not, there's no reason it can't be introduced in a `v0.4.1` release.

**Comment by saschagrunert** [comment]
/close
Done :heavy_check_mark:

**Comment by justaugustus** [comment]
ref: https://github.com/kubernetes/release/releases/tag/v0.4.0
