### ISSUE TITLE
the marker latest-1.15 was deleted

### ISSUE THREAD

**Issue by neolit123** [kubernetes/release#1468]
#### What happened:
i've mentioned this in the #release-management channel today:
https://kubernetes.slack.com/archives/CJH2GBF7Y/p1596638740060400

the kubeadm upgrade and skew tests are still consuming the `latest-1.15.txt` marker to ensure users can upgrade to a supported version e.g. from 1.15 -> 1.16, while 1.16 is still in support.

this resulted in failures of the kubeadm skew and upgrade jobs for 1.16:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-1-16-on-1-15
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-upgrade-1-15-1-16

#### What you expected to happen:
the 1.15 marker to exist until 1.19 is released and 1.16 goes out of support.
at that point we should keep 1.16 to support the kubeadm 1.16->1.17 upgrade/skew signal until 1.17 goes out of support.

but alternatively we can definite a time when it's appropriate to remove e.g. the 1.15 earlier. for example, remove the 1.15 marker once code-freeze for 1.19 happens and we can reflect that in our kubeadm housekeeping tasks for each cycle.
this however is not ideal, because it leaves us without signal for this upgrade/skew path for a period of time until e.g. 1.16 goes out of support.

#### How to reproduce it (as minimally and precisely as possible):
```
curl -L https://dl.k8s.io/ci/latest-1.15.txt
```

**Comment by neolit123** [comment]
/sig cluster-lifecycle

/priority important-soon
(given this is related to the 1.19 release and 1.16 going out of support).

**Comment by saschagrunert** [comment]
Closing since 1.16 is now end of life. Feel free to reopen if you still see a gap
/close
