### ISSUE TITLE
krel should support some emergency commands for editing production artifacts

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#1494]
#### What would you like to be added:

krel should support some emergency commands for editing production artifacts, skipping certain anago checks.

#### Why is this needed:

We occasionally enter scenarios (like https://github.com/kubernetes/release/issues/1493) where releases move into a unreleaseable state, which require a slew of hacks in `anago` and `lib/releaselib.sh` to disable checks to allow a release to proceed.

cc: @kubernetes/release-engineering

**Comment by puerco** [comment]
Once things settle a little, perhaps we can chat a bit on what's needed most and I'll be happy to help build some of these commands :)

**Comment by tpepper** [comment]
Probably a relatively easy feature for somebody to add and which we hit a once or twice a year: to push marker of a failed patch release tag so tools (like relnotes) can diff versus prior non-failed release tag.  Eg: ‘krel mark-as-failed 1.17.10’ leaves a crumb somewhere that 1.17.10 was a dud.  1.17.11's build compares against prior non-dud which it discovers to be 1.17.9.

**Comment by justaugustus** [comment]
/assign @hasheddan 
ref: https://github.com/kubernetes/release/pull/1640#issuecomment-721157074
