### ISSUE TITLE
Merge blocker for Kubernetes v1.19.0 release

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#1503]
To be closed once Kubernetes v1.19.0 is released.
cc: @kubernetes/release-engineering 

(Opened as an example for https://kubernetes.slack.com/archives/C09QZ4DQB/p1598238256025300?thread_ts=1598238256.025300&cid=C09QZ4DQB, but also because we should start doing this near release dates)

**Comment by saschagrunert** [comment]
Will temporarily remove the blocker to let https://github.com/kubernetes/release/pull/1505 in, which contains a critical fix to let the `stage` succeed.

**Comment by justaugustus** [comment]
[Kubernetes v1.19.0 has been released](https://groups.google.com/g/kubernetes-announce/c/oX-AjJkYhH4) and we are reopened for k/release development.

/close
