### ISSUE TITLE
Missed action required release note in 1.19

### ISSUE THREAD

**Issue by JamesLaverack** [kubernetes/release#1506]
#### What happened:

In Kubernetes 1.19 a change (https://github.com/kubernetes/kubernetes/pull/89069) was missed from the [release notes](https://github.com/kubernetes/kubernetes/commit/b1f2f1a32bf4c04abf6c077cfdc8c0c68fc9e4a8).

#### What you expected to happen:

For https://github.com/kubernetes/kubernetes/pull/89069 to be mentioned, and for it's "action required" note to be mentioned in the action required section.

#### How to reproduce it (as minimally and precisely as possible):

See Above.

#### Anything else we need to know?:

The note has been added manually https://github.com/kubernetes/kubernetes/pull/94261

#### Environment:

N/A

**Comment by JamesLaverack** [comment]
https://github.com/kubernetes/kubernetes/pull/89069 was one of the first things to be merged into Kubernetes following the 1.18.0-rc.1 branch and subsequent code thaw in the 1.18 release cycle. As such it was [present in Kubernetes for 1.19 from the 1.19.0-alpha.1 tag](https://github.com/kubernetes/kubernetes/commit/f899ad704ae6bd87560a3e21b9cfbb8bdeef404e). However, this release note is *also* absent from [older runs of the release note tool](https://github.com/kubernetes/sig-release/commits/master/releases/release-1.19/release-notes-draft.md). This suggests to me that this isn't a GitHub API flake, or other transient issue, that happened to only hit when the final notes were generated.

**Comment by saschagrunert** [comment]
Thank you for the report @JamesLaverack, a fix is incoming in #1508.
