### ISSUE TITLE
Add verification logic to ensure all Golang binaries in core images are of the same arch

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#1521]
#### What would you like to be added:

Add verification logic to ensure all Golang binaries in core images are of the same arch.

#### Why is this needed:

Reported in https://github.com/kubernetes/kubernetes/issues/94540 and requested in https://github.com/kubernetes/kubernetes/pull/94552#issuecomment-687688271.

/milestone v1.20
/priority important-soon

**Comment by justaugustus** [comment]
/help
cc: @liggitt

**Comment by saschagrunert** [comment]
We could do this as part of the Bill of Materials / artifact verification epic. We could try to read the elf header for the verification logic …

**Comment by hasheddan** [comment]
@saschagrunert SGTM!

**Comment by dims** [comment]
ooh! that's neat idea @saschagrunert

**Comment by saschagrunert** [comment]
Awesome! I think darwin and windows binaries are not written in the elf format, but let's discuss the technical solution as part of the artifact epic. :+1:

**Comment by puerco** [comment]
My thoughts exactly, I assigned it to myself because while researching the bom and figured I could solve it along with that.
