### ISSUE TITLE
[krel] Introduce krel subcommand to screenshot testgrid dashboards

### ISSUE THREAD

**Issue by cpanato** [kubernetes/release#1531]
#### What would you like to be added:
Replace the `testgridshot` bash script with a `krel` subcommand to generate the testgrid dashboard screenshots and upload to GS Bucket

Already discussed with Sascha and this is a nice idea to deprecate bash scripts and also to add this functionality to krel to be able in the future create an automated pipeline to do all the steps.

/priority important-soon

/assign

**Comment by puerco** [comment]
Are you planning on still using rendertron to take the screenshots?

**Comment by cpanato** [comment]
Sincerely I dont know @puerco, I was thinking to check if we have something already in the library, and if not check what is on the wild related to this.

do you have any ideas?

**Comment by puerco** [comment]
I've used chrome headless in the past with good results. It seems that rendertron is the same thing behind the scenes. Would there be any reason to run it ourselves? (like, for example, not connecting to the internet for some reason).

**Comment by saschagrunert** [comment]
Hm, now I’m wondering if it would be cool to have a markdown export/snapshot feature directly in testgrid. This way we could utilize the api to just query the data without having a need to screenshot anything.
