### ISSUE TITLE
[krel] Introduce krel anago subcommand to update GitHub release

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/release#1534]
Target is to replace this section of anago with a go-based implementation as `krel anago` subcommand:
https://github.com/kubernetes/release/blob/8b9e5c8483acfc5aec67bece8d0114295d96562a/anago#L939-L1101

**Comment by saschagrunert** [comment]
/help
@kubernetes/release-engineering feel free to take this if you want. I can guide you through the details :)

**Comment by xmudrii** [comment]
I would like to give it a try. :)
/assign

**Comment by saschagrunert** [comment]
I think this can be closed now, since we have the logic in `krel release` in place.
/close
