### ISSUE TITLE
Automate CI Signal Status Weekly Updates

### ISSUE THREAD

**Issue by RobertKielty** [kubernetes/release#1546]
Automate the retrieval of data from the CI Signal Github Project Boards and TestGrid to  allows us to create a highly customized status report at a point in time.

There is prior art here (Alena Varkockova did [good work on this](https://github.com/alenkacz/ci-signal-report)) and there are ongoing discussions with @hasheddan and @alejandrox1 on how we present the state of CI Signal Flake discovery work.

But there a small steps that we can take today.

1. Periodically retrieve and store CI Jobs that are flaking.
2. Group reported /kind flake issues by status, sig, age etc.

**Comment by RobertKielty** [comment]
Current status of the work is that

I've modified @alenkacz's code ref as follows
- I've updated the git client to more a recent version
- I've added null/empty string guards for various responses from GH
- The report needs testing and @hkamel will take the lead on that but are all welcome to pitch on that once the work is available publicly.  See below ...

**Comment by RobertKielty** [comment]
@LappleApple @jeremyrickard @alejandrox1 @hasheddan @lachie83 @spiffxp 

### This issue needs a board on which it can be tracked.
From yesterday's Rel Team meeting perhaps that is the Release Engineering board? 

#### I need a kubernetes repo where I can commit the work
I'm happy to use whatever repo the team want me to use 

From the existing repo locations that I know test-infra (experiments) would seem like a good place to put it in so far as that is where similar CI related code resides. 

I am open to suggestions on what kubernetes org I should use.

Code is being written now so I need a place to commit this code today.
 
#### Next step 
jsonify the report output and timestamp each data collection
user acceptance testing (myself and @hkamel)

#### Deployment planning
So I need help on this, this is what I would like to do 

- Run the report periodically (thinking 1 to 4 times an hour?) could this be a Pro Job? 
- Store timestamped json output in a bucket/repo
- Make the data available to grafana/prometheus so that we can track flake movements over time.

**Comment by alenkacz** [comment]
yay, I love that the code lives on and the idea is being pushed forward. Thanks @RobertKielty

**Comment by hasheddan** [comment]
`test-infra` sounds like a good place for this to live. I think the primary goal here is to provide a view of flakiness / failure over time, rather than manually presenting a point-in-time snapshot at release meetings. Something to keep in mind is how we want to aggregate the data collected. While some jobs are owned pretty much exclusively by a single SIG, many include tests owned by a variety of SIGs. Ultimately I believe we want to be able to quantify how healthy a given SIGs tests are over time, so we need to be able to categorize flakes and failures by owners, then compare them to any policies / SLAs we enact.

**Comment by RobertKielty** [comment]
I've removed an un-authenticated http client get on the report which means I can no run the report repeatedly ....

Sample output here ....

https://gist.github.com/RobertKielty/07c90d71d7c8561303554534d3006fdd

**Comment by RobertKielty** [comment]
Next steps here

1. Add timestamp to a data collection
2. Make the output format selectable and suitable usage by tools that can process time-series data
3. Convert to Prow Job
4. Deploy to a Prow instance

**Comment by RobertKielty** [comment]
I restarted report development and am developing this [on a feature branch on my test-infra fork](https://github.com/RobertKielty/test-infra/tree/flake-tracker/experiment/flake-tracker) 

Although, I am using this code as it stands now to provide Signal status updates for the 1.20 Release this is still very much a work in progress. 

Here's a sample [Google Sheet](https://docs.google.com/spreadsheets/d/1E5pFHC7kiDTv6QGUKVxWfA-lSJdrs71JJk2nQ9eNjV8/edit#gid=144771858) where I imported csv reports for the blocking and informing Job Groups and created some rough pivot tables for same. I do not see Sheets as being part of a final implementation but it is a good temporary option while I develop the report. 

The same can be said of the CSV file, this is a temp output option based on development needs and I may offer this as an option to allow an end-user to run an ad-hoc report in the final implementation but again this is likely not the final default output to capture the data.

**Comment by RobertKielty** [comment]
I have published a WIP first draft to https://github.com/RobertKielty/flake-tracker

**Comment by chaunceyt** [comment]
Forked.

**Comment by RobertKielty** [comment]
I am continuing to work on this and will do so up to the end of the 1.20 release.

I will then put together a presentation of what went well what the next steps could be arising out of this work.

**Comment by RobertKielty** [comment]
Summary of work done, challenges and suggested next steps  

Code committed to https://github.com/RobertKielty/flake-tracker

It is easy to retrieve CI Status data by scraping TestGrid json 

Generating reports is easy; reports are template driven.

It is currently too difficult to parse data from Github Issues logged for problems with Tests because 

 - Issue data is entered manually
 - Resulting in inconsistent formatting and variance in issue data quality
 - The data is interpreted as markdown in GH (this adds awkward edge cases)
 - Flattened test names make referring to test code impossible
 - Test names can include markdown! (Rare in fairness)  
 - Conflation of Job Name/TestGrid Dashboard Name

Suggested next steps:
 
We could park this effort and concentrate on automating the reporting of flaking tests.

Although we have talked about doing this from TestGrid I think it would make more sense to use the data provided by Triage to automate reporting of test flakes and failures. 

When I talk about _automation_ here I am referring to human triggered reporting of test issues based on either reacting to alerts or through the proactive monitoring of e2e tests.
