### ISSUE TITLE
Changelog problems

### ISSUE THREAD

**Issue by jessfraz** [kubernetes/release#155]
While doing the 1.4.3 release it errored out on the Changelog, so then I re-ran it with `--noclean` and I realized now it basically did the changelog twice: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md. I will submit a PR to fix it up. Not sure if that is avoidable though.

**Comment by david-mcmahon** [comment]
anago is not re-entrant ready.  Definitely ensure you can run a mock release prior to running a real release.  We can pick up the pieces if a real release fails in the middle, but it's easier if we just make sure it runs a successful mock first.   Still we can encounter issues with real releases.  If that happens, please forward logs and details to me so I can resolve.  cc @ixdy

**Comment by jessfraz** [comment]
makes sense! thanks!
