### ISSUE TITLE
[krel] Evaluate possible krel stage/release subcommands

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/release#1551]
In parallel to the ongoing anago to krel migration we will introduce new krel stage and krel release subcommands. The plan is to re-evaluate the current functionality within anago and build a declarative approach of cutting releases. We can re-use the already migrated parts as well as using the existing logic in anago as guidance for the necessary feature set of krel stage/release.

/help

**Comment by markyjackson-taulia** [comment]
After chatting with @saschagrunert, I will work on this.
/assign @markyjackson-taulia

**Comment by markyjackson-taulia** [comment]
Initial review completed and documented here: https://docs.google.com/document/d/18vENxC2c3uVsYbTTwlaSrb6X_-6I3fAZ_TtDg2IDDVw/edit#

@saschagrunert and I are meeting tomorrow morning to review and determine tasks

**Comment by markyjackson-taulia** [comment]
> Can I join?

Totally. I will DM you the details

**Comment by saschagrunert** [comment]
I think this is done
/close
