### ISSUE TITLE
Split-up integration and unit tests

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/release#1556]
The golang test execution takes too long for our CI to always succeed. A good refactoring would be to split-up integration and unit tests by a build tag. An example project how to achieve this can be found in the seccomp-operator. There we provide two Make targets to execute the e2e and unit tests:

https://github.com/kubernetes-sigs/seccomp-operator/blob/b292dd72053e9868d39e6d2063dcfb1f4454e99a/Makefile#L130-L137

We can say that our integration tests are in `cmd`, whereas all other tests in `pkg` are unit tests, so we only need to add an integration buildtag to the `*_test.go` files in `cmd` like:
```go
// +build integration
```
/assign @gianarb 
ref: https://kubernetes.slack.com/archives/C2C40FMNF/p1600420000006900?thread_ts=1600420000.006900&cid=C2C40FMNF

**Comment by justaugustus** [comment]
Ideally, completion of this issue will also include a new presubmits.
Name it `pull-release-integration` and have it closely mirror this configuration: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/release/release-config.yaml#L41-L55

Note that we should also set the `-timeout` flag for the integration tests. Let's try 15 minutes, since the test run is panicking around 10 minutes right now (ref: https://github.com/kubernetes/release/pull/1554#issuecomment-694724070)

**Comment by gianarb** [comment]
I am probably missing something but I have a couple of questions.

1. if we know that integration tests are only in `cmd`, why we need a build tag? We can run `go test ./cmd/...` for the `pull-release-integration` and `go test $(go list ./... | grep -v k8s.io/release/cmd)` for the unit tests.

2. If I use build tags with `go test -tags integration` I can **include** the integration tests, but it is not clear to me how I can run **only** them 

Thanks

**Comment by saschagrunert** [comment]
> I am probably missing something, but I have a couple of questions.
> 
> 1. if we know that integration tests are only in `cmd`, why we need a build tag? We can run `go test ./cmd/...` for the `pull-release-integration` and `go test $(go list ./... | grep -v k8s.io/release/cmd)` for the unit tests.

Hah, yeah this makes sense to me. I think we can do it this way to keep it simple.

> The seccomp operator runs the e2e tests from the tests package `$(GO) test -timeout 20m -tags e2e -count=1 ./test/... -v` (almost like I proposed in 1.). Not sure why it uses build tags as well.

It uses a build-tag because we were thinking about having tests in other directories than `pkg` as well. I think we probably could remove the build tag there, too :thinking:

**Comment by gianarb** [comment]
>  I think we probably could remove the build tag there, too

yeah, build tags are not exclusive but additive. You test or build everything that does not have a tag + what you tagged. So if you would like to `build/test` only what is tagged with a build tag it won't work
