### ISSUE TITLE
Oficial kube-proxy packege

### ISSUE THREAD

**Issue by dawidmalina** [kubernetes/release#156]
It would be very nice to have oficial package with kube-proxy. I can provide pull request for this if needed.

**Comment by ixdy** [comment]
cc @mikedanese @luxas

**Comment by mikedanese** [comment]
I don't think we want this. Our supported mechanism for deploying kube-proxy is in a container.

**Comment by dawidmalina** [comment]
Ok I understand. Motivation for having kube-proxy as native service is because I would like to disable privileged mode via kubelet `--allow-privileged=true`. Can you guys guide me what is the best approach? Or I should rather convinced myself that privilidged pod in my cluster are ok?

**Comment by dawidmalina** [comment]
@ixdy @mikedanese even if you will not use this package directly I think it would be good idea to have this package in oficial repository. I will prepare Pull Request just give me green light:)

**Comment by dawidmalina** [comment]
Ok. I will try proxy in docker.
