### ISSUE TITLE
Replace requirement for `cip-mm` with API usage in krel promote-images

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/release#1615]
#### What would you like to be added:

Right now `krel promote-images` checks if `cip-mm` is available in `$PATH`:
https://github.com/kubernetes/release/blob/bc552db2420afaa3e704c41afa93b15d2b3a7cfa/cmd/krel/cmd/promote-images.go#L146-L150

It would be good to use the already existing API to not have a need for the binary at all:
https://github.com/kubernetes-sigs/k8s-container-image-promoter/blob/4b2f14a1108a9cec649af5785ae4fbafac36a3e5/cmd/cip-mm/main.go#L76-L90

#### Why is this needed:

Reducing runtime dependencies makes the usage of the image promotion easier as well as reduces documentation overhead.

/cc @puerco

**Comment by saschagrunert** [comment]
#1615 got not finished, this is still free to pick since @justaugustus applied the necessary changes to the image promoter project.

**Comment by saschagrunert** [comment]
@puerco do you plan to work on this? We have an open discussion in our Google Doc related to it:
https://docs.google.com/document/d/1tXUHioi1dlobs_zvassr4InS-1pHH0cMUSZff5dTti4/edit?disco=AAAAKWGG05M

**Comment by puerco** [comment]
Sure I'll take it
/assign
