### ISSUE TITLE
[krel] gcbmgr should forbid nomock stage/releases on user forks

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/release#1630]
Right now we can specify a user fork like this to run `krel gcbmgr` on custom repository slugs:
```
> export TOOL_ORG=myself && \
  export TOOL_REPO=repo && \
  export TOOL_BRANCH=the-branch && \
  krel gcbmgr …
```

If the user specifies the `--nomock` flag, then we should disallow using anything other than `kubernetes/release:master`. This can be achieved by adding the functionality to the repository state verification there:

https://github.com/kubernetes/release/blob/6f3a537b8c25cd2264e3da28a3668a55e07bd318/pkg/release/repository.go#L88-L172

Tests can be added as well since we already unit-test this function.

/help
/good-first-issue

**Comment by saschagrunert** [comment]
Thanks for taking this one, @jlsong01 :pray: ! Feel free to reach out anytime if you have any questions.

**Comment by jlsong01** [comment]
@saschagrunert  Hi, I am new to the community. For the issue, what I need to do is:
1. add the implementation into CheckState() to check that "If the user specifies the --nomock flag, then we should disallow using anything other than kubernetes/release:master"
2. add ut for the CheckState to verify the added code is correct as expected

Is my understanding right?

**Comment by saschagrunert** [comment]
> @saschagrunert Hi, I am new to the community. For the issue, what I need to do is:
> 
> 1. add the implementation into CheckState() to check that "If the user specifies the --nomock flag, then we should disallow using anything other than kubernetes/release:master"
> 2. add ut for the CheckState to verify the added code is correct as expected
> 
> Is my understanding right?


Yep, that's correct :+1:

**Comment by jlsong01** [comment]
Here is my change plan, could you help to review it?
1. Add a bool parameter noMock into CheckState() as CheckState(expOrg, expRepo, expBranch string, noMock bool)
2. in CheckState(), if the current branch is NOT "kubernetes/release:master", then return with errors
3. add UT to verify the new added content

Another 2 questions:

1.  After code change, how to verify the result is correct or not? Currently i managed to compile and run krel gcbmgr successfully. but I have not account on Google Cloud Build (GCB). how to verify it?
2.  For ut, how should I do the ut for the change? do we have some command, toolkit, script for ut?

Thanks

**Comment by saschagrunert** [comment]
> Another 2 questions:
> 
> 1. After code change, how to verify the result is correct or not? Currently i managed to compile and run krel gcbmgr successfully. but I have not account on Google Cloud Build (GCB). how to verify it?
I'm happy to verify it for you. :)

> 2. For ut, how should I do the ut for the change? do we have some command, toolkit, script for ut?

We stick to testify (the golang package) and a mock-based testing approach. Let's discuss the details when the PR is open. :)

**Comment by jlsong01** [comment]
Hi, @saschagrunert , PR is open. Your feedback would be highly appreciated.

**Comment by saschagrunert** [comment]
This works now and is considered as finished.
/close
