### ISSUE TITLE
Reseed the git remote before starting the "release" phase of anago

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#1645]
#### What would you like to be added:

Reseed the git remote before starting the "release" phase of anago.

#### Why is this needed:

We may occasionally encounter scenarios where we need to rotate the @k8s-release-robot GitHub personal access token.

Sometimes, this needs to happen in-between the "stage" and "release" phases of a release.
In the event that it does, we essentially need to "throw out"/rerun the staged build (because the now-revoked credentials are stored as part of the staged build's git HTTP remote).

So at a bare-minimum, we should rerun the relevant functions (`lib/gitlib.sh`) that set the git HTTP remote (this should pull in the new token, assuming it's been updated in the GCB config before the run).

BONUS POINTS: Ensure the git HTTP remote gets removed prior to pushing to GCS.

@puerco initially expressed interest, but I'll tag this as help wanted if any other intrepid Release Manager Associates want to work on it.
/help 

cc: @kubernetes/release-engineering 
ref: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1602716642286500?thread_ts=1602693775.210300&cid=CJH2GBF7Y

**Comment by puerco** [comment]
What if we replace this entire block from gitlib.sh:

https://github.com/kubernetes/release/blob/b067ca634072851e41baaf71cb27a543bce3dc95/lib/gitlib.sh#L207-L233

with `krel anago sync-repo` and call that? less bash!

**Comment by justaugustus** [comment]
Go for it!
BONUS BONUS POINTS: Remove all of `lib/gitlib.sh`, but let's start small.

/assign @puerco 
/remove-help

**Comment by saschagrunert** [comment]
@puerco any update on this? Is it still in your scope of planned work?

**Comment by LappleApple** [comment]
From April 21, 2021 triage: @puerco will take a look at this again to decide what to do next

**Comment by saschagrunert** [comment]
I think this is not done yet 

/reopen
