### ISSUE TITLE
Migrate the vulnerability dashboard (vulndash) to k/release and enable the update job

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#1665]
(This is a port of https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/274 and https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/253)

I've done some initial work to enable 

- [x] migrate the vulnerability dashboard (`vulndash`) to k/release: https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/276
- [x] fixup image building for vulndash: https://github.com/kubernetes/release/pull/1662
- [x] update image locations, job refs in k/test-infra: https://github.com/kubernetes/test-infra/pull/19725
- [x] set the arch for the vulndash: https://github.com/kubernetes/test-infra/pull/19737
- [x] use absolute path for vulndash: https://github.com/kubernetes/test-infra/pull/19742

You can see the job history for `ci-k8sio-vuln-dashboard-update` [here](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-k8sio-vuln-dashboard-update).

As of writing this issue, we're getting the following [error](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-k8sio-vuln-dashboard-update/1321640222257057792):

```console
level=info msg="Updating the vulnerability dashboard..."
level=fatal msg="updating vulnerability dashboard: opening dashboard file: open /home/prow/go/src/k8s.io/release/cmd/vulndash/dashboard.html: no such file or directory" 
```

@cpanato -- I think this is in a good place for you to continue debugging, so I'm assigning this to you.

**Additional note...**

I also tried this out locally (with a different GCP project / GCS bucket) and got the following:

```console
$ time vulndash --project=k8s-staging-artifact-promoter --bucket=k8s-staging-artifact-promoter-gcb --dashboard-file-path=cmd/vulndash/ --log-level debug
DEBU Setting commands globally into verbose mode  
DEBU Using log level "debug"                       file="cmd/root.go:108"
INFO Updating the vulnerability dashboard...       file="cmd/root.go:129"
FATA updating vulnerability dashboard: Unable to upload latest version of dashboard HTML: storage.NewClient: dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.  file="cmd/root.go:73"

real	0m0.035s
user	0m0.029s
sys	0m0.016s
```

After fixing the `--dashboard-file-path` error, depending on the results, you may have to dig into the credential problem I pasted above :point_up: 

/assign @cpanato 
cc: @kubernetes/release-engineering 
/area security

**Comment by cpanato** [comment]
I'm testing locally the credentials, but did not get the error you mention

**Comment by justaugustus** [comment]
Latest failure is:

```console
 level=info msg="Updating the vulnerability dashboard..."
level=fatal msg="updating vulnerability dashboard: Unable to upload latest version of dashboard HTML: Writer.Close: Post \"https://storage.googleapis.com/upload/storage/v1/b/gs%3A%2F%2Fk8s-artifacts-prod-vuln-dashboard/o?alt=json&name=dashboard.html&prettyPrint=false&projection=full&uploadType=multipart\": metadata: GCE metadata \"instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control\" not defined"
```

ref: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-k8sio-vuln-dashboard-update/1321792478734454784

**Comment by cpanato** [comment]
now looks like related to permission in GCP, I think I don't have permissions to check the `k8s-infra-gcr-vuln-dashboard` service account 

I've set up a personal GCP project for me and create the svcacc with the permissions `Container Analysis Admin` and `Storage Admin` and running the vulndash works, maybe those permission are too wide :)

maybe @spiffxp can check that svcacc

**Comment by justaugustus** [comment]
FYI -- as of https://github.com/kubernetes/test-infra/pull/19748, the job is now correctly named `ci-release-vulndash-update`.

Here's the most recent run: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-release-vulndash-update/1321824946191601664
Overall job history is here: https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-release-vulndash-update

**Comment by spiffxp** [comment]
The job was using a KSA which was bound to a non-existent GCP SA, https://github.com/kubernetes/k8s.io/pull/1378 should fix

**Comment by cpanato** [comment]
Now the error is the bucket is not correct
```
level=fatal msg="updating vulnerability dashboard: Unable to upload latest version of dashboard HTML: Writer.Close: googleapi: Error 400: Invalid bucket name: 'gs://k8s-artifacts-prod-vuln-dashboard', invalid"
```
@justaugustus do you know in which gcp project is the bucket should be? Or the name is not the right one?

**Comment by cpanato** [comment]
Ahhh found the issue

Will open a pr

**Comment by cpanato** [comment]
@spiffxp now looks like we have some retention policy in the bucket, can you update that to fix it? thanks!

```
level=fatal msg="updating vulnerability dashboard: Unable to upload latest version of dashboard HTML: Writer.Close: googleapi: Error 403: Object 'k8s-artifacts-prod-vuln-dashboard/dashboard.html' is subject to bucket's retention policy and cannot be deleted, overwritten or archived until 2030-10-31T10:08:40.300944987-07:00, forbidden"
```

**Comment by spiffxp** [comment]
@cpanato I would prefer if releng made a PR to the appropriate scripts in k8s.io, I will run them once it's merged

I'm guessing this needs to be something different, or there need to be other special cases added after this call
https://github.com/kubernetes/k8s.io/blob/6b8214d386746c63c6e50de3f38bc981b0de2a7e/infra/gcp/ensure-prod-storage.sh#L392

**Comment by justaugustus** [comment]
Promoted the vulndash:v0.3.0 image in https://github.com/kubernetes/k8s.io/pull/1385.

**Comment by justaugustus** [comment]
> @cpanato I would prefer if releng made a PR to the appropriate scripts in k8s.io, I will run them once it's merged
> 
> I'm guessing this needs to be something different, or there need to be other special cases added after this call
> https://github.com/kubernetes/k8s.io/blob/6b8214d386746c63c6e50de3f38bc981b0de2a7e/infra/gcp/ensure-prod-storage.sh#L392

@spiffxp -- I've opened https://github.com/kubernetes/k8s.io/pull/1390 for this.

**Comment by spiffxp** [comment]
Current status: the job appears to be timing out at 2h
```
[36mINFO[0m Updating the vulnerability dashboard...      
[36mINFO[0m opening /home/prow/go/src/github.com/kubernetes/release/cmd/vulndash/dashboard.html 
[36mINFO[0m parsing /home/prow/go/src/github.com/kubernetes/release/cmd/vulndash/dashboard.html 
[36mINFO[0m uploading /home/prow/go/src/github.com/kubernetes/release/cmd/vulndash/dashboard.html to gcs 
[36mINFO[0m uploading updated dashboard.js to gcs        
[36mINFO[0m checking all vulnerabilities for k8s-artifacts-prod 
[36mINFO[0m listing the vulnerabilities, will take a while... 
{"component":"entrypoint","file":"prow/entrypoint/run.go:165","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 2h0m0s timeout","severity":"error","time":"2020-11-18T22:48:26Z"}
{"component":"entrypoint","file":"prow/entrypoint/run.go:247","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Process gracefully exited before 15m0s grace period","severity":"error","time":"2020-11-18T22:48:26Z"}
```

**Comment by cpanato** [comment]
@spiffxp maybe we increase a bit to check? i was thinking on that.

Also we can add more logs to see if is actually doing something.

thoughts?

**Comment by spiffxp** [comment]
Increasing log verbosity and timeout sgtm

**Comment by cpanato** [comment]
will open the PRs for that

**Comment by cpanato** [comment]
Running with debug mode and 6h timeout 
https://prow.k8s.io/log?job=ci-release-vulndash-update&id=1329499512300900352

**Comment by cpanato** [comment]
Still timing out
when I run that locally with my credentials it ran for 1-2 minutes and complete.

lets sync over slack

**Comment by cpanato** [comment]
job is running now, and some initial tweaks are done, closing this because we complete all items in the issue
/close
