### ISSUE TITLE
push-build.sh container image pushes should precede staging GCS artifacts and writing version markers

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#1693]
#### What happened:

Tracking issue for https://kubernetes.slack.com/archives/CJH2GBF7Y/p1604669572198400.
Noticed in https://github.com/kubernetes/test-infra/issues/19483.

Our attempts to move the `ci-kubernetes-build` to Community Infra are failing because container images are not successfully getting pushed.

Comment from @ameukam (https://github.com/kubernetes/test-infra/issues/19483#issuecomment-723118951):

> > do this via adding the service account e-mail address to the [k8s-infra-staging-ci-images@kubernetes.io](mailto:k8s-infra-staging-ci-images@kubernetes.io) group?
> 
> `ci-kubernetes-build-canary` still fails even after the service account is added (see [kubernetes/k8s.io#1393](https://github.com/kubernetes/k8s.io/pull/1393)) to [k8s-infra-staging-ci-images@kubernetes.io](mailto:k8s-infra-staging-ci-images@kubernetes.io) : https://testgrid.k8s.io/sig-testing-canaries#build-master-canary
> 
> `prow-build` service account inherits of the permissions of the role `roles/cloudbuild.builds.editor` as member of [k8s-infra-staging-ci-images@kubernetes.io](mailto:k8s-infra-staging-ci-images@kubernetes.io) :
> 
> https://github.com/kubernetes/k8s.io/blob/74bfdc5741bdde3b8f489bdd8327474101b3b5e4/infra/gcp/lib.sh#L209-L231
> 
> which is not enough to make the job successful.

That's a credential issue that needs to be fixed in parallel.

This issue is specifically for some of my expectations around push-build.sh behavior.

#### What you expected to happen:

1. Any build jobs should verify access to the container image registry before proceeding

This is a fail-fast scenario.
If we know that a build is supposed to push GCR images, we should check that we're able to do that first, instead of build artifacts and waiting for the container push failure at the end of the scenario.

2. The check for the existence of a build only checks for GCS bucket artifacts, not container images

In `scenarios/kubernetes_build.py`

https://github.com/kubernetes/test-infra/blob/329444781ba13be597917343cca4aa1b92366b6d/scenarios/kubernetes_build.py#L45-L84

If we consider a "complete" build to also include container images, this check should verify that those exist as well before claiming a build is not required.

3. A build should not push artifacts if it cannot guarantee that all of them will be available

The current push-build.sh logic:
https://github.com/kubernetes/release/blob/4c6b5aaa75a0de1adad64e02a7ca0a7eb7d81e68/push-build.sh#L867-L918

Here, we should probably attempt to publish artifacts in the following order:
1. container images 
2. GCS artifacts
3. version marker

That way, if images fail to push, then the build job fails before copying to GCS.
If there's nothing in the bucket, then the check in #1 will cause a new build to always be attempted.

@hasheddan -- I'll leave you to divide up the work as appropriate.

/assign @hasheddan @ameukam @cpanato 
cc: @kubernetes/release-engineering @spiffxp 
/priority critical-urgent

#### How to reproduce it (as minimally and precisely as possible):

See https://github.com/kubernetes/test-infra/issues/19483.

#### Environment:

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by justaugustus** [comment]
FYI @kubernetes/ci-signal, as this broadly explains some build job failures you may be seeing.

**Comment by spiffxp** [comment]
There is strong overlap with https://github.com/kubernetes/test-infra/issues/18808

Saving the version marker for last hopefully addresses most of the concerns that prevent us from overwriting incomplete builds.

**Comment by spiffxp** [comment]
Where do we stand on trying to make this happen in v1.21 timeframe?

**Comment by mkorbi** [comment]
looks like WIP
will we get this done in 1.22? 👍 
/remove-lifecycle stale
