### ISSUE TITLE
Release note targeting for multiple branches

### ISSUE THREAD

**Issue by david-mcmahon** [kubernetes/release#17]
There's no way to target different release note states for multiple branches due to the fact that the release note state is based on the one source PR, not the individual cherry-picks.

For example, #27861 seems like a good release note for 1.3 but we don't want it as a relnote for 1.2.5 (since it was rolled back). 

The fix probably entails checking the cherry-pick for a release note state and letting it override the source PRs state and then updating the cherry-pick doc to allow for that in these special circumstances.    I can't immediately think of any issues with that approach.

It will mean more processing time and github polling to check labels for both PRs for every merge pull.

cc @eparis @roberthbailey

**Comment by erictune** [comment]
Can the release note generator detect rolled back changes?

**Comment by david-mcmahon** [comment]
@erictune No.  I had considered adding that, but then our canonical method for exposing release notes is through labeling and that single interface provides more flexibility in deciding what should or should not be captured as a release note (rollback spanned releases, rollback itself was relevant for capturing the fact that a feature didn't make it in a release, etc).  Adding more moving parts here might confuse things.
