### ISSUE TITLE
ci-kubernetes-build-* jobs should build without requiring bootstrap.py scenarios

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#1711]
#### What would you like to be added:

Add machinery to replace the [`bootstrap.py`](https://github.com/kubernetes/test-infra/blob/master/jenkins/bootstrap.py) [`kubernetes_build.py`](https://github.com/kubernetes/test-infra/blob/master/scenarios/kubernetes_build.py) scenario.

#### Why is this needed:

- `bootstrap.py` is deprecated, but still in use for the Kubernetes build jobs
- `krel` and the underlying libraries are quickly replacing our shell tools. Ideally we should build in CI roughly the same way we do during the release process.

##### Now

- [x] (https://github.com/kubernetes/release/pull/1698) Create a `krel ci-build` command which mimics the `kubernetes_build.py` scenario
- [x] (https://github.com/kubernetes/release/pull/1700) Create the `k8s-ci-builder` image to support this use case
- [x] (https://github.com/kubernetes/release/pull/1710, https://github.com/kubernetes/test-infra/pull/19909) Enable image building
- [x] (https://github.com/kubernetes/test-infra/pull/19887, https://github.com/kubernetes/test-infra/pull/19889, https://github.com/kubernetes/test-infra/pull/19894) Create a Prowjob (`ci-kubernetes-build-no-bootstrap`) using the new image and `krel ci-build` command
- [x] (https://github.com/kubernetes/release/pull/1731, https://github.com/kubernetes/release/pull/1738) Don't attempt to set ACLs on K8s Infra buckets

  ref: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-build-no-bootstrap/1326345795653341184
  ```console
  FATA Failed to run:: publish release: publish release to GCS: change gs://k8s-release-dev/ci/latest-fast.txt permissions: executing gsutil: command /google-cloud-sdk/bin/gsutil acl ch -R -g all:R gs://k8s-release-dev/ci/latest-fast.txt did not succeed: CommandException: Failed to set acl for gs://k8s-release-dev/ci/latest-fast.txt. Please ensure you have OWNER-role access to this resource.
  ```

- [x] (https://github.com/kubernetes/release/pull/1731, https://github.com/kubernetes/release/pull/1738) Properly handle jobs with GCS Suffix
  - [x] (https://github.com/kubernetes/release/pull/1738) Version markers write to `BuildType` path instead of `BuildType` + `GCSSuffix`
- [x] (https://github.com/kubernetes/release/pull/1713) Validate images when checking if build exists
- [x] (https://github.com/kubernetes/release/pull/1738) Add basic tests (prioritize version and path handling)

##### Later

- [x] Cleanup unnecessary flags
- [x] (https://github.com/kubernetes/release/pull/1710) Pull krte wrapper script into build job
- [x] (https://github.com/kubernetes/release/pull/1710) Set up per-branch build job variants
- [ ] Cut over jobs (in order of fastest signal and lowest impact)
  - [x] `canary`: https://github.com/kubernetes/test-infra/pull/20663
  - [x] `canary` release branch jobs: https://github.com/kubernetes/test-infra/pull/20755
  - [ ] `master`
  - [ ] fast
  - [ ] release branch jobs
- [ ] Deprecate `kubernetes_build.py`
- [ ] Ensure build jobs have RelEng alerts:
  - [x] manual: https://github.com/kubernetes/test-infra/pull/19797
  - [ ] presubmit-based: 
- [ ] Prevent bootstrap images from being used for build jobs

This is related to https://github.com/kubernetes/release/issues/1693 and https://github.com/kubernetes/test-infra/issues/19483, but can be completed in parallel.

/assign

**Comment by spiffxp** [comment]
Where do we stand on the "cut over jobs" part of this, will this happen in v1.21 timeframe?

**Comment by justaugustus** [comment]
> Where do we stand on the "cut over jobs" part of this, will this happen in v1.21 timeframe?

https://github.com/kubernetes/test-infra/pull/20663

**Comment by xmudrii** [comment]
cc @saschagrunert to check the status with @justaugustus

**Comment by saschagrunert** [comment]
@justaugustus can we carve-out the open points and hand it over to a release manager (associate)?

**Comment by spiffxp** [comment]
Is the checklist above accurate for what remains to be done?
