### ISSUE TITLE
[krel] Add krel anago subcommand to check prerequisites

### ISSUE THREAD

**Issue by markyjackson-taulia** [kubernetes/release#1739]
As noted in #1673, add krel anago subcommand to check Prerequisites

**Comment by saschagrunert** [comment]
Hey @markyjackson-taulia, I think you can directly integrate the functionality into the new structure (krel stage/release), like:

https://github.com/kubernetes/release/blob/b4ca2f60c7b46eb86d118b9a9af0811b89e71cb1/pkg/anago/stage.go#L245
https://github.com/kubernetes/release/blob/b4ca2f60c7b46eb86d118b9a9af0811b89e71cb1/pkg/anago/release.go#L243

**Comment by markyjackson-taulia** [comment]
@saschagrunert awesome! I will have this completed by end of my day US west last time.
