### ISSUE TITLE
krel release-notes mapping to remove entry

### ISSUE THREAD

**Issue by wilsonehusin** [kubernetes/release#1786]
#### What would you like to be added:
With the new mapping feature of running `krel release-notes --fix`, would be nice if we can also override a release note entry to be removed.

#### Why is this needed:
One use case that came up is that PR was reverted and PR author isn't responsive. This will remove the extra manual step at the end of release notes collection.

#### Notes:
Conversation [was started on Slack](https://kubernetes.slack.com/archives/C2C40FMNF/p1606242358207300).

/sig release
/kind feature

**Comment by saschagrunert** [comment]
Do you already have an idea how this would look like from a usability perspective?

**Comment by puerco** [comment]
My $0.02 from what I was writing:

I was working on adding a datafield to the map, marking the PR as overriding another. Like this:
```yaml
pr: 123
datafields:
    reverts: 12345
releasenote:
  author: xxxxx
```
Where 12345 is the old PR with the reverted change, which would not show up when rendering the doc.

**Comment by wilsonehusin** [comment]
(I wrote this before reading @puerco's comment above)

In my mind at the moment is to have an extra field as `ReleaseNotesMap.ReleaseNote.ForceNone bool`
https://github.com/kubernetes/release/blob/f2b80b72191a30935455009a2af8f069df293989/pkg/notes/notes_map.go#L80-L115

That said, I'm not sure how implementable that path would be. Ideally, I probably would want the user to be able to run `krel relase-notes ... --remove-notes` offline because I would know ahead of time on which PR number I want gone, without having to go through each PR in `--fix`

**Comment by saschagrunert** [comment]
Adding a new field seems reasonable to me. I would stick to something less specific than `reverts`, because there could be other reasons to remove a note. How about just calling the field `removed: true`?

We could add a third option to the edit question "Fix note for PR #%d? (y/N)" about removing it, like: "Fix note for PR #%d? (y/N/r)". (`r` for delete)
