### ISSUE TITLE
Allow for staged release steps for milestone releases

### ISSUE THREAD

**Issue by david-mcmahon** [kubernetes/release#18]
This came up today as we're approaching the 1.3 release.  There's not much time to do anything (carefully) for this release, but for 1.4 lets collect the requirements here for allowing for a staged release process, if needed.

This is related to the timing of press announcements and PM engagements as we approach a release.  To move ahead here we'll need to collect some requirements.

@aronchick

**Comment by ixdy** [comment]
Embargoed security releases are another example.

**Comment by david-mcmahon** [comment]
Progress has been made here.  Releases can now be staged, handling ~80% of the workload of a release, in preparation for the final release step.
