### ISSUE TITLE
[RFC] Do we need an API package?

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#1819]
As we start to build more and more tools, bake them into processes, and publicize them, it'll will become even more important that consumers are resilient to refactors, while having the opportunity to try out new functionality.

So, some questions for you all...

- Do you think we have an API?
- If so, what is it?
- Do you think we need an `api/` folder?
- If so, what goes in it?
- What does it mean to release a patch, minor, or major release of this repo?

p.s. "I don't think we need an API and what we're doing today works" is a perfectly acceptable answer. :)

cc: @kubernetes/release-engineering

**Comment by saschagrunert** [comment]
> * Do you think we have an API?

Yes, I already use k/release in some other projects as direct dependency.

> * If so, what is it?

Mostly CI automation about release branch forwarding/creating and release notes generation. So those packages are actively used:
- k8s.io/release/pkg/command
- k8s.io/release/pkg/git
- k8s.io/release/pkg/github
- k8s.io/release/pkg/util

If we think about kubetest2, then we also use the `k8s.io/release/pkg/build` package directly.

> * Do you think we need an `api/` folder?

No, what we could do is hiding some packages in `k8s.io/release/internal` and still have everything public in `pkg`. This seems more idiomatic golang to me.

> * If so, what goes in it?
> * What does it mean to release a patch, minor, or major release of this repo?

We could think about releasing a `1.0.0` and strictly follow semver. I'd be in favor of that, but before doing so we should probably make everything internal and decide which API we really need to be public. I'd like to see that we never expose internally used types, which gives us the freedom to maintain an `internal` API as well as an external one. Both should not be dependent on each other.

**Comment by justaugustus** [comment]
https://github.com/kubernetes/release/pull/1934 is the current plan.

**Comment by cpanato** [comment]
@justaugustus @saschagrunert in the RelEng meeting today we said that can be closed and if needed we can open follow-up issues.

I will close this, but if I did that wrong just reopen it. thanks!

/close
