### ISSUE TITLE
Add machine readable description of platforms

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/release#1836]
#### What would you like to be added:

A machine-readable file describing the platforms (OS / architecture) that each binary is expected to be released for (xref https://github.com/kubernetes/sig-release/pull/1360).

#### Why is this needed:

This description will allow krel to perform checks on produced artifacts and make sure that the artifacts that are intended to be released actually are being released.

/assign

**Comment by hasheddan** [comment]
@justaugustus @saschagrunert thinking about this a little more, I wonder if it may make sense for this to live in k/k. Krel theoretically should be able to run a release for any project, so it seems the project itself should indicate the artifacts that it intends to be released. This could be a standard that we define for "krel-releasable" projects, in which case maybe we add that standard in this repo and then add an implementation in k/k. Thoughts?

**Comment by hasheddan** [comment]
@dims in case you have any thoughts on this as well :)

**Comment by hasheddan** [comment]
This could also be related to #1819 if we want to have a formal specification.

**Comment by dims** [comment]
@hasheddan it would make sense to reach out to @swinslow from LF to have a chat as it looks like there is scanning to SPDX that's being done:
https://github.com/lfscanning/spdx-cncf/tree/master/kubernetes/2020-02

Also related:
https://github.com/cncf/foundation/issues/6

The license exceptions granted by CNCF for non-standard licenses are also in SPDX:
https://github.com/cncf/foundation/blob/master/license-exceptions/README.md

**Comment by hasheddan** [comment]
Thanks @dims! This looks pretty important in regards to the BOM effort, but I am not sure it directly relates the list of supported platforms that we intend to release

**Comment by saschagrunert** [comment]
> Krel theoretically should be able to run a release for any project,

`krel stage/release` is tightly scoped to Kubernetes, so it seems fine to me to stick to k/release. I can imagine that we have an API for checking binaries of different formats (like elf) against a set of criterias (like ABI or ISA).

**Comment by dims** [comment]
whoops! sorry my head was still in the BOM :)

**Comment by hasheddan** [comment]
> krel stage/release is tightly scoped to Kubernetes, so it seems fine to me to stick to k/release.

@saschagrunert this is definitely true today, but some of the original discussion when krel was started was around moving towards more generally applicable tooling, which I think could influence this decision if we still have that goal.

**Comment by saschagrunert** [comment]
@hasheddan I see your point. From a usability perspective, would it be better if the definitions live in k/k? Let's say we add/remove a binary, then it probably would make more sense for developers to modify the definition in k/k.

On the other hand: Let's assume that SIG Release owns the definitions. It's easier for us to change it in k/release rather than modifying k/k which might lead into a release blocker.

**Comment by hasheddan** [comment]
@saschagrunert @justaugustus I am leaning towards something like a `.krel.yml` file in repos that krel releases. I think we should add an API in the form of Go structs in k/release that defines the schema for declaring binaries / images that should be produced. We could start with a `kubernetes.krel.yml` in k/release and test this out for a while before moving it to k/k, how does that sound?

**Comment by saschagrunert** [comment]
> how does that sound?

Sounds good to me! :+1:
