### ISSUE TITLE
Update cri-tools in k/kubernetes to v1.20.0

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/release#1838]
cri-tools v1.20.0 has been release a couple of days ago: https://github.com/kubernetes-sigs/cri-tools/releases/tag/v1.20.0

We now have to update it in the main Kubernetes repository, too. Before doing that, we also have to make sure that the cri-tools binaries from the GitHub release are available in the SIG Release production bucket.

Steps to be done:

1. Ask one of the @kubernetes/release-managers to upload the binaries for you
2. Create a PR similar to https://github.com/kubernetes/kubernetes/pull/94307 to update cri-tools

Please make sure that the CI passes and uses the new version. It is also recommended to grep the whole k/kubernetes repository for newly added occurrences of cri-tools.

/assign @rajibmitra

**Comment by rajibmitra** [comment]
#https://github.com/kubernetes/kubernetes/pull/97967

**Comment by saschagrunert** [comment]
This is done
/close
