### ISSUE TITLE
GCP "extra" staging files are always skipped for a make build

### ISSUE THREAD

**Issue by amwat** [kubernetes/release#1840]
#### What happened:
```
Skipping not existing extra dir `_output/gcs-stage/$VERSION/extra `
```
#### What you expected to happen:
`extra/` is staged
#### How to reproduce it (as minimally and precisely as possible):
`kubetest2 gce --build --strategy=make --stage=gs://my-bucket`
#### Anything else we need to know?:
looks like we only stage if `extra/` already exists under `_output/gcs_stage/$VERSION` whereas the files are actually coming from `_output/release-stage/full/kubernetes/cluster/gce`
https://github.com/kubernetes/release/blob/d1fdfdc96f964beedcab6f29048229ead1d871ca/pkg/build/push.go#L297-L298

which doesn't exist since we recreate a clean directory on https://github.com/kubernetes/release/blob/d1fdfdc96f964beedcab6f29048229ead1d871ca/pkg/build/push.go#L284-L287 

Seems to work for bazel builds since they output an `extra/` directory under `release-tars` which gets copies over in 
https://github.com/kubernetes/release/blob/d1fdfdc96f964beedcab6f29048229ead1d871ca/pkg/build/push.go#L290-L295
#### Environment:

/cc @saschagrunert

**Comment by saschagrunert** [comment]
Thank you for the report @amwat, it looks like that we can remove the corresponding code parts.
/priority important-soon
