### ISSUE TITLE
Fail to get release-notes on MacOSX Big Sur

### ISSUE THREAD

**Issue by stafot** [kubernetes/release#1862]
#### What happened:

Running `GO111MODULE=on go get k8s.io/release/cmd/release-notes` failing and resulting the following errors
```
go: found k8s.io/release/cmd/release-notes in k8s.io/release v0.6.0
# github.com/shirou/gopsutil/disk
.go/pkg/mod/github.com/shirou/gopsutil@v3.20.10+incompatible/disk/disk_darwin.go:64:52: cannot use stat.Mntfromname[:] (type []int8) as type []byte in argument to common.ByteToString
.go/pkg/mod/github.com/shirou/gopsutil@v3.20.10+incompatible/disk/disk_darwin.go:65:50: cannot use stat.Mntonname[:] (type []int8) as type []byte in argument to common.ByteToString
.go/pkg/mod/github.com/shirou/gopsutil@v3.20.10+incompatible/disk/disk_darwin.go:66:51: cannot use stat.Fstypename[:] (type []int8) as type []byte in argument to common.ByteToString
.go/pkg/mod/github.com/shirou/gopsutil@v3.20.10+incompatible/disk/disk_darwin.go:77:44: cannot use stat.Fstypename[:] (type []int8) as type []byte in argument to common.ByteToString
```

#### What you expected to happen:
Successfully get `release-notes` 
#### How to reproduce it (as minimally and precisely as possible):
Run  `GO111MODULE=on go get k8s.io/release/cmd/release-notes`

#### Anything else we need to know?:
Other projects reported similar problems for macos and freebsd. [ref1](https://github.com/IBM/the-mesh-for-data/issues/216), [ref2](https://github.com/shirou/gopsutil/issues/853), [ref3](https://github.com/Velocidex/velociraptor/issues/707) 
There is a proposed workaround which I could raise PR for if no objections and if there is no better alternative/solution. [ref](https://github.com/IBM/the-mesh-for-data/pull/217)

#### Environment:

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): MacOS Big Sur Version 11.1 (20C69)
- Kernel (e.g. `uname -a`): `Darwin Kernel Version 20.2.0`
- Others: `go version go1.15.6 darwin/amd64`

**Comment by saschagrunert** [comment]
Hey @stafot, thank you for opening the issue! :pray: 

I think this issue is not valid for the `master` any more. Adding a few tests around cross compilation and releasing a new version of this library should already solve the issue.

**Comment by stafot** [comment]
@saschagrunert Ack and thanks. So my alternative is to get the latast `master` instead of use `go get` for the latest release and build it through the tooling provided for my platform? Is my understanding correct?

**Comment by saschagrunert** [comment]
> @saschagrunert Ack and thanks. So my alternative is to get the latast `master` instead of use `go get` for the latest release and build it through the tooling provided for my platform? Is my understanding correct?

Yep, can you verify that this works for you?

**Comment by stafot** [comment]
@saschagrunert Yes, building it from `master` on my local did the trick. Thanks for the advice. Before your PR got merged.

**Comment by saschagrunert** [comment]
Thanks for the verification @stafot, lets close this for now. We can create a new release soon'ish.

/close
