### ISSUE TITLE
relnotes: incorrect escaping of '#' in CHANGELOG files

### ISSUE THREAD

**Issue by tpepper** [kubernetes/release#1873]
#### What happened:

https://github.com/kubernetes/kubernetes/pull/98209 noted one broken link.  That turned into a couple dozen broken links on closer inspection.  It looks like '#' is being escaped in the markdown file to "&#35;".

For normal html you can get a '#' from "&#35;" apparently and that works fine in some cases:
https://github.com/kubernetes/kubernetes/blame/master/CHANGELOG/CHANGELOG-1.19.md#L1319
```    cachingMode: None  &#35; ReadOnly host caching is not available for premium SSDs with maxShares>1```

When the '#' is meant to be an anchor relative to an url the encoding leads to a 404 error, eg: 
https://github.com/kubernetes/kubernetes/blame/master/CHANGELOG/CHANGELOG-1.19.md#L920
```https://kubernetes.io/docs/setup/release/version-skew-policy/&#35;kube-controller-manager-kube-scheduler-and-cloud-controller-manager```
which [then leads to a 404](https://kubernetes.io/docs/setup/release/version-skew-policy/&#35;kube-controller-manager-kube-scheduler-and-cloud-controller-manager).

#### What you expected to happen:

Urls with anchors should not 404 due to improperly escaped '#'

#### How to reproduce it (as minimally and precisely as possible):

Initial looking with @wilsonehusin did not show where in the relnotes code (or deps) this is coming from.  Needs more investigation.

Once the generator is fixed a scrub should be done (eg: ```git grep -e "&#35;"```) to make sure there aren't any other docs' urls needing fixed up.

**Comment by puerco** [comment]
I think sascha already fixed this in https://github.com/kubernetes/release/pull/1715. Have you seen more recent cases of this bug?

I still see some links encoded wrong in the 1.20 changelog but they date back to the alphas and none in the 1.21 changelog so far. Let's see if we get more instances after generating the notes for 1.21-alpha.2

/assign

**Comment by puerco** [comment]
I've been looking at the latest release notes runs and we have not seen another instance of this bug. I'm going to close this one for now, feel free to reopen if one shows up.
/close
