### ISSUE TITLE
[RFC] etcd images do not get consistently updated. Should RelEng manage?

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#1887]
#### What happened:

I've noticed as a result of the Release Managers group working on base image updates, that we're usually the ones to make changes to the `cluster/images/etcd` in kubernetes/kubernetes: https://github.com/kubernetes/kubernetes/commits/master/cluster/images/etcd

However, while we have permissions to the etcd staging project, we're not the primary owners, so we don't take care of the image promotion there.

The result is more than a few etcd images get missed in promotion.
I've backfilled a few of the recent image bumps here: https://github.com/kubernetes/k8s.io/pull/1591

RelEng-wise, our process is roughly:
- PR to update `debian-base`
- PR to promote `debian-base`
- PR to update `debian-iptables`
- PR to promote `debian-iptables`
- PR to update `debian-hyperkube-base`
- PR to promote `debian-hyperkube-base`
- PR to update Debian base image references in kubernetes/kubernetes (which includes the etcd image)
- Cherry picks, as needed

This is already cumbersome and you can see from the list that the etcd image is not included in it.
If the etcd image definition lived in k/release, we could make this a part of the steps where we update/promote `debian-iptables`.

Let me know what you think and if there are blockers that I'm not considering.

For feedback/approval

[`cluster/images/etcd/OWNERS`](https://github.com/kubernetes/kubernetes/blob/master/cluster/images/etcd/OWNERS): @jpbetz @wenjiaswe 
[`cluster/images/OWNERS`](https://github.com/kubernetes/kubernetes/tree/master/cluster/images/OWNERS): @justaugustus (lol)

cc: @kubernetes/release-engineering @kubernetes/sig-api-machinery-feature-requests @dims

**Comment by wenjiaswe** [comment]
@justaugustus thanks for bringing this up. I agree with you. I am not very familiar with RelEng team but for base image updates, RelEng probably knows better than etcd people, while etcd image owner could still be responsible for etcd image upgrade that's related to etcd change itself, like etcd version update when needed (e.g. https://github.com/kubernetes/kubernetes/pull/94287).

Could you please explain a little more about how to have "the etcd image definition lived in k/release"?

cc @ptabor @gyuho

**Comment by justaugustus** [comment]
> Could you please explain a little more about how to have "the etcd image definition lived in k/release"?

@wenjiaswe -- Sure! Concretely, this would mean:
- moving `k/k/cluster/images/etcd` (and any other related etcd image directories) to k/release/images
- configuring the image building jobs to point at k/release instead of k/k
- keeping the etcd image version up to date in our dependencies.yaml, like this: https://github.com/kubernetes/release/blob/139ec19a4303f169f9f9935244b77f74f803becc/dependencies.yaml#L49-L56

We would copy across the current image OWNERS, so you'd still be tagged for reviews/approvals.

**Comment by saschagrunert** [comment]
Had a short look at the contents of `k/k/cluster/images/etcd` and the whole directory seems fairly isolated from the rest of k/k. So I'm in favor of moving it over here.

**Comment by liggitt** [comment]
I'm -1 on moving non-trivial images to kubernetes/release for the same reasons discussed in https://github.com/kubernetes/release/pull/1545#issuecomment-692192276

**Comment by dims** [comment]
Agree with @liggitt

**Comment by justaugustus** [comment]
SGTM!
/close
