### ISSUE TITLE
[KREL] Allow specifying the kubernetes repo root

### ISSUE THREAD

**Issue by amwat** [kubernetes/release#1891]
#### What would you like to be added:
Add a RepoRoot (or equivalent) attribute to the build `Options` to specify the kubernetes repo path.
#### Why is this needed:
Currently KREL needs to be run from the kubernetes repo root, making it customizable makes it easier to use from CI (e.g. kubetest2 https://github.com/kubernetes-sigs/kubetest2/pull/89/files/ab0692e57492ce18bfc8d6e8bc74b7d78c150de3#r569042995 )

/cc @BenTheElder @saschagrunert

**Comment by saschagrunert** [comment]
Hey @amwat, yeah I think this makes sense, right now we implicitly assume that we're already within a repository. Do you wanna work on that or should we take it over?

**Comment by amwat** [comment]
Thanks for confirming! Yeah, I can work on it (unless someone gets to it before me).
I'll take a look at this tomorrow (PT)

**Comment by saschagrunert** [comment]
Sounds great, thank you! :pray:
