### ISSUE TITLE
relnotes.k8s.io is missing the latest patches

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/release#1892]
The [Kubernetes Release Notes](https://github.com/kubernetes-sigs/release-notes) website is missing the latest patch releases. We should give the website some love and add the missing ones for now.

/priority important-soon
/help
/cc @kubernetes/release-managers

**Comment by mkorbi** [comment]
/assign @mkorbi 
happy to do that!

**Comment by mkorbi** [comment]
https://github.com/kubernetes/sig-release/pull/1452
@saschagrunert

**Comment by saschagrunert** [comment]
> [kubernetes/sig-release#1452](https://github.com/kubernetes/sig-release/pull/1452)
> @saschagrunert

This PR goes to the wrong repository :) We have to update the website, which lives in https://github.com/kubernetes-sigs/release-notes
