### ISSUE TITLE
Add a check to ensure release binaries have the correct tag versions before publishing

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#1898]
#### What would you like to be added:

From @kfox1111 in https://github.com/kubernetes/kubernetes/issues/97178#issuecomment-747606759:

> Since this has happened before, could a unit test of some kind be added to check the output of the built kubectl version before pushing any artifacts?

#### Why is this needed:

See: https://github.com/kubernetes/kubernetes/issues/97178

/assign @hasheddan @puerco

**Comment by puerco** [comment]
:+1: this is one of the two new checks to binaries coming with the Bill of Materials, I've added this issue to the BOM to track it there: https://github.com/kubernetes/release/issues/1837
