### ISSUE TITLE
spec files for "building" rpms of kube-{controller-manager,scheduler,apiserver}

### ISSUE THREAD

**Issue by SEJeff** [kubernetes/release#190]
There is a great [kubelet spec file](https://github.com/kubernetes/release/blob/master/rpm/kubelet.spec) for building rpms for the kubelet. It would be nice to have the same for these:

* kube-apiserver
* kube-scheduler
* kube-controller-manager

**Comment by ixdy** [comment]
I think the plan is to use Bazel for building these RPMs? @kad

**Comment by kad** [comment]
Yes, eventually we want that bazel builds will produce packages.
