### ISSUE TITLE
handle release tags as versions correctly

### ISSUE THREAD

**Issue by ixdy** [kubernetes/release#191]
It seems like when a new release is tagged, the release scripts can't parse the version correctly.
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-build-1.3/138
```
Unable to get latest version from build tree!

kubectl version output:
Client Version: version.Info{Major:"1",
Minor:"3+", GitVersion:"v1.3.11-beta.0",
GitCommit:"759dd0dfb826658c78db42d97b77b9594cd43333", GitTreeState:"clean",
BuildDate:"2016-11-03T19:27:58Z", GoVersion:"go1.6.2", Compiler:"gc",
Platform:"linux/amd64"}
```

The issue seems to be that there's no `.#commits+sha` at the end of the version string, since there are no additional commits on the tag, but https://github.com/kubernetes/release/blob/master/lib/gitlib.sh#L42 expects the `.#commits+sha` suffix.

**Comment by david-mcmahon** [comment]
Yes, push-build.sh introduced a new use for that regex.  I'll have a look.

**Comment by ixdy** [comment]
This isn't the first time we've run into issues like this... https://github.com/kubernetes/kubernetes/issues/24535 and https://github.com/kubernetes/kubernetes/pull/24825 also reference it.

I'm still not sure what's doing the wrong thing. :)

**Comment by ixdy** [comment]
Both the 1.3 and 1.4 builds are broken on Jenkins because of this.

**Comment by david-mcmahon** [comment]
Those earlier issues were related, but I think the issue here is that we shifted the push activity to the release repo but the release repo never had to validate versions sans `+sha`.  So this was just an oversight/bug at the time we moved to `push-build.sh`, so the regex needs to be made CI friendly.
