### ISSUE TITLE
Release Notes Draft in k/sig-release to be submitted under release-notes/

### ISSUE THREAD

**Issue by wilsonehusin** [kubernetes/release#1919]
#### What would you like to be added:

The current `krel` behavior submits `release-notes-draft.{json,md}` to [`releases/release-1.21/` directory of `k/sig-release`](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.21). I'd like to propose a change that we move these two files to be under `release-notes` directory of each release, together with the maps and sessions files and folders.

#### Why is this needed:

Currently only release team lead and lead shadows have approvers access on `releases/release-1.21/` directory. By having all release notes artifacts be in a specific directory, we can have release notes lead to be approver in that directory, which allows quicker iteration for release notes team. This is important because the current workflow is a merge conflict magnet if PRs are not merged quickly.

#### Impact:

I know on top of my head `krel release-notes` need to change that behavior, but I suspect the scope of impact is more than that, since a minor release will capture the `release-notes-draft.md` on release and there is a work in progress for relnotes.k8s.io to point towards `release-notes-draft.json`.

---

Thoughts?

/cc @saschagrunert @puerco @cartyc

**Comment by saschagrunert** [comment]
Yeah I think this makes sense :+1:

**Comment by puerco** [comment]
I agree completely. The idea behind the release-notes directory where the maps live was to delegate full ownership to the relnotes team. It males sense to have the draft in there :)
