### ISSUE TITLE
Adjust Logging for Zeitgeist

### ISSUE THREAD

**Issue by onlydole** [kubernetes/release#1935]
#### What happened:

We should either tweak zeitgeist logging or tweak the prow config because right now it outputs:

```sh
INFO Validating zeitgeist options...              
ERRO /home/prow/go/src/k8s.io/kubernetes/build/dependencies.yaml indicates that coredns-kube-up should be at version 1.7.0, but the following files didn't match: cluster/addons/dns/coredns/coredns.yaml.base, cluster/addons/dns/coredns/coredns.yaml.in, cluster/addons/dns/coredns/coredns.yaml.sed 
FATA Dependencies are not in sync                 
+++ exit code: 1
+++ error: 1
FAILED   verify-external-dependencies-version.sh    40s
Verifying verify-vendor-licenses.sh
```

#### What you expected to happen:

`FATA`, `ERRO` are not highlighted in the log viewer (unlike error)
(and the job outputs many lines that are not errors)

#### How to reproduce it (as minimally and precisely as possible):

Run a task and view the highlighted logs.

#### Anything else we need to know?:

N/A

**Comment by justaugustus** [comment]
Slack thread: https://kubernetes.slack.com/archives/C2C40FMNF/p1614878190178700

**Comment by BenTheElder** [comment]
so it seems the output is also breaking shell2junit (see thread above), so we don't get structured pass fail for `make verify`. we probably just want a mode to disable coloring etc. we should check if logrus has this OOTB with something like `TERM`

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/release-utils/blob/82d28490440ddfd54696fd3803210850fcc688b8/log/log.go#L35 prevents `CLICOLORS` etc. from working.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/release-utils/pull/3

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/pull/99810#issuecomment-791013609

Confirming that we get structured results again with the colors disabled.

Right now using a workaround to drop them externally to the process. To land this in zeitgeist we'll perhaps need a release-utils tag containing https://github.com/kubernetes-sigs/release-utils/pull/3, update the version used in zeitgeist, and then update zeitgeist in k/k.

**Comment by justaugustus** [comment]
> Right now using a workaround to drop them externally to the process. To land this in Kubernetes we'll perhaps need a release-utils tag containing [kubernetes-sigs/release-utils#3](https://github.com/kubernetes-sigs/release-utils/pull/3), update the version used in zeitgeist, and then update zeitgeist in k/k.

Opened https://github.com/kubernetes-sigs/zeitgeist/pull/37 for this.

**Comment by BenTheElder** [comment]
Thank you!

In the meantime kubernetes is already using some clever bash (if I do say so myself) to strip out the terminal escape sequences so we can continue getting structured results from the wrapper, which helps surface failures. We can drop this when zeitgeist is ready (it's a single, easily revertable commit in https://github.com/kubernetes/kubernetes/pull/99810).

It would also still be nice to have some layer of invoking the tool (the script, the tool itself) output a greppable string like "failed", "failure", or "error" similar to other verify tools.

**Comment by cpanato** [comment]
@onlydole this still an issue?

**Comment by BenTheElder** [comment]
at kubernetes HEAD I still see that `CLICOLOR=0 CLICOLOR_FORCE=0` is not respected.

**Comment by BenTheElder** [comment]
I updated zeitgeist to v0.3.0 and it still doesn't work. The current pipe / sed workaround in kubernetes works but is a bit ugly. Ideally tools should have some way to disable escape codes, currently it seems anything using this log package cannot.

Besides shell2junit issues / desiring to process the log output easily there are CI environments that poorly emulate a terminal tty environment.

It would also still be nice to either print things that match the existing regexes or update prow.k8s.io's config to highlight these, as FATA etc. is not highlighted in prow.k8s.io, that part is both unchanged and not attempted to be changed yet.

**Comment by cpanato** [comment]
thanks @BenTheElder do you have a job execution that I can see, I will try my best to get this fixed, but I would like to understand what is going on.

thanks

**Comment by BenTheElder** [comment]
> thanks @BenTheElder do you have a job execution that I can see, I will try my best to get this fixed, but I would like to understand what is going on.

pull-kubernetes-verify

though I think it's easier to work with locally with running hack/verify-external-dependencies.sh

https://github.com/kubernetes/test-infra/blob/50cc7c5db83d7f21b70164ebbb080efe07039475/prow/spyglass/README.md#L92
https://github.com/kubernetes/test-infra/blob/9d41255bf9c00802cb02031e1e82cf21f15759c3/config/prow/config.yaml#L60
(note: we have to run these over all log lines of all viewed logs, so it's not the most preferable to add many of them)

**Comment by cpanato** [comment]
did some changes and now the color does not show up, but the logs are slight different, not sure if that is ok, so checking

```
level=error msg="/Users/cpanato/code/src/k8s.io/kubernetes/build/dependencies.yaml indicates that k8s.gcr.io/debian-base: dependents should be at version buster-v1.9.1, but the following files didn't match: cluster/images/etcd/Makefile, cluster/images/etcd/Makefile, cluster/images/etcd/Makefile, cluster/images/etcd/Makefile, cluster/images/etcd/Makefile"
level=fatal msg="error during command execution: checking local dependencies: Dependencies are not in sync"
```

before:
![Screenshot 2021-09-08 at 11 36 53](https://user-images.githubusercontent.com/4115580/132485434-62a8298f-d374-4b6f-a24c-e827f6cb9315.png)


after:

![Screenshot 2021-09-08 at 11 37 10](https://user-images.githubusercontent.com/4115580/132485469-5ed7498e-d8fd-4902-920a-adccff1f0e3f.png)


cc @BenTheElder

**Comment by BenTheElder** [comment]
I think the previous format was a bit easier to read but at least this one will highlight.

We're still relying on the bash hack to deal with lack of support for disabling color as well, which is not great. IMHO that should work regardless of format but ...

**Comment by cpanato** [comment]
agree, but looks like that is some way that the login lib works, I tried to make it similar but looks like when you disable it changes for format, I will dig a bit more, but if this is ok to we have I will move forward and make the changes in our side

thanks for your feedback @BenTheElder

**Comment by BenTheElder** [comment]
/reopen
was this ever fixed to revert https://github.com/kubernetes/kubernetes/pull/99810#issuecomment-791013609 hack? (only if we have also actually gotten colors disabled)
