### ISSUE TITLE
Lightweight arg parser needs to bark about invalid flags

### ISSUE THREAD

**Issue by david-mcmahon** [kubernetes/release#196]
I'd really like to [K.I.S.S. and lightweight on the arg parsing](https://github.com/kubernetes/release/blob/master/lib/common.sh#L493), but we should find a way to detect invalid flags too.  I fear this might be the straw that bloats things, but let's have a look.

**Comment by techtonik** [comment]
http://docopt.org/ ?

**Comment by david-mcmahon** [comment]
@techtonik not exactly what I was thinking as 'lightweight', but will look closer...
