### ISSUE TITLE
Compiling krel in Cloud Build fails when using KUBE_CROSS_VERSION

### ISSUE THREAD

**Issue by puerco** [kubernetes/release#1960]
#### What happened:

When cutting new releases, Google Cloud Build jobs fail when trying to compile `krel`. Compiling `krel` now requires golang 1.16 and the kube-cross versions referenced in `release-*` branches in k/k are older. Example:
```
curl https://raw.githubusercontent.com/kubernetes/kubernetes/release-1.20/build/build-image/cross/VERSION
v1.15.8-legacy-1
```

Output while trying to compile:
```
pkg/cip/dockerregistry/grow_manifest.go:141:9: undefined: os.WriteFile
pkg/cip/dockerregistry/inventory.go:134:12: undefined: os.ReadFile
pkg/cip/dockerregistry/inventory.go:161:12: undefined: os.ReadFile
pkg/cip/dockerregistry/inventory.go:199:12: undefined: os.ReadFile
pkg/cip/dockerregistry/inventory.go:321:16: undefined: os.ReadDir
pkg/cip/dockerregistry/inventory.go:1097:13: undefined: io.ReadAll
note: module requires Go 1.16
```
#### What you expected to happen:

`krel` should build successfully and the release process should finish successfully.

#### How to reproduce it (as minimally and precisely as possible):

Submit a new mock stage build without the below-referenced patch:
```bash
krel stage --type official --branch release-1.20
```

#### Anything else we need to know?:
Currently mitigated by hardcoding a specific version of `releng-ci` in https://github.com/kubernetes/release/pull/1959 (stage job) and https://github.com/kubernetes/release/pull/1961 (release job).

#### Environment:

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Fedora 33 (Workstation Edition)
- Kernel (e.g. `uname -a`): 5.10.22-200.fc33.x86_64
- Others:
```
release]$ krel version
GitVersion:    v0.7.0
GitCommit:     b39e63bad4e3ac7a2dbbfd7cd575d33d067281a0
GitTreeState:  clean
BuildDate:     2021-03-17T21:34:22Z
GoVersion:     go1.16
Compiler:      gc
Platform:      linux/amd64

```
/priority critical-urgent
/cc @kubernetes/release-engineering

**Comment by saschagrunert** [comment]
I guess a solution would be to build krel with one of our latest images while building kubernetes with the provided kube-cross version.

**Comment by cpanato** [comment]
Makes sense to me
