### ISSUE TITLE
Customizable BASEIMAGE for kube-cross image

### ISSUE THREAD

**Issue by chewong** [kubernetes/release#1963]
#### What would you like to be added:

The ability to customize BASEIMAGE for kube-cross instead of using the default `golang` BASEIMAGE.

#### Why is this needed:

Enables scenarios such as using FIPS-compliant-crypto `golang` to build Kubernetes binaries.

/cc @sozercan

**Comment by saschagrunert** [comment]
Hey @chewong, thank you for opening this request! Would it be enough to add the variable to the `images/build/cross/Makefile`?

**Comment by chewong** [comment]
Yes, that'd be enough. I can help open a PR

**Comment by saschagrunert** [comment]
> Yes, that'd be enough. I can help open a PR

Sounds great, thank you!
/assign @chewong
