### ISSUE TITLE
carried out `make stage-ci`

### ISSUE THREAD

**Issue by newhuangchuan** [kubernetes/release#1968]
make stage-ci
#### What happened:
#    go get k8s.io/release/pkg/notes/document
go get: module k8s.io/release/pkg/notes/document: reading https://goproxy.cn/k8s.io/release/pkg/notes/document/@v/list: 404 Not Found
	server response: not found: module k8s.io/release/pkg/notes/document: no matching versions for query "latest"

Unable to pull the go package

**Comment by saschagrunert** [comment]
This should be fixed now, verified that `go get k8s.io/release/pkg/notes/document` works locally
/close
