### ISSUE TITLE
Building at version marker commit leaves out latest changes 

### ISSUE THREAD

**Issue by puerco** [kubernetes/release#1976]
#### What happened:

When cutting a release, `krel` will fetch the version marker at https://dl.k8s.io/ci/latest-1.20.txt (the same thing applies to https://dl.k8s.io/ci/master.txt ) and cut the release (and possibly the branch) at that commit. 

The commit contained in the version marker is not, however, the last in the branch, This leaves out the last 3-4 commits in the branch, potentially leaving out important last-minute changes

Example:
```
git log --format=format:"%H" | head
30a261d97c65f3e1e46a93eb368376f68935a057
9af6f70f8f05479c96efcb23c77447e15fb69eed
999a1f5c76bbb01aa46be860cb6deb4cea45842c
931516a87bc2f75607a29b50045f1c2b8f62b9e2
447e338e26183322fb9fb57fd3b3ca724e46d9d1
7ede8a264743c0600dd8489d9d0dbf83a8ca0d29

curl -L https://dl.k8s.io/ci/latest.txt
v1.21.0-beta.1.439+931516a87bc2f7
```
As seen above building at `931516a87bc2f7` leaves out of the release 3 commits.

#### What you expected to happen:

The version marker file should point to the last commit. Or maybe we should stage at HEAD.

#### How to reproduce it (as minimally and precisely as possible):
Simply `curl -L https://dl.k8s.io/ci/latest.txt`  and compare to the git log or the [github commit history of k/k](https://github.com/kubernetes/kubernetes/commits/master).

**Comment by saschagrunert** [comment]
I think we do not have a version marker which gets immediately updated on a merge. We would need a postsubmit job in any case, even if it just updates a marker. We can reduce this kind of racy window, but not completely eliminate it from what I can see right now.

I'm not completely sure about the implications, but how about retrieving the latest commits directly via `git`?

```
> git ls-remote https://github.com/kubernetes/kubernetes | grep -E 'refs/heads/(master|release-1.20)'
30a261d97c65f3e1e46a93eb368376f68935a057        refs/heads/master
a8fea20470050ce393fdfacb6e208a74d933e54f        refs/heads/release-1.20
```
