### ISSUE TITLE
Release binaries?

### ISSUE THREAD

**Issue by evankanderson** [kubernetes/release#1987]
#### What would you like to be added:

Released binaries, particularly for `release-notes`. Alternatively, a [packaged GitHub Action] would be even more useful.

#### Why is this needed:

The Knative team is using the very helpful `release-notes` command. Currently, we build the command from source, but that seems:

1. Wasteful (running the go compiler many times)
2. Prone to breakage (e.g. with the recent Go 1.16 updates, we would need to update [our action here](https://github.com/knative/eventing/blob/main/.github/workflows/knative-release-notes.yaml#L44))

It would be nifty if there was a way to reuse an existing artifact from the current release process instead of running `go get` each time.

**Comment by puerco** [comment]
Sounds like a good idea to me. We don't release binaries for the releng tools (we compile them on the fly as well), but we could look into publishing them whenever we cut a new tag of `k/release`.  I'm currently building several actions at work perhaps I can look into this.
/cc @kubernetes/release-engineering

**Comment by saschagrunert** [comment]
Personally I'd love to see this working in prow. This way we could put our artifacts to the release bucket and avoid GitHub API rate limits. We could also change our release process to directly download those artifacts without having a need to rebuild them everytime.

Beside that, I'm also happy to move on with GitHub actions if someone is seeing a blocker to utilize prow.

**Comment by evankanderson** [comment]
I'm not sure this is a completely XOR situation between Prow and GitHub Actions, but in Knative we've found GitHub Actions generally easier to diagnose and debug using repo forks and the GitHub UI compared with Prow, particularly for non-Google employees. (We do have heavier automation that runs on a shared Google-donated Prow instance.)

**Comment by puerco** [comment]
I will sync with @palnabarun this week to discuss some release strategies for artifacts 
/remove-lifecycle stale

**Comment by evankanderson** [comment]
Not sure if this would be a `/good-first-issue`?

**Comment by saschagrunert** [comment]
@cpanato can you support us with this? I think it would be good to have the binaries in the same way as we have it for bom etc.

**Comment by cpanato** [comment]
yes will do with a happy face ! 

/assign

**Comment by cpanato** [comment]
I think is done, you did that @saschagrunert right?

**Comment by saschagrunert** [comment]
Yep, all done
