### ISSUE TITLE
Remove duplicates in `krel release-notes` output

### ISSUE THREAD

**Issue by wilsonehusin** [kubernetes/release#1993]
#### What happened:

- Having headers in `krel release-notes` output caused the end result of k/k changelog to have duplicated headers. [We had to fix this in 1.20](https://github.com/kubernetes/kubernetes/pull/97134) and [again in 1.21](https://github.com/kubernetes/kubernetes/pull/100968) after the release.
- We also have duplicated `dependencies` section. In 1.21 we handled it in the same PR linked previously, while in [1.20 it was caught later on](https://github.com/kubernetes/kubernetes/pull/98347).

#### What you expected to happen:

Release notes team need not to manually edit document in k/sig-release before the release

#### How to reproduce it (as minimally and precisely as possible):

Create a minor release in k/k 😅 

#### Anything else we need to know?:

/assign
/cc pmmalinov01 puerco

#### Environment:

- Cloud provider or hardware configuration: -
- OS (e.g: `cat /etc/os-release`): -
- Kernel (e.g. `uname -a`): -
- Others: -

**Comment by wilsonehusin** [comment]
/priority backlog

heh `/cc` doesn't work on issues, so manually now -- cc: @pmmalinov01 @puerco

**Comment by jihoon-seo** [comment]
The code that generates the unwanted `# Release notes for` part:

https://github.com/kubernetes/release/blob/c0d02130e78a83d0f7262cbb776cd9e9928686b5/pkg/notes/document/template.go#L25-L27

---

The code that generates the unwanted `# Changelog since` (H1) part:

https://github.com/kubernetes/release/blob/c0d02130e78a83d0f7262cbb776cd9e9928686b5/pkg/notes/document/template.go#L64

(c.f. The codes that generate the desired `## Changelog since` (H2) part:)
- pkg/changelog/const.go
- pkg/notes/document/document.go

**Comment by jihoon-seo** [comment]
Note: This comment is Work In Progress.

[Call chains of appending-dependencies-changes functions]
- Call chain 1
  - ...
  - In `cmd/krel/cmd/release_notes.go`,
`func buildNotesResult()` calls `notes.NewDependencies().Changes()`
- Call chain 2
  - ...
  - In `pkg/changelog/changelog.go`,
  `func (c *Changelog) Run()` calls `c.impl.DependencyChanges(startRev, endRev)`
- Call chain 3
  - ...
  - In `cmd/release-notes/main.go`,
`func WriteReleaseNotes()` calls `notes.NewDependencies().ChangesForURL(`

**Comment by jihoon-seo** [comment]
1. `const defaultReleaseNotesTemplate` in `release/pkg/notes/document/template.go` writes these lines:

https://github.com/kubernetes/release/blob/c0d02130e78a83d0f7262cbb776cd9e9928686b5/pkg/notes/document/template.go#L25-L27

https://github.com/kubernetes/release/blob/c0d02130e78a83d0f7262cbb776cd9e9928686b5/pkg/notes/document/template.go#L64



2. `func CreateDownloadsTable` in `release/pkg/notes/document/document.go` writes these lines:

https://github.com/kubernetes/release/blob/6190955e74c3cac443e2bedb4e6dd0b69cb3c484/pkg/notes/document/document.go#L366-L367

https://github.com/kubernetes/release/blob/6190955e74c3cac443e2bedb4e6dd0b69cb3c484/pkg/notes/document/document.go#L375-L376

(Strictly speaking, these lines in `func CreateDownloadsTable` seems not responsible to `func CreateDownloadsTable`.)

---

It seems that this causes duplicate.

---

[Suggestion]

In `release/pkg/notes/document/template.go`,

```diff
- # Release notes for {{$CurrentRevision}} 
-  
- [Documentation](https://docs.k8s.io/docs/home) 
```

```diff
- # Changelog since {{$PreviousRevision}} 
```

**Comment by jihoon-seo** [comment]
[Suggestion]

In `release/pkg/notes/document/template.go`,

```diff
- # Release notes for {{$CurrentRevision}} 
-  
- [Documentation](https://docs.k8s.io/docs/home) 
```

```diff
- # Changelog since {{$PreviousRevision}} 
```

---

Reflecting this suggestion will cause some changes on generated `release-notes-draft.md` file:

[As-is]
```Markdown
# Release notes for v1.21.0

[Documentation](https://docs.k8s.io/docs/home)
# Changelog since v1.20.0

## Urgent Upgrade Notes 

### (No, really, you MUST read this before you upgrade)

- Kube-proxy's IPVS proxy mode no longer sets the net.ipv4.conf.all.route_localnet sysctl parameter.
...
```

[To-be]
```Markdown
## Urgent Upgrade Notes 

### (No, really, you MUST read this before you upgrade)

- Kube-proxy's IPVS proxy mode no longer sets the net.ipv4.conf.all.route_localnet sysctl parameter.
...
```

As you can see, some headings are removed.
So if someone opens the generated [`sig-release/releases/release-1.21/release-notes-draft.md`](https://github.com/kubernetes/sig-release/blob/master/releases/release-1.21/release-notes-draft.md) file.

But eventually and consequently, the full release notes ([here](https://kubernetes.io/docs/setup/release/notes/) and [here](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md)) will have decent form without duplicate headings.

**Comment by jihoon-seo** [comment]
[Suggestion 2]

In `release/pkg/notes/document/template.go`,

```diff
- # Release notes for {{$CurrentRevision}} 
-  
- [Documentation](https://docs.k8s.io/docs/home) 
+ # Release notes for {{$CurrentRevision}} <!-- Or, just # {{$CurrentRevision}} -->
+  
+ [Documentation](https://docs.k8s.io) 
```

```diff
- # Changelog since {{$PreviousRevision}} 
+ ## Changelog since {{$PreviousRevision}} 
```

In `release/pkg/notes/document/document.go`,
```diff
- fmt.Fprintf(w, "# %s\n\n", newTag) 
- fmt.Fprintf(w, "## Changelog since %s\n\n", prevTag) 
```

```diff
- fmt.Fprintf(w, "# %s\n\n", newTag) 
- fmt.Fprintf(w, "[Documentation](https://docs.k8s.io)\n\n") 
```

**Comment by wilsonehusin** [comment]
woah this is awesome investigation @jihoon-seo!

I think I like the first suggestion which we simply remove them, including the dependency / import diff because they're also duplicated. the data in k/sig-release will be quite self-explanatory with _which directory_ they're located in.

in the scenario of people running `release-notes` tool (without `krel`, different binary), they can change the output file name with the version :smile:

@puerco what do you think?

**Comment by pmmalinov01** [comment]
Amazing detective skillz! 
+1 for going with the first suggestion. In my mind, it falls in the idiomatic way of golang.
