### ISSUE TITLE
push-build.sh should support dirty branches for dev pushes

### ISSUE THREAD

**Issue by cjcullen** [kubernetes/release#200]
VER_REGEX will fail to match `*-dirty` versions of kubectl, so the script fails if I built kubernetes from a dirty branch.

Unless there is a good reason to not allow developer testing from dirty branches, I think we should add back support for that flow.

**Comment by cjcullen** [comment]
@spxtr

**Comment by ixdy** [comment]
Probably fine, though we will want to enforce that official release and CI builds are clean.

**Comment by pipejakob** [comment]
How about a flag to enable dirty pushes that makes it obvious it shouldn't be used for releases, such as `--dev` or `--allow-dirty`?

Happy to take this on myself, as I've been bitten by this in my development cycle.

**Comment by ixdy** [comment]
@pipejakob sgtm
