### ISSUE TITLE
Confusing logging in push-build.sh

### ISSUE THREAD

**Issue by cjcullen** [kubernetes/release#201]
Logging a phrase that ends in a colon at the beginning of a long-running operation makes it look like the script is waiting on user input.

For example:
```
Check/make release bucket kubernetes-release-dev:
```
feels like I am supposed to respond, until the `OK` happens and the script starts up again.

@spxtr

**Comment by ixdy** [comment]
This could probably be "..." instead of ":".

@david-mcmahon WDYT?

**Comment by david-mcmahon** [comment]
`Statement: STATUS` is the common logging style throughout this ecosystem.  

That said, `push-build.sh` is somewhat of a standalone tool used by kubernetes proper.  Feel free to experiment with logging/messaging.  If we find something better here, we can retrofit the rest of k/r too.
