### ISSUE TITLE
Add missing 'Source Code' heading in `krel` output

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/release#2012]
#### What happened:
'Source Code' heading is missing in `krel`-generated files.
Please refer to https://github.com/kubernetes/kubernetes/pull/101299/files .

[As-is]
```Markdown
## Downloads for v1.21.0

filename | sha512 hash
-------- | -----------
```

#### What you expected to happen:

[To-be]

```Markdown
## Downloads for v1.21.0

### Source Code

filename | sha512 hash
-------- | -----------
```

#### How to reproduce it (as minimally and precisely as possible):
Run `krel changelog` and/or `krel release-notes` commands, maybe..?

#### Anything else we need to know?:
- Related issue: #1993
- Related issue: https://github.com/kubernetes/sig-release/issues/1528
- CC: @wilsonehusin @pmmalinov01 

#### Environment:

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by wilsonehusin** [comment]
possibly related -- https://github.com/kubernetes/release/issues/1993

/priority backlog
/milestone v1.22

**Comment by jihoon-seo** [comment]
It seems that this is caused from:

https://github.com/kubernetes/release/blob/c0d02130e78a83d0f7262cbb776cd9e9928686b5/pkg/notes/document/document.go#L380-L402

---

[Suggestion]

```diff
-		"", "Client Binaries", "Server Binaries", "Node Binaries",
+		"Source Code", "Client Binaries", "Server Binaries", "Node Binaries",
```

**Comment by jihoon-seo** [comment]
Note:

[Capitalization issue]
- `Client binaries`, `Server binaries`, `Node binaries`
  - pkg/changelog/const.go
  - pkg/notes/document/template.go
- `Client Binaries`, `Server Binaries`, `Node Binaries`
  - pkg/notes/document/document.go
  - pkg/notes/document/document_test.go

**Comment by wilsonehusin** [comment]
good catch on capitalization too!

I wonder how we end up with `""` -- my gut feeling is that this might be due to an off-by-one fix at some point. just trying to make sure there are no side effect if we add the suggested changes (which I agree with)

**Comment by jihoon-seo** [comment]
@wilsonehusin Thank you for your comment.

To check the effect of suggestions ([here](https://github.com/kubernetes/release/issues/1993#issuecomment-824751873) and [here](https://github.com/kubernetes/release/issues/2012#issuecomment-823956368)),

I ran `krel release-notes --create-draft-pr --fork=jihoon-seo --tag v1.21.0 --fix`,
and the results are as follows.

[[Before](https://gist.github.com/jihoon-seo/c45795f86c982074a52bddaff306a6e8#file-210423-with-dup-headings-md)]

[[After](https://gist.github.com/jihoon-seo/c45795f86c982074a52bddaff306a6e8#file-210423-no-dup-headings-md)]

You can see that there is no "Downloads" section in the Markdown file generated by `krel release-notes`.
And the `krel` source code confirms that 
`func CreateDownloadsTable()` in `release/pkg/notes/document/document.go` is called only by 
`func (c *Changelog) Run()` in `release/pkg/changelog/changelog.go`,
which means that I should run "Downloads"-section-related test with `krel changelog` command.

The problem here is that, I don't know how to use [`krel changelog`](https://github.com/kubernetes/release/blob/master/docs/krel/changelog.md).

https://kubernetes.slack.com/archives/C2C40FMNF/p1618996488120700

I want to try running krel changelog, but it gives error.

```
FYI: I made a softlink: /tmp/k8s -> /root/go/src/github.com/kubernetes/kubernetes

/tmp/k8s @ master branch ❯ krel changelog --branch release-1.21 --tag v1.21.0
INFO Using release branch release-1.21            
INFO Using local repository path /tmp/k8s         
INFO We're currently on branch: master            
FATA get latest branch commit: reference not found
```

```
❯ git checkout release-1.21
Switched to branch 'release-1.21'
Your branch is up to date with 'upstream/release-1.21'.

/tmp/k8s @ release-1.21 branch ❯ krel changelog --branch release-1.21 --tag v1.21.0
INFO Using release branch release-1.21            
INFO Using local repository path /tmp/k8s         
INFO We're currently on branch: release-1.21      
FATA get latest branch commit: reference not found
```

```
❯ git checkout release-1.20
Switched to branch 'release-1.20'
Your branch is up to date with 'upstream/release-1.20'.

/tmp/k8s @ release-1.20 branch ❯ krel changelog --branch release-1.21 --tag v1.21.0
INFO Using release branch release-1.21            
INFO Using local repository path /tmp/k8s         
INFO We're currently on branch: release-1.20      
FATA get latest branch commit: reference not found
```

What am I missing? 🤔

**Comment by wilsonehusin** [comment]
nice work! want to PR your changes and we can discuss there?

I never had to use `krel changelog`, so I'm not sure either 🤔 I'll give it a try

on links `/tmp/k8s` to your real path, you can use `--repo` to do that 😄

**Comment by jihoon-seo** [comment]
Okay, I will try --repo flag and open a PR, next week! 😄

**Comment by jihoon-seo** [comment]
I tried `--repo` flag, but it did not give any difference. 😢

`krel changelog --branch release-1.21 --tag v1.21.0 --repo /root/go/src/github.com/kubernetes/kubernetes`

```
INFO Using release branch release-1.21            
INFO Using local repository path /root/go/src/github.com/kubernetes/kubernetes 
INFO We're currently on branch: master            
FATA get latest branch commit: reference not found
```

**Comment by jihoon-seo** [comment]
Instead of `krel changelog`, I could do the tests using the Go test functions of `krel`.

- `func TestCreateDownloadsTable` in `pkg/notes/document/document_test.go`
- `func TestDocument_RenderMarkdownTemplate` in `pkg/notes/document/document_test.go`

Ref: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/release/2020/pull-release-test/1386495494221467648
