### ISSUE TITLE
'Just generate md or html' flag for `krel release-notes`

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/release#2013]
#### What would you like to be added:

'Just generate md or html' flag for `krel release-notes`

#### Why is this needed:

[`krel changelog`](https://github.com/kubernetes/release/blob/master/docs/krel/changelog.md) generates Markdown file and HTML file.
It also provides the flag `--html-file` for users who want to drop the generated HTML file somewhere else than the default path.
```
--html-file string   The target html file to be written. If empty, then it will be CHANGELOG-x.y.html in the current path.
```

---

[`krel release-notes`](https://github.com/kubernetes/release/blob/master/docs/krel/release-notes.md) provides `--create-draft-pr` and `--create-website-pr` flags,
```
--create-draft-pr     update the Release Notes draft and create a PR in k/sig-release
--create-website-pr   patch the relnotes.k8s.io sources and generate a PR with the changes
```
but I cannot find a flag that just generates Markdown or HTML file, not creating a PR.

It might be useful for people who want to test and debug the `krel release-notes`.

**Comment by jihoon-seo** [comment]
I browsed the PRs created by `krel release-notes`, and found that the PRs do not contain just one file.

[PR created with `--create-draft-pr` flag]
- Example: https://github.com/kubernetes/sig-release/pull/1503/files
  - This PR adds and updates many `yaml`, `json`, and `md` files.

[PR created with `--create-website-pr` flag]
- Example: https://github.com/kubernetes-sigs/release-notes/pull/233/files
  - This PR Adds one big `json` file and updates one `ts` file.

**Comment by jihoon-seo** [comment]
There are codes about `interactive mode` in [`release_notes.go`](https://github.com/kubernetes/release/blob/master/cmd/krel/cmd/release_notes.go),
but there is no mention about `interactive mode` in two `krel release-notes`-related documents:

- https://github.com/kubernetes/release/blob/master/docs/krel/release-notes.md
- https://github.com/kubernetes/release/blob/master/cmd/release-notes/README.md

**Comment by wilsonehusin** [comment]
yeah `--fix` deserves some explanation. historical context on this is that `krel` would automate gathering of release notes then folks would manually fix them on markdown. now, with `--fix`, folks can edit YAML representation of notes before they even make it to markdown.

thoughts? cc @puerco

**Comment by puerco** [comment]
Sorry, I missed this one @jihoon-seo I was browsing through open issues and noticed it.

Krel is not a general purpose tool, it is really meant to be run only by the release team and release managers. That is why it does not have more options like specifying a path. Likewise, the interactive mode started by `--fix` is only meant to edit the kubernetes release notes for the current cycle.  It certainly needs more information in the command line but if you are curious, all the process is described here: https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/release-notes/editing-flow.md 

For all other uses, all of its functionality is also exposed by the `release-notes` tool ([see here](https://github.com/kubernetes/release/tree/master/cmd/release-notes)). If you need to test the output or the format you can do it with it as `krel` and `release notes` share the same libraries.

Can you share a little bit more about what you want to do?
