### ISSUE TITLE
Predictable tag schedule

### ISSUE THREAD

**Issue by wilsonehusin** [kubernetes/release#2073]
#### What would you like to be added:

`k/release` repository to have a predictable tagging schedule.

#### Why is this needed:

While most of the consumption `k/release` is internal to Kubernetes as open-source project, we do have tools which are meant to be consumed outside of the open-source project context (e.g. [`release-notes` generator](https://github.com/kubernetes/release/tree/master/cmd/release-notes)). Would be helpful to have a predictable / defined tagging schedule for folks to work on their features.

---

This started as [a conversation on `#release-management` Slack](https://kubernetes.slack.com/archives/CJH2GBF7Y/p1621375303019600?thread_ts=1621373568.018100&cid=CJH2GBF7Y).

**Comment by saschagrunert** [comment]
How about cutting a release monthly right before the k8s patch releases. Then we could use that krel version for cutting the release instead of the master.

**Comment by wilsonehusin** [comment]
🤔 that's a good idea -- I was initially under the impression that our releases are almost quarterly but it makes a lot of sense to do monthly with schedule of n days before patch releases.

which leads to... versioning scheme: should we do the YYYY.MM scheme? i.e. 2021.05 or 21.05 for short?

**Comment by puerco** [comment]
I'd stick with semver and discuss around the semantic part :)

**Comment by saschagrunert** [comment]
I’m also in favor of semver, but don’t want to raise the discussion about an stable API again at this point. 😅

**Comment by wilsonehusin** [comment]
hahaha I didn't mean to imply stable API -- my thought process was mostly "we're versioning things so it's easy to track and discern", but yeah I'm overall indifferent between the two, just a thought :)

**Comment by saschagrunert** [comment]
Do you have thoughts on writing a policy around pre-patch releases @kubernetes/sig-release-leads ?

**Comment by justaugustus** [comment]
Let's only consider SemVer here.
- _at least_ as frequently as the monthly patch releases
- whenever core dependencies have releases that address security vulnerabilities
- whenever the UX of a release tool has significantly changed
- whenever there are significant changes in dependencies
- whenever there is significant buildup of commits (hopefully this isn't a huge consideration if we're releasing monthly)

**Comment by puerco** [comment]
Well. this sounds like a nice rule set for a first draft :)

**Comment by justaugustus** [comment]
Awesome!
Wilson and Adolfo, can I ask you two to get a draft going for the team to review?

/assign @wilsonehusin @puerco
