### ISSUE TITLE
Automatically create image promotion PRs

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/release#2076]
Right now we manually create an image promotion PR for every release, for example [this one](https://github.com/kubernetes/k8s.io/pull/2075). The tooling already provides the implementation for the automatism, but has to be executed by a release manger for now.

The idea is to bring this image promotion into `krel stage` to reduce the manual overhead when cutting releases.

What do you think, @kubernetes/release-engineering?

**Comment by puerco** [comment]
I had been holding on implementing this because there have been discussions around signing the images and I think we should automate this once we have a plan for that. WDYT?

**Comment by saschagrunert** [comment]
> I had been holding on implementing this because there have been discussions around signing the images and I think we should automate this once we have a plan for that. WDYT?

I'm not sure if we have to make auto promotion dependent on signing. I see them as separate steps, whereas we could start working on the promotion part and add the signing later on. Thoughts on that?

**Comment by xmudrii** [comment]
I think this is still relevant.
/remove-lifecycle stale

**Comment by xmudrii** [comment]
@saschagrunert @puerco Do we have some conclusion on this issue? I agree with Sascha on this:

> I'm not sure if we have to make auto promotion dependent on signing. I see them as separate steps, whereas we could start working on the promotion part and add the signing later on. Thoughts on that?

We can always start with basic functionality (auto promotion) and then extend it later with signing. Considering that we can get GitHub token in the Cloud Run (at least AFAIK), I think fixing this should be doable.
