### ISSUE TITLE
`krel release-notes --create-draft-pr --fix` save original text into yaml file causing yaml parsing issue

### ISSUE THREAD

**Issue by cici37** [kubernetes/release#2114]
#### What happened:

I was trying to generate release notes for v1.22.0-alpha.3 release with command:
`krel release-notes --create-draft-pr --fix --fork=cici37 --tag v1.22.0-alpha.3` and go with `y` when was asked `Would you like to continue from the last session? (Y/n) (1/10)` follow release note [documentation](https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/release-notes/editing-flow.md).

The error I got:
```
Release Note for PR 101739:
===========================
Pull Request URL: https://github.com/kubernetes/kubernetes/pull/101739
FATA creating Draft PR: while running release notes fix flow: while getting map for PR #101739: while reading release notes maps: while parsing note map in /tmp/k8s-3777994465/releases/release-1.22/release-notes/maps/pr-101496-map.yaml: decoding note map: yaml: line 3: found character that cannot start any token
```
which comes from paring the release note [map](https://github.com/kubernetes/release/blob/f3f045344694c286947b17e720a35a66f75e50d5/pkg/notes/notes_map.go#L58).

The map file(/tmp/k8s-3777994465/releases/release-1.22/release-notes/maps/pr-101496-map.yaml) shows:
```
pr: 101496
releasenote:
  text: `podAffinity`, `NamespaceSelector` and the associated `CrossNamespaceAffinity`
    quota scope features graduate to Beta and they are now enabled by default.
```
Which is the original text from the PR without editing. Seems like the original text is saved to a yaml file before editing which sounds problematic to me.

#### What you expected to happen:
Be able to edit the release note and create the draft pr.

#### How to reproduce it (as minimally and precisely as possible):
Generate release notes for v1.22.0-alpha.3 release with command:
`krel release-notes --create-draft-pr --fix --fork=cici37 --tag v1.22.0-alpha.3` and go with `y` when was asked `Would you like to continue from the last session? (Y/n) (1/10)`

#### Environment:

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by cici37** [comment]
cc @pmmalinov01

**Comment by pmmalinov01** [comment]
Thanks for reporting this, from my experience so far I just put "" around the value. This is exactly to prevent errors related to quotes.
```
pr: 101496
releasenote:
  text: "`podAffinity`, `NamespaceSelector` and the associated `CrossNamespaceAffinity`
    quota scope features graduate to Beta and they are now enabled by default."
```

As a side note could you please also use `--list-v2` parameter, it will speed up your initial download of the PRs and we should evaluate it. If it is working as expected it will be moved to default behaviour.

**Comment by pmmalinov01** [comment]
This is really strange, as we spoke the plan to take is:
1) @cici37  will create a PR to fix the broken map(101496) manually 
2) run krel again to see if this will fix the issue
3) then a code change should be made to fix this issue from occurring.


cc @wilsonehusin @puerco We could use your super powers on this. Do you know any way to fix and prevent this from future runs?

**Comment by cici37** [comment]
I raised a PR to manually fix the issue as of now. Please have a look when you have time. Thanks

Possible future plan:
Adding a yaml checking/validation process to prevent it from further happening.

**Comment by cici37** [comment]
The script did a great job on checking/validating yaml files while auto editing. However, it would not prevent it from manual editing(after the PR is created). My suggestion would be to add an presubmit check under `https://github.com/kubernetes/sig-release` to check the yaml files under `sig-release/releases/release-[version]/release-notes/maps/`. So the PR failed yaml checking would not be able to get merged.  Please let me know if there is any misunderstanding I have. :)

**Comment by puerco** [comment]
OK, I was investigating this and just like @cici37 pinted out. I think the file that caused the error was indeed edited by hand and not inside the release notes flow. Ie, the bad yaml was not introduced into the file by hand as the isse states but rather in a manual edit. Here's the commit history for that particular map file:

https://github.com/kubernetes/sig-release/commits/master/releases/release-1.22/release-notes/maps/pr-101496-map.yaml

Can you confirm if this was the case for this map @Damans227 ? 

There will always be ways to send a PR manually, so the only way to save ourselves from ourselves is to add the presubmit that cici suggested above (https://github.com/kubernetes/sig-release/issues/1595)

**Comment by Damans227** [comment]
Hi @puerco Unfortunately, I don't remember whether I manually edited this PR outside of `Krel` workflow, sorry! But, the subject line of that commit which you have pointed out looks unusual (Update pr-101496-map.yaml). Lemme know how else I can help.
