### ISSUE TITLE
Ensuring up to date patches when building images

### ISSUE THREAD

**Issue by puerco** [kubernetes/release#2125]
When running an experimental kube-cross build, we ran into a non-fatal timeout when fetching the package indexes from ubuntu:

```
69.56 Err:4 http://archive.ubuntu.com/ubuntu xenial InRelease
#7 69.56   Could not connect to archive.ubuntu.com:80 (91.189.88.152), connection timed out Could not connect to archive.ubuntu.com:80 (91.189.88.142), connection timed out [IP: 91.189.88.142 80]
#7 69.57 Reading package lists...
#7 70.32 W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/InRelease  Could not connect to archive.ubuntu.com:80 (91.189.88.152), connection timed out Could not connect to archive.ubuntu.com:80 (91.189.88.142), connection timed out [IP: 91.189.88.142 80]
#7 70.32 W: Some index files failed to download. They have been ignored, or old ones used instead.
```
As we are building various images in parallel, this could result in an inconsistency where two images, with the same ubuntu base , have different patches as the timeout causes the failed build to read a stale version of the package index.

Should we think about a retry loop or another mechanism to ensure packages are guaranteed to be the same?

**Comment by saschagrunert** [comment]
> As we are building various images in parallel

For different architectures, right? If so, then we will have different package contents in any case.

Having a retry for the ubuntu remotes seems reasonable to me.
