### ISSUE TITLE
`krel announce send` is unable to retrieve release announcement form URL

### ISSUE THREAD

**Issue by onlydole** [kubernetes/release#2141]
#### What happened:

When running `krel announce send --nomock --tag=v1.22.0-beta.0` I received an error about the announcement HTML not being found (404). 

```FATA unable to retrieve release announcement form url: https://dl.k8s.io/archive/anago-v1.22.0-beta.0/announcement.html: HTTP error 404 Not Found for https://storage.googleapis.com/kubernetes-release/archive/anago-v1.22.0-beta.0/announcement.html```

#### What you expected to happen:

I would expect for this command to successfully send an email message, leveraging SendGrid.

#### How to reproduce it (as minimally and precisely as possible):

Run `krel announce send --nomock --tag=v1.22.0-beta.0` and you will receive the message above.

#### Anything else we need to know?:

This issue was paired with improper SHAs being sourced (from the mock test) and any way to help check SHAs at send time would be ideal.

#### Environment:

```
GitVersion:    v0.9.0
GitCommit:     e54e70d64eb7cb1d46dff0c336365c36b610dd0c
GitTreeState:  clean
BuildDate:     2021-06-22T19:38:16Z
GoVersion:     go1.16.5
Compiler:      gc
Platform:      darwin/amd64
```

**Comment by saschagrunert** [comment]
This got introduced in https://github.com/kubernetes/release/pull/2130, which is now compressing the full archive which we probably do not want. Having a fix in mind,
/assign
