### ISSUE TITLE
Create tool for synchronizing `OWNERS` across repositories

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/release#2175]
The main motivation behind this request is that our [`OWNERS`](https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#owners) (and [`OWNERS_ALIASES`](https://go.k8s.io/owners#owners_aliases)) are out of sync across multiple repositories. The goal is to write a tool which allows us to update (manually) and verify (via a prow periodic job) them across a set of defined repos.

For example, sigs.yaml already references the OWNERS of a subproject, for example for Release Engineering:
https://github.com/kubernetes/community/blob/6042eed74ab108c617af1162b85f7fdb3f9c2c27/sigs.yaml#L1909-L1924

The tool could use this data to map the personas to the actual file content to ensure that everything is up-to-date.

/help

**Comment by mritunjaysharma394** [comment]
Hi @saschagrunert, I would like to work on this tool and according to my naive understanding, should this tool be somewhat like a GitHub action or do we have different expectations? 

Thanks! 

/assign

**Comment by saschagrunert** [comment]
> Hi @saschagrunert, I would like to work on this tool and according to my naive understanding, should this tool be somewhat like a GitHub action or do we have different expectations?

Sounds great! Yeah the tool should be able to run locally and in a CI, which is usually prow in our case.

**Comment by mritunjaysharma394** [comment]
> > Hi @saschagrunert, I would like to work on this tool and according to my naive understanding, should this tool be somewhat like a GitHub action or do we have different expectations?
> 
> Sounds great! Yeah the tool should be able to run locally and in a CI, which is usually prow in our case.

Thanks a lot @saschagrunert! I will try to draft my approach and share the initial proposal may be on the slack #sig-release as well, looking forward making this interesting tool :partying_face:

**Comment by mritunjaysharma394** [comment]
Hi @saschagrunert , extremely sorry for getting back to this so late, I will begin working on this but would love to understand more on couple of things: 
* when we say to "write a tool which allows us to update (manually)", we mean we will supply this tool some input (yaml? in our case?) where there shall be updated names and maybe on pushing  (possible trigger for prow?) the yaml, we run our periodic prow jobs and verify and update across defined repos?
* would love if you can direct me to some existing examples where  `OWNERS` (and `OWNERS_ALIASES`) are out of sync?

Thanks a lot for all the help :smile:!

**Comment by saschagrunert** [comment]
Hey :wave:,

> when we say to "write a tool which allows us to update (manually)", we mean we will supply this tool some input (yaml? in our case?) where there shall be updated names and maybe on pushing  (possible trigger for prow?) the yaml, we run our periodic prow jobs and verify and update across defined repos?

Yes, I would expect that we use the [sigs.yaml](https://github.com/kubernetes/community/blob/6042eed74ab108c617af1162b85f7fdb3f9c2c27/sigs.yaml#L1909-L1924) as basic input. :+1: 

We can create a periodic prow job which fails to inform us to take action in the first place. Increasing the automation later on seems like a reasonable next step. 

> would love if you can direct me to some existing examples where  `OWNERS` (and `OWNERS_ALIASES`) are out of sync?

How about those: https://github.com/kubernetes-sigs/release-notes/blob/master/OWNERS_ALIASES

**Comment by mritunjaysharma394** [comment]
Thanks a lot, @saschagrunert for all the guidance, I will create a WIP PR against k8s/test-infra as soon as a basic prototype gets ready!

**Comment by mritunjaysharma394** [comment]
Hi @saschagrunert, the prototype is almost ready but I had one more question. With which file or input should we match the out of sync `OWNERS` and `OWNERS_YAML` to check the condition of whether they are out of sync or not? Do we plan to modify the existing `sigs.yaml` with names of updated `OWNERS` for it or there exists somewhere the up-to-date `OWNERS` file? Thanks a lot!

**Comment by saschagrunert** [comment]
> With which file or input should we match/map the out of sync `OWNERS` and `OWNERS_YAML` to check the condition of whether they are out of sync or not?

That's the tricky part. I would just report that the aliases differ if that's the case. How a resolution should look like, is something we can resolve by defining a "main alias" in k/community or somewhere else later on.

**Comment by upodroid** [comment]
@puerco @saschagrunert 

I haven't seen updates or a response from @mritunjaysharma394.

We have solved this in Knative, we have a scheduled GitHub action that pushes OWNER_ALIASES updates from peribolos to all the repos. I can set this up for Kubernetes as well.

 - https://github.com/knative-sandbox/knobots/blob/main/.github/workflows/auto-update-community.yaml
 - https://github.com/knative-sandbox/knobots/actions/runs/2406250965
 - Sample PRs:
   - https://github.com/knative/serving/pull/12946
   - https://github.com/knative/eventing/pull/6369

I have a few questions:

- Do you want to consume this as a GitHub Action or a Prow Periodic Job?
- Where do you want to me put this? k/org or k/test-infra

Thanks

/assign

**Comment by saschagrunert** [comment]
Thank you @upodroid! 

> Do you want to consume this as a GitHub Action or a Prow Periodic Job?

I'd prefer having it as a prow periodic job.

> Where do you want to me put this? k/org or k/test-infra

The job itself has to run in test-infra, but we could add it to the informing testgrid dashboard: https://testgrid.k8s.io/sig-release-releng-informing

**Comment by upodroid** [comment]
This PR will only automate syncing OWNERS_ALIASES. OWNERS file will be set by each repo owners and in appropriate sub folders. Automated syncing of OWNERS isn't in scope(need to update the original issue).

**Comment by mrbobbytables** [comment]
Sorry, I meant owners aliases.

**Comment by mrbobbytables** [comment]
We have lots of repos that use their own custom owners aliases, its not something we want to automatically generate, especially as there are a slew of people that aren't in all orgs.

The only ones that we have some sort of guarantees around are the leads and their aliases.

**Comment by upodroid** [comment]
> We have lots of repos that use their own custom owners aliases, its not something we want to automatically generate, especially as there are a slew of people that aren't in all orgs.

I assumed all reviewers/approvers were org members in all the repos. In that case, I can rework this to read a yaml file of all repos that want automated syncing of OWNERS_ALIASES. Is there a plan for switching to aliases and getting those people added to the respective organisations?

**Comment by mrbobbytables** [comment]
Nope, people are ONLY reviewers/approvers for things related to them. We have wildly divergent OWNERS_ALIASES files across the 320ish repos in the project. 

I think a syncing tool is fine, but it definitely is not something we want to do for everyone. If sig-release wants to specify a source of truth for their own OWNERS_ALIASES files and ensures their own members are in the appropriate orgs, that is fine but it is not something we want to enable for all.

**Comment by mrbobbytables** [comment]
> Switching OWNERS to reference GitHub Teams
> Align all OWNERS_ALIASES with actual GitHub teams specified in the k/org repository

Aliases for teams rarely map to github teams. It might hold true for sig-release, but not the case for most sigs. We have quite a few where we have reviewers/approvers that are not admins/maintainers of repos.
