### ISSUE TITLE
Getting kompose rpm in the repo

### ISSUE THREAD

**Issue by sebgoa** [kubernetes/release#219]
Hi, we have kompose rpms on different repos (EPEL testing, openshift origin).

Is it possible to get `kompose` in the official k8s repo (like `kubedadm`) ?

I think it would be great for users to have a single repo they can pull things from.

https://github.com/kubernetes-incubator/kompose/issues/328

**Comment by errordeveloper** [comment]
cc @mikedanese

**Comment by errordeveloper** [comment]
I fully support this and happy to help with reviews etc.

**Comment by errordeveloper** [comment]
From my point of view, any incubator projects should be able to reach their audience, package repos help a lot.

**Comment by mikedanese** [comment]
This sounds good to me. Please also include a deb.

**Comment by bgrant0607** [comment]
See also #3

**Comment by bgrant0607** [comment]
People also run clients on at least Mac and maybe Windows

**Comment by errordeveloper** [comment]
@sebgoa would you rather keep this open or we can let it rot?
