### ISSUE TITLE
Version tag has extra characters in s390x binaries

### ISSUE THREAD

**Issue by puerco** [kubernetes/release#2191]
#### What happened:
During the `v1.22.0-rc.0` release cut, the verification of staged artifacts failed when checking the tags in the linux/s390x binaries. The string found inside of some files for this platform did not match the expected version tag and the release process exited.

Upon inspection, the binaries reported the correct version string using --version inside of an s390 VM, which points to a bug in the code and/or the way we check the strings inside of the binaries. 

The strings are found in the binary as follows:
```
)v1.23.0-alpha.0
$v1.23.0-alpha.0
```

#### What you expected to happen:

Find the version string as in other platforms:
```
v1.23.0-alpha.0
v1.23.0-alpha.0
```

#### How to reproduce it (as minimally and precisely as possible):

Download the binary and check it with `strings`:
```bash
gsutil cp gs://kubernetes-release/release/v1.23.0-alpha.0/bin/linux/s390x/kube-apiserver .
strings kube-apiserver | grep v1.23.0

# Output has an extra char before:
)v1.23.0-alpha.0
$v1.23.0-alpha.0
```

#### Anything else we need to know?:

Checking the tags for other platforms works as expected.

Slack ref:  https://kubernetes.slack.com/archives/CJH2GBF7Y/p1626799309232800?thread_ts=1626797390.231900&cid=CJH2GBF7Y

#### Environment:

GCB run link:  https://console.cloud.google.com/cloud-build/builds/00aa0621-2e26-43a4-8fa0-cea29e481e93?project=648026197307

/kind bug
/milestone v1.23

**Comment by puerco** [comment]
Note that due to this bug, version checks in binaries are temporarily disabled:
https://github.com/kubernetes/release/pull/2176

**Comment by saschagrunert** [comment]
I think we could evaluate if it's worth to switch to qemu-* for the binary tests. This way we can also check if the binary works in general and verify the correct version number, like:
```
 qemu-s390x ./kube-apiserver --version
Kubernetes v1.23.0-alpha.0
```
