### ISSUE TITLE
Illegal char '-' (0x2d) in: Version: 1.5.0-beta.2

### ISSUE THREAD

**Issue by tonyjames3212** [kubernetes/release#222]
Hi,i am new to k8s.There is an error when i building the rpm packages in a Docker container with `./docker-build.sh` in Centos7:
```
# ./docker-build.sh 
Sending build context to Docker daemon 13.31 kB
Step 1 : FROM fedora:24
 ---> f623aaef07f0
Step 2 : MAINTAINER Devan Goodwin <dgoodwin@redhat.com>
 ---> Using cache
 ---> 55b3bf73e46a
Step 3 : RUN dnf install -y rpm-build rpmdevtools createrepo && dnf clean all
 ---> Using cache
 ---> 53ec756279e6
Step 4 : RUN rpmdev-setuptree
 ---> Using cache
 ---> 7faf70d5452e
Step 5 : USER root
 ---> Using cache
 ---> 7e0a93ddede3
Step 6 : ADD entry.sh /root/
 ---> Using cache
 ---> 5c0e13b551fa
Step 7 : COPY ./ /root/rpmbuild/SPECS
 ---> Using cache
 ---> 04ef048d4657
Step 8 : CMD /root/entry.sh
 ---> Using cache
 ---> d902626d0f23
Successfully built d902626d0f23
Cleaning output directory...
error: line 7: Illegal char '-' (0x2d) in: Version: 1.5.0-beta.2
```
And i try to modify kubelet.spec like this:
```
Name: kubelet
Version: 1.5.0.beta.2
Release: %{RPM_RELEASE}
Summary: Container cluster management
License: ASL 2.0
```
Then the building works.But im not sure if there will be any other problems.
@luxas can u help me?

**Comment by ixdy** [comment]
Changing the `-` to `.` breaks the semantic version compatibility though (http://semver.org/).

Reading the [Fedora docs](https://fedoraproject.org/wiki/Packaging:Versioning), it seems like we might need to put the `-beta.2` in `Release:`, which is kinda gross. (I'm also not sure how `RPM_RELEASE` really fits into the semver.)
