### ISSUE TITLE
Release notes API rate limiting throws 403

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/release#2225]
The release notes tool seems to get a new API response from GitHub if the rate limit kicks in:

```
level=fatal msg="gathering release notes: listing release notes: gathering notes: GET https://api.github.com/repos/cri-o/cri-o/commits/1aaf47484dcf1206663610c622a1b37a84e2e91b/pulls?page=1&per_page=100&state=closed: 403 You have exceeded a secondary rate limit. Please wait a few minutes before you try again. []"
```

Ref: https://github.com/cri-o/cri-o/runs/3422342329?check_suite_focus=true

It seems that we can mitigate by checking for the error and waiting a bit longer before trying it again.

**Comment by saschagrunert** [comment]
cc @kubernetes/release-managers

**Comment by sandipanpanda** [comment]
Hi there, I am a new contributor to Kubernetes and hopped in seeing good first issue label, can you please give a little insight on how to get started working on this issue?

**Comment by saschagrunert** [comment]
Sounds great @sandipanpanda, thank you for taking this opportunity. I think a good starting point would be to reproduce the issue with the `release-notes` tool: https://github.com/kubernetes/release/tree/master/cmd/release-notes

After that, we can try to catch the error in the retry logic of the release notes gatherer, which is using the go-github API. The retry logic can be found there: https://github.com/kubernetes/release/blob/a85ab2bd513a295abb765e230236a7b8101976ec/pkg/github/internal/retry.go#L63-L91

**Comment by rayandas** [comment]
Hi @sandipanpanda are you working on this issue? If not then I can take this up and give it a try.

**Comment by justaugustus** [comment]
This just burned a stage and should have higher priority.
/remove-priority important-soon
/priority critical-urgent
/milestone v1.23
cc: @kubernetes/release-engineering 
ref: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1631645686102400?thread_ts=1631606375.087500&cid=CJH2GBF7Y
