### ISSUE TITLE
Signing artifacts with `cosign`

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#2227]
#### What would you like to be added:

Signing artifacts with `cosign`

(I'm opening a placeholder to capture work. Let's capture thoughts here and we'll iterate over the issue description together.)

- [x] Grant Release Manager Admins `roles/cloudkms.signerVerifier`: https://github.com/kubernetes/k8s.io/pull/2614
- [x] Generate a key for testing: https://github.com/kubernetes/release/pull/2226

#### Why is this needed:

Should supersede sections of https://github.com/kubernetes/release/issues/914 once we flesh this out.

/assign @justaugustus @cpanato @puerco 
cc: @kubernetes/sig-release-admins @kubernetes/release-engineering @dlorenc @lukehinds

**Comment by sftim** [comment]
My question: does this change need a KEP?

**Comment by shibumi** [comment]
A few thoughts on this:

Right now, there is a cosign test key for signing. It would be nice, if we could switch to keyless signing via workload identities.
I wrote  a little blog article about how to sign BLOBs with cosign keyless: https://shibumi.dev/posts/first-look-into-cosign/

The next cosign version should be able to:

* create a keyless signature for any artifact
* store the signature on disk/github release log and/or in the rekor transparency log.

Current blockers:

* The public rekor/fulcio instances are still "test environments" and not meant for production use.
* The cosign feature for keyless signatures is still considered experimental.
* I don't know how the Github OIDC-Issuer / Workload Identity part will work in a big org like kubernetes.

I would suggest to wait until the sigstore stack is ready :)

It also might make sense to combine all of this with TUF or in-toto on the long run. First TUF, then in-toto.

**Comment by BenTheElder** [comment]
>  if we could switch to keyless signing via workload identities.

+1, one concern I have is making sure that the signatures are meaningful, having workload identity based signatures from the relatively locked down release process would provide some assurances.

> I don't know how the Github OIDC-Issuer / Workload Identity part will work in a big org like kubernetes.

build / publish actually runs in Google Cloud Build currently anyhow, FWIW. (or CI builds happen in our own Kubernetes based CI, which has GKE workload identity available).

Definitely smells like a KEP to me :-)

Somewhat related: I think if we want to sign CI builds we need to better secure them first (move them out to GCB for starters).

**Comment by shibumi** [comment]
@BenTheElder  Just for the record: https://github.com/google-github-actions/auth this might be interesting then, right?

**Comment by BenTheElder** [comment]
Er I don't think so for the main project 😅
The main Kubernetes project isn't using GitHub Actions.
We use:
- https://github.com/kubernetes/test-infra/tree/master/prow
- https://cloud.google.com/build

Some of the smaller repos use GitHub Actions for various things but not Kubernetes releases or CI builds.

**Comment by saschagrunert** [comment]
The initial draft of the sining KEP is proposed in https://github.com/kubernetes/enhancements/pull/3061

**Comment by trishankatdatadog** [comment]
Would be a great pioneering use case for [sigstore trust delegations](https://docs.google.com/document/d/1lNW2lNu9QmDhCgXJaNTYxBUzCjuWS2wj8fCHSadbzxQ/edit?usp=sharing)! @asraa

**Comment by saschagrunert** [comment]
Tracking the first implementation in https://github.com/kubernetes/release/issues/2383

**Comment by saschagrunert** [comment]
I think this can be closed and we can track the work in https://github.com/kubernetes/enhancements/issues/3031
