### ISSUE TITLE
Dynamically updating latest version URL for sbom.k8s.io

### ISSUE THREAD

**Issue by PushkarJ** [kubernetes/release#2234]
#### What would you like to be added:

Currently this command allows fetching the SBOM for a particular release like this:
`curl -L https://sbom.k8s.io/v1.22.1/release`

Is it possible to support this `curl -L https://sbom.k8s.io/latest/release` and then let it redirect automatically, to whichever is the latest semver release ?

#### Why is this needed:

Although this can be done canonically with two `curl` calls like this, the above URL could be appealing from better user experience and built-in support for getting latest SBOM

```
curl -Ls "https://sbom.k8s.io/$(curl -Ls https://dl.k8s.io/release/stable.txt)/release"
```

Slack convo: https://kubernetes.slack.com/archives/C2C40FMNF/p1630538458068700

**Comment by justaugustus** [comment]
/help
@kubernetes/release-engineering Associates -- this could be a good one to pick up!

**Comment by PushkarJ** [comment]
@palnabarun I was playing around with this some more and it seems like SBOM is generated for alpha releases as well. e.g. `v1.23.0-alpha.2`. 

Wondering if there is a URL for pre-release versions, similar to how we get stable release dynamically using this: `curl -Ls https://dl.k8s.io/release/stable.txt`
