### ISSUE TITLE
relnotes: Promotion of `--list-v2` to be default behavior

### ISSUE THREAD

**Issue by wilsonehusin** [kubernetes/release#2241]
#### What would you like to be added:

#1888 introduces `--list-v2` flag for release notes with performance improvements and bug fix. This has been the preferred method for collecting release notes for one (and a half-ish) release cycle.

I personally feel comfortable with promoting this into default behavior and begin "fix and roll forward" for any bug which shows up in the future, thought I would like to solicit feedback on this process and how people feel / think with regards to timeline.

#### Why is this needed:

- Cut down variations and simplify `krel` to the necessary lines of code.
- I'm reviving efforts to #1889 which was abandoned for the past few months, which would benefit from having this resolved.

/cc puerco cici37 pmmalinov01

**Comment by wilsonehusin** [comment]
I keep forgetting that `/cc`doesn't work on issues lol

cc @puerco @cici37 @pmmalinov01

**Comment by cici37** [comment]
We have been trying with `--list-v2` since last release cycle(1.22) and it has been working great :blush:
