### ISSUE TITLE
Integrate file promotion into k/k release process

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#2248]
#### What would you like to be added:

Integrate file promotion into k/k release process
(peeling this off of the tracking issue here: https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/266)

#### Why is this needed:

Umbrella for automated file promotion: https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/413

/assign

**Comment by saschagrunert** [comment]
@justaugustus @puerco what needs to be done here? Is this a candidate for https://github.com/kubernetes/release/issues/2513
