### ISSUE TITLE
Automatically label CVE covert PRs with area/cve

### ISSUE THREAD

**Issue by puerco** [kubernetes/release#2264]
#### What would you like to be added:

SIG Security has proposed a new label `area/cve` to mark all PRs and issues related to CVEs:
ref: https://github.com/kubernetes/test-infra/pull/23428

Once this proposal merges and is enabled in all repos, we should modify the release process to stamp all pull requests in the CVE data files as `area/cve` when reading the vulnerability information. 

#### Why is this needed:

Tagging the covert PRs with the new label enables downstream consumers to monitor a feed reading from the GitHub label and get a programmatic notice of vulnerabilities as soon as we cut a new release.

/cc @PushkarJ @tabbysable @justaugustus

**Comment by PushkarJ** [comment]
@puerco is request perhaps similar to this : https://github.com/kubernetes/sig-security/issues/1

**Comment by puerco** [comment]
It's an enabler for kubernetes/sig-security#1. Once we have this geature in place, you'll get the CVE pull requests automatically labeled, saving you from "_Search and Identify closed issues that have a CVE ID_" for any future CVE in Kubernetes. They will get tagged at release time, which is usually right after the embargo is lifted.

If you want, add this issue to your umbrella we can work SIG to SIG: we take care of working on this and contribute to your project :)

**Comment by PushkarJ** [comment]
The initial goal for the label and the label name have significantly shifted (from all issues and PRs for CVEs to only officially announced issues for CVEs). So labelling all CVE related issues and PR from sig-release with the new label may not be useful. Instead of that the SRC issues for official CVEs are now being labelled with the new label with the update to their template: https://github.com/kubernetes/committee-security-response/pull/133

Suggest that we close this for now, and revisit in future if necessary!

**Comment by puerco** [comment]
OK, so the PRs will not get the label?

**Comment by PushkarJ** [comment]
>OK, so the PRs will not get the label?

Yes correct. Folks recommended that the label be used by SRC for only officially announced CVEs in k8s, not the ones let's say that we fix in images or build time deps.

**Comment by puerco** [comment]
Oh yeah, my understanding was that we were going to label the PRs that contain the fix when the CVE data got read by the release process:

https://github.com/kubernetes/test-infra/pull/23428#issuecomment-925540948

**Comment by tabbysable** [comment]
/close

(Please re-open if I was wrong and this still needs further discussions.)
