### ISSUE TITLE
General promote-images tool for k8s image maintainers

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes/release#2279]
#### What would you like to be added:

Currently, the krel promote-images tool only works for kubernetes images. It would be great to extend it to other projects in k8s and k8s-sigs that have staging images hosted in k8s.gcr.io.

Slack thread for context: https://kubernetes.slack.com/archives/CCK68P2Q2/p1629334254082700

**Comment by justaugustus** [comment]
Completed in https://github.com/kubernetes/release/pull/2280, https://github.com/kubernetes-sigs/promo-tools/pull/458, and https://github.com/kubernetes-sigs/promo-tools/pull/460.

Docs here: https://sigs.k8s.io/promo-tools/docs/promotion-pull-requests.md

Thanks for working on this, Cecile!
/close
