### ISSUE TITLE
Yum repository pool is empty, Why?

### ISSUE THREAD

**Issue by aoxn** [kubernetes/release#228]
## kubelet yum source mirror fail

When i try to mirror ```http://yum.kubernetes.io/repos/kubernetes-el7-x86_64``` for kubelet and kubadm release to my own repository, i get 404 errror.  Then I found yum/pool directory is empty, Could anyone take a look at this?

```
root@iZ62dw79jn3Z:~# curl -L https://packages.cloud.google.com/yum/pool

<html>
  <head>
    <title>Directory listing for /yum/pool/</title>
    <base href="/yum/pool/">
  </head>
  <body>
    <h2>Index of /yum/pool/</h2>
    <p></p>
  </body>
</html>
```

**Comment by spacexnice** [comment]
@ncdc @willb Could you take a look?

**Comment by willb** [comment]
@spacexnice Sorry, I can't help with that repository.  But I bet someone who can will see this issue!

**Comment by luxas** [comment]
I clearly see some packages here: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/filelists.xml

But I'm not familiar with the rest of the rpm packaging process.

cc @dgoodwin

**Comment by spacexnice** [comment]
@luxas  @dgoodwin The file filelist.xml is in there, but not the pool directory which should contain the actual file.

**Comment by Slahser** [comment]
@spacexnice you can direct download rpm by concat `location` [here](https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/primary.xml) with `https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64` over the wall.


![screen shot 2016-12-14 at 17 14 13](https://cloud.githubusercontent.com/assets/3760744/21176302/10e8de84-c221-11e6-94c1-fc35b2e315a3.png)

**Comment by spacexnice** [comment]
Thanks! @Slahser  @luxas

**Comment by spacexnice** [comment]
@Slahser  Does k8s yum | apt  source ```https://packages.cloud.google.com/yum```  has the willing to open rsync port to let ```mirrors.aliyun.com`` do file synchronize?    Since k8s source does not open rsync port or have any file timestamp or opening pool directory , we can not do a standard file synchronization.

**Comment by Slahser** [comment]
theres a delay between release and repo.
you should build the release and modify the KUBE_VERSION to 1.5.1
i have try your pr in 1.5.1,works fine.

**Comment by luxas** [comment]
1.5.1 is released already

**Comment by Starefossen** [comment]
@luxas any thoughts on when 1.5.2 will be available?

**Comment by xiaoping378** [comment]
now should be v1.5.3

**Comment by ixdy** [comment]
not sure who owns the yum repository - @mikedanese?

**Comment by mikedanese** [comment]
I'm deleting off topic questions about rpm releases. Please stay on topic.

Since https://packages.cloud.google.com is a shared yum repo I'm fairly certain you don't want to mirror terabytes of packages. It would be better if you more precisely crawled the repo with the method that @Slahser pointed out.

**Comment by rareshornet** [comment]
If anyone needs to mirror the rpms using cobbler u can do that by adding the package names in the RPM list as vobbler repo add --name=CentOS-7-x86_64-kubernetes-update --mirror-locally=True --keep-updated=True --mirror="http://yum.kubernetes.io/repos/kubernetes-el7-x86_64" --rpm-list="kubeadm kubelet kubectl"

This will download only latest packages

after this you can reserve the repo as rsync with cobbler
