### ISSUE TITLE
Centos7: ARM/ARM64 Support (Multiarch)

### ISSUE THREAD

**Issue by EmbeddedAndroid** [kubernetes/release#232]
Hi,

I've been using the .spec file in this repo to produce and test ARM64 rpm packages for kubernetes[0]. I'd like to get rid of this forked work, and include it in the official .spec file. Is there interest in building rpms for multiple architectures? If so, I can send a PR to enable multiarch, and by default build packages for x86_64/ARM/ARM64. I'd also volunteer to test and maintain the ARM/ARM64 rpms as needed.

Cheers,

[0] http://repo.linaro.org/rpm/tbaker/centos-7/repo/

**Comment by luxas** [comment]
Cool, I wrote on http://kubernetes.io/docs/getting-started-guides/kubeadm/ under the multiarch section that we could do that if there's interest for rpms as well.

We've had it from the start with the debs, you can use that script as a reference.
Cheers!

**Comment by EmbeddedAndroid** [comment]
Excellent! Thanks for the response, and the pointer to the documentation about multiarch requests! I'll send a PR referencing this issue.
