### ISSUE TITLE
Automate tasks post branch cut

### ISSUE THREAD

**Issue by palnabarun** [kubernetes/release#2332]
Following on from https://kubernetes.slack.com/archives/CJH2GBF7Y/p1637728877246300?thread_ts=1637714492.229600&cid=CJH2GBF7Y, there is a need to investigate the possibility of automating the following steps in order.

From @justaugustus -- 
```
the reason for the order of operations is that:
- you need the release branch to have been created, so that:
- the version marker latest-<version> will exist, so that:
- it can be used in the kubekins-e2e/krte image
After merging the kubekins PR, it'll:
- trigger an image build, which allows you to:
- generate the release branch jobs discovering the latest image tag
```

#### Why is this needed:

To make things simpler and seamless for Release Managers.

**Comment by daemon1024** [comment]
Hey 👋🏽 

I believe this is not done yet! I would like to help out here 😄 

From my understanding,
When kubekins PR i.e. something like https://github.com/kubernetes/test-infra/pull/24450 is merged. We follow it up with changes made in https://github.com/kubernetes/test-infra/pull/24453.

Essentially trying to automate the steps mentioned here - https://github.com/kubernetes/sig-release/blob/master/release-engineering/role-handbooks/branch-manager.md#update-e2e-variants=
