### ISSUE TITLE
krel will create PR with empty changes

### ISSUE THREAD

**Issue by cici37** [kubernetes/release#2338]
#### What happened:
When create release notes draft pr with krel command, the PR will be raised with empty changes.

#### What you expected to happen:
Inform the user there is no changes and stop from further raising the PR.

#### How to reproduce it (as minimally and precisely as possible):
Use command like `krel release-notes --create-draft-pr --fix --list-v2` to generate release notes draft pr repeatly

#### Environment:

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by wilsonehusin** [comment]
🤔 do you have an example?

**Comment by cici37** [comment]
> thinking do you have an example?

https://github.com/kubernetes/sig-release/pull/1763
