### ISSUE TITLE
Implement container image signing MVP (KEP-3031)

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/release#2383]
We're now able to implement a Minimum Viable Product (MVP) after the merge of the release artifact signing KEP proposal:
- https://github.com/kubernetes/enhancements/issues/3031
- https://github.com/kubernetes/enhancements/pull/3061

This issue is part of https://github.com/kubernetes/release/issues/2227, which covers the whole topic from a release engineering perspective.

---

As a first iteration, we decided to sign the [official Kubernetes container images](https://console.cloud.google.com/gcr/images/k8s-staging-kubernetes) using cosigns keyless signing feature: https://github.com/sigstore/cosign/blob/main/KEYLESS.md

#### Implementation details and constraints:

- It's fine to use the default root trust for singing in the MVP, we will switch to our own in later iterations.
- The main implementation should be done in [kubernetes-sigs/release-sdk](https://github.com/kubernetes-sigs/release-sdk) 
  with keeping in mind that it will be reused by [krel](https://github.com/kubernetes/release/tree/master/cmd/krel) as well as [kpromo](https://github.com/kubernetes-sigs/promo-tools/tree/main/cmd/kpromo)
- We assume that we sign in a Google Cloud Build environment (the same where we push the images around) for simplicity reasons
- We should check if we can use cosign as a golang library rather than having the binary as direct dependency
- There is a documentation requirement for end-users to verify the signatures

cc @kubernetes/release-engineering

---

#### KEP updates

- https://github.com/kubernetes/enhancements/pull/3061
- https://github.com/kubernetes/enhancements/pull/3191

#### Implementation into release-sdk

- https://github.com/kubernetes-sigs/release-sdk/pull/19
- https://github.com/kubernetes-sigs/release-sdk/pull/20
- https://github.com/kubernetes-sigs/release-sdk/issues/21
    - https://github.com/kubernetes-sigs/release-sdk/pull/25
    - https://github.com/kubernetes-sigs/release-sdk/pull/26
    - https://github.com/kubernetes-sigs/release-sdk/pull/27
    - https://github.com/kubernetes-sigs/release-sdk/pull/28
    - https://github.com/kubernetes-sigs/release-sdk/pull/48
- https://github.com/kubernetes-sigs/release-sdk/issues/22 
  (Out of scope of the MVP but still required for follow-ups)
  - https://github.com/kubernetes-sigs/release-sdk/pull/29
- https://github.com/kubernetes-sigs/release-sdk/issues/23
  - https://github.com/kubernetes-sigs/release-sdk/pull/32
  - https://github.com/kubernetes-sigs/release-sdk/pull/33
  - https://github.com/kubernetes-sigs/release-sdk/pull/39
- https://github.com/kubernetes-sigs/release-sdk/issues/30
  (Out of scope of the MVP but still required for follow-ups)
- https://github.com/kubernetes-sigs/release-sdk/issues/24
  - https://github.com/kubernetes-sigs/release-sdk/pull/31
  - https://github.com/kubernetes-sigs/release-sdk/pull/34
  - https://github.com/kubernetes-sigs/release-sdk/pull/35
- https://github.com/kubernetes-sigs/release-sdk/pull/36
- https://github.com/kubernetes-sigs/release-sdk/issues/37
  - https://github.com/kubernetes-sigs/release-sdk/pull/53
- https://github.com/kubernetes-sigs/release-sdk/pull/42
- https://github.com/kubernetes-sigs/release-sdk/pull/44
- https://github.com/kubernetes-sigs/release-sdk/pull/46

#### Integration into krel

- https://github.com/kubernetes/release/pull/2397
- https://github.com/kubernetes/release/issues/2417

#### Integration into the Container Image Promoter 
- https://github.com/kubernetes-sigs/promo-tools/pull/494
- https://github.com/kubernetes-sigs/promo-tools/pull/498
- https://github.com/kubernetes-sigs/promo-tools/pull/501
- https://github.com/kubernetes-sigs/promo-tools/pull/542 

#### Infrastructure changes

- https://github.com/kubernetes/k8s.io/issues/3299
- https://github.com/kubernetes/release/issues/2445
  - https://github.com/kubernetes/k8s.io/issues/3461
  - https://github.com/kubernetes/k8s.io/pull/3451
  - https://github.com/kubernetes/k8s.io/pull/3456
  - https://github.com/kubernetes/k8s.io/pull/3462
 - https://github.com/kubernetes-sigs/promo-tools/issues/523
   - https://github.com/kubernetes/test-infra/pull/25857
   - https://github.com/kubernetes-sigs/promo-tools/pull/529
   - https://github.com/kubernetes-sigs/promo-tools/pull/532
   - https://github.com/kubernetes-sigs/promo-tools/pull/535
   - https://github.com/kubernetes/k8s.io/pull/3601
   - https://github.com/kubernetes/test-infra/pull/25891
   - https://github.com/kubernetes-sigs/promo-tools/pull/538
   - https://github.com/kubernetes/k8s.io/pull/3611
   - https://github.com/kubernetes/test-infra/pull/25942

#### End user documentation

- https://github.com/kubernetes/release/pull/2400
- https://github.com/kubernetes/website/issues/31420
  - https://github.com/kubernetes/website/pull/31610
  - https://github.com/kubernetes/website/pull/31611
  - https://github.com/kubernetes/website/pull/32184

#### Other relevant implementations
- https://github.com/kubernetes-sigs/cri-tools/pull/906

**Comment by puerco** [comment]
About this:
> We should check if we can use cosign as a golang library rather than having the binary as direct dependency

Yes, `cosign` can be used as a library, the end goal is to make all functionality available to other programs. If something is missing we can certainly add it. Everything here is intended to be improtable:

https://github.com/sigstore/cosign/tree/main/pkg/cosign

**Comment by saschagrunert** [comment]
As per [slack discussion thread](https://kubernetes.slack.com/archives/CJH2GBF7Y/p1641892345007500), @jimangel, @palnabarun and @xmudrii are happy to work on this one with guidance from @puerco and myself.

I think a good first step would be to implement the raw code bits converted from the [keyless signing doc](https://github.com/sigstore/cosign/blob/main/KEYLESS.md) in release-sdk and add (mockable) unit tests for them. This way we can define an API and review if it would fit for the MVP (and future) use cases.

**Comment by PushkarJ** [comment]
RelEng team, It is so great to see this coming together. 

@saschagrunert are there are any meeting minutes / slack channels / calendar invites I can subscribe to so that I can keep up to date with the progress and discussions around this KEP implementation?

/sig security

**Comment by saschagrunert** [comment]
> @saschagrunert are there are any meeting minutes / slack channels / calendar invites I can subscribe to so that I can keep up to date with the progress and discussions around this KEP implementation?

Thank you for considering to help us with the effort! We have a Release Engineering meeting every other week where we discuss the current progress and sync: https://bit.ly/k8s-releng-meeting

**Comment by saschagrunert** [comment]
Only https://github.com/kubernetes/release/issues/2417 is missing, otherwise we can consider this one as done :partying_face:

**Comment by saschagrunert** [comment]
We can do https://github.com/kubernetes/release/issues/2417 in a different scope. Since 1.24 will be released today we now consider this EPIC is done. :partying_face:
