### ISSUE TITLE
Create automatic release branch fast forward job

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/release#2386]
As discussed in https://github.com/kubernetes/sig-release/discussions/1794, there is a gap between the content of the k/k `release-*` branch and `master` when we cut the RC on test freeze, because:

- PRs in the milestone may not have been merged yet into the `master`, because they're in the prow test queue
- PRs get the latest milestone applied after the RC creation

To streamline the process of the latest release branch, I now propose to automate the branch fast forward until we cut the final release. This has to be communicated and documented clearly to all contributors before the automation goes live. That said, we have to:

- [x] Modify `krel ff` to automatically determine if a fast forward is required (latest release branch has no final tag):
      https://github.com/kubernetes/release/pull/2389
      https://github.com/kubernetes/release/pull/2390
      https://github.com/kubernetes-sigs/release-sdk/pull/18
      https://github.com/kubernetes/release/pull/2413
      https://github.com/kubernetes/release/pull/2414
      https://github.com/kubernetes/release/pull/2424
- [x] Create a new periodic prow job to run a new Google Cloud Build job in our project (the token there has the permissions to push to k/k):
     https://github.com/kubernetes/release/pull/2391
     https://github.com/kubernetes/test-infra/pull/24901
     https://github.com/kubernetes/test-infra/pull/25140
     https://github.com/kubernetes/k8s.io/pull/3372
- [x] Update documentation
     https://github.com/kubernetes/sig-release/pull/1855
     https://github.com/kubernetes/test-infra/pull/25300
- [x] Add new testfreeze plugin
    https://github.com/kubernetes/test-infra/pull/25535
    https://github.com/kubernetes/test-infra/pull/25644
- [x] Run the job in nomock mode
    https://github.com/kubernetes/test-infra/pull/26188
    https://github.com/kubernetes/sig-release/pull/1898
- [x] Change the testfreeze plugin to mention the auto fast-forward once the job goes live in 1.25.
    https://github.com/kubernetes/test-infra/pull/26190
- [x] Get in touch with SIG Contribex about the workflow change.

For now everything should run in `mock` mode, meaning that no modifications to the main repository will be done until we have communicated the change accordingly.

---

**Testgrid:** https://testgrid.k8s.io/sig-release-releng-informing#git-repo-kubernetes-fast-forward

**Comment by cpanato** [comment]
i like this approach and i think that will be good for us

**Comment by puerco** [comment]
+1 I think this is the best scenario.

From our side, I preferred the idea of reopening `master` instantly after branch creation, but @liggitt made an [excellent point here](https://github.com/kubernetes/sig-release/discussions/1794#discussioncomment-1832793) against here.

Cherry picks have been chaotic, especially the last two releases. Although we did a poor job communicating the change back in 1.19, I feel they are an unnecessary burden on humans and I think efforts should go into a better system to apply the milestones more carefully while the branch is frozen.

**Comment by saschagrunert** [comment]
Only the integration into prow is missing now, see https://github.com/kubernetes/test-infra/pull/24901

**Comment by saschagrunert** [comment]
Update email sent to k-dev: https://groups.google.com/a/kubernetes.io/g/dev/c/qbHPJjUF3s8/m/f_6NI4-TBAAJ

**Comment by saschagrunert** [comment]
Sent a note to k-dev: https://groups.google.com/a/kubernetes.io/g/dev/c/qbHPJjUF3s8/m/6tjttkfHAAAJ

Everything works so far, we can consider this one as finished. :)
