### ISSUE TITLE
ci-signal-reporter, use new ci signal github project board

### ISSUE THREAD

**Issue by leonardpahlke** [kubernetes/release#2396]
which part of the ci-signal-tool does this effect 
* :green_circle: ci-signal-report-cli

**Summary:** The CI signal reporter should use the new [ci signal project board](https://github.com/orgs/kubernetes/projects/68/)

<details>
<summary>Current situation</summary>
Currently the [old project board](https://github.com/orgs/kubernetes/projects/65/) is used which does not get updated anymore
</details>

<details>
<summary>Desired outcome</summary>
The new project board should be accessed
</details>
<br>

**Benefits:** Prevent outdated ci signal reports with more features as the beta project board stores more information

**Concerns:** None

/kind feature
/assign

**Comment by Nivedita-coder** [comment]
Hey @leonardpahlke,
For this feature does this involve both (k/release, k-sigs/release-sdk) repos?

**Comment by leonardpahlke** [comment]
Ideally yes but this can also be done in two steps. First update the logic in k/release and afterwards refactored it to sigs/release-sdk. It’s up to you if you like to do it all at once or step by step.

**Comment by leonardpahlke** [comment]
Hey @Nivedita-coder how is it going on this? I am happy to help or pick up your work / the issue 🙌

**Comment by leonardpahlke** [comment]
BTW there is another issue for the GitHub logic refactoring #2404

**Comment by Nivedita-coder** [comment]
Hi @leonardpahlke, for the last two weeks I'm a bit busy with offline college, but by the end of this weekend, I'll push the PR.:raised_hands:

**Comment by leonardpahlke** [comment]
xref: [slack discussion](https://kubernetes.slack.com/archives/CN0K3TE2C/p1643981567813309)

**Comment by leonardpahlke** [comment]
echo my message from [slack thread](https://kubernetes.slack.com/archives/CN0K3TE2C/p1646310409857229?thread_ts=1643981567.813309&cid=CN0K3TE2C).  
---
I looked into this a bit and build a quick project to play around with the github graphql  api. We can use the graphql API for our usecase. If you find time check out the main.go file. I use a 3rd party library to use the graphql api (see [githubv4](https://github.com/shurcooL/githubv4))
```go
package main
​
import (
	"context"
	"fmt"
	"os"
​
	"github.com/shurcooL/githubv4"
	"golang.org/x/oauth2"
)
​
const (
	CiSignalProjectDashboardNumber = 68
	CiSignalProjectDashboardOrg    = "Kubernetes"
)
​
func main() {
	// setup clients
	src := oauth2.StaticTokenSource(
		&oauth2.Token{AccessToken: os.Getenv("GITHUB_TOKEN")},
	)
	httpClient := oauth2.NewClient(context.Background(), src)
​
	// lookup project board ID
	var queryProjectBoardID struct {
		Organization struct {
			ProjectNext struct {
				ID string
			} `graphql:"projectNext(number: $projectDashboardNumber)"`
		} `graphql:"organization(login: $projectDashboardOrg)"`
	}
	variablesProjectBoardID := map[string]interface{}{
		"projectDashboardNumber": githubv4.Int(CiSignalProjectDashboardNumber),
		"projectDashboardOrg":    githubv4.String(CiSignalProjectDashboardOrg),
	}
	client := githubv4.NewClient(httpClient)
	if err := client.Query(context.Background(), &queryProjectBoardID, variablesProjectBoardID); err != nil {
		panic(err)
	}
	fmt.Println("ProjectID:", queryProjectBoardID.Organization.ProjectNext.ID)
​
	// lookup project fields
	var queryProjectBoardFields struct {
		Node struct {
			ProjectNext struct {
				Items struct {
					Nodes []struct {
						ID          string
						Title       string
						FieldValues struct {
							Nodes []struct {
								Value        string
								ProjectField struct {
									Name string
								}
							}
						} `graphql:"fieldValues(first: 20)"`
					}
				} `graphql:"items(first: 100)"`
			} `graphql:"... on ProjectNext"`
		} `graphql:"node(id: $projectBoardID)"`
	}
	variablesProjectBoardFields := map[string]interface{}{
		"projectBoardID": githubv4.ID(queryProjectBoardID.Organization.ProjectNext.ID),
	}
	if err := client.Query(context.Background(), &queryProjectBoardFields, variablesProjectBoardFields); err != nil {
		panic(err)
	}
	fmt.Println("queryProjectBoardFields:", queryProjectBoardFields.Node.ProjectNext.Items)
}
```
