### ISSUE TITLE
Add container image signatures to changelog

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/release#2417]
We now feature a list of container images in our changelog: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#container-images

After the container image signing PR got merged (https://github.com/kubernetes/release/pull/2397), we have to modify that table to link the actual signatures for each image. The idea is to add a placeholder on `krel stage` and modify it after the images have been signed via kpromo on `krel release`.

The tricky part is that we have to do yet another repository modification on `krel release`, verify the signatures and link them to their corresponding image.

/help

Refers to https://github.com/kubernetes/release/issues/2383

**Comment by xmudrii** [comment]
I'm currently super busy with the university, so I'll unassign myself and someone else can take over.
/unassign

**Comment by cpanato** [comment]
no worries @xmudrii

**Comment by saschagrunert** [comment]
I think it would make sense to reassemble the link to the signature in the changelog, for example:

https://console.cloud.google.com/gcr/images/k8s-staging-kubernetes/global/mock%2Fconformance-amd64@sha256:e7587c67d37a6628f56d9b859472d2a9646db9b013e91446d5ec38b60f54fbaa/details?tab=pull

**Comment by saschagrunert** [comment]
Any update on this @cpanato? Would be awesome to get this final bit in to resolve the MVP :)

**Comment by saschagrunert** [comment]
@cpanato are you still working on this one? :upside_down_face:

**Comment by cpanato** [comment]
> @cpanato are you still working on this one? 🙃

I'm trying but the past two weeks were too busy :(

**Comment by saschagrunert** [comment]
The tricky part is that we generate the changelog before staging the releases and therefore cannot foresee which signatures we will generate. Therefore I think we should close it as wont-fix.
