### ISSUE TITLE
Image Signing: Impersonation Flows and Service Account Interaction

### ISSUE THREAD

**Issue by puerco** [kubernetes/release#2445]
## Impersonation Flow During Release Staging

During staging, there are two accounts in play: The account that runs the release process and the account that provides the identity to sign. The former should be able to generate identity tokens for the latter. 

```mermaid
flowchart LR
  subgraph Impersonation Flow During Staging
  P1[Start] ==> P2[Build] ==>P3[Sign Images] ==> P4[Stage Artifacts]  ==>P6[End]
  end
  P3 <-- OIDC ID Tokens --o SP1[Staging ID Service Acct]
```

### Service Accounts and Roles

* Main Release Process SA: This account provides the identity under which krel is during staging by the GCB job
* Staging Signer Account: This account serves as an identity provider for the signatures done during staging

## Impersonation Flow During Image Promotion

There are several roles that service accounts need to be able to do during image promotion. The interaction between them can turn complex and there are several accounts involved to create a successful promotion.

```mermaid
flowchart LR
  subgraph Signer Project
    SP1[Main Kubernetes Signer Account]
  end
  subgraph Impersonation Flow During Image Promotion
  P1[Start] ==> P2[Promotion] ==>P3[Sign Images] ==> P4[Attach Signatures] ==>P5[Attach SBOM] ==>P6[End]
  end
  P2 o-- impersonate --o I1[Promotion Service Account] 
  P3 o-- OIDC ID Tokens --o SP1
  P4 o-- impersonate --o I1
  P5 o-- impersonate --o I1
```
### Service Accounts and Roles

The following service accounts play a role during image promotion

* Main Promoter SA. This account runs the promoter pod
* Source Registry SA. This account needs access to the source registry to read images bound for promotion. Since most source registries republic, this account is optional
* Target Registries SAs. The promoter needs read and write access to each target registry images are promoted to. This means that accounts for accessing the target registries are required. It may be the case that the same SA is used for all.
* Signer Service Account. This service account provides the identity for the image signatures.

## Impersonation Flow During e2e Tests

During e2e tests, things are simpler as we can use a dedicated SA for running the tests and one SA (in the same project) for generating test signatures

```mermaid
flowchart LR
  subgraph Impersonation Flow During e2e Tests
  P1[Start] ==> P2[e2e test] 
  P1==>P3[Signing Tests]
  P2==>P6[End]
  P3==>P6
  P2 o-- activate --o I1[Testing Service Account] 
  P3 o-- activate --o I1
  P3 <-- OIDC ID Tokens --o SP1[Signing Tests Service Acct]
  SP1 o--o I1
  end
  
```

### Service Accounts and Roles

* Main Promoter SA. This account runs the promoter pod
* Registry Access SA. This account I used to read and write to the test registries
* Test Signer Account. This account serves only as the identity provider for the test signatures during e2es.

## Infra Tasks and ToDos

In order to cover the identity needs of the above flows, we need to create the required projects and service accounts.

#### krel staging
- [x] Determine project for the signer service account  (`k8s-releng-prod` ref: https://github.com/kubernetes/k8s.io/issues/3461#issuecomment-1056017938)
- [ ] create signer service account - https://github.com/kubernetes/k8s.io/pull/3456
- [x] Activate IAM Service Account Credentials API in Release Process Project - https://github.com/kubernetes/k8s.io/pull/3462
- [ ] Grant Release Process SA Token Creator Permissions in staging signer acct - https://github.com/kubernetes/k8s.io/pull/3456

#### Image Promoter e2e Tests
- [x] Enable IAM Service Account Credentials API in promoter test project - https://github.com/kubernetes/k8s.io/pull/3451
- [x] Create Signer Account for e2e Tests - https://github.com/kubernetes/k8s.io/pull/3451

#### Image promotion
- [x] ~~Create Kubernetes Signer Project~~ (reusing `k8s-release prod` ref: https://github.com/kubernetes/k8s.io/issues/3461#issuecomment-1056017938)
- [ ] Remove Cross Project Impersonation Constraint in Signer Project - https://github.com/kubernetes/k8s.io/pull/3456
- [ ] Enable IAM Service Account Credentials API in Promoter Project - https://github.com/kubernetes/k8s.io/pull/3451
- [ ] Create Main Kubernetes Signer Service Account - https://github.com/kubernetes/k8s.io/pull/3456
- [ ] Grant Token Creator Access in Main Kubernetes Signer to Main Promoter Accounts - https://github.com/kubernetes/k8s.io/pull/3456

**Comment by puerco** [comment]
/sig release
/sig k8s-infra
/sig security
/cc @kubernetes/sig-release-leads @kubernetes/release-engineering
SIG liaisons: @ameukam @PushkarJ

**Comment by saschagrunert** [comment]
Depends on https://github.com/kubernetes/release/pull/2397

**Comment by saschagrunert** [comment]
@puerco can this one be closed?

**Comment by saschagrunert** [comment]
Closing since it seems resolved.
