### ISSUE TITLE
Replace old hash listing with SBOM + verification instructions

### ISSUE THREAD

**Issue by puerco** [kubernetes/release#2446]
#### What would you like to be added:

As noted in a recent slack conversation, we stopped publishing the SHA256/SHA512 hashes of the sole artifact that gets uploaded to the GitHub release pages. We should instead replace the old SHAs with instructions to verify any artifact using the SBOM and maybe upload the SBOMs to the release pages as well.

#### Why is this needed:

There is little value in publishing SHAs to the release page. The SBOM contains the hashes for the kubernetes.tar.gz file that gets uploaded there and for every other artifact in the release.

**Comment by rajibmitra** [comment]
what is the sbom url ? if we know the url we can get it verified by grype.

**Comment by matglas** [comment]
> what is the sbom url ? if we know the url we can get it verified by grype.

It looks like sbom is here for example:
https://sbom.k8s.io/v1.24.0/release
