### ISSUE TITLE
ci-signal-reporter, github report bug, type miss match

### ISSUE THREAD

**Issue by leonardpahlke** [kubernetes/release#2473]
#### What happened:

After the [most recent change](https://github.com/kubernetes/release/pull/2454) to the CI Signal Report CLI which uses the new [CI Signal project board](https://github.com/orgs/kubernetes/projects/65) via a [GitHub GraphQL libary](https://github.com/shurcooL/githubv4) now does not run when a GH report generated.
From the error message it seems to be a type missmatch / convertion bug. 

```
FATA[0000] getting GitHub report data: json: cannot unmarshal number into Go struct field GitHubProjectBoardFieldSettings.width of type string 
exit status 1

```  

#### How to reproduce it (as minimally and precisely as possible):

Run the report and you should see the error message above

/assign @RobertKielty

**Comment by RobertKielty** [comment]
Reproduced locally on go version go1.17.6 linux/amd64
Root cause analysis to follow ...
