### ISSUE TITLE
jobResultsCache.json only keeps one entry

### ISSUE THREAD

**Issue by enisoc** [kubernetes/release#249]
I was investigating why `find_green_build` keeps failing (which is blocking me from cutting 1.6 alpha), and I found that `jobResultsCache.json` only has one entry for each job.

I think it's because `hack/jenkins/upload-to-gcs.sh` expects the JSON file to come back verbatim [as it's printed](https://github.com/kubernetes/kubernetes/blob/a988f71ef06d5b1c128a6e7f28600f69e3b46c4a/hack/jenkins/upload-to-gcs.sh#L220):

```shell
echo "{\"version\": \"${version}\", \"buildnumber\": \"${BUILD_NUMBER}\"," \
       "\"result\": \"${build_result}\"}" >> ${tmp_results}
```

However, it's actually coming back "helpfully" auto-formatted:

```console
$ gsutil -q cat gs://kubernetes-jenkins/logs/ci-kubernetes-e2e-gce/jobResultsCache.json
[
  {
    "buildnumber": "3173", 
    "job-version": "v1.6.0-alpha.0.3641+54ff40670269fb", 
    "version": "v1.6.0-alpha.0.3641+54ff40670269fb", 
    "result": "SUCCESS", 
    "passed": true
  }
]
```

As a result, the [filter to select previous entries](https://github.com/kubernetes/kubernetes/blob/a988f71ef06d5b1c128a6e7f28600f69e3b46c4a/hack/jenkins/upload-to-gcs.sh#L215) matches nothing and all previous builds are erased:

```shell
sed -n 's/^\({"version".*}\),*/\1,/p'
```

**Comment by ixdy** [comment]
We don't use upload-to-gcs.sh anymore.

This might be a bug in [bootstrap.py](https://github.com/kubernetes/test-infra/blob/master/jenkins/bootstrap.py#L329-L368). cc @kubernetes/test-infra-maintainers

**Comment by fejta** [comment]
@enisoc when do you need to cut a 1.6 alpha branch?

**Comment by enisoc** [comment]
@ixdy Oops, thanks for the correction. :)

@fejta I don't have a specific deadline, but it looks like the first meeting of the 1.6 release team will be at the end of next week (Jan 27). I'd like to have the alpha cut working in mock mode by then so I'm locked and loaded.

**Comment by ixdy** [comment]
@enisoc no worries, it's confusing, and the infrastructure is in a state of flux. even I'm not entirely sure where it's used right now.

**Comment by enisoc** [comment]
I was able to confirm that it's a bug in `bootstrap.py` by modifying it to run locally and directly calling `append_result()`. The fix should be https://github.com/kubernetes/test-infra/pull/1726.

**Comment by enisoc** [comment]
I think it's working!

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/jobResultsCache.json
