### ISSUE TITLE
Duplicated release notes in 1.24

### ISSUE THREAD

**Issue by wilsonehusin** [kubernetes/release#2532]
#### What happened:

The release notes for [#107554](https://github.com/kubernetes/kubernetes/pull/107554) was listed twice in "Urgent upgrade notes" section.

#### What you expected to happen:

Listing only once.

#### How to reproduce it (as minimally and precisely as possible):

(Triage required).

#### Anything else we need to know?:

https://github.com/kubernetes/kubernetes/pull/110184

#### Environment:

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by wilsonehusin** [comment]
well, not exactly — the point of this issue is that "how did the duplicate happen that https://github.com/kubernetes/kubernetes/pull/110184 was necessary to fix the problem?" :)

**Comment by ramrodo** [comment]
I see. My bad. I misunderstood the description of this issue. We'll try to fix this before we'll create the CHANGELOG for v1.25.
