### ISSUE TITLE
Support cutting Release Candidates

### ISSUE THREAD

**Issue by enisoc** [kubernetes/release#254]
@ixdy @calebamiles @ethernetdan

For 1.6, we will need the ability to cut Release Candidates with anago. Our tentative schedule places the first RC cut on March 28.

**Comment by ixdy** [comment]
For more context: we expect to have at least one RC release (i.e. v1.6.0-rc.1) after the last beta release before the final GA release (v1.6.0), so tooling needs to understand how to handle this. (It probably just requires updating a few regexes to support "rc". An open question is whether the RC # should start at 0 or 1.)

**Comment by enisoc** [comment]
Fixed by https://github.com/kubernetes/release/pull/280.
