### ISSUE TITLE
Modify krel Error message when github token env not set

### ISSUE THREAD

**Issue by DiptoChakrabarty** [kubernetes/release#2574]
#### What would you like to be added:
On running the krel tool when no github token env var is set the error message returned is this 
`validating command line options: Cannot generate release notes if GitHub token is not set`

comparing to the release-notes tool the error message for the same case is this, which gives a better idea of the error
`neither environment variable `GITHUB_TOKEN` nor `replay` option is set`

It would be good if the krel error returned would be something similar to the release notes where we specify that the Github token is the required environment variable
`validating command line options: Cannot generate release notes if GitHub token environment variable is not set`

#### Why is this needed:
Error message sounds better compared to previous error message  as it can help debug faster and identify the issue

/good-first-issue

**Comment by saschagrunert** [comment]
@DiptoChakrabarty this makes sense, are you going to work on that and propose a PR? :)

**Comment by DiptoChakrabarty** [comment]
@saschagrunert Ill keep it open for new contributors , if someone doesnt pick it up in a prolonged period Ill take it up :)

**Comment by RajGM** [comment]
Hi @Nawaz027 
Are you still working on this issue?

**Comment by RajGM** [comment]
Hi @DiptoChakrabarty 
Can somebody else pick this up?

**Comment by DiptoChakrabarty** [comment]
Sure @RajGM if @Nawaz027 is not working on it assign yourself
