### ISSUE TITLE
kubeadm postinst should not fail when systemd is missing

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/release#259]
There should be a condition [around configuration](https://github.com/kubernetes/release/blob/bbbf4fb1721362d31c06ffccc95775ff7a2c6acc/debian/xenial/kubeadm/debian/postinst#L25-L26), there are cases where you'd want to install the package and configure it manually afterwards, there no good way of skipping this configuration.

**Comment by errordeveloper** [comment]
I'd make a PR now, but not sure what is the best way of check for that in this particular context. Any suggestions are welcome.

**Comment by kargakis** [comment]
@errordeveloper please reopen in the kubeadm repo

/close

**Comment by kargakis** [comment]
Sorry, this may more make sense for this repo

/reopen

**Comment by kvaps** [comment]
Hey, why are you don't want to accept https://github.com/kubernetes/release/pull/388 patch?
Kubeadm still can't be installed in chroot because of that. 
The solution is quite easy and similar one is already used in kubelet postinstall script.

**Comment by kvaps** [comment]
merged: https://github.com/kubernetes/release/pull/388
/close
