### ISSUE TITLE
https://packages.cloud.google.com/apt/pool is not browsable

### ISSUE THREAD

**Issue by 12101111** [kubernetes/release#2598]
**This is a Bug Report**

**Problem:**

`https://packages.cloud.google.com/apt/pool` is not browsable.

`https://packages.cloud.google.com/apt/pool` only contains

```html
<html>
 <head>
  <title>Index of /apt/pool/</title>
 </head>
 <body>
  <h1>Index of /apt/pool/</h1>
  <table>
</table>
<i></i>
</body></html>
```

This makes people think that the directory has no files.

**Proposed Solution:**

List those deb files in 
`https://packages.cloud.google.com/apt/pool`

**Comment by saschagrunert** [comment]
Someone from @kubernetes/release-engineering may pick this up.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/release/issues/913, the project does not control this infrastructure and should be moving to community managed infrastructure in the future.

you can browse at the link @neolit123 provided in the meantime.

**Comment by sftim** [comment]
Is this actually important-soon?

**Comment by BenTheElder** [comment]
@xmudrii I think we should close this. There is no future where we make this browsable. It is not something the project has a say in.

If we want a new package host to be browsable, we should track that in a properly documented issue or requirement.

**Comment by saschagrunert** [comment]
I agree, let's close-out this one.
