### ISSUE TITLE
Stars in multiline release note

### ISSUE THREAD

**Issue by erictune** [kubernetes/release#26]
https://github.com/kubernetes/kubernetes/pull/28132
has a multiline release note, which renders as this in the CHANGELOG.md:

---
* If you use one of the kube-dns replication controller manifest in `cluster/saltbase/salt/kube-dns`, i.e. `cluster/saltbase/salt/kube-dns/{skydns-rc.yaml.base,skydns-rc.yaml.in}`, either substitute one of `__PILLAR__FEDERATIONS__DOMAIN__MAP__` or `{{ pillar['federations_domain_map'] }}` with the corresponding federation name to domain name value or remove them if you do not support cluster federation at this time. If you plan to substitute the parameter with its value, here is an example for `{{ pillar['federations_domain_map'] }` ([#28132](https://github.com/kubernetes/kubernetes/pull/28132), [@madhusudancs](https://github.com/madhusudancs))
    * pillar['federations_domain_map'] = "- --federations=myfederation=federation.test"
    * where `myfederation` is the name of the federation and `federation.test` is the domain name registered for the federation.
---

I want it to render like this:

---

* If you use one of the kube-dns replication controller manifest in `cluster/saltbase/salt/kube-dns`, i.e. `cluster/saltbase/salt/kube-dns/{skydns-rc.yaml.base,skydns-rc.yaml.in}`, either substitute one of `__PILLAR__FEDERATIONS__DOMAIN__MAP__` or `{{ pillar['federations_domain_map'] }}` with the corresponding federation name to domain name value or remove them if you do not support cluster federation at this time. If you plan to substitute the parameter with its value, here is an example for `{{ pillar['federations_domain_map'] }` ([#28132](https://github.com/kubernetes/kubernetes/pull/28132), [@madhusudancs](https://github.com/madhusudancs))
     pillar['federations_domain_map'] = "- --federations=myfederation=federation.test"
    where `myfederation` is the name of the federation and `federation.test` is the domain name registered for the federation.

---

I think the carriage returns need to indent but not have leading stars.

**Comment by david-mcmahon** [comment]
Yes I wrestled with this trying to normalize a very varied stream of notes entered by folks. 
The rule I settled on is that newlines get stars because more often than not that worked out for formatting.  

If a continuous line is desired, edit the PR to make the change and we'll regenerate.
