### ISSUE TITLE
Implement file signing into krel

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/release#2600]
Once https://github.com/kubernetes-sigs/release-sdk/issues/30 has been resolved, we can start working on integrating the file signing into `krel stage/release`.

We have to sign the:
- [ ] binary artifacts and the source code tarball
- [ ] Software Bill of Materials (SBOM)

The signatures should be generated during `krel stage`, while we copy them over to the release bucket on `krel release`.

Part of https://github.com/kubernetes/enhancements/issues/3031

**Comment by matglas** [comment]
First action point I'm thinking of is which files do we want to sign? This will allow us to define each place as an implementation task maybe.

**Comment by saschagrunert** [comment]
> First action point I'm thinking of is which files do we want to sign? This will allow us to define each place as an implementation task maybe.

Sounds good, [the KEP states](https://github.com/kubernetes/enhancements/tree/master/keps/sig-release/3031-signing-release-artifacts#beta-graduation):

> Graduation the KEP to beta means that we will now sign all artifacts which got created during the release process. This includes binary artifacts, source code tarballs, documentation and the SBOM.
>
> This explicitly exudes the provenance data, which will be signed into a different location once we graduate the feature to GA.

So I'll create subtasks for binary artifacts and the source code tarball as well as the SBOM.

**Comment by matglas** [comment]
@saschagrunert I think you miss the documentation that is also stated in that KEP quote. Is that a tar with docs?

**Comment by saschagrunert** [comment]
> @saschagrunert I think you miss the documentation that is also stated in that KEP quote. Is that a tar with docs?

Yeah this issue was more meant to hold the implementation parts into krel. The docs, for example which files have been signed and how to verify them, has to land in https://github.com/kubernetes/website

**Comment by saschagrunert** [comment]
@matglas do you still consider to work on this? Kubernetes v1.25.0 is approaching and I'd like to deliver something at this point in time.

**Comment by matglas** [comment]
I am just back from holiday and I think I won't be able to deliver anything quickly. But I'd review for sure otherwise.

**Comment by saschagrunert** [comment]
@kubernetes/release-managers do we have anyone who wants to work on this? :upside_down_face:

**Comment by saschagrunert** [comment]
Superseded by https://github.com/kubernetes/release/issues/2618
