### ISSUE TITLE
Update official yum repository

### ISSUE THREAD

**Issue by Starefossen** [kubernetes/release#263]
The official yum repository for Kubernetes is still at v1.5.1.
Also, there it would be nice if older versions was also available and not just the newest one.

**Comment by idvoretskyi** [comment]
@Starefossen "/you/yum/" in the title :)

**Comment by Starefossen** [comment]
Sorry, fixed. Thanks for noticing 👍🏼😄

**Comment by jimmyjones2** [comment]
+1 It's also missing the latest releases of older branches - eg 1.4.12 was released less than 2 months ago, but there are no packages in the repo
