### ISSUE TITLE
Enhance Weekly CI/CD Report with Human Content

### ISSUE THREAD

**Issue by puerco** [kubernetes/release#2651]
#### What would you like to be added:

(Trying to capture @jberkus thoughts from the retro for this issue, Josh feel free to correct this to your liking)

Add the capability to add human content to the weekly report

#### Why is this needed:

The weekly CI/CD report is great as an automated reflection of the state of the code, but enhancing it with human content would make it much more valuable. Adding things like these could improve the value of the weekly email:

* calls for action on any stuck failures
* kudos to people fixing failing tests.

/priority important-longterm

**Comment by jberkus** [comment]
That's correct.  IMHO, the main reason to send the report to k-dev in the first place is to get more eyes on things that are broken.  And that doesn't work very well if people have to click through several times to find out where help is needed.
