### ISSUE TITLE
Community support for building releases (anago)

### ISSUE THREAD

**Issue by jbeda** [kubernetes/release#268]
It should be possible and documented for privileged developers to create "unofficial" releases that mirror the official release process.  This should include container images, debs/rpms and release download locations.

Not only will this let others contribute to these tools, but it will allow those working on install tools (like kubeadm) to test the entire flow before we integrate everything at release time.

Anago also just doesn't work if you aren't a Googler.  I'm going to be looking to address some of those issues also.

**Comment by jbeda** [comment]
I'll update this comment as I find issues:

Issues:
 * [ ] _annoying_ `--basedir` defaults to `/usr/local/google/$USER`.  This is a goobuntu-ism that shouldn't be in this script.

**Comment by mwielgus** [comment]
This will be also needed for the process described in https://github.com/kubernetes/community/pull/126.

**Comment by cblecker** [comment]
/remove-lifecycle stale
This is still relevant.

**Comment by cblecker** [comment]
/remove-lifecycle stale
/lifecycle frozen

This is still needed.

**Comment by tpepper** [comment]
/cc @calebamiles 
/cc @BenTheElder 

Can we get a short list of remaining to-do's here?  This is almost done right?  We've got non-Google branch managers now for 1.11.x and 1.12, so any final issues should get worked through.

But also we need a next level issue for documenting the back end machinery and plumbing so it's maintainable by non-Googlers.  If gcb makes for a push button that's usable by community release team folks, we still should aspire to the machinery also being more community supported and that will start with documenting what metadata feeds what machinery to generate what artifacts, and probably also should add test cases on artifact creation/publication so SIG-Cluster-Lifecycle's not pointing out that some part of the artifacts didn't build/publish correctly.

**Comment by BenTheElder** [comment]
I don't have any major updates or a list of to-dos other than I know the owners are working on fixing some of this, and that push-button GCB should work for the release managers, Google or otherwise for Anago at least AFAIK. My understanding is that it had already, but we regressed a bit WRT the docker images and that is being fixed.

I'd tend to agree on all of those points. I'll hopefully defer to Caleb for the moment on a more specific list.

**Comment by justaugustus** [comment]
We're moving the needle here and I'll have a write-up for this in 1.18.

/unassign @timothysc @david-mcmahon 
/milestone v1.18

**Comment by justaugustus** [comment]
I'm closing this out, as I think we've served much of the intent of the original request.

- Container images are now build on community infrastructure: https://github.com/kubernetes/k8s.io/tree/master/k8s.gcr.io
- `anago` has been [removed](https://github.com/kubernetes/release/pull/1765) and reimagined in Golang as [`krel`](https://github.com/kubernetes/release/tree/master/docs/krel)

For stories on artifact management (including debs/rpms), see this epic: https://github.com/kubernetes/sig-release/issues/1372

And this project board: https://github.com/orgs/kubernetes/projects/48

deb/rpm tooling in progress here: https://github.com/kubernetes/release/issues/1027

/close

**Comment by BenTheElder** [comment]
> anago has been removed and reimagined in Golang as krel

And more importantly both have been executed by non-googlers, we have had releases without googlers for some time now *


\* Unlike the rest of the release, for debian / RPMs packages this is not the case. The community continues to rely on google's package host. https://github.com/kubernetes/release/issues/1027 is linked there, but doesn't seem to cover that. Currently a community member could build a deb/rpm (sources are public, no dependency on infrastructure in particular) but in practice they are built + signed by my team and uploaded to Google's package host still. I believe this should be tracked somewhere, as it ultimately still requires Googlers to fully ship a release.

**Comment by justaugustus** [comment]
>  I believe this should be tracked somewhere, as it ultimately still requires Googlers to fully ship a release.

Tracked on the Artifact Management project board as https://github.com/kubernetes/release/issues/281.

**Comment by BenTheElder** [comment]
Thanks Stephen! ❤️ That's exactly what I was looking for 👍 

Also want to add: We don't mind doing this in the slightest, my team is happy to help! but I believe for the future of the project it is best to make sure releases in particular are a common effort with ~neutral access and publicly auditable infra (config in git like the rest of our wg-k8s-infra / SIG testing / release efforts). 

(also for context: I'm certain @justaugustus beleives this too :-), more of a comment for anyone reading along)

**Comment by justaugustus** [comment]
@BenTheElder -- Right you are!

My biggest focus for v1.21 is refining the plan around artifact management on all axes (roughly in order of what's already been started):
- Cleaning up image promotion tooling/processes
- Continuing the file promotion work in earnest
- deb/rpm generation, signing, hosting

One of the first things I'm planning is making it faster/easier for the @kubernetes/build-admins to sign and publish.
I already have a branch in progress and I'll tag you on the PR when it's closer.
