### ISSUE TITLE
Allow customizable distroless image and builder image for go-runner

### ISSUE THREAD

**Issue by jeremyrickard** [kubernetes/release#2702]
#### What would you like to be added:

The ability to override the builder image used in the go-runner Dockerfile, along with fully specifying the DISTROLESS_IMAGE. 

#### Why is this needed:

The current Dockerfile and Makefile support specifying a specific distroless image to use, but the registry is not part of that customizability (i.e. it always points to gcr.io).  We'd like to be able to fully specify where the distroless image comes from so that we can build go-runner images for our use, that are based on those distroless images we are producing.  Additionally, we'd like to be able to fully specify the builder image so utilize our custom Go builder image. 

I have a PR that I believe does this (and updates the cloudbuild.yaml and variants.yaml files to fully specify the registry+repo for the distroless images.

**Comment by saschagrunert** [comment]
Sounds like a reasonable enhancement to me. Do you plan to work on this topic as well @jeremyrickard ?

**Comment by jeremyrickard** [comment]
@saschagrunert sure thing! I’ll propose a PR soon.
