### ISSUE TITLE
krel keeps throwing an error when `--draft-pr` command is run!

### ISSUE THREAD

**Issue by sayantani11** [kubernetes/release#2713]
#### What happened:
I ran`krel release-notes --create-draft-pr --fork=sayantani11 --fix --tag=v1.26.0-alpha.1 --list-v2` the command started as it should and I edited a few of the PRs as well, but after that it threw an error and I have tried everything but still not able to overcome the problem. 
Following is the error:
```sh
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
sigs.k8s.io/release-utils/util.WrapText({0x41c00d0?, 0xc0001b0008?}, 0x50)
        sigs.k8s.io/release-utils@v0.7.3/util/common.go:494 +0x154
k8s.io/release/cmd/krel/cmd.fixReleaseNotes({0xc00682b700, 0x36}, 0xc0050b9980)
        k8s.io/release/cmd/krel/cmd/release_notes.go:1152 +0x1307
k8s.io/release/cmd/krel/cmd.createDraftPR({0xc00056e530, 0x8}, {0x7fff5e8d825a, 0xf})
        k8s.io/release/cmd/krel/cmd/release_notes.go:380 +0x874
k8s.io/release/cmd/krel/cmd.runReleaseNotes()
        k8s.io/release/cmd/krel/cmd/release_notes.go:288 +0x574
k8s.io/release/cmd/krel/cmd.glob..func15(0x426bc80?, {0x297a536?, 0x5?, 0x5?})
        k8s.io/release/cmd/krel/cmd/release_notes.go:118 +0x17
github.com/spf13/cobra.(*Command).execute(0x426bc80, {0xc000576910, 0x5, 0x5})
        github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0x426c180)
        github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.5.0/command.go:918
k8s.io/release/cmd/krel/cmd.Execute()
        k8s.io/release/cmd/krel/cmd/root.go:60 +0x25
main.main()
        k8s.io/release/cmd/krel/main.go:24 +0x17
```

#### What you expected to happen:
After the `--draft-pr` is run, we should be able to edit the PRs and then it will create an auto-generated PR.

#### Environment:
WSL version 2 using Ubuntu 18.04.5 

```sh
sayantani@DESKTOP-5QRA9IS:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:           7782          89        7651           0          41        7543
Swap:         16384           0       16384
```
- Cloud provider or hardware configuration:

- OS (e.g: `cat /etc/os-release`):
```sh
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

- Kernel (e.g. `uname -a`):
```Linux DESKTOP-5QRA9IS 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux```

- Others:
GO 1.18.5

🤔 So I did make a PR but this is how it happened and I don't think that's a correct way of doing it https://github.com/kubernetes/sig-release/pull/2059#issuecomment-1284604025

**Comment by sayantani11** [comment]
cc @ramrodo

**Comment by jorgearteiro** [comment]
@sayantani11 Please, try to install latest WSL2 version with latest Linux Kernel from here https://devblogs.microsoft.com/commandline/a-preview-of-wsl-in-the-microsoft-store-is-now-available/. 
You can also enable systemd on WSL2 if required. https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/
Let me know if you need help.

**Comment by sayantani11** [comment]
> @sayantani11 Please, try to install latest WSL2 version with latest Linux Kernel from here https://devblogs.microsoft.com/commandline/a-preview-of-wsl-in-the-microsoft-store-is-now-available/. You can also enable systemd on WSL2 if required. https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/ Let me know if you need help.

Followed the above steps and also updated to `Go 1.19.2`. I am on WSL2.
```sh
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
sigs.k8s.io/release-utils/util.WrapText({0x4234250?, 0xc000014018?}, 0x50)
        sigs.k8s.io/release-utils@v0.7.3/util/common.go:494 +0x154
k8s.io/release/cmd/krel/cmd.fixReleaseNotes({0xc00fc72340, 0x36}, 0xc004fbade0)
        k8s.io/release/cmd/krel/cmd/release_notes.go:1152 +0x1307
k8s.io/release/cmd/krel/cmd.createDraftPR({0xc000950070, 0x8}, {0x7ffd8f1c31b1, 0xf})
        k8s.io/release/cmd/krel/cmd/release_notes.go:380 +0x874
k8s.io/release/cmd/krel/cmd.runReleaseNotes()
        k8s.io/release/cmd/krel/cmd/release_notes.go:288 +0x566
k8s.io/release/cmd/krel/cmd.glob..func15(0x42dfde0?, {0x29b08d7?, 0x5?, 0x5?})
        k8s.io/release/cmd/krel/cmd/release_notes.go:118 +0x17
github.com/spf13/cobra.(*Command).execute(0x42dfde0, {0xc00074d900, 0x5, 0x5})
        github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0x42e02e0)
        github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.5.0/command.go:918
k8s.io/release/cmd/krel/cmd.Execute()
        k8s.io/release/cmd/krel/cmd/root.go:60 +0x25
main.main()
        k8s.io/release/cmd/krel/main.go:24 +0x17
```
This error still pops up!

**Comment by ramrodo** [comment]
According to [this comment](https://github.com/kubernetes/sig-release/pull/2059#issuecomment-1284604025), the error was more related to how to stop/pause the process of editing release notes before creating the PR. Since the PR was successfully created and we have not seen this error again, I'll proceed to close this PR. Open it later if it is necessary.

/close
