### ISSUE TITLE
Mechanism for interim signing of packages

### ISSUE THREAD

**Issue by sftim** [kubernetes/release#2714]
#### What would you like to be added:
Provide and document a way for a package builder to provide interim signing so that further signing can be more trustworthy.

#### Why is this needed:
https://github.com/kubernetes/release/issues/913#issuecomment-1279378444 suggests that Google's folk can _sign_ packages, which we might want or need.
However, the provenance of what Google's team sign is going to be important. Similarly, if we use an in-project key for ultimate signing, we might well only want to use that in-project key to sign packages that come from our (trusted) build system.

In this issue I'm suggesting that we might want to develop a way to run a package build (via Rapture or otherwise) that produces signed packages, signed by a private key that is interim and perhaps quite short lived. A separate mechanism can take packages signed by the interim key and produce packages signed for trusted public consumption.

**Comment by sftim** [comment]
I am not sure whether we should triage this issue as accepted. However, it feels worth putting the idea forward.

**Comment by BenTheElder** [comment]
> https://github.com/kubernetes/release/issues/913#issuecomment-1279378444 suggests that Google's folk can sign packages, which we might want or need.

I believe we can sign RPM packages only. Normally in APT and RPM the repository is signed, I don't think we want to cross-sign between these within a repo and make users need two keys.

Users still using rapture should use the rapture key.
Users that migrate should use whatever key we sign the new repo with.

That comment is referring to the potential to sign and publish to rapture packages that are built somewhere other than "MushuEE's workstation".
