### ISSUE TITLE
Anago tries to push images to kubernetes-release-test

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/release#272]
Anago tries to push images to kubernetes-release-test. It fails due to missing permissions.
```
/usr/bin/gcloud docker -- push gcr.io/kubernetes-release-test/kube-controller-manager-amd64:v1.5.4
denied: Unable to access the repository; please check that you have permission to access it.
```
If this is a required step then it should stop the whole process and ideally the permissions (whose?) should be validated at the very beginning of the process. If not then it should be removed.

cc: @ixdy @david-mcmahon

**Comment by ixdy** [comment]
#164
