### ISSUE TITLE
krel stage broken on SBOM generation

### ISSUE THREAD

**Issue by jeremyrickard** [kubernetes/release#2729]
#### What happened:

While running `krel stage`, we encountered an error with SBOM generation which keeps the build from finishing: 

```
FATA[2022-10-25T11:38:48Z] generating sbom: generating the kubernetes source SBOM: generating Kubernetes source code SBOM: creating SPDX document: generating package from directory: generating SPDX package from directory: scanning file for license: classifying file to determine license: ID does not correspond to a valid license: Copyright (and 436 more errors) 
```

#### What you expected to happen:

`krel stage` ran successfully and an SBOM was correctly generated

#### How to reproduce it (as minimally and precisely as possible):

```
`krel stage --type alpha --branch master --build-version v1.26.0-alpha.2.382+256ade5aa49aa9
```

#### Anything else we need to know?:

This issue is probably in `bom`?  There hadn't been a release in some time and this is with a new version. We should investigate this in `bom` as well.

#### Environment:

N/A

**Comment by jeremyrickard** [comment]
I'm able to replicate this locally with the latest `bom` on a fresh Kubernetes clone results in:

```
INFO Scanning 23203 files and adding them to the SPDX package
WARN Label Copyright is not an identifier of a known license
WARN Label Copyright is not an identifier of a known license
WARN Label Copyright is not an identifier of a known license
WARN Label Copyright is not an identifier of a known license
WARN Label Copyright is not an identifier of a known license
WARN Label Copyright is not an identifier of a known license
```

That warning repeats for quite a while, then:

```
FATA generating doc: creating SPDX document: generating package from directory: generating SPDX package from directory: scanning file for license: classifying file to determine license: ID does not correspond to a valid license: Copyright (and 438 more errors)
```

I'll open an issue over there and link here.

**Comment by puerco** [comment]
Filed https://github.com/kubernetes-sigs/bom/pull/189 to fix this issue in the SBOM code.

**Comment by cpanato** [comment]
fixed
https://console.cloud.google.com/cloud-build/builds;region=global/b4984330-6ea2-4c99-843d-4e821e5ad1c1?project=kubernetes-release-test

/close
