### ISSUE TITLE
Delete draft release question is misleading

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/release#273]
It is not obvious how to answer this the below question.
If I say "Y" will the tool recreate the release as "final" or not?

```
────────────────────────────────────────────────────────────────────────────────
UPDATE GITHUB RELEASES PAGE
────────────────────────────────────────────────────────────────────────────────

Posting the v1.5.4 release on github...
Uploading binary to github: OK

ATTENTION: A draft release of v1.5.4 was created at
https://github.com/kubernetes/kubernetes/releases.

Delete draft release (id #5669951) now? (Y/n):
```

cc: @ixdy @david-mcmahon

**Comment by ixdy** [comment]
was this a mock or nomock run?

**Comment by mwielgus** [comment]
Regular run https://github.com/kubernetes/test-infra/issues/1795

**Comment by mwielgus** [comment]
The final release was NOT created after answering Y. The message is totally broken.

**Comment by mwielgus** [comment]
Ok. My fault - i missed that it was a mock run.

**Comment by ixdy** [comment]
closing this in favor of #274.
