### ISSUE TITLE
Integrate `hack/rapture/build-packages.sh` into `krel`

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/release#2737]
We can add a new deb/rpm package build/publish step into `krel stage/release` by creating a wrapper around something like:

```
./hack/rapture/build-packages.sh 1.26.0
```

The script runs the package builds within containers so we should already have the requirements for running in GCB.

The build script assumes that the binaries already exist on `dl.k8s.io`, which technically means that it has to run in `krel release`. Ideally it would be better to create the packages in `krel stage` and the publish them in `krel release`, but we could probably work around that.

I expect that we create a new subpackage as part of this project to be later able to swap the implementation with something else.

**Comment by ameukam** [comment]
cc @ameukam

**Comment by saschagrunert** [comment]
@jeremyrickard do you need support on that?

**Comment by saschagrunert** [comment]
Discussed with @jeremyrickard that I can take a stab on this one.

**Comment by saschagrunert** [comment]
We still have to update the docs, let's keep it open until that.
