### ISSUE TITLE
go-runner s390x image/binary builds are flaky

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/release#2738]
#### What happened:

The `post-release-push-image-go-runner` job flakes often because s390x image builds are failing.

The most common reason why image builds fail is that the Go toolchain fails to compile the s390x binary. For example, today it took 7 retries before we were able to build the binary for s390x and therefore the image. The underlying reason why the Go build fails differs from run to run. What we observed so far is:

* `compile: invalid GOAMD64: must be v1, v2, v3, v4` (https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-release-push-image-go-runner/1587740507818168320)
* `signal SIGSEGV: segmentation violation` 
  * try 1: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-release-push-image-go-runner/1587743321164353536 
  * try 2: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-release-push-image-go-runner/1587770127514865664
  * try 3: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-release-push-image-go-runner/1587791949761351680
* `go: error obtaining buildID for go tool compile: exit status 2` (https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-release-push-image-go-runner/1587755816650280960)
* `note: module requires Go 1.19` (https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-release-push-image-go-runner/1587795684591931392)

#### What you expected to happen:

go-runner s390x builds are not failing.

#### How to reproduce it (as minimally and precisely as possible):

TBD

**Comment by dims** [comment]
cc @huoqifeng @srajmane @guirish @mkumatag @cwsolee 

![FlawedRichBrontosaurus-max-1mb](https://user-images.githubusercontent.com/23304/199529093-a24cfa3c-f9d3-4aac-91b0-6f7d292f52b1.gif)

**Comment by BenTheElder** [comment]
I'm pretty sure all of these trace back to emulation bugs, which is also what we've previously seen with these problems.
ARM and AMD64 have no issues, but the others have emulation bugs that surface like https://github.com/golang/go/issues/53797 https://github.com/golang/go/issues/50584

**Comment by guirish** [comment]
Hi @xmudrii , are we good to close this issue as the issue has been fixed with latest QEMU version 

Thanks @dims for the #2739 PR.

**Comment by xmudrii** [comment]
Sounds good, let's close the issue for now and we can reopen it if the problem appears again. Thank y'all for taking care of this!
/close
