### ISSUE TITLE
Remove darwin/386 from cross 

### ISSUE THREAD

**Issue by jeremyrickard** [kubernetes/release#2759]
We currently define the `KUBE_CROSSPLATFORMS` env var in the cross Dockerfiles as:

```
ENV KUBE_CROSSPLATFORMS \
  linux/386 \
  linux/arm linux/arm64 \
  linux/ppc64le \
  linux/s390x \
  darwin/amd64 darwin/386 \
  windows/amd64 windows/386
```

Per the [release notes](https://go.dev/doc/go1.15), Go 1.15 dropped support for 32 bit darwin binaries: 

```
As [announced](https://go.dev/doc/go1.14#darwin) in the Go 1.14 release notes, Go 1.15 drops support for 32-bit binaries on macOS, iOS, iPadOS, watchOS, and tvOS (the darwin/386 and darwin/arm ports). Go continues to support the 64-bit darwin/amd64 and darwin/arm64 ports.
```

The oldest supported version of Kubernetes is now Kubernetes 1.23, which currently uses  `1.17.13`. Since we have moved past Go 1.14, we should remove the `darwin/386` platform.

**Comment by cpanato** [comment]
Should drop the windows/386 as well?
