### ISSUE TITLE
Print github author name and email on build confirmation

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/release#276]
Anago force-push a commit with release changes. It may happen that the github default author is not correct.

I was doing a release on a brand-new, clean, Google-internal virtual machine to avoid any possible pollution and didn't set the username at all. As a result the commit went under mwielgus@mwusa.hot.corp.google.com.

cc: @david-mcmahon @ixdy

**Comment by mwielgus** [comment]
ref: https://github.com/kubernetes/kubernetes/commit/d5df405bb10488e6b39983b7ef89da3cd3998476

**Comment by ixdy** [comment]
oops. yeah, there should definitely be a `git email` check in `check_prerequisites`.
