### ISSUE TITLE
Key expires gLinux Rapture Automatic Signing Key

### ISSUE THREAD

**Issue by michizubi-SRF** [kubernetes/release#2775]
```
pub   rsa2048 2020-12-04 [SC] [expires: 2022-12-04]
      59FE 0256 8272 69DC 8157  8F92 8B57 C5C2 836F 4BEB
uid           [ unknown] gLinux Rapture Automatic Signing Key (//depot/google3/production/borg/cloud-rapture/keys/cloud-rapture-pubkeys/cloud-rapture-signing-key-2020-12-03-16_08_05.pub) <glinux-team@google.com>
```

#### What happened:
The key used to sign the packages is about to expire on 12-04-2022.

#### What you expected to happen:
Key should be updated before it actually expires.

#### Anything else we need to know?:
Related issue: [kubernetes/test-infra#7505](https://github.com/kubernetes/test-infra/issues/7505)

Thanks!

**Comment by ameukam** [comment]
cc @kubernetes/release-engineering

**Comment by xmudrii** [comment]
cc @kubernetes/build-admins Can you help us with this one?

**Comment by dims** [comment]
slack thread : https://kubernetes.slack.com/archives/CJH2GBF7Y/p1669736104022759

**Comment by dims** [comment]
Here's the latest

```
[davanum@c889f3bd53ed 13:12] ~/Downloads ⟩ curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg > apt-key.gpg
[davanum@c889f3bd53ed 13:12] ~/Downloads ⟩ gpg apt-key.gpg
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   rsa2048 2021-03-01 [SC] [expires: 2023-03-02]
      7F92E05B31093BEF5A3C2D38FEEA9169307EA071
uid           Rapture Automatic Signing Key (cloud-rapture-signing-key-2021-03-01-08_01_09.pub)
sub   rsa2048 2021-03-01 [E]
pub   rsa2048 2020-12-04 [SC] [expires: 2022-12-04]
      59FE0256827269DC81578F928B57C5C2836F4BEB
uid           gLinux Rapture Automatic Signing Key (//depot/google3/production/borg/cloud-rapture/keys/cloud-rapture-pubkeys/cloud-rapture-signing-key-2020-12-03-16_08_05.pub) <glinux-team@google.com>
sub   rsa2048 2020-12-04 [E]
```

**Comment by michizubi-SRF** [comment]
Any updates on this? The key has now expired.

**Comment by xmudrii** [comment]
From what I see, the key is supposed to expire on 2023-03-02, so it should be renewed:

```
pub   rsa2048 2022-05-21 [SC]
      A362B822F6DEDC652817EA46B53DC80D13EDEF05
uid                      Rapture Automatic Signing Key (cloud-rapture-signing-key-2022-03-07-08_01_01.pub)
sub   rsa2048 2022-05-21 [E]

pub   rsa2048 2021-03-01 [SC] [expires: 2023-03-02]
      7F92E05B31093BEF5A3C2D38FEEA9169307EA071
uid                      Rapture Automatic Signing Key (cloud-rapture-signing-key-2021-03-01-08_01_09.pub)
sub   rsa2048 2021-03-01 [E]
```

Please try the steps shared in https://github.com/kubernetes/test-infra/issues/7505#issuecomment-378045292 and let us know if that fixes the issue for you.

**Comment by michizubi-SRF** [comment]
So apparently this key

`pub   rsa2048 2020-12-04 [SC] [expires: 2022-12-04]
      59FE0256827269DC81578F928B57C5C2836F4BEB
uid           gLinux Rapture Automatic Signing Key (//depot/google3/production/borg/cloud-rapture/keys/cloud-rapture-pubkeys/cloud-rapture-signing-key-2020-12-03-16_08_05.pub) <glinux-team@google.com>
sub   rsa2048 2020-12-04 [E]`

is obsolete. When removing this, apt doesn't complain and instead uses this key

`pub   rsa2048 2021-03-01 [SC] [expires: 2023-03-02]
      7F92E05B31093BEF5A3C2D38FEEA9169307EA071
uid                      Rapture Automatic Signing Key (cloud-rapture-signing-key-2021-03-01-08_01_09.pub)
sub   rsa2048 2021-03-01 [E]`
