### ISSUE TITLE
missing golang image kube-cross:v1.26.0-go1.19.4-bullseye.0 

### ISSUE THREAD

**Issue by medyagh** [kubernetes/release#2806]
#### What happened:
in minikube project we have an automation job that whenever, the golang in 
[version](https://github.com/kubernetes/kubernetes/blob/master/build/build-image/cross/VERSION) is updated we update our golang image to be "us.gcr.io/k8s-artifacts-prod/build-image/kube-cross:v1.26.0-go{{.GO_VERSION}}-bullseye.0"

but this time the automation failed since there is no us.gcr.io/k8s-artifacts-prod/build-image/kube-cross:v1.26.0-go1.19.4-bullseye.0 does not exists

#### What you expected to happen:
expected the image us.gcr.io/k8s-artifacts-prod/build-image/kube-cross:v1.26.0-go1.19.4-bullseye.0 to exist
but only us.gcr.io/k8s-artifacts-prod/build-image/kube-cross:v1.26.0-go1.19.4-bullseye.1 exists

#### How to reproduce it (as minimally and precisely as possible):
As seen in our github action job https://github.com/kubernetes/minikube/actions/runs/3641996237/jobs/6148589636
#### Environment:

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by cpanato** [comment]
hello @medyagh in this [PR](https://github.com/kubernetes/release/pull/2795) we build the `kube-cross:v1.26.0-go1.19.4-bullseye` and indeed we did not generate the `.0` but `.1` that was a mistake from our side.

you can update your config you use `registry.k8s.io/build-image/kube-cross:v1.26.0-go1.19.4-bullseye.1`

thanks will close this one
cc @xmudrii @saschagrunert @kubernetes/release-managers 
/close
