### ISSUE TITLE
Pause Automatic FF when the release stage runs

### ISSUE THREAD

**Issue by puerco** [kubernetes/release#2807]
#### What would you like to be added:

We should have a way to pause the auto FF process. Or even better, make it aware of a release stage running on the branches it forwards.

#### Why is this needed:

When running the release stage of a new minor release, the FF process can pick up new commits and forward the branch, leaving the clone in GCB behind. This has dangerous implications as it fails late in the release process, while it is pushing the git artifacts.

We think this actually happened during the 1.26.0 cut and it broke the release as krel could not push the branch cleanly:

```
push git objects: pushing branches to the remote repository: pushing release-1.26 branch: 
   merge remote if required: merging remote branch origin/release-1.26 to local repo:
   run git merge: command /usr/bin/git merge -X ours origin/release-1.26 did not succeed:  
```
(unfortunately, we did not get the rest of the error)

**Comment by leonardpahlke** [comment]
Is this a bug / flake?

**Comment by saschagrunert** [comment]
This is unfortunate, and I have not considered that the fast forward can cause conflicts when cutting the minor together with the patches in parallel. So it's not a flake, but an uncovered corner case.

Two example for breaking fast forwards are:
- https://github.com/kubernetes/kubernetes/compare/6bb8d266fffdc71bd3bddbf9d975507e77b5a89d...2b26e0bbe825beb46c90320cca33dfeed2c4a9db
- https://github.com/kubernetes/kubernetes/compare/2b26e0bbe825beb46c90320cca33dfeed2c4a9db...9675a7cdefa1eb26f84481be0e335b8930a3df6c

Means we could check the author of the commits, and if we find the `Kubernetes Release Robot <k8s-release-robot@users.noreply.github.com>`, then we do not do the fast forward.

**Comment by saschagrunert** [comment]
The release cut issue may be a good indicator, though.
