### ISSUE TITLE
Scorecards supply-chain security CI test is broken

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/release#2820]
The test on `master` is broken since quite some time: https://github.com/kubernetes/release/actions/runs/3685473157/jobs/6236483402

Fixing it seems to be a great opportunity for @kubernetes/release-managers or anyone else interested. :upside_down_face:

**Comment by shubhbapna** [comment]
Hi, first time contributor here! Took a look and I suspect that the reason behind this might simply be the expired token that scorecard analysis uses - https://github.com/kubernetes/release/blob/master/.github/workflows/scorecards-analysis.yml#L41

I think simply getting a new token and updating the corresponding secret should fix this

**Comment by varunagarwal315** [comment]
@saschagrunert Made and linked a PR that should fix this.
