### ISSUE TITLE
k8s.io/release/pkg/release TestPublish is flaking

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/release#2833]
#### What happened:

Flaked twice on this PR

https://prow.k8s.io/pr-history/?org=kubernetes&repo=release&pr=2831

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/release/2831/pull-release-test/1605332879217266688
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/release/2831/pull-release-test/1605325116026130432
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/release/2831/pull-release-test/1605371283082579968

(Note: there is one other run where it passed, but none of the commits should be affecting this test)

#### What you expected to happen:

No unit test flakes

#### How to reproduce it (as minimally and precisely as possible):

run pkg/release tests

#### Environment:

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by BenTheElder** [comment]
/remove-lifecycle stale
still flaky
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/release/2960/pull-release-test/1639627160224272384

**Comment by xmudrii** [comment]
Looks like the test has been fixed, last runs are consistently green. @BenTheElder okay to close this issue and reopen if this appears again?
