### ISSUE TITLE
go-runner in 1.24.8 kube-proxy Docker Image is built with 1.17.3 GO

### ISSUE THREAD

**Issue by jhawkins1** [kubernetes/release#2841]
### What happened?

It appears although 1.24.x moved to 1.18 GO that the "go-runner"  in kube-proxy Docker Image is built using 1.17.3 GO.   This is being detected by Vulnerability Scanners, therefore, all 1.17.3 CVEs are being reported for the kube-proxy Image due to "go-runner".  

### What did you expect to happen?

"go-runner" should be built with the same version of GO that the Kubernetes Release is using.  For 1.24.8 that is GO 1.18.x.

### How can we reproduce it (as minimally and precisely as possible)?

Vulnerability Scan of the Container Image will show that 1.17.3 is being used to build the "go-runner" in the kube-proxy image.

### Kubernetes version

<details>

1.24.8

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
https://github.com/kubernetes/release/blob/master/images/build/debian-iptables/variants.yaml says `IMAGE_VERSION: 'bullseye-v1.5.1'` is for `Kubernetes 1.23 and newer`, but 1.23 is still on `bullseye-v1.1.0` and 1.24 is still on `bullseye-v1.3.0`... should those update to 1.5.1+?

**Comment by aojea** [comment]
I think that this is the change https://github.com/kubernetes/release/commit/d36a24a8661a01e2d8a5bb7882540712ca331d40

**Comment by aojea** [comment]
dup of https://github.com/kubernetes/release/issues/2507 ?

**Comment by liggitt** [comment]
https://github.com/kubernetes/release/commit/d36a24a8661a01e2d8a5bb7882540712ca331d40 didn't update the debian-iptables IMAGE_VERSION, and didn't produce a new image, did it? (was 1.5.1 before and is still 1.5.1)

**Comment by liggitt** [comment]
also, the go-runner image is still stale (should be 1.19.4 now)

**Comment by liggitt** [comment]
should 1.23 and 1.24 update from bullseye-v1.1.0 and bullseye-v1.3.0 to bullseye-v1.5.1?

**Comment by aojea** [comment]
> [d36a24a](https://github.com/kubernetes/release/commit/d36a24a8661a01e2d8a5bb7882540712ca331d40) didn't update the debian-iptables IMAGE_VERSION, and didn't produce a new image, did it? (was 1.5.1 before and is still 1.5.1)

I see new images pushed with the same tag
https://console.cloud.google.com/gcr/images/k8s-staging-build-image/global/debian-iptables?project=k8s-staging-build-image

**Comment by aojea** [comment]
> should 1.23 and 1.24 update from bullseye-v1.1.0 and bullseye-v1.3.0 to bullseye-v1.5.1 (or whatever 1.5.x is after we update go-runner 1.19.4)?

I think so

**Comment by liggitt** [comment]
> I see new images pushed with the same tag
https://console.cloud.google.com/gcr/images/k8s-staging-build-image/global/debian-iptables?project=k8s-staging-build-image

really? 😱 I didn't expect mutable tags there

**Comment by BenTheElder** [comment]
FWIW we normally don't consume from staging directly and what we promote to production (registry.k8s.io) is promoted by digest so the tag mutability isn't as problematic as it sounds.

**Comment by liggitt** [comment]
do we know if the 1.5.1 image that got promoted included the go-runner update or not?

**Comment by jhawkins1** [comment]
@liggitt , in January we updated to 1.24.10, and it is still using the old go-runner.  So, it does not look like this has been corrected unless it made it into the 1.24.11 release that just came out  -- I could not really tell from the CHANGELOG comments.

**Comment by liggitt** [comment]
1.23 (EOL):
* https://github.com/kubernetes/kubernetes/blob/release-1.23/build/common.sh#L93
* references debian-iptables v1.1.0
* https://github.com/kubernetes/release/blob/b874bdeb575f5b347cdaebfca5246cd410fa5d49/images/build/debian-iptables/Makefile#L21-L24
* references gorunner built with go1.17.x

1.24:
* https://github.com/kubernetes/kubernetes/blob/release-1.24/build/common.sh#L93
* references debian-iptables v1.3.0
* https://github.com/kubernetes/release/blob/0ced957a8b2f5dc05e982ec507675000a4113031/images/build/debian-iptables/Makefile#L21-L24
* references gorunner built with go1.17.x

1.25:
* https://github.com/kubernetes/kubernetes/blob/release-1.25/build/common.sh#L93
* references distroless-iptables v0.1.0
* https://github.com/kubernetes/release/blob/2c2e73f4e15c85beba135e4513308bffa79abc64/images/build/distroless-iptables/Makefile#L21-L24
* references gorunner built with go1.17.x

1.26:
* https://github.com/kubernetes/kubernetes/blob/release-1.26/build/common.sh#L98
* references distroless-iptables v0.1.2
* https://github.com/kubernetes/release/blob/44d60ecc7542828e2ae286b659d7e2b2d80c8abf/images/build/distroless-iptables/Makefile#L21-L24
* references gorunner built with go1.19.1 (should update to go1.19.6)

**Comment by liggitt** [comment]
cc @cpanato for visibility / gap in dependency tracking / propagating new go versions through image chains

**Comment by cpanato** [comment]
looks like in the past we missed to update distroless-iptables, but now we are tracking that and keeping up-to-date

i will review the active branches and check those things

**Comment by cpanato** [comment]
@liggitt should we build a new distrolles-iptables using go 1.19 and update that in the active patch branches?

today we are building that only with go 1.20
