### ISSUE TITLE
Create issue template for base image updates

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/release#2855]
#### What would you like to be added:

It would be beneficial to have an issue template for base image updates in the same way we have one for [golang updates](https://github.com/kubernetes/release/blob/master/.github/ISSUE_TEMPLATE/dep-golang.md).

**Comment by XDRAGON2002** [comment]
@saschagrunert This sounds like a good issue for a beginner to work on I suppose? Could I take this up?

**Comment by saschagrunert** [comment]
@XDRAGON2002 sure thing, thank you! Feel free to open a PR. :pray:

**Comment by XDRAGON2002** [comment]
@saschagrunert just another query, what all fields would be required to be present in the template? Just the same as the ones in the golang one or different?

**Comment by xmudrii** [comment]
/remove-lifecycle stale
@saschagrunert Is this issue eventually duplicate of #3074?
