### ISSUE TITLE
CI Signal reporter tool update deprecated ProjectNext API to Projectv2

### ISSUE THREAD

**Issue by lauralorenz** [kubernetes/release#2864]
#### What happened: 
CI Signal reporter tool errors when run with an appropriately scoped Github access token:
```
lauralorenz@lauralorenz:release$ GITHUB_TOKEN=$GITHUB_TOKEN go run cmd/ci-reporter/main.go -s -v 1.27
loading data ⠙ Error: getting GitHub report data: No such type ProjectNext, so it can't be a fragment condition
```
#### What you expected to happen:
 CI signal report to be generated

#### How to reproduce it (as minimally and precisely as possible): 

Run the CI signal reporter per its README documentation i.e `GITHUB_TOKEN=$GITHUB_TOKEN go run cmd/ci-reporter/main.go -s -v 1.27` with a personal access github token with org:read permissions.

#### Anything else we need to know?: 
The Github API's ProjectNext API was deprecated in favor of ProjectV2 ([announcement blog post](https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/)) and it seems to me this is the underlying issue. Looking at the [changelog](https://docs.github.com/en/graphql/overview/changelog#schema-changes-for-2023-01-18) it appears the ProjectNext API was officially removed today 😅 which is also the first day I tried to run this tool 😰  as the CI Signal lead 🥵 lol

#### Environment:

- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): Debian 12
- Kernel (e.g. `uname -a`): Debian 5.19.11-1rodete1 (2022-10-31) x86_64 GNU/Linux
- Others: 
  - go version go1.20-20221229-RC00 cl/498461153 +db36eca33c linux/amd64

**Comment by leonardpahlke** [comment]
uff, let me know if you need support!
