### ISSUE TITLE
Improvement in Krel Documentation

### ISSUE THREAD

**Issue by yrs147** [kubernetes/release#2870]
#### What happened:
The steps to install Krel given in the documentation are not sufficient for installation on windows and first-time users may face issues installing it on their local system.

#### What you expected to happen:
Expected that krel will get installed on my local by following the steps in Docs but didn't worked.

#### How to reproduce it (as minimally and precisely as possible):
Can't say much about other OS, but the installation guide is not helpful for windows.

#### Anything else we need to know?:
I propose we add the go command to install krel tool as an alternative, cause it worked fine.

#### Environment:
- OS - Windows

**Comment by palnabarun** [comment]
Can you also paste what went wrong when you tried to install `krel` using the compile script?

**Comment by yrs147** [comment]
> Can you also paste what went wrong when you tried to install `krel` using the compile script?

![image](https://user-images.githubusercontent.com/98258627/214111887-85b6acd3-d065-4d20-aace-d47ac68aba60.png)


This doesn't work and gives "The term 'krel' is not recognized as the name of a cmdlet, function, script file, or operable program.", but when I try the go command for installation it works perfectly fine

**Comment by yrs147** [comment]
Issue Resolved
