### ISSUE TITLE
Debian package kubernetes-cni 1.1.1 bundles plugins 0.8.6

### ISSUE THREAD

**Issue by chdxD1** [kubernetes/release#2884]
#### What happened:
When installing kubernetes-cni version 1.1.1 from the apt repo of Kubernetes it installs CNI plugins version 0.8.6

#### What you expected to happen:
CNI plugin version 1.1.1 is installed

#### How to reproduce it (as minimally and precisely as possible):
- Download dist package https://packages.cloud.google.com/apt/pool/kubernetes-cni_1.1.1-00_amd64_910d5920eab8d7cf9a66cc4b0faf998fb3ee909bd6ee0bd7d1c6605b6a82f98f.deb manually
OR
- Add apt source (kubernetes-xenial)
- `apt-get install kubernetes-cni=1.1.1`
- Verify plugin version `/opt/cni/bin/macvlan --help`
```
# /opt/cni/bin/macvlan --help
CNI macvlan plugin v0.8.6
```

#### Anything else we need to know?:
As kubernetes-cni package version 1.2.0 is now published (which installs 1.2.0) it should be fine on newer installs but shipping a 1.1.1 with 0.8.6 bundled is weird.

#### Environment:
- Cloud provider or hardware configuration: n/a
- OS (e.g: `cat /etc/os-release`): 20.04.5 LTS (Focal Fossa)
- Kernel (e.g. `uname -a`): 5.15.0-50-generic

**Comment by afbjorklund** [comment]
* https://github.com/kubernetes/release/issues/821#issuecomment-1250371849
