### ISSUE TITLE
Deprecated k8s.gcr.io container image registry still in use

### ISSUE THREAD

**Issue by rjsadow** [kubernetes/release#2904]
#### What happened: 

There are several uses of the deprecating k8s.gcr.io registry in k/release. These need to be updated and moved prior to the April 3rd freeze of the registry. 

Tracking: https://github.com/kubernetes/k8s.io/issues/4738
Search results: https://cs.k8s.io/?q=k8s.gcr.io&i=nope&files=&excludeFiles=vendor%2F&repos=kubernetes/release

**Comment by rjsadow** [comment]
Hi all,

I'd like to help update some of these references but want to double check a few things with someone more knowledgeable first. 

[.github/workflows/scorecards-analysis.yml](https://github.com/kubernetes/release/blob/d7ae6f49d76c3536487bef3d2527400cf80c2ebd/.github/workflows/scorecards-analysis.yml#L39) - I believe this can be a straight replace. 
[dependencies.yaml](https://github.com/kubernetes/release/blob/d7ae6f49d76c3536487bef3d2527400cf80c2ebd/dependencies.yaml) - Is this document safe to change? My understanding is that it's to track dependencies but not necessarily used during any build/release process, is that true? 
[images/build/debian-iptables/Makefile](https://github.com/kubernetes/release/blob/d7ae6f49d76c3536487bef3d2527400cf80c2ebd/images/build/debian-iptables/Makefile) - Straight replace should be fine, I've confirmed registry.k8s.io/build-image/debian-base-${ARCH} and registry.k8s.io/build-image/go-runner are present for the latest build versions.
 [images/build/debian-iptables/README.md](https://github.com/kubernetes/release/blob/d7ae6f49d76c3536487bef3d2527400cf80c2ebd/images/build/debian-iptables/README.md) - Doc updated with debian-iptables change
[images/build/distroless-iptables/Makefile](https://github.com/kubernetes/release/blob/d7ae6f49d76c3536487bef3d2527400cf80c2ebd/images/build/distroless-iptables/Makefile) - Similar to debian-iptables, it uses go-runner at the same version
[images/build/distroless-iptables/README.md](https://github.com/kubernetes/release/blob/d7ae6f49d76c3536487bef3d2527400cf80c2ebd/images/build/distroless-iptables/README.md) - Doc update with distroless-iptables change 
[images/build/setcap/Makefile](https://github.com/kubernetes/release/blob/d7ae6f49d76c3536487bef3d2527400cf80c2ebd/images/build/setcap/Makefile) - Similar to debuan-iptalbes it uses registry.k8s.io/build-image/debian-base-${ARCH} at the same version.
[images/build/setcap/README.md](https://github.com/kubernetes/release/blob/d7ae6f49d76c3536487bef3d2527400cf80c2ebd/images/build/setcap/README.md) - Doc update with setcap
[images/k8s-cloud-builder/Dockerfile](https://github.com/kubernetes/release/blob/d7ae6f49d76c3536487bef3d2527400cf80c2ebd/images/k8s-cloud-builder/Dockerfile) - Should be a straight replace, I've verified  registry.k8s.io/build-image/kube-cross exists for all currently used [variants](https://github.com/kubernetes/release/blob/d7ae6f49d76c3536487bef3d2527400cf80c2ebd/images/k8s-cloud-builder/variants.yaml)
[pkg/announce/announce.go](https://github.com/kubernetes/release/blob/d7ae6f49d76c3536487bef3d2527400cf80c2ebd/pkg/announce/announce.go) - Logging output, straight replace. 
[pkg/release/images_test.go](https://github.com/kubernetes/release/blob/d7ae6f49d76c3536487bef3d2527400cf80c2ebd/pkg/release/images_test.go) - Logging output, straight replace. 
[push-build.sh](https://github.com/kubernetes/release/blob/d7ae6f49d76c3536487bef3d2527400cf80c2ebd/push-build.sh) - I don't actually see where or how the variables GCRIO_PATH_MOCK or KUBE_CROSS_CONFIG_LOCATION are being used within the script. I'm not sure the implications of changing this reference. 

There are a few other references from the search results which can be kept or marked as relative (krel test data)

**Comment by sftim** [comment]
/retitle Deprecated k8s.gcr.io container image registry still in use
