### ISSUE TITLE
Manifest fetch flakes on krel release

### ISSUE THREAD

**Issue by cici37** [kubernetes/release#2913]
#### What happened:
Hit flakes with fetching manifest and needed to re-run the no mock release:
[Flake in v1.27.0-alpha2 release](https://console.cloud.google.com/cloud-build/builds/93721a0d-b452-4842-a4d9-9589bc397701?project=648026197307)

It failed with `Step #4: FATA[2023-02-15T02:59:59Z] push artifacts: validate container images: get manifest images: traversing path: executing tarball callback: verify signed image: verify image: verify if images are signed: check if images are signed: get digest for image reference: GET https://k8s.gcr.io/v2/conformance-amd64/manifests/v1.27.0-alpha.2: MANIFEST_UNKNOWN: Failed to fetch "v1.27.0-alpha.2" from request "/v2/conformance-amd64/manifests/v1.27.0-alpha.2".`

Got error `{"errors":[{"code":"MANIFEST_UNKNOWN","message":"Manifest with tag 'v1.27.0-alpha.2' has media type 'application/vnd.docker.distribution.manifest.v2+json', but client accepts 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'."}]}` while directly make a get call to https://k8s.gcr.io/v2/conformance-amd64/manifests/v1.27.0-alpha.2

#### Environment:

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by saschagrunert** [comment]
Hm, I'm not sure we can do much about this one since it really seems to be an transient issue :thinking:
