### ISSUE TITLE
kubeadm 1.6+ Validating kernel version

### ISSUE THREAD

**Issue by wbtxd2004** [kubernetes/release#292]
I runned
```
 kubeadm init
```
but I got errors like this:
Log file created at: 2017/03/22 16:43:40
```
Running on machine: *****
Binary: Built with gc go1.7.5 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0322 16:43:40.841902    2890 kernel_validator.go:77] Validating kernel version
I0322 16:43:40.842175    2890 kernel_validator.go:92] Validating kernel config
```

my kernel version is 3.1 before, then I updated it to 4.4.55, it also not work well, which kernel version is support?

```
$uname -r
4.4.55-1.el7.elrepo.x86_64
```

**Comment by ivdimitro** [comment]
My kubeadm init stopped at the same point in fully updated Centos 7. 
I see you closed the issue. What was the solution?
`uname -r
3.10.0-514.10.2.el7.x86_64`
