### ISSUE TITLE
Google Cloud Packages Automatic Signing Key - Expired

### ISSUE THREAD

**Issue by Saliha067** [kubernetes/release#2933]
#### What happened:
The key used to sign all the packages from the packages.cloud.google.com repos has expired.

#### What you expected to happen:
The key to be refreshed

#### How to reproduce it (as minimally and precisely as possible):
Follow these steps : https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl

#### Anything else we need to know?:
<img width="1238" alt="Screenshot 2023-02-27 at 10 15 16 PM" src="https://user-images.githubusercontent.com/49085460/221574150-cc719280-aca1-4cf4-bba3-dc9e67efad43.png">

#### Environment:
Ubuntu 20.04 LTS

**Comment by dims** [comment]
Please see the email thread - https://groups.google.com/a/kubernetes.io/g/dev/c/gR5xDzzIcW8/m/SK5ARWkGAQAJ
