### ISSUE TITLE
release note generation mangles markdown links

### ISSUE THREAD

**Issue by calebamiles** [kubernetes/release#299]
Comparing the [final version of the release notes](https://github.com/kubernetes/kubernetes/blob/0a13fef494c938d42252e8a6bab7f6273dd91b37/CHANGELOG.md) with [the draft](https://github.com/kubernetes/features/blob/master/release-1.6/release-notes-draft.md) [2] it was noted that markdown links will be rendered incorrectly due to what looks like an automated link to PR. The link generation is also subtly incorrect as some links of the form `github.com/someCompany/someRepo/issues/someIssue` will be rewritten as `github.com/kubernetes/kubernetes/pull/someIssue`.

**cc: @bgrant0607**

**Comment by xiangpengzhao** [comment]
xref: https://github.com/kubernetes/release/issues/360

**Comment by bgrant0607** [comment]
cc @kubernetes/sig-release-bugs

**Comment by xiangpengzhao** [comment]
I will try to understand the scripts. @david-mcmahon any ideas?
BTW, we had this issue both in 1.7 (https://github.com/kubernetes/kubernetes/pull/48328) and 1.8 (https://github.com/kubernetes/kubernetes/pull/53286). Hope we don't meet this in the future releases...

**Comment by enisoc** [comment]
For 1.9, I'm hoping to switch to the new Go implementation (#434).

@jennybuckley @roycaihw Does the new implementation still exhibit this problem?

**Comment by david-mcmahon** [comment]
Good point @enisoc. Once this gets submitted and we integrate with `anago`, we can close this issue.

**Comment by roycaihw** [comment]
@enisoc @david-mcmahon Yes, I think it still exhibit the problem. HTML-izing markdown file is kind of complicated, and the Go implementation relies on the same sed command as #360 pointed out.
