### ISSUE TITLE
Create a client tool release

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/release#3]
Addon components get updated in Kubernetes clusters by updating manifests referring to new image tags. The images don't need to be bundled directly with the Kubernetes release because they are just pulled from the registry.

Tools, however, typically can't be pulled in that way. However, we would like to make it easy for users to get popular tools. [Helm](https://github.com/kubernetes/helm) is a prime candidate. It should be ready for bundling with K8s 1.4. [Kompose](https://github.com/skippbox/kompose) is another possibility.

cc @technosophos @sebgoa

**Comment by bgrant0607** [comment]
cc @pwittrock

**Comment by pwittrock** [comment]
Would this include upgrading bundled tools when upgrading releases?

**Comment by bgrant0607** [comment]
@pwittrock We'd ship the latest release of each tool. We don't provide an installer. The distros do that.

**Comment by bgrant0607** [comment]
cc @monopole

**Comment by dims** [comment]
/close

totally stale issue
