### ISSUE TITLE
Wait for packages to be published before proceeding with release

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/release#3053]
The appropriate `krel obs` command should wait for packages to be fully built and published before proceeding with the release step (#3052).

We're yet to decide if we want to wait for all packages and architectures or only "for the most important" and the fastest ones, but that shouldn't affect the implementation in any way.

OBS has a RabbitMQ instance (http://rabbit.opensuse.org/) that we could integrate with. Alternatively, we could try to integrate with some OBS API if such API exists.

/sig release
/area release-eng
/priority important-longterm

**Comment by xmudrii** [comment]
@saschagrunert We have wait mechanism based on polling. Do we still need RabbitMQ implementation?

**Comment by saschagrunert** [comment]
No, I think that's done

**Comment by xmudrii** [comment]
Fixed by #3304 #3315 #3318
