### ISSUE TITLE
1.6.0 kubelet changed behaviour for cgroups on Centos

### ISSUE THREAD

**Issue by coeki** [kubernetes/release#306]
Somehow the rpm's for Centos, fedora and rhel for the 1.6.0 release make the cgroup-driver between docker and the kubelet different. Docker has cgroup-driver=systemd, kubelet has cgroup-driver=cgroupfs.

A quick fix to building the rpm's would be to add 

`Environment="KUBELET_CGROUP_ARGS=--cgroup-driver=systemd"` 

to the 10-kubeadm.conf file.

Not seeing this on ubuntu, so not sure about the real cause.

**Comment by coeki** [comment]
ah forgot to mention in regard to https://github.com/kubernetes/kubernetes/pull/43835 and https://github.com/kubernetes/kubernetes/issues/43815

**Comment by liggitt** [comment]
cc @derekwaynecarr

**Comment by silentred** [comment]
Agree. Now I have to edit kubelet config by hand.

**Comment by mikedanese** [comment]
@dgoodwin

**Comment by mikedanese** [comment]
I don't have much experience with el derivatives but it seems like the resolution here is that we can either align kubelet with the docker default cgroup driver or vica versa. I'm not sure what the implications are either way so I would be happy to have someone with more familiarity weigh in.

cc @kubernetes/sig-node-misc

**Comment by yujuhong** [comment]
> the resolution here is that we can either align kubelet with the docker default cgroup driver or vice versa.

I think it's required to configure docker and kubelet to use the same cgroup driver, but @derekwaynecarr is the right person to answer.

**Comment by vishh** [comment]
If the docker cgroup driver is `systemd` set kubelet to use that as well.

**Comment by arunm8489** [comment]
#yum install -y kubelet kubeadm kubectl docker
Jst try installing docker 1.12...iam not getting solution with docker 1.17ce.( i think its not supported with kubelet)
Make swap off by #swapoff -a
Now reset kubeadm by #kubeadm reset
Now try #kudeadm init
after that check #systemctl status kubelet
for me it worked
