### ISSUE TITLE
kubelet and kubernetes-cni packages depencies

### ISSUE THREAD

**Issue by Seb-Solon** [kubernetes/release#310]
Hi,

The rpm package of  kubernetes-cni depends on kubelet and the rpm package of kubelet depend on kubernetes-cni as described here https://github.com/kubernetes/release/blob/master/rpm/kubelet.spec

This makes a circular dep. Do you agree guys that we can remove the dependency of kubelet from the kubernetes-cni package? If so I can do a PR for you.

It looks like it is fine for debian if I look at the control file: https://github.com/kubernetes/release/blob/master/debian/xenial/kubernetes-cni/debian/control  or the Release file on the repository : https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/binary-amd64/Packages

Regards,

Slightly related to #97

**Comment by Seb-Solon** [comment]
Is this legit guys?

**Comment by luxas** [comment]
This line is indeed wrong: https://github.com/kubernetes/release/blob/master/rpm/kubelet.spec#L39
Feel free to send a PR

Sorry that I haven't seen this earlier, but I'm not watching the release repo...
