### ISSUE TITLE
Add presubmit job to run rpmlint on package specs

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/release#3166]
#### What would you like to be added:

Add a presubmit job to run rpmlint on package specs. This is needed because OBS has strict rpmlint settings which can fail the build process. To avoid this happening, we should run rpmlint on our own as well.

**Comment by saschagrunert** [comment]
I think we can also integrate it into `pull-release-verify` if the dependency chain is not too big.

**Comment by saschagrunert** [comment]
We now have rpmlint in `gcr.io/k8s-staging-releng/releng-ci:latest-go1.20-bookworm`. I think we have to generate the specs for a possible verification step using `krel obs --spec-only …` and then run rpmlint against the results.

**Comment by xmudrii** [comment]
Yes, that would be the plan. I can take care of that when working on tests for the OBS implementation which should be soon.

**Comment by saschagrunert** [comment]
@xmudrii this is a good opportunity to include other @kubernetes/release-managers and mentor them into the code. Let's check if anyone is interested in contributing here.

**Comment by xmudrii** [comment]
@saschagrunert Sounds good to me!

**Comment by cpanato** [comment]
discussed with marko and i will take this
/assign
