### ISSUE TITLE
Enhance release staging dashboard and make external

### ISSUE THREAD

**Issue by david-mcmahon** [kubernetes/release#32]
The beginnings of a very useful dashboard exist at https://x20web.corp.google.com/~djmm/k8s-master.html (internal only).  What else does it need?

* [ ] Make it external
* [ ] Make it prettier
* [ ] Based on testing state and the last good git hash that would be chosen for a release, cross out the release notes that would get missed if we released today(now).
* [ ] ???

Closing.  Dup of #2

**Comment by erictune** [comment]
Having release notes for the current candidate seems useful.  Need some
experience with it to know if anything else is needed.

**Comment by david-mcmahon** [comment]
Yes, thanks. Please add any suggestions to #2.
