### ISSUE TITLE
publish-release SBOM's the .git directory

### ISSUE THREAD

**Issue by puerco** [kubernetes/release#3213]
#### What happened:

When cutting a release using `publish-release`, the autogenerated SBOM collects all the .git repo. `bom` (when not embedded) has an ignore rule that skips .git and other files. 

#### What you expected to happen:

Commonly ignored files should not be included in the autogenerated SBOM

#### How to reproduce it (as minimally and precisely as possible):

run `publish-release github` on a repo and check the SBOM

#### Anything else we need to know?:

Also there is no way to supply ignore patterns to the SBOM generator

**Comment by puerco** [comment]
Ah I traced this back to the `bom` source and the reason is that the `.git` directory only is ignored when there is a `.gitignore ` file in the project:

https://github.com/kubernetes-sigs/bom/blob/857ce3a04acde533953e525ea264ccb7b4115516/pkg/spdx/implementation.go#L515-L517

I'm not sure if I like this behavior  :thinking:

**Comment by saschagrunert** [comment]
At least we should not introduce a breaking change, but you may remember the reasons for the code from 2 years ago. :upside_down_face:

**Comment by puerco** [comment]
2 pandemic years ago feel like 10 years :older_man: 

I think this behavior can be overridden by adding some flags. I'll close this and revisit if we need it.
