### ISSUE TITLE
Can we have a release digest file?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/release#3222]
Today we have .sig files which can be individually downloaded and verified for any one binary.  To download two binaries, we have to go through the verification twice.  Each verification requires that we download the .sha256 file, the .sig file and the .cert file.

We also have a SHA256SUMS file which has all the artifact hashes in one convenient place.

It would be very convenient/faster to be able to download the SHA256SUMS file, verify it, and then fetch the other binaries and simply verify their hash.  I don't believe this would be any less secure either.

We're pretty close to this, however there are two issues:

* As can be seen from `curl https://cdn.dl.k8s.io/release/v1.28.0/SHA256SUMS`, the file is corruptish, it does not use relative paths and seems to embed a build workspace prefix.    For example, I would expect `218fff24ac77d1d99844a0daadf29a52ded8cc2cdeac76f451438e9a45280e56  /workspace/src/k8s.io/kubernetes/_output-v1.28.0/gcs-stage/v1.28.0/bin/linux/s390x/kube-aggregator` to be `218fff24ac77d1d99844a0daadf29a52ded8cc2cdeac76f451438e9a45280e56 bin/linux/s390x/kube-aggregator`
* We don't currently publish a .sig or .cert for the SHA256SUMS file.

If we're worried about the path fix being a breaking change, we could publish an additional file like `RELEASE`, but my view is that despite https://xkcd.com/1172/ the existing SHA256SUMS file is already broken.

**Comment by saschagrunert** [comment]
@justinsb thank you for the report, I addressed the first point in #3227

**Comment by saschagrunert** [comment]
Still to be addressed:

> We don't currently publish a .sig or .cert for the SHA256SUMS file.

**Comment by xmudrii** [comment]
> We don't currently publish a .sig or .cert for the SHA256SUMS file.

I think fixing this should be as easy as removing this line: https://github.com/kubernetes/release/blob/0e27c3880058e74893a1286eef8651523947fe18/cmd/krel/cmd/sign_blobs.go#L171

However, I don't have any context on why we skip these files, so it would be nice to get some input from @cpanato and @puerco

**Comment by saschagrunert** [comment]
@xmudrii I removed that in https://github.com/kubernetes/release/pull/2779 because I thought it would not be necessary. :shrug:

**Comment by justinsb** [comment]
Thanks for fixing the paths in the SHA256 file - greatly appreciated!

As to whether we should be signing the SHA256 file, my use case is that I'm trying to avoid having to verify N signatures (in kOps we need to get kubectl, kubelet etc), because each verification is relatively heavy.  I guess instead of the SHA256SUMS file I could instead use the SBOM (`https://sbom.k8s.io/$(curl -Ls https://dl.k8s.io/release/stable.txt)/release`) , but that isn't signed either (that I could see).

Or maybe I'm just doing it wrong and I should be looking for an attestation from sigstore (i.e. on the rekor chain), for example if we published something similar to SHA256SUMS or the SBOM with `cosign attest-blob`, then maybe that is the "right" way to indicate that "this particular set of files correspond to release 1.30.2" (rather than having to infer it from a path).

**Comment by saschagrunert** [comment]
@justinsb the SBOM's are signed, but the rewrite `sbom.k8s.io` does only support the spdx file:

- https://storage.googleapis.com/kubernetes-release/release/v1.28.0/kubernetes-release.spdx.cert
- https://storage.googleapis.com/kubernetes-release/release/v1.28.0/kubernetes-release.spdx.sig

https://github.com/kubernetes/k8s.io/blob/201c0495389fd225981da7287f081383ef649c49/apps/k8s-io/configmap-nginx.yaml#L328-L334

We should fix that.

**Comment by saschagrunert** [comment]
@justinsb do you think we can close this issue now or do you still see points left open?

**Comment by saschagrunert** [comment]
Closing, feel free to reopen.
