### ISSUE TITLE
`apt list` shows all architectures instead of only the system's architecture for pkgs.k8s.io

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/release#3228]
#### What happened:

Running `apt list` for `pkgs.k8s.io` repo returns output such as this one:

```
root@dcb61ebbcc3e:/go# apt list kubeadm
Listing... Done
kubeadm/unknown 1.28.1-1.1 amd64
kubeadm/unknown 1.28.1-1.1 arm64
kubeadm/unknown 1.28.1-1.1 ppc64el
kubeadm/unknown 1.28.1-1.1 s390x
```

This is generally unexpected because `apt list` should show only the architecture that's being used, not all architectures.

#### What you expected to happen:

`apt list` should show only the architecture that's being used, e.g.:

```
root@dcb61ebbcc3e:/go# apt list kubeadm
Listing... Done
kubeadm/unknown 1.28.1-1.1 amd64
```

#### How to reproduce it (as minimally and precisely as possible):

* [Add the Kubernetes community-hosted repository to your system](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#dpkg-k8s-package-repo)
* Run `apt list kubeadm` (or any other package present in that repository)

#### Anything else we need to know?:

The correct behavior is present in the Google-hosted repositories. More information about this issue can be found in the following Slack thread: https://kubernetes.slack.com/archives/C03U7N0VCGK/p1692949309763199

This might also be an issue on the OBS side.

#### Environment:

- Cloud provider or hardware configuration: Docker container
- OS (e.g: `cat /etc/os-release`): Debian GNU/Linux 11 (bullseye)
- Kernel (e.g. `uname -a`): 5.15.49-linuxkit-pr
- Others: apt 2.2.4 (amd64)

**Comment by afbjorklund** [comment]
I think it is a generic OpenBuildSystem thing, since `cri-o` looks the same:

```
cri-o-runc/unknown 1.0.1~2 amd64
cri-o-runc/unknown 1.0.1~2 arm64
cri-o-runc/unknown 1.0.1~2 armhf
cri-o-runc/unknown 1.0.1~2 ppc64el
cri-o-runc/unknown 1.0.1~2 s390x
cri-o/unknown 1.27.1~0 amd64
cri-o/unknown 1.27.1~0 arm64
cri-o/unknown 1.27.1~0 armhf
cri-o/unknown 1.27.1~0 s390x
```

**Comment by Conan-Kudo** [comment]
OBS creates so-called “flat” repositories in Debian parlance, where the packages all sit together in one directory. APT is perfectly capable of handling this situation, it just produces different output than what people are used to.

The lack of a suite and component is probably fine for our case, since the packages are not distro specific.

**Comment by afbjorklund** [comment]
Yes, there was nothing wrong with the functionality - it was mostly cosmetic (and makes the list longer).

**Comment by xmudrii** [comment]
Given that this is how OBS works, there's nothing that we can or should do about this. IMO, this behavior is completely okay and package managers handle it well. Regardless, thanks for bringing this up @afbjorklund, at least we have it documented here. 🙂 
/close

**Comment by afbjorklund** [comment]
That's ok, probably an improvement for the OBS backlog - to split the `Packages` by arch...

Just that it was another change for Kubernetes, when you moved the package hosting (like the new revisions). So tracking regressions could be done either way.
