### ISSUE TITLE
Use native packaging .spec & .debs 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/release#324]
Almost done with CNI, and will put up for fedora review, then I have an update for fedora packages to include a kubernetes-kubeadm sub-package.  

/cc @dgoodwin @ingvagabund @mikedanese

**Comment by timothysc** [comment]
CNI review - https://bugzilla.redhat.com/show_bug.cgi?id=1451124 

+ I have packaging sub-package for kubeadm once that is done.

**Comment by mikedanese** [comment]
How do we coordinate this with releases?

**Comment by timothysc** [comment]
I'm going to setup triggers on tags to push updates.

**Comment by timothysc** [comment]
@mikedanese I could also push the full .spec files back such that you can mock build and then your packages will be up to guidelines.  Right now the binary .specs files gives pause to those in the know, b/c they can't full reproduce from .srpm files.  

I could PR back to this repo once all channels are updated and the instructions would need to be cleaned up too.

**Comment by timothysc** [comment]
I'll try to update the kube-spec tool.  The channeled on is kind of a mess.
