### ISSUE TITLE
buildx bake failed with: ERROR: failed to solve: cannot copy to non-directory when distroless-iptables is upgraded to v0.3.2

### ISSUE THREAD

**Issue by jwtty** [kubernetes/release#3260]
#### What happened:
Hi, when distroless-iptables's version is upgraded to v0.3.2, our buildx build failed with error:
```
FROM registry.k8s.io/build-image/distroless-iptables:v0.3.2
   3 |     USER 0:0
   4 | >>> COPY --from=baseimg /${MAIN_ENTRY} .
buildx bake failed with: ERROR: failed to solve: cannot copy to non-directory: /var/lib/buildkit/runc-overlayfs/cachemounts/buildkit2113282869/usr/share/zoneinfo/posix/Africa
```

Can someone help take a look?

#### What you expected to happen:
Build should succeed.

#### How to reproduce it (as minimally and precisely as possible):
The only change is to upgrade distroless-iptables image from v0.2.7 to v0.3.2.

#### Environment:
linux
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by saschagrunert** [comment]
Hey @jwtty, thank you for opening the issue! Can you share a `Dockerfile` to reproduce the issue?

**Comment by jwtty** [comment]
nvm, it should be an issue on our side. Thanks @saschagrunert !
