### ISSUE TITLE
Version issue with new community repo

### ISSUE THREAD

**Issue by Cloud-Mak** [kubernetes/release#3284]
#### What happened:
After adding community based repo (https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/) I could only find k8s version 1.25.x. 
1.26 and above are not visible. Mentioned current k8s minor version as per step here - https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/

#### What you expected to happen:
If one is sepcifying version the upgrade is an issue (e.g. I specified my current k8s version as 1.25 and I can not find anythign beyond 1.25 for upgrade.) I guess the language of blog needs to be modified to include note about upgrade. Mention the vesion you would want to upgrade to if you're switching to community based repo for upgrade.

#### How to reproduce it (as minimally and precisely as possible):
https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/ 
follow these instructions. And commnet / delere .list file for legacy repo.
#### Environment:

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
ubutu 20
- Kernel (e.g. `uname -a`):
5.4.0-159-generic
- Others:

**Comment by xmudrii** [comment]
> I guess the language of blog needs to be modified to include note about upgrade. Mention the vesion you would want to upgrade to if you're switching to community based repo for upgrade.

This is already mentioned in the blog post in `What you need to know about the new package repositories?` section:

> There's a dedicated package repository for each Kubernetes minor version. When upgrading to a different minor release, you must bear in mind that the package repository details also change.

Additionally, the relevant upgrade guides are updated to highlight the importance of this change. We also have a document describing how to do it: https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/change-package-repository/

We should probably link to that guide from the blog post to show how it is done.

**Comment by dweineha** [comment]
What's the recommended way to check (from software) whether there are newer minor versions available? With the previous repos it was enough to just use apt update and check the latest package version, but this isn't feasible anymore, and polling by adding repos for possibly non-existing versions doesn't seem like an appealing idea.

**Comment by xmudrii** [comment]
Please use our Release Information page for information about releases: https://kubernetes.io/releases/

**Comment by dweineha** [comment]
So the recommended way to check the latest version from software is to parse that page?

**Comment by PetterSa** [comment]
What is the reasoning behind doing it this way, having one repository per minor version? It is causing some friction when we mirror apt repositories into our organization.

**Comment by Cloud-Mak** [comment]
Just to update - the old Google-hosted package repositories are stil working. I just setup 5 nodes HA cluster with same. The highest version is 1.28.2 avaialble. 

Are not these repos suppose to be stop functioning by now? 

Location of the servers - Phoenix Arizona (USA).

**Comment by xmudrii** [comment]
@Cloud-Mak We don't publish packages to the Google repositories since September 13, 2023. We **strongly recommend** using the new community-owned package repositories (pkgs.k8s.io) because we can't provide guarantees how long the legacy (Google-hosted) packages repositories will be available.

We're working with AWS and OpenBuildService folks to find out a resolution for this problem and we'll keep this ticket updated. While we're trying our best, please note that it might take several days to receive feedback because many folks are on vacations at this time.

**Comment by xmudrii** [comment]
I think we're all good here, but if I missed anything, please let me know
/close
