### ISSUE TITLE
`kubeadm` package should depend on the same version of `kubelet` and `kubectl` packages

### ISSUE THREAD

**Issue by paralika** [kubernetes/release#3295]
**What happened**:
`kubeadm` package always install latest version of `Kubelet` and `kubectl` packages. 

```
root@node01:/var/cache/apt/archives# apt install kubeadm=1.11.6-00 --download-only
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  cri-tools ebtables kubectl kubelet kubernetes-cni socat
The following NEW packages will be installed:
  cri-tools ebtables kubeadm kubectl kubelet kubernetes-cni socat
0 upgraded, 7 newly installed, 0 to remove and 11 not upgraded.
Need to get 48.0 MB of archives.
After this operation, 285 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://asia-south1-a.gce.clouds.archive.ubuntu.com/ubuntu xenial-updates/main amd64 ebtables amd64 2.0.10.4-3.4ubuntu2.16.04.2 [79.9 kB]
Get:2 https://apt.kubernetes.io kubernetes-xenial/main amd64 cri-tools amd64 1.12.0-00 [5,343 kB]
Get:3 http://asia-south1-a.gce.clouds.archive.ubuntu.com/ubuntu xenial/universe amd64 socat amd64 1.7.3.1-1 [321 kB]
Get:4 https://apt.kubernetes.io kubernetes-xenial/main amd64 kubernetes-cni amd64 0.6.0-00 [5,910 kB]
Get:5 https://apt.kubernetes.io kubernetes-xenial/main amd64 kubelet amd64 1.13.2-00 [19.0 MB]
Get:6 https://apt.kubernetes.io kubernetes-xenial/main amd64 kubectl amd64 1.13.2-00 [7,847 kB]
Get:7 https://apt.kubernetes.io kubernetes-xenial/main amd64 kubeadm amd64 1.11.6-00 [9,427 kB]
Fetched 48.0 MB in 6s (7,576 kB/s)                                                                                                                                                     
Download complete and in download only mode
```
**What you expected to happen**:
`kubeadm` package should be depend on the same version of `kubelet` and `kubectl`. 
Above command should download `kubeadm 1.11.6`, `Kubelets 1.11.6` and `kubectl 1.11.6`. 

**How to reproduce it (as minimally and precisely as possible)**:
Add Kubernetes repository (`deb https://apt.kubernetes.io/ kubernetes-xenial main`) in source.list.d.
`apt-get update`
`apt install kubeadm=1.11.6-00 --download-only`

**Anything else we need to know?**:
I believe we need to update the dependancy of `kubeadm` package. 

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: GCP VM instance
- OS (e.g. from /etc/os-release): `Ubuntu 16.04.5 LTS`
- Kernel (e.g. `uname -a`): `Linux node01 4.15.0-1026-gcp kubernetes/kubernetes#27~16.04.1-Ubuntu SMP Fri Dec 7 09:59:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Others:

**Comment by saschagrunert** [comment]
In OBS we now have dedicated projects for minor versions, for example:

- v1.27.z: https://build.opensuse.org/project/show/isv:kubernetes:core:stable:v1.27
- v1.28.z: https://build.opensuse.org/project/show/isv:kubernetes:core:stable:v1.28

This means that we now install the latest minor version, which should be fine component wise:

```Dockerfile
ARG FROM=ubuntu:22.04
FROM $FROM

ARG PROJECT_PATH=prerelease:/main

RUN apt-get update && \
    apt-get install -y \
        curl \
        software-properties-common

ENV KUBERNETES_VERSION=v1.27
RUN curl -fsSL https://pkgs.k8s.io/core:/stable:/$KUBERNETES_VERSION/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
RUN echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/$KUBERNETES_VERSION/deb/ /" | tee /etc/apt/sources.list.d/kubernetes.list

RUN apt-get update && apt-get install -y kubeadm=1.27.3-1.1 kubeadm
RUN kubelet --version
```

```
…
Setting up kubelet (1.27.6-1.1) ...
Setting up kubeadm (1.27.6-1.1) ...
…
STEP 8/8: RUN kubelet --version
Kubernetes v1.27.6
```

I'd say we're happy with that if we don't want to constraint the packages even more. Feel free to reopen if there is more discussion required.
