### ISSUE TITLE
Not able to install K8s Cluster using kubeadm init command

### ISSUE THREAD

**Issue by lokesh090909** [kubernetes/release#3299]
#### What happened:

Not able to install K8s Cluster using kubeadm init command due to x509: certificate signed by unknown authority.

#### What you expected to happen:

while running kubeadm init, K8s command is should able to pull images from repository.

#### How to reproduce it (as minimally and precisely as possible):

We are not able to access below link even in browser as well:

https://pkgs.k8s.io/core:/stable:/v1.28/deb/

#### Environment:

- Cloud provider or hardware configuration: VMware
- OS (e.g: `cat /etc/os-release`): Ubuntu 22.04.3 LTS
- Kernel (e.g. `uname -a`):Linux k8s-master 5.15.0-84-generic #93-Ubuntu SMP Tue Sep 5 17:16:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- Others:

**Comment by xmudrii** [comment]
The error that you're seeing is related to kubeadm not being able to pull the needed images from registry.k8s.io. This mostly like doesn't have anything to do with pkgs.k8s.io and therefore we can't provide support for your issue. I recommend reaching out to folks in https://github.com/kubernetes/registry.k8s.io and checking their [debugging guidelines](https://github.com/kubernetes/registry.k8s.io/blob/main/docs/debugging.md).

**Comment by xmudrii** [comment]
> We are not able to access below link even in browser as well:
>
> https://pkgs.k8s.io/core:/stable:/v1.28/deb/

This is as expected because this link is pointing to a S3 bucket and at this time we don't have a public browser for that S3 bucket.

**Comment by neolit123** [comment]
> The error that you're seeing is related to kubeadm not being able to pull the needed images from registry.k8s.io. This mostly like doesn't have anything to do with pkgs.k8s.io and therefore we can't provide support for your issue. I recommend reaching out to folks in https://github.com/kubernetes/registry.k8s.io and checking their [debugging guidelines](https://github.com/kubernetes/registry.k8s.io/blob/main/docs/debugging.md).

+1
try opening issue in k/registry.k8s.io

/close
