### ISSUE TITLE
Can not install kubelet kubeadm kubectl through the new repo : pkgs.k8s.io/core

### ISSUE THREAD

**Issue by ValeYuki91** [kubernetes/release#3341]
I've tried to install them through :

>dnf install -y kubelet-1.28.3-0 kubeadm-1.28.3-0 kubectl-1.28.3-0 --disableexcludes=kubernetes

But return this : 

No match for argument: kubelet-1.28.3-0
No match for argument: kubeadm-1.28.3-0
No match for argument: kubectl-1.28.3-0
Error: Unable to find a match: kubelet-1.28.3-0 kubeadm-1.28.3-0 kubectl-1.28.3-0

Here a screenshot of the entire situation : 
![k8s-repo-bug](https://github.com/kubernetes/release/assets/126324118/ebda643d-471c-4aec-9354-01e454444131)

I'm sorry I'm relatively new to this world,I don't know if I'm doing something wrong or there's some kind of issue, thank you everyone

**Comment by neolit123** [comment]
our official install guide is here:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl
(click the redhat tab, it uses yum)

but for support questions, please use the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
