### ISSUE TITLE
Update the test matrix in lib/releaselib.sh

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/release#335]
The tests [matrix](https://github.com/kubernetes/release/blob/master/lib/releaselib.sh#L106) might not be up-to-date. @dchen1107 @krzyzacy what are the other tests we need for 1.7?

**Comment by krzyzacy** [comment]
for 1.6 we had https://github.com/kubernetes/test-infra/issues/2029, maybe @dchen1107 we should make one for 1.7, or it need to go into some documentation somewhere?

**Comment by david-mcmahon** [comment]
dup of https://github.com/kubernetes/test-infra/pull/2967
