### ISSUE TITLE
Share public Google Calendar that has all release dates and deadlines on it

### ISSUE THREAD

**Issue by mml** [kubernetes/release#337]
Makes it easy for contributors to plan their contributions, code reviews, etc.  Once published, it'll be important to make sure that timeline changes are reflected on it, because folks (I at least) will be relying on it to be authoritative to plan their days and nights.

cc @calebamiles

**Comment by calebamiles** [comment]
Calendar updated for 1.7 [available now](https://calendar.google.com/calendar/embed?src=coreos.com_regcvcrgvq98lua2ikijg1g1uk%40group.calendar.google.com&ctz=America/Los_Angeles) [1]

1. https://calendar.google.com/calendar/embed?src=coreos.com_regcvcrgvq98lua2ikijg1g1uk%40group.calendar.google.com&ctz=America/Los_Angeles
