### ISSUE TITLE
The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05

### ISSUE THREAD

**Issue by estem** [kubernetes/release#3371]
'm trying to set up a kubernetes cluster,I have Ubuntu on my VMS :
`DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"`

when I try to execute these cmds :

`sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg`
and 
`echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
`

then this error occurs when I run

`sudo apt update :`

the error 👍 
`The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05
W: Failed to fetch https://apt.kubernetes.io/dists/kubernetes-xenial/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05`
Could you help please to fix this issue ?

**Comment by xmudrii** [comment]
The package repositories hosted at `apt.kubernetes.io` and `yum.kubernetes.io` are deprecated and we don't provide active support for these repositories any longer. The new package repositories are available at `pkgs.k8s.io` and you can learn more about these repositories in our [official announcement](https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/).

/close
