### ISSUE TITLE
kubeadm configuration file in wrong place

### ISSUE THREAD

**Issue by JooyoungPark73** [kubernetes/release#3392]
#### What happened:
Before migrating to `pkgs.k8s.io`, `10-kubeadm.conf` was located in `/etc/systemd/system/kubelet.service.d`
After Migrating,  `10-kubeadm.conf` is located in `/usr/lib/systemd/system/kubelet.service.d/`

https://github.com/kubernetes/kubeadm/issues/1575
From past issue, it seems that configuration files are placed in different place between centOS and Ubuntu/Debian.
However, after the migration, it seems that the package repository does not consider specific type.

This hinders us from migrating to a new package repository.

#### What you expected to happen:
`10-kubeadm.conf` to be located in `/etc/systemd/system/kubelet.service.d`

#### How to reproduce it (as minimally and precisely as possible):
use past package repository (`https://dl.k8s.io/apt/doc/apt-key.gpg`for example) and install kubeadm, kubelet, and kubectl

#### Environment:

- Cloud provider or hardware configuration: Baremetal Server
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04 LTS
- Kernel (e.g. `uname -a`): 5.4.0-164-generic
- Others: Kubernetes 1.25.9

**Comment by JooyoungPark73** [comment]
Thank you so mucht for yourquick replye.
We use scripts that modifies the `10-kubeadm.conf` file directly, or drop in .conf  from other programs such as containerd or stargz.

**Comment by JooyoungPark73** [comment]
From `man systemd.unit`,
```
UNIT FILE LOAD PATH
       Unit files are loaded from a set of paths determined during compilation, described in the two tables below. Unit files
       found in directories listed earlier override files with the same name in directories lower in the list.

       When the variable $SYSTEMD_UNIT_PATH is set, the contents of this variable overrides the unit load path. If
       $SYSTEMD_UNIT_PATH ends with an empty component (":"), the usual unit load path will be appended to the contents of the
       variable.

       Table 1.  Load path when running in system mode (--system).
       ┌──────────────────────────────┬─────────────────────────────────────────────┐
       │Path                          │ Description                                 │
       ├──────────────────────────────┼─────────────────────────────────────────────┤
     
       ├──────────────────────────────┼─────────────────────────────────────────────┤
       │/etc/systemd/system           │ System units created by the administrator   │
       ├──────────────────────────────┼─────────────────────────────────────────────┤

       └──────────────────────────────┴─────────────────────────────────────────────┘
```

It seems the directory `/etc/systemd/system/kubelet.service.d` is more appropriate for `10-kubeadm.conf` location.

**Comment by xmudrii** [comment]
I'll investigate this.
/assign

**Comment by embik** [comment]
@JooyoungPark73 

> From `man systemd.unit`,
> 
> ```
>  [...]
>        │/etc/systemd/system           │ System units created by the administrator   │
>  [...]
> ```
> 
> It seems the directory `/etc/systemd/system/kubelet.service.d` is more appropriate for `10-kubeadm.conf` location.

As the man page says, `/etc/systemd/system` is for unit and drop-ins created by _administrators_. `10-kubeadm.conf` is however created by a _package_ (`kubeadm`). It shouldn't be modified either, as that might mess with future kubeadm upgrades. Can you elaborate on why this makes you think `/etc/systemd/system/kubelet.service.d` is the proper location? It's unfortunate that the location changed and broke some expectations, but from a pure conventions perspective, `/usr/lib/systemd/system/kubelet.service.d` is probably the correct location.

Looking at https://github.com/vhive-serverless/vHive/issues/898, it seems you are trying to set `KUBELET_EXTRA_ARGS` in a drop-in, but this is not how the `10-kubeadm.conf` drop-in is supposed to be used:

https://github.com/kubernetes/release/blob/918fdf22bd7d9cfaa2222c5d1c90219f289c34ad/cmd/krel/templates/latest/kubeadm/10-kubeadm.conf#L7-L9

Have you tried using `/etc/sysconfig/kubelet` or the kubeadm configuration to pass additional flags/configuration?

**Comment by JooyoungPark73** [comment]
@embik I thought the file location that was used prior to repository migration is a correct place, and in convention. Because If something does not work after migration, and configuration file location is changed, then I can only suspect that there was a misconfiguration in the new repo, not the legacy repo. 

If current implementation is correct, I will fix our side to fit to current implementation.

**Comment by xmudrii** [comment]
@JooyoungPark73 I would agree with @embik here. Generally speaking, `10-kubeadm.conf` shouldn't be much/at all modified by users, instead, alternatives should be used:

- [kubeadm configuration file](https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/) (preferable whenever possible), or
- `/etc/sysconfig/kubelet`

However, before closing this ticket, I would also love to hear from other Release Managers (@kubernetes/release-engineering).

**Comment by JooyoungPark73** [comment]
@xmudrii 
Thank you for your response to my issue. Yes, I understand our implementation is far from preferable usage.
We will fix this from our side.
