### ISSUE TITLE
Store release-blocking jobs in a central place for /release, /test-infra and others

### ISSUE THREAD

**Issue by david-mcmahon** [kubernetes/release#340]
The values [here](https://github.com/kubernetes/release/blob/master/lib/releaselib.sh#L104) need to be moved somewhere central so that updating names happens once and Just Works everywhere.

https://github.com/kubernetes/test-infra/blob/bdaf001/testgrid/config/config.yam looks like the canonical source, but it's also quite a bit larger than the current list.

See also: https://groups.google.com/d/msg/kubernetes-sig-release/Xme1qaOU2JI/fp0PqPsjAQAJ

**Comment by spiffxp** [comment]
I'm not sure testgrid's config should be considered the canonical source, it might just be the best thing we have today? /cc @fejta

**Comment by david-mcmahon** [comment]
@spiffxp I'm less concerned about where *the* canonical list is sourced, just that we need one, because today have significant drift between what the release process has been gating on for the last year and a half and what is currently evolving on testgrid.  No matter where we keep the config, testgrid and release both need to consume it.

**Comment by spiffxp** [comment]
Agreed, just hoping we're not talking about closing out this issue once the testgrid config is consumed.  That's a good first step but feels like tech debt.
