### ISSUE TITLE
release-notes tool creates invalid links for some dependency entries

### ISSUE THREAD

**Issue by mboersma** [kubernetes/release#3424]
#### What happened:

Using `release-notes` in a recent CAPZ release generated a number of URLs in markdown that failed link validation (404s).

#### What you expected to happen:

All links should be valid.

##### Examples:

https://github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/internal/tree/v1.1.2
should have been 
https://github.com/Azure/azure-sdk-for-go/tree/sdk/resourcemanager/internal/v1.1.2
The `/tree` segment was mistakenly added right before `/<version>`.
 
https://github.com/nats-io/jwt/v2/tree/v2.4.1
should have been
https://github.com/nats-io/jwt/tree/v2.4.1
The `/v2` section was mistakenly added.

#### Environment:

- release-notes version: v0.12.0 as well as v0.16.4.

**Comment by cpanato** [comment]
thanks for the report @mboersma can you also add the command that you ran? then we can reproduce the issue

thanks!

**Comment by mboersma** [comment]
I don't yet have a simple repro for this, but I'll try to create one. For now, one way to do it is:

- clone the CAPZ repo (https://github.com/kubernetes-sigs/cluster-api-provider-azure)
- run `make release-notes`, which should create a diff that contains bad links
- The specific command run in this case is:

    ```
    ./hack/tools/bin/release-notes-v0.16.4 \
    --org kubernetes-sigs \
    --repo cluster-api-provider-azure \
    --branch main \
    --repo-path $PWD \
    --start-sha 7ee3a6a063edd5c1a599e4b21e407fb0f05e74e4 \
    --end-sha 721d85b7e6a119e319c0497b12a0326c08ae50b2 \
    --markdown-links true 
    --output CHANGELOG/v1.13.0.md \
    --list-v2
    ```

**Comment by willie-yao** [comment]
I'm working on adding dependencies to the Cluster API release notes tool and faced the same issue. Looks like the issue lies within [`go-modiff`](https://github.com/saschagrunert/go-modiff). I was able to reproduce this issue by running `go-modiff -r github.com/kubernetes-sigs/cluster-api -f v1.3.9 -t v1.3.10 -l`. I think the `-l` link flag is broken and I'll see if I can work on a fix.

**Comment by saschagrunert** [comment]
@willie-yao thank you! Feel free to keep us posted if there is anything we can do for support.

**Comment by willie-yao** [comment]
@saschagrunert Of course! I opened a PR here for a fix. Let me know what you think!

https://github.com/saschagrunert/go-modiff/pull/171
