### ISSUE TITLE
[question] about how to build images locally

### ISSUE THREAD

**Issue by zijin520** [kubernetes/release#3436]
#### What happened:
I am confused about how to build the docker images(go-runner, distroless-iptables, cross. etc.) locally from this README, Is there any document detailed? Thanks.

#### Environment:

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by saschagrunert** [comment]
Hey @zijin520, thank you for the request.

For go-runner as example, you can run:

```
> make -C images/build/go-runner container REGISTRY=localhost PLATFORMS=linux/amd64
```

The resulting images are then prefixed with `localhost/`:

```
> docker images | rg localhost
localhost/go-runner-amd64   latest-go1.21-bookworm                        6f992eb02a23   7 seconds ago   3.6MB
localhost/go-runner-amd64   v0.16.4-117-g06d3d14b-dirty-go1.21-bookworm   6f992eb02a23   7 seconds ago   3.6MB
localhost/go-runner-amd64   v2.3.1-go1.21.6-bookworm.0                    6f992eb02a23   7 seconds ago   3.6MB
```

**Comment by zijin520** [comment]
> Hey @zijin520, thank you for the request.
> 
> For go-runner as example, you can run:
> 
> ```
> > make -C images/build/go-runner container REGISTRY=localhost PLATFORMS=linux/amd64
> ```
> 
> The resulting images are then prefixed with `localhost/`:
> 
> ```
> > docker images | rg localhost
> localhost/go-runner-amd64   latest-go1.21-bookworm                        6f992eb02a23   7 seconds ago   3.6MB
> localhost/go-runner-amd64   v0.16.4-117-g06d3d14b-dirty-go1.21-bookworm   6f992eb02a23   7 seconds ago   3.6MB
> localhost/go-runner-amd64   v2.3.1-go1.21.6-bookworm.0                    6f992eb02a23   7 seconds ago   3.6MB
> ```

Thanks very much. It is very useful .
