### ISSUE TITLE
Automating `krel` binary releases

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/release#3473]
A few months ago, we switched away from building krel in GCB to pulling the latest release from GH/GCS. With that, all releases that we cut are using krel v0.16.4 which is from November 15. This doesn't include many changes that we did since then.

The goal is to automate krel binary releases to always use the latest and greatest set of features.

**Comment by puerco** [comment]
there are now [binaries in the releases](https://github.com/kubernetes/release/releases/tag/v0.16.5), should we close this one?

**Comment by cpanato** [comment]
yes and i will check if everything is good and cut a new release

/close
