### ISSUE TITLE
Break Release Notes Down By Sig

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/release#348]
The release team's goal was to achieve better visibility into the 1.7 release by:

Enforcing that all issues in the milestone have sig/ labels
Enforcing that all non-trivial PRs in the milestone have associated issues
As a result, we should be able to guarantee that all PRs are associated with a sig (not actually true since these policies started around code freeze), but can we try to generate release notes such that they are broken down by sig.

cc @dchen1107 @marun @spiffxp

**Comment by david-mcmahon** [comment]
Yes, release notes are currently organized by the different release-note-* labels.  There's no reason the notes cannot be further organized by additional (sig) labels.  And you can continue to sort them into the higher level general/action-required with sig sub groupings or however you like.

**Comment by david-mcmahon** [comment]
cc @roycaihw, @enisoc @jdumars
