### ISSUE TITLE
krel/templates: remove kubeadm's dependencies on kubelet and kubectl

### ISSUE THREAD

**Issue by neolit123** [kubernetes/release#3480]
#### What would you like to be added:

we should remove kubeadm's dependencies on kubelet and kubectl:
- kubeadm - only cri-tools (needed for crictl)
- kubelet - kuberentes-cni, iptables, other
- kubectl - no dependencies

xref https://github.com/kubernetes/website/issues/45393#issuecomment-1972924171
https://github.com/kubernetes/release/blob/master/cmd/krel/templates/latest/metadata.yaml

#### Why is this needed:

today users of kubeadm must update packages in a sequence, kubeadm first, then kubelet. if kubeadm depends on the kubelet this means they need to hold the kubelet package so that it's not upgraded.
the kubeadm upgrade sequence requires that we upgrade kubelet later.

the kubectl direct dependency is redundant, since kubeadm has its own client.

https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

example user report ticket related to the hold issue in docs:
https://github.com/kubernetes/website/issues/45393

the new package repo layout allows us to apply this change for 1.30.
please LMK if i can send a PR.

**Comment by neolit123** [comment]
cc @SataQiu @pacoxu FYI

**Comment by saschagrunert** [comment]
Sounds good to me. 

/cc @kubernetes/release-engineering

**Comment by xmudrii** [comment]
+1, I agree with the proposed change. The dependencies were mirrored from the legacy packages, but now that we have a much better control over repositories, it makes sense to change this.

> the new package repo layout allows us to apply this change for 1.30.

Technically, we can do it for all supported releases (v1.29, v1.28, v1.27) if we want. We would have to double check if there are any negative implications, but I think that shouldn't be the case.

**Comment by neolit123** [comment]
> Technically, we can do it for all supported releases (v1.29, v1.28, v1.27) if we want. We would have to double check if there are any negative implications, but I think that shouldn't be the case.

perhaps it's safer to update only the new release 1.30 as a first target.
i can send the PR for that in a bit.

i recall in the past, making a dependency update broke users who did PATCH level updates, but that may have been resolved with the switch to the new package repo layout.

**Comment by neolit123** [comment]
PR is here
https://github.com/kubernetes/release/pull/3481

**Comment by jhannink** [comment]
Wow, thanks for the super-fast change guys :)

**Comment by pacoxu** [comment]
late +1
