### ISSUE TITLE
E: The repository 'https://apt.kubernetes.io kubernetes-xenial Release' does not have a Release file.

### ISSUE THREAD

**Issue by 403-html** [kubernetes/release#3484]
#### What happened:

We get on downloading github cli the error "E: The repository 'https://apt.kubernetes.io/ kubernetes-xenial Release' does not have a Release file."

#### What you expected to happen:
No error

#### How to reproduce it (as minimally and precisely as possible):

```sh
type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
  curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
  && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
  && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
  && sudo apt update \
  && sudo apt install gh -y
```

#### Environment:

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others: It's GHA so Linux's runner

**Comment by saschagrunert** [comment]
Hey @403-html, sorry but we do not maintain the packages hosted on cli.github.com here. I also assume that we do not support Ubuntu 16.04 (xenial) any more because it got EOL in 2021.

**Comment by xmudrii** [comment]
This has nothing to do with the GitHub repos. The legacy Kubernetes package repositories (`apt.kubernetes.io`, `yum.kubernetes.io`, aka `packages.cloud.google.com`) have been removed over the weekend and your system is trying to pull from these repositories. You need to migrate to the official Kubernetes package repositories as described here: https://kubernetes.io/blog/2023/08/31/legacy-package-repository-deprecation/

/close
