### ISSUE TITLE
few days ago the old repo has been turned off and now trying to use the new repo https://pkgs.k8s.io/core:/stable:/ fails for specific version

### ISSUE THREAD

**Issue by mkocaks** [kubernetes/release#3490]
I am trying to regain access to the k8s packages for 1.26.6 can anyone explain how this can be achieved  ?
Its not clearly described here at all
https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/#how-to-migrate

The old way that has stopped working few days ago I used to use is:

curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
sudo apt update && sudo apt upgrade -y

... some other bits like cri sockets etc... then

sudo apt install -y kubelet=1.26.6-0.0 kubeadm=1.26.6-0.0 kubectl=1.26.6-0.0
sudo apt-mark hold kubelet kubeadm kubectl

**Comment by mkocaks** [comment]
i.e. ??

https://[prod-cdn.packages.k8s.io/repositories/isv:/kubernetes:/core:/stable:/v1.26.6-0.0/deb/Release.key](https://prod-cdn.packages.k8s.io/repositories/isv:/kubernetes:/core:/stable:/v1.26.6-0.0/deb/Release.key)

**Comment by mkocaks** [comment]
Now the examples fail ?

echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
sudo apt update && sudo apt upgrade -y
deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /
gpg: can't create '/etc/apt/keyrings/kubernetes-apt-keyring.gpg': No such file or directory
gpg: no valid OpenPGP data found.
gpg: dearmoring failed: No such file or directory
(23) Failed writing body
Hit:1 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Hit:4 http://security.debian.org/debian-security bullseye-security InRelease
Get:5 https://prod-cdn.packages.k8s.io/repositories/isv:/kubernetes:/core:/stable:/v1.28/deb  InRelease [1,189 B]
Err:5 https://prod-cdn.packages.k8s.io/repositories/isv:/kubernetes:/core:/stable:/v1.28/deb  InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 234654DA9A296436
Reading package lists... Done
W: GPG error: https://prod-cdn.packages.k8s.io/repositories/isv:/kubernetes:/core:/stable:/v1.28/deb  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 234654DA9A296436
E: The repository 'https://pkgs.k8s.io/core:/stable:/v1.28/deb  InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by mkocaks** [comment]
Obviously this is fine but how do I flag for a specific patch verison i.e. patch .6 ?

echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.26/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.26/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
sudo apt update && sudo apt upgrade -y

**Comment by neolit123** [comment]
follow the steps here
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl

then to install a particular patch you can patch of a component you can do:
```
apt-get install -y kubelet='1.29.2-*'
```

**Comment by mkocaks** [comment]
darn it. thanks!!! I was doing apt install rather than get and install....
Thank you!!
