### ISSUE TITLE
How to upgrade 1.21 clusters 

### ISSUE THREAD

**Issue by bjolivot** [kubernetes/release#3493]
Hello !
It seems that only >=1.24 version are available on the new repositories.
How to deal with older cluster upgrade ?

Is there some archive repository ?
Can i upgrade from 1.21.x to 1.24.x without applying 1.22 and 1.23 ?

I use kubeadm, on ubuntu >=20.04

Thank you !

**Comment by neolit123** [comment]
> Hello ! It seems that only >=1.24 version are available on the new repositories. How to deal with older cluster upgrade ?
> 
> Is there some archive repository ? Can i upgrade from 1.21.x to 1.24.x without applying 1.22 and 1.23 ?
> 

are the old packages complete gone?
MINOR versions must not be skipped during upgrade - this is not a kubeadm limitation but a general k8s limitation.

**Comment by bjolivot** [comment]
@neolit123 
Thank you for the install without package manager !

And yes, old packages are gone, dangerous behavior imho, 
can't wait to see fake archive repo with malware inside

**Comment by neolit123** [comment]
> And yes, old packages are gone, dangerous behavior imho,
can't wait to see fake archive repo with malware inside

you can log a new ticket in this repository and describe the potential attack vectors.
then our SIG Security group can also take a look.

/close
