### ISSUE TITLE
new kubernetes el7 repo ?

### ISSUE THREAD

**Issue by krodger5759** [kubernetes/release#3500]
Hi, So what exactly is the new url for what used to be: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
I cant seem to find the new url ? I have that repository built in to Redhat satellite server. It does not work anymore, thanks.

**Comment by krodger5759** [comment]
Thanks all, however these blogs are not helping, I understand what they did, but I need the exact url. Normally it will index the file system with pkgs, etc that you can see. the link for pkgs.k8s,io does not work for me. The link "https://pkgs.k8s.io/core:/stable:/v1.28/rpm/repodata/repomd.xml.key" just brings me to the kubernetes partners page. I need the actual index of pkgs page. Thanks.

**Comment by xmudrii** [comment]
Can you please be more specific about what page/error do you see? Can you share the text or a screenshot of that page? Otherwise, we can't help much. The URL is valid and there's no index page available at the moment, see https://github.com/kubernetes/release/issues/3317 for more details

**Comment by krodger5759** [comment]
thanks, here is an example of the url for the epel7 repo,"https://dl.fedoraproject.org/pub/epel/7/x86_64/" , 
this is just an example of what I'm looking for: see attached screenshot .
<img width="280" alt="Capture" src="https://github.com/kubernetes/release/assets/60623236/2f2cea40-eb2c-4d2e-8294-882d1e9f75fc">

now, when I use the link "https://pkgs.k8s.io" I only see the kubernetes partners page, or when I use this link "https://pkgs.k8s.io/core:/stable:/v1.28/rpm/repodata/repomd.xml.key" I get the same page, please see other attached file. And again, thanks for your help.
<img width="756" alt="Capture1" src="https://github.com/kubernetes/release/assets/60623236/c4ab7401-aeba-4b43-9d3a-a19620b3e7af">

Thanks again. Hope you can see these images.

**Comment by xmudrii** [comment]
The file browser (repository index) is something that we're working on, but we don't have any ETA at the moment. Speaking of your issue, it's really hard to debug it without any additional context. What operating system are you using? If you're using Linux or macOS, can you try something like this:

```shell
curl -o /dev/null -vvv https://pkgs.k8s.io/core:/stable:/v1.28/rpm/repodata/repomd.xml.key
```

The output is a bit longer but it should show what's exactly happening. We never redirect to the partners page, so this is likely something related to your browser/DNS/network configuration, but let's double check to be sure.

**Comment by krodger5759** [comment]
its linux, but that doesn't matter in this case. Here is the picture from the satellite server. All I have to do is put in the url.:
![image](https://github.com/kubernetes/release/assets/60623236/245d18ce-3aba-4509-abb1-c59f8b8b8d61)

**Comment by krodger5759** [comment]
when I run the curl command, everything connects and look ok, but it says "no content" :
![image](https://github.com/kubernetes/release/assets/60623236/0a5da38f-7232-4508-bec4-c02e2b05085f)

**Comment by xmudrii** [comment]
Please share the complete logs. From your screenshot, we can't tell where are you getting redirected. You can also run the `curl` command with `-L` to follow redirects and share that output.

**Comment by krodger5759** [comment]
ok, attached is the whole file and with the -L option also.
[curl-out.txt](https://github.com/kubernetes/release/files/14573397/curl-out.txt)

**Comment by xmudrii** [comment]
I looked into your logs but I don't see anything outstanding. I recommend taking it further with your vendor (given that you use the Red Hat Satellite server). We in general don't provide support for the Kubernetes releases that have reached the end of life.
