### ISSUE TITLE
Release Notes Collection Picks Up Incorrect Text 

### ISSUE THREAD

**Issue by npolshakova** [kubernetes/release#3516]
#### What happened:

Release notes collection automation has resulted in incorrect text and markdown being collected: https://github.com/kubernetes/sig-release/pull/2449#discussion_r1521495247

You can see examples of this merged in sig-release for 1.30 due to past release notes collection:
- [PR 123082](https://github.com/kubernetes/kubernetes/pull/123082) 
- [PR 121413](https://github.com/kubernetes/kubernetes/pull/121413)
- [PR 122893](https://github.com/kubernetes/kubernetes/pull/122893)

Updated examples from 1.29 that are still in the repo after 1.30 was cleaned up:
- https://github.com/kubernetes/kubernetes/pull/119394, release notes [here](https://github.com/kubernetes/sig-release/blob/master/releases/release-1.29/release-notes/release-notes-draft.json#L1265). 

#### What you expected to happen:

This release note should not be collected since it is empty: 

```
 "123082": {
    "commit": "d29f38efd83f5dcf18870c8772b9a0bb68c56097",
    "text": "```\n\n#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:\n\n\u003c!--\nThis section can be blank if this pull request does not require a release note.\n\nWhen adding links which point to resources within git repositories, like\nKEPs or supporting documentation, please reference a specific commit and avoid\nlinking directly to the master branch. This ensures that links reference a\nspecific point in time, rather than a document that may change over time.\n\nSee here for guidance on getting permanent links to files: https://help.github.com/en/articles/getting-permanent-links-to-files\n\nPlease use the following format for linking documentation:\n- [KEP]: \u003clink\u003e\n- [Usage]: \u003clink\u003e\n- [Other doc]: \u003clink\u003e\n--\u003e",
    "markdown": "```\n  \n  #### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:\n  \n  \u003c!--\n  This section can be blank if this pull request does not require a release note.\n  \n  When adding links which point to resources within git repositories, like\n  KEPs or supporting documentation, please reference a specific commit and avoid\n  linking directly to the master branch. This ensures that links reference a\n  specific point in time, rather than a document that may change over time.\n  \n  See here for guidance on getting permanent links to files: https://help.github.com/en/articles/getting-permanent-links-to-files\n  \n  Please use the following format for linking documentation:\n  - [KEP]: \u003clink\u003e\n  - [Usage]: \u003clink\u003e\n  - [Other doc]: \u003clink\u003e\n  --\u003e ([#123082](https://github.com/kubernetes/kubernetes/pull/123082), [@alexzielenski](https://github.com/alexzielenski)) [SIG API Machinery and Testing]",
    "author": "alexzielenski",
    "author_url": "https://github.com/alexzielenski",
    "pr_url": "https://github.com/kubernetes/kubernetes/pull/123082",
    "pr_number": 123082,
    "areas": [
      "test"
    ],
    "kinds": [
      "flake"
    ],
    "sigs": [
      "api-machinery",
      "testing"
    ],
    "duplicate": true,
    "do_not_publish": true
  },
```

**Comment by saschagrunert** [comment]
@npolshakova thank you for the bug report, are you considering to work on a fix?

**Comment by npolshakova** [comment]
> @npolshakova thank you for the bug report, are you considering to work on a fix?

I'd be interested, but I'm not super familiar with the code that does the release notes collection. Do you think this is an issue on the krel side [here](https://github.com/kubernetes/release/blob/master/pkg/notes/notes.go#L242)?

**Comment by saschagrunert** [comment]
@npolshakova I assume it's part of the release notes gathering logic of this repository. We just need a reproducer to see what we can fix.

**Comment by npolshakova** [comment]
I think the issue is in the regex in the exclude filter: https://github.com/kubernetes/release/pull/3523/files I'm able to reproduce it, but still need a fix for the regex.

**Comment by saschagrunert** [comment]
@npolshakova are you still working on this? 

/remove-lifecycle stale

**Comment by npolshakova** [comment]
> @npolshakova are you still working on this?
> 
> /remove-lifecycle stale

Yep, my team is looking into this still. It looks like the last release notes PR didn't run into this issue though!
