### ISSUE TITLE
branchff should disallow fast-forward release-1.x if tag 1.(x+1).0.alpha.1 exists

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/release#353]
Not sure if the description is accurate.
I don't know why the 1.8.0.alpha.0 doesn't cause the same problem. Is it because we have 1.7.0.beta.0 right after we made 1.8.0.alpha.0, so that the latest tag is still 1.7.0.beta.0?

**Comment by dchen1107** [comment]
@kubernetes/kubernetes-release-managers
