### ISSUE TITLE
Refactor `pkg/announce` package to adhere to the interfaces pattern

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/release#3565]
We follow the pattern of using interfaces to provide an option to mock parts of the implementation, e.g. see https://github.com/kubernetes/release/blob/a00489762c923fe58d7e02ea67e06c54123594e6/pkg/release/archive.go

The [`pkg/announce` package](https://github.com/kubernetes/release/tree/a00489762c923fe58d7e02ea67e06c54123594e6/pkg/announce) doesn't follow this pattern at the moment and it's hard to write tests for it. We would like to have that tests for this package to make it easier to accept changes such as #3559 

To make writing tests possible, we should refactor the package to adhere to the "interfaces pattern" that we use in other packages. This issue assumes only refactoring the package, writing tests is the second step once the package is successfully refactored.

From the high level overview, we need the following:

- `Announce` struct that contains `announceOptions` and `announceImpl`
- `announceOptions` struct that contains options and parameters for relevant functions
- `announceImpl` interface that contains functions that should be mocked in testing (e.g. reading files...)
- functions should be refactored to be have `Announce` or `announceImpl` as a receiver (e.g. `func (a Announce) ...` or `func (impl announceImpl) ...`)

**Comment by embik** [comment]
I'd be interested in working on this.

**Comment by xmudrii** [comment]
Thank you! I'll assign the issue to you
/assign @embik
