### ISSUE TITLE
Cannot upgrade kubeadm to 1.30.0 via apt

### ISSUE THREAD

**Issue by martinwang2002** [kubernetes/release#3574]
### What happened?

Kubeadm cannot upgrade to version 1.30.0 because cri-tools is at 1.29.0

```
sudo apt upgrade kubeadm
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kubeadm : Depends: cri-tools (>= 1.30.0) but 1.29.0-1.1 is to be installed
E: Broken packages
```

### What did you expect to happen?

Maybe a release of cri-tools 1.30.0

### How can we reproduce it (as minimally and precisely as possible)?

1. change version in apt sources `/etc/apt/sources.list.d/kubernetes.list`
```
deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /
```
2. run apt update
```
sudo apt-mark unhold kubeadm && \
sudo apt-get update && sudo apt-get install -y kubeadm='1.30.x-*' && \
sudo apt-mark hold kubeadm
```

### Kubernetes version

<details>

```console
$ kubectl version
kubectl version
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux instance 5.15.0-102-generic kubernetes/kubernetes#112-Ubuntu SMP Tue Mar 5 16:49:56 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
kubeadm 1.30 depends on cri-tools 1.30
https://github.com/kubernetes/release/blob/master/cmd/krel/templates/latest/metadata.yaml#L72-L76

can you show the list of dependencies of kubeadm 1.30:
https://askubuntu.com/questions/128524/how-to-list-dependent-packages-reverse-dependencies

manually installing cri-tools 1.30 should fix it but we better understand why this happens
https://askubuntu.com/a/606896

**Comment by saschagrunert** [comment]
We're planning to release cri-tools soon: https://github.com/kubernetes-sigs/cri-tools/issues/1402

**Comment by afbjorklund** [comment]
How did this work with the RC packages, wouldn't they also have been blocked ?

**Comment by xmudrii** [comment]
@afbjorklund RC (and alpha and beta) packages are using a dedicated prerelease repo that had both cri-tools and kubernetes-cni packages published at the start of the release cycle. However, we push those two packages at the end of the release cycle to the stable repo as that's the point when we know for sure what package versions we exactly need.

**Comment by afbjorklund** [comment]
I was able to install the cluster before by force-installing the old cri-tools 1.29.0-1.1 from the v1.29 package track.

And was able to upgrade it now, with the new version from v1.30. That also gets rid of the dockershim warning:

`ERRO[0000] validate service connection: validate CRI v1 runtime API for endpoint "unix:///var/run/dockershim.sock": rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial unix /var/run/dockershim.sock: connect: no such file or directory" `

Which was the feature I was looking for, in the new cri-tools (otherwise k8s 1.30 seemed to be happy with CRI 1.29)

**Comment by afbjorklund** [comment]
The versions in the [documentation](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl) are still not updated, but (unfortunately) that is handled separately.

`CNI_PLUGINS_VERSION="v1.3.0"`

`CRICTL_VERSION="v1.28.0"`

* https://github.com/kubernetes/website/issues/40655

**Comment by martinwang2002** [comment]
This is now resolved.
