### ISSUE TITLE
anago: Push deb/rpm packages as part of the release process

### ISSUE THREAD

**Issue by jimmycuadra** [kubernetes/release#358]
/etc/apt/sources.list.d/kubernetes.list:

```
deb http://apt.kubernetes.io/ kubernetes-xenial main
```

In a shell:

```
$ sudo apt-get update
$ sudo apt-get install kubelet
Reading package lists... Done
Building dependency tree
Reading state information... Done
kubelet is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
$ kubelet --version
Kubernetes v1.6.6
```

It seems that has happened with previous releases: https://github.com/kubernetes/release/issues/263. This should be added to a release checklist, or ideally, automated.

**Comment by praseodym** [comment]
v1.7.0 packages are now available: https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/binary-amd64/Packages

**Comment by jimmycuadra** [comment]
There still seems to be a problem with the repositories getting updated when a new Kubernetes release is made. v1.7.2 was released 2 days ago but the apt repo still has only v1.7.1.

**Comment by jimmycuadra** [comment]
Any update on getting this part of the release process fixed? 1.8 has been released by the apt repo isn't updated.

**Comment by luxas** [comment]
This will be done very soon, I hope you understand @jimmycuadra that after a 14+ hour day for most of us (and unexpected problems with the pushing process), this part was deferred a couple of hours to today. Will be done in the coming hours.

If you want to dig into the releasing scripts in this repo, feel free to, this is open source :wink:

cc @jdumars

**Comment by luxas** [comment]
This is now done, both debs and rpms are pushed.

**Comment by jimmycuadra** [comment]
I apologize that my tone made this issue sound demanding—that's not what I intended. I just wanted to track the fact that updates to the apt repo are not currently automated or tied to the release process of the binaries, so there is no way for people installing/updating k8s through the apt repo to know when it's actually ready besides just trying and seeing if an update is found.

I think this issue should be reopened to track the fact that this is still the case in general (I changed the title to make it clear that it's not about a specific k8s version being released.) I appreciate that the repo is open source and anyone can work on fixing this. I think there is still value in the issue being open so folks interested in contributing can see that it's something to be addressed. In other words, this can be used as a tracking issue, separate from a PR implementing improvements.

**Comment by luxas** [comment]
ok, I can reopen this then. I think @timothysc is planning to do this for v1.8, right?

**Comment by jdumars** [comment]
@jimmycuadra , I wasn't at all concerned about tone or anything.  This is a very important part of the release process, and has been something that's slipped off the radar many times.  As @luxas said, @timothysc has generously offered to look into the effort required to get this done.  So, we basically have a dream team of engineering solving this now.  How cool is that?

**Comment by praseodym** [comment]
I'm not seeing deb packages for v1.7.6 and v1.7.7. It would be great if these could be released as well!

Also, because Docker versions 1.12.6, 1.13.1, and 17.03.2 are newly validated for Kubernetes 1.8, maybe these versions could be added to the apt repository? Currently only docker-engine 1.11.2 is available there.

**Comment by colemickens** [comment]
Not to keep piling on (this is something I'd like to circle back on eventually and help with as well), but `kubernetes-cni` is alos behind the releases from the containernetworking plugins repository. Not sure if it's supposed to be updated as there are new CNI releases. Also, not sure if releases for CNI are managed through this repo, but I'm assuming `kubernetes-cni` package issues go here at least.

**Comment by luxas** [comment]
@colemickens CNI releases are tied to a specific k8s release. We're bumping the CNI version in v1.9 to v0.6: https://github.com/kubernetes/kubernetes/pull/51250#issuecomment-336502529

**Comment by timothysc** [comment]
@luxas lets enqueue this for @kubernetes/sig-cluster-lifecycle-feature-requests next week.

**Comment by jdumars** [comment]
re-opening per @colemickens

**Comment by luxas** [comment]
Let's track this only in one place. This is a duplicate of https://github.com/kubernetes/sig-release/issues/10, where I think the release team actually tracks issues to be fixed these days. Correct me if I'm wrong @jdumars
