### ISSUE TITLE
anago should give user a second chance to run prodaccess

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/release#361]
[Sending mail](https://github.com/kubernetes/release/blob/master/anago#L1091) requires that the user has run prodaccess. Although anago checks for the prerequisites at the beginning of the script, prodaccess could have expired when anago reaches the sending mail step. Instead of exiting, anago could ask user to run prodaccess and retry.

Alternatively, if anago records all the global variables in a file before exiting, it will be easy to fix the problem and continue from the exiting point.

@david-mcmahon could you help take a look?

**Comment by david-mcmahon** [comment]
Requirement for this is going away / mitigated by the upcoming 'release from GCB' effort.
