### ISSUE TITLE
New branches should be protected and restricted

### ISSUE THREAD

**Issue by enisoc** [kubernetes/release#364]
As a policy, we set release branches as "protected" (can't be force-pushed or deleted) and "restricted" (only repo admins can push to it, not all repo writers).

It would be nice to have some automation for this at the time when the branch is created, although I don't know if the GitHub API makes that easy. We often forget to do this for a while - for example I just now applied protection to `release-1.7`, and `release-1.6` has been protected but not restricted all this time.

**Comment by spiffxp** [comment]
I think the API gives us the event we'd need to find out the branch was created, and write access to what we'd need to protect the branch
- https://developer.github.com/v3/activity/events/types/#createevent
- https://developer.github.com/v3/repos/branches/#update-branch-protection

Could probably be done as a prow plugin

**Comment by david-mcmahon** [comment]
cc @abgworrall

**Comment by kargakis** [comment]
/remove-help

@fejta is already soaking a branchprotector job in test-infra.

**Comment by spiffxp** [comment]
/close
We [now do this for all branches](https://github.com/kubernetes/test-infra/blob/master/prow/config.yaml#L100-L103) using prow's [branchprotector](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/branchprotector) cmd
