### ISSUE TITLE
 anago should push debs/rpms

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/release#365]
These two scripts might do the job, we should include them in anago.

https://github.com/kubernetes/release/blob/master/debian/jenkins.sh
https://github.com/kubernetes/release/blob/master/rpm/entry.sh

cc @mikedanese

**Comment by david-mcmahon** [comment]
@mikedanese is this something we can/should do at this point?  It seems this has been separate as we worked out the kinks, but it should be mature enough to include in-line in the standard release workflow now, yes?

**Comment by caesarxuchao** [comment]
Those scripts build the packages, but we rely on an internal tool `rapture` to publish the packages.

**Comment by david-mcmahon** [comment]
Regardless of the publishing mechanism, It looks like  there are a number of prepublishing steps, mostly manual, sometimes delayed.  Everything up to the publish button like updating version numbers can/should be done in the workflow automation.  Because, why not?   Where best to track those steps/actions?

**Comment by mikedanese** [comment]
@david-mcmahon those manual steps go away when we can switch fully to bazel:

https://github.com/kubernetes/kubernetes/blob/master/build/debs/BUILD

We are lacking cross platform support which should land in a month or two

**Comment by david-mcmahon** [comment]
Ah, ok thanks for the explanation.  Just wanting to make sure we're tracking this initiative (integrating deb build/deploy to standard workflow) somewhere.

**Comment by ixdy** [comment]
note that I don't expect to switch fully to bazel before k8s 1.9.
