### ISSUE TITLE
Get rid of `kubernetes-release/archive`

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/release#3716]
The archives are inherited from anago times, for example: https://console.cloud.google.com/storage/browser/kubernetes-release/archive/anago-v1.31.0

They mainly contain:
- the build logs (available using GCB)
- the announcement (can be moved over to `kubernetes-release/release/v1.31.0`)
- the release notes html and JSON (not used, because already part of `kubernetes-release/release/v1.31.0`)
- the archive k8s.io.tar.gz (probably not needed)

The idea is to move the announcement into the release artifacts (`release/v1.y.z`) directory and completely avoid collecting the archive. All of that can be done in krel.

cc @kubernetes/release-engineering

**Comment by ameukam** [comment]
We should drop the archive `k8s.io.tar.gz` and the release logs to begin with.

**Comment by BenTheElder** [comment]
> the build logs (available using GCB)

I do think this should probably be published publicly? We have a build process that is not fully reproducible.

**Comment by saschagrunert** [comment]
> > the build logs (available using GCB)
> 
> I do think this should probably be published publicly? We have a build process that is not fully reproducible.

Funnily we just publish the `release` logs right now, but not the `stage` ones. I think we have to follow-up on that. I'm not sure what the best way is to deal with them.
