### ISSUE TITLE
[Failing Test] ci-fast-forward 

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/release#3789]
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-fast-forward?buildId=1835200253544894464

Failure message: 

> level=fatal msg="run GCB job: error running /google-cloud-sdk/bin/gcloud builds submit --verbosity info --config /tmp/k-release-782178283/gcb/fast-forward/cloudbuild.yaml --substitutions _LOG_LEVEL=info,_TOOL_ORG=kubernetes,_TOOL_REF=master,_RELEASE_BRANCH=,_NOMOCK_TAG=nomock,_NOMOCK=--nomock,_GCP_USER_TAG=gcb-builder-at-k8s-infra-prow-build-trusted-iam-gserviceaccount-com,_TYPE=,_TYPE_TAG=,_KUBE_CROSS_VERSION=v1.32.0-go1.23.0-bullseye.0,_TOOL_REPO=release,_K8S_ORG=kubernetes,_K8S_REF=HEAD,_K8S_REPO=kubernetes,_GIT_TAG=v0.17.7-14-g7e38e89b-20240913 --project k8s-staging-releng-test --gcs-log-dir gs://k8s-staging-releng-test-gcb/logs --gcs-source-staging-dir gs://k8s-staging-releng-test-gcb/source --no-source --disk-size=500: command /google-cloud-sdk/bin/gcloud builds submit --verbosity info --config /tmp/k-release-782178283/gcb/fast-forward/cloudbuild.yaml --substitutions _LOG_LEVEL=info,_TOOL_ORG=kubernetes,_TOOL_REF=master,_RELEASE_BRANCH=,_NOMOCK_TAG=nomock,_NOMOCK=--nomock,_GCP_USER_TAG=gcb-builder-at-k8s-infra-prow-build-trusted-iam-gserviceaccount-com,_TYPE=,_TYPE_TAG=,_KUBE_CROSS_VERSION=v1.32.0-go1.23.0-bullseye.0,_TOOL_REPO=release,_K8S_ORG=kubernetes,_K8S_REF=HEAD,_K8S_REPO=kubernetes,_GIT_TAG=v0.17.7-14-g7e38e89b-20240913 --project k8s-staging-releng-test --gcs-log-dir gs://k8s-staging-releng-test-gcb/logs --gcs-source-staging-dir gs://k8s-staging-releng-test-gcb/source --no-source --disk-size=500 did not succeed: ERROR: (gcloud.builds.submit) INVALID_ARGUMENT: generic::invalid_argument: key in the template \"_FORCE_BUILD_KREL\" is not matched in the substitution data; substitutions = map[_GCP_USER_TAG:gcb-builder-at-k8s-infra-prow-build-trusted-iam-gserviceaccount-com _GIT_TAG:v0.17.7-14-g7e38e89b-20240913 _K8S_ORG:kubernetes _K8S_REF:HEAD _K8S_REPO:kubernetes _KUBE_CROSS_VERSION:v1.32.0-go1.23.0-bullseye.0 _LOG_LEVEL:info _NOMOCK:--nomock _NOMOCK_TAG:nomock _RELEASE_BRANCH: _TOOL_ORG:kubernetes _TOOL_REF:master _TOOL_REPO:release _TYPE: _TYPE_TAG:]\n"

https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-fast-forward/1834656414711156736/

The test started to fail after https://github.com/kubernetes/release/pull/3760 was merged.
/cc @saschagrunert @cpanato

**Comment by pacoxu** [comment]
The test grid: https://testgrid.k8s.io/sig-release-releng-blocking#git-repo-kubernetes-fast-forward

**Comment by saschagrunert** [comment]
I assume we need a newer `gcr.io/k8s-staging-releng/k8s-ci-builder:latest-default` image which is broken right now. It should be fixed after https://github.com/kubernetes/release/pull/3781

**Comment by saschagrunert** [comment]
Tests are green again: https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-fast-forward :green_circle:
