### ISSUE TITLE
./relnotes script has hidden assumption that "upstream repo" is called "origin"

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/release#380]
I couldn't make the ./relnotes script work in my environment successfully due to the assumption that the "upstream" repo is called origin.

So I finally changed the script as following:
```
-  range="$start_tag..${release_tag:-$branch_head}"
+  range="$start_tag..upstream/${release_tag:-$branch_head}"
```

and it started working for me.

We should get rid of this assumption and make it possible to e.g. configure it with flag or sth like that.

**Comment by david-mcmahon** [comment]
Is there a way we can dynamically set the upstream remote in this case?  `relnotes` is used from different types of repo clones (forks, etc) with different remotes.  It'd be great to find a way to make this Just Work vs. more flags.

**Comment by wojtek-t** [comment]
Maybe some kind of "git remove -v" + grep ?

**Comment by ixdy** [comment]
You can steal [this function](https://github.com/kubernetes/kubernetes/blob/d20414e2b639ef1188e36722381f7719c6e28077/hack/lib/util.sh#L431-L437) from `kubernetes/hack/lib`.
