### ISSUE TITLE
Update kubeadm.conf for k8s >= 1.8

### ISSUE THREAD

**Issue by pipejakob** [kubernetes/release#391]
There was a [PR](https://github.com/kubernetes/release/pull/386) to update this repository's `kubeadm.conf` to match the copy used by bazel builds in the [kubernetes repo](https://github.com/kubernetes/kubernetes/blob/898b1b333068430edfa29b6f7b17dbab458c1846/build/debs/kubeadm-10.conf). Unfortunately, this commit needed to be rolled back because its changes should only apply to Kubernetes versions >= 1.8, and a release of 1.7.3 erroneously included the change.

Since the `release` repository doesn't follow the same branching scheme as the main `kubernetes` repository, this logic might need to live in the [debian](https://github.com/kubernetes/release/blob/17849e6a6c6f206a68f1a33e6c2e7d71bee6564a/debian/build.go)/[rpm](https://github.com/kubernetes/release/blob/17849e6a6c6f206a68f1a33e6c2e7d71bee6564a/rpm/docker-build.sh) builders.

@kubernetes/sig-cluster-lifecycle-bugs

**Comment by pipejakob** [comment]
I chatted with @mikedanese about this, and in the longer-term, we would really like deb/rpm building to be done exclusively by bazel, and to kill this duplicated `release` logic. That won't realistically happen until 1.9 or later, though.

**Comment by luxas** [comment]
@pipejakob What's blocking it?

**Comment by pipejakob** [comment]
I believe we're still lacking support for cross builds in bazel, and that's something that the bazel team is working on. We can use our bazel builds now to build debs/rpms for the current local architecture, but not all the others.

**Comment by luxas** [comment]
@pipejakob Ah yeah, that's right.
I was first thinking if there was a blocker on our side...

**Comment by kad** [comment]
#413 seems to be closing that issue, isn't it ?

**Comment by pipejakob** [comment]
Yup. The deb changes were in https://github.com/kubernetes/release/pull/413 and rpm changes in https://github.com/kubernetes/release/pull/414. Closing.
