### ISSUE TITLE
1.7.4 RPMs not found

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/release#395]
1.7.4 RPMs not found in repo <https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64>.

When will it be available? I thinks it should be released together with binaries.

**Comment by wojtek-t** [comment]
Should be fixed now.

**Comment by feiskyer** [comment]
@wojtek-t Cool. Thanks

**Comment by bamb00** [comment]
Hi,  I'm a newbie.  I want to retrieve the 1.7.4 rpm from the url above.  How would I go about of doing that? 

Thanks in Advance.
