### ISSUE TITLE
Anago needs to check for github branch restrictions

### ISSUE THREAD

**Issue by david-mcmahon** [kubernetes/release#396]
A recent alpha release was pushed and the tag went, but the branch push failed due to newer branch restriction ACLs at what appears to be the github level.  The check we use to verify that someone is able to push before getting too far "git push -q --dry-run origin master" will return OK, but then fail when the actual non dry-run push occurs.

Need to figure out how to ask github about branch restrictions and check that in the tooling where we now check the standard push.

cc @mbohlool @pwittrock

**Comment by david-mcmahon** [comment]
https://developer.github.com/v3/repos/branches looks promising, but there's not much in the way of descriptions.  it's not clear which one of those would return the "I'm authenticated as user via a token.  Do I have access to the named branch?"

**Comment by david-mcmahon** [comment]
@enisoc You don't appear to have this issue, but according to https://github.com/kubernetes/kubernetes/settings/branches/master, only kubernetes-admins have access to push and you are not on that list and neither is anyone else who is creating releases. 

Who set up the branch restrictions originally who might understand these ACLs?

**Comment by david-mcmahon** [comment]
@shawnajean (from github) was helpful enough to explain that there's no simple endpoint for this kind of check and it requires a bit more parsing and constructing to figure out if a user is on the list or in a group, but given the disconnect between what the master branch restriction page is telling us and who actually has permission to push to these branches, it means we need to figure out that bit first.

**Comment by enisoc** [comment]
Perhaps we could create a dummy branch with the same authorized users as master, but that allows force push. Then in the check phase, do a real push to the dummy branch, then a force push to undo it. The undo push prevents the accumulation of useless cruft in the main repo.

**Comment by david-mcmahon** [comment]
That may be an option, but it adds moving parts to the process and a maintenance burden to maintain the additional branch with the same permissions.  I could see that easily getting out of sync too.

My plan for now is to assume (yuk) that kubernetes-release-managers is authoritative and then check that whoever or whatever is running anago is in that list.  Unless there's some way to connect the fact that kubernetes-release-managers is one of "Organization and repository administrators" via the API.
