### ISSUE TITLE
kubeadm v1.8 does not mount /etc/kubernetes

### ISSUE THREAD

**Issue by mattymo** [kubernetes/release#406]
## What keywords did you search in kubeadm issues before filing this one?

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): v1.8.0-beta1

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.7.3
- **Cloud provider or hardware configuration**: none
- **OS** (e.g. from /etc/os-release): Ubuntu Xenial
- **Kernel** (e.g. `uname -a`):
- **Others**:

## What happened?
In kubeadm v1.7.3, /etc/kubernetes is mounted directly on kube-apiserver static pod. This allows me to specify `basic-auth-file: /etc/kubernetes/users/known_users.csv` in the apiServerExtraArgs section. In v1.8.0-beta1, this mount was removed. Now only very specific mounts are made. If I move my users file into my pki dir, then it could be seen, but I don't prefer to store my user file there.

## What you expected to happen?
Keep /etc/kubernetes mount or make an option to specify extra mount volumes.

## How to reproduce it (as minimally and precisely as possible)?
Add to kubeadm config YAML:
Create a basic auth csv file.
```
apiServerExtraArgs:
  basic-auth-file: /etc/kubernetes/users/known_users.csv
```

## Anything else we need to know?
There should be an option to make extra mounts for static pods.

**Comment by kargakis** [comment]
@mattymo please reopen in the [kubeadm repo](https://github.com/kubernetes/kubeadm)

cc @kubernetes/sig-cluster-lifecycle-bugs 

/close
