### ISSUE TITLE
kubectl, kubelet binaries v1.6.9 doesn't exist on kubernetes repository

### ISSUE THREAD

**Issue by pekfi** [kubernetes/release#409]
yum search kubectl
 ======================================================= N/S matched: kubectl =======================================================
 kubectl-1.5.4-0.x86_64 : Command-line utility for interacting with a Kubernetes cluster.
 kubectl-1.6.0-0.x86_64 : Command-line utility for interacting with a Kubernetes cluster.
 kubectl-1.6.1-0.x86_64 : Command-line utility for interacting with a Kubernetes cluster.
 kubectl-1.6.2-0.x86_64 : Command-line utility for interacting with a Kubernetes cluster.
 kubectl-1.6.3-0.x86_64 : Command-line utility for interacting with a Kubernetes cluster.
 kubectl-1.6.4-0.x86_64 : Command-line utility for interacting with a Kubernetes cluster.
 kubectl-1.6.5-0.x86_64 : Command-line utility for interacting with a Kubernetes cluster.
 kubectl-1.6.6-0.x86_64 : Command-line utility for interacting with a Kubernetes cluster.
 kubectl-1.6.7-0.x86_64 : Command-line utility for interacting with a Kubernetes cluster.
 kubectl-1.6.7-0.x86_64 : Command-line utility for interacting with a Kubernetes cluster.
 kubectl-1.7.0-0.x86_64 : Command-line utility for interacting with a Kubernetes cluster.
 kubectl-1.7.1-0.x86_64 : Command-line utility for interacting with a Kubernetes cluster.
 kubectl-1.7.2-0.x86_64 : Command-line utility for interacting with a Kubernetes cluster.
 kubectl-1.7.3-1.x86_64 : Command-line utility for interacting with a Kubernetes cluster.
 kubectl-1.7.4-0.x86_64 : Command-line utility for interacting with a Kubernetes cluster.
 kubectl-1.7.5-0.x86_64 : Command-line utility for interacting with a Kubernetes cluster.

/etc/yum.repos.d/kubernetes.repo
 [kubernetes]
 name=Kubernetes
 baseurl=http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
 enabled=1
 gpgcheck=1
 repo_gpgcheck=1
 gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

**Comment by pipejakob** [comment]
Hey @pekfi, in order to give us an idea of priority, can you let us know the impact of this specific release being missing? I'm not saying it's expected, but I'm wondering if this is something you casually noticed and wanted to point out, or if it's actively blocking you. Thanks!

**Comment by pekfi** [comment]
Hi @pipejakob, I would like to update 1.6.X to greater then 1.6.7 asap. This is a requirement of my customer. I do not want to update to 1.7.X at the moment. I found the binaries in the tarball of kubernetes v.1.6.9, why is it not released on the kubernetes.repo ? Thanks Peter

**Comment by kongslund** [comment]
Given the [vulnerability in DNSMasq](https://security.googleblog.com/2017/10/behind-masq-yet-more-dns-and-dhcp.html) which has been fixed in 1.5.8, 1.6.11, 1.7.7, and 1.8.0, I would hope that Debian and RPM packages for those versions will be published soon.

**Comment by lareeth** [comment]
What's the expect process to upgrade to the latest version of 1.5, 1.6 or 1.7 if these rpms are not available? This is blocking us from upgrading, as we choose the rpm version when provisioning a server, and we cant provision newer than 1.6.7.

**Comment by enisoc** [comment]
@wojtek-t I heard that you helped with getting RPMs pushed for 1.7. What's the process here?

**Comment by dawidmalina** [comment]
Looks like this issue is related to https://github.com/kubernetes/release/issues/455

**Comment by enisoc** [comment]
I've pushed packages for the latest 1.6 patch release, 1.6.12. I also pushed the latest 1.7.10, and am working on 1.8.2.

This is still a time-consuming manual process, but we are working on adding some automation to help reduce the delay from release to deb/rpm packages being available. Thank you for your patience.

**Comment by lareeth** [comment]
Is there anything we can do to help with the automation? I found it easy to modify the build to allow you pass in the version at build time, I then was able to create a build pipeline for each release from 1.5 to 1.8. You would just need to keep each pipeline minor release number parameter up to date.

**Comment by enisoc** [comment]
The actual building of the packages is pretty well automated already. The manual steps involve signing and pushing them to the official k8s repositories. Currently, these repos are hosted by Google, and the process to push to them involves Google-internal tools.

More details here:

https://github.com/kubernetes/release/issues/281
https://github.com/kubernetes/release/issues/358
