### ISSUE TITLE
Publish produced from bazel builds deb and rpm packages

### ISSUE THREAD

**Issue by kad** [kubernetes/release#415]
I would like to discuss possibility to improve release scripts and CI jobs to be able to publish
packages produced during bazel builds for all branches. 

I would like to propose also list of repositories that would be matching labels that are used in CI (latest-1.x, stable-1.x, etc).

Naming convention I suggest to use: `kubernetes-$distro-$arch-$ci_label`

For example, for RPMs it would be something like: this under https://packages.cloud.google.com/yum/repos 

```
kubernetes-el7-x86_64-stable-1
kubernetes-el7-x86_64-stable-1.8
kubernetes-el7-x86_64-latest-1
kubernetes-el7-x86_64-latest-1.8
kubernetes-el7-x86_64-latest-1.9
kubernetes-el7-x86_64-ci-latest-1
kubernetes-el7-x86_64-ci-latest-1.8
kubernetes-el7-x86_64-ci-latest-1.9
```

For Debian/APT based repositories, I'd suggest to use  similar naming schema, but without `$arch`:
```
kubernetes-xenial-stable-1
kubernetes-xenial-stable-1.8
kubernetes-xenial-latest-1
kubernetes-xenial-latest-1.8
kubernetes-xenial-latest-1.9
kubernetes-xenial-ci-latest-1
kubernetes-xenial-ci-latest-1.8
kubernetes-xenial-ci-latest-1.9
```

Those repositories would be good if they will be populated in similar time and way when `gs://kubernetes-release/release/*.txt` and `gs://kubernetes-release-dev/ci-cross/*.txt` are populated. 
Examples:
-  once 1.8.2 is published and `gs://kubernetes-release/release/stable-1.8.txt` updated for it, set of packages should be uploaded to repository `kubernetes-el7-x86_64-stable-1.8` and corresponding deb `kubernetes-xenial-stable-1.8`. 
- once CI finishes build for branch, corresponding packages uploaded to `kubernetes-xenial-ci-latest-1.8` or similarly `kubernetes-el7-x86_64-ci-latest-1.8`. 

Related: kubernetes/kubernetes#53163 - this makes packages produced during bazel build usable on x86-64. Not ideal case, as we don't have multi-arch support, but better than nothing for now for testing.

I don't have enough knowledge of k8s CI and release infra to develop that myself, but hope people who knows more about it will be able to comment and maybe guide on how to implement that idea.

cc @ixdy @mikedanese @luxas

**Comment by luxas** [comment]
@kad are you interested in helping with a program that would push debs/rpms in a apt-get/yum-compatible manner to some GCS bucket?

I think the general style above looks very good; except that I think we should have it to be
kubernetes(-xenial)(-ci) with `stable`, `stable-1`, `stable-1.8`, etc. as the sub-repos.

**Comment by kad** [comment]
@luxas I'm interested to help here, but I have no idea how this publishing is implemented now :( 
I fear that we need some googler for that task.

Regarding sub-repos: I'm not sure if GCS bucket support different ways if sub-repos.
Because in case of RPMs, sub repos are just directory structure, but in case of debs, it can be one pool but different dists for different branch. Something like:
`deb http://download.k8s.io/debs/ xenial stable-1.8`

**Comment by luxas** [comment]
@kad are you still working on/thinking about this?
