### ISSUE TITLE
changelog generation should write to file per release-branch

### ISSUE THREAD

**Issue by liggitt** [kubernetes/release#427]
In order to keep changelog files from growing without bound, and to make it easier to see what is changing in a given release stream, the changelog files are being split per release branch.

However, anago is still generating new point release notes in the main CHANGELOG file. It should target release notes for tag `x.y[...]` to `CHANGELOG-x.y.md` (creating it if needed)

**Comment by enisoc** [comment]
PR is out for review: #421

**Comment by liggitt** [comment]
amazing, the time-traveling PR opener strikes again :)
