### ISSUE TITLE
find_green_build picks wrong secondary build

### ISSUE THREAD

**Issue by enisoc** [kubernetes/release#471]
One of the secondary jobs on the `release-1.9` branch has been mistakenly building from `master` (https://github.com/kubernetes/test-infra/issues/5727). I would have expected `find_green_build` to fail to find any matching green run for that secondary job, but instead it was marked as `PASSED` with a build number that doesn't match:

```
  Job #                                   Run #   Build # Time/Status
= ======================================= =====   ======= ===========
* build-1.9                               #6      #713    [11:13 11/29]
* (--buildversion=v1.9.0-beta.0.713+5898890a735c4e)
- verify-release-1.9                      No Good Runs    SKIPPING
- test-go-release-1.9                     #2911   #713    PASSED
- bazel-build-1-9                         #202    #711    PASSED
```

Due to the misconfigured job, [run number 202](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-bazel-build-1-9/202) for `bazel-build-1-9` is actually a completely different commit than the `buildversion` listed for the primary job (`build-1.9`).

**Comment by david-mcmahon** [comment]
If prow is configured wrong, `find_green_build` doesn't know that and will just grab the named ("1.9") job.
`find_green_build` *could* scan the json contents for a version that doesn't match here.  There could also be a test on prow config changes that verifies that jobs names somehow match the named branches in the config.

**Comment by enisoc** [comment]
Those sound like good checks to prevent this in the future.

BTW, aside from the misconfiguration, is it expected that the build number for a secondary job (711) could be different from the build number for the primary job (713) and still be considered "PASSED"? I would have thought those build numbers have to match.

**Comment by david-mcmahon** [comment]
Expecting to see a @kubernetes/test-infra-maintainers replacement solution to this before I would get to a fix for `find_green_build`.

**Comment by BenTheElder** [comment]
@david-mcmahon what fix would you expect? the job should be fixed but this could happen again very easily given the vast number of jobs ... since we publish this metadata shouldn't we check it?

**Comment by BenTheElder** [comment]
> There could also be a test on prow config changes that verifies that a job name fits with the named branch in the config.

Job names often don't include a branch at all, so I'm not sure this would help much. It'd also have to be aware of every way in which code can be fetched (including kubetest --extract for various tarball locations, as well as the normal checkout mechanisms), to be correct, but since we publish the actual detected commit it should be relatively trivial to verify that a test ran against some actual commit / branch.
