### ISSUE TITLE
[release-1.9] find_green_build commit count doesn't match CI build

### ISSUE THREAD

**Issue by enisoc** [kubernetes/release#472]
On the release-1.9 branch, the latest primary build from HEAD is:

```
* build-1.9                               #6      #713    [11:13 11/29]
* (--buildversion=v1.9.0-beta.0.713+5898890a735c4e)
```

However, `find_green_build` gives a different commit count since the `v1.9.0-beta.0` tag for the same commit:

```
ATTENTION: The release-1.9 branch HEAD is ahead of the last
good run by 19 commits.

If you want to use the head of the branch anyway,
--buildversion=v1.9.0-beta.0.694+5898890a735c4e
```

**Comment by david-mcmahon** [comment]
Expecting to see a @kubernetes/test-infra-maintainers replacement solution to this before I would get to a fix for `find_green_build`.

**Comment by krzyzacy** [comment]
so currently we changed what we do in test-infra:
- trigger the build job every like 10 min
- check a build of current k8s version exists or not
- if exists, exit 0
- if not, do a build

not sure if that's related, but I assume you can grab the 1st green build from gcs build job?
