### ISSUE TITLE
Stage on a public repository binary, debs, rpm and docker images for alpha/beta releases

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/release#479]
It would be really useful for testing if, when cutting a alpha/beta release, the corresponding binary, debs and rpm will be staged on a public bucket (e.g. `gs://kubernetes-release-dev/bazel/v1.9.0-beta.2`), while corresponding debs published on a public docker registry (e.g. `gcr.io/kubernetes-ci-images/`)

cc @luxas

**Comment by fabriziopandini** [comment]
I noticed that this issue is somehow related to https://github.com/kubernetes/release/issues/415

**Comment by ixdy** [comment]
Yeah, currently the official build process is not using bazel, and the non-bazel build process generates rpms and debs out-of-band, somewhat manually. 1.9 is too far along for any meaningful progress here, but it might be possible to improve the rpm/deb situation for 1.10.
