### ISSUE TITLE
1.10.0 RPM not found

### ISSUE THREAD

**Issue by lareeth** [kubernetes/release#539]
The 1.10.0 RPM is not found in the repo https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64.

When will it be available? Could you try and release packages together with binaries.

**Comment by lareeth** [comment]
Issue also here: https://github.com/kubernetes/kubernetes/issues/61763

**Comment by calebamiles** [comment]
should be fixed now, @lareeth 

**cc: @jdumars, @kubernetes/kubernetes-release-managers**

**Comment by lareeth** [comment]
@calebmiles Just checked, and working as expected. How can we stop RPMs being so delayed in the future?

**Comment by calebamiles** [comment]
@lareeth we've been making slow progress on improving the release tooling  https://github.com/kubernetes/sig-release/issues/10 in order to support automated rpm/deb publishing, however, the work has not yet been completed
