### ISSUE TITLE
Add --exclude-suites= to gcbmgr

### ISSUE THREAD

**Issue by david-mcmahon** [kubernetes/release#551]
We are still in a state where the blocking test sets on a branch are flaky/failing often and with the shift from desktop->GCB, we should provide the `--exclude-suites=` flag to `gcbmgr`.

A workaround for this is to use `find_green_build` directly which already has `--exclude-suites=` and come up with a `--buildversion=` arg that `gcbmgr` already supports.

cc @MaciekPytel

**Comment by MaciekPytel** [comment]
/remove-lifecycle rotten
I still think it would be useful. Admittedly it's not very hard to workaround (editing gcb script and hardcoding the value is pretty easy) and not needed often, so the priority is low.
