### ISSUE TITLE
1.10.1 RPM not found

### ISSUE THREAD

**Issue by philbour** [kubernetes/release#552]
Similiar to [kubernetes/release/#539](https://github.com/kubernetes/release/issues/539), the 1.10.1 RPM is not available in the https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64 repo.

Can this be added? There is a bug fixed in 1.10.1 which I really need.

**Comment by MaciekPytel** [comment]
It should be there now. Sorry for the delay, building RPM is much harder than cutting the release and building deb and it took me some time to figure it out.

**Comment by philbour** [comment]
Perfect I can see it there now.

**Comment by iupender** [comment]
I don't see the rpm's. is it moved to other location?
