### ISSUE TITLE
Produce signed binaries/artifacts for releases

### ISSUE THREAD

**Issue by david-mcmahon** [kubernetes/release#56]

**Comment by ixdy** [comment]
/lifecycle frozen
/remove-lifecycle rotten

This is still worth doing, though we probably need someone to own it and draft a design.

**Comment by ixdy** [comment]
cc @kubernetes/sig-release-feature-requests

**Comment by spiffxp** [comment]
/remove-help
I don't think this meets [the criteria for `help wanted`](http://git.k8s.io/community/contributors/devel/help-wanted.md). Please add back via `/help` if I'm incorrect

**Comment by dims** [comment]
closing in favor of https://github.com/kubernetes/kubernetes/issues/70132
