### ISSUE TITLE
create OWNERS and enable automation

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/release#566]
Please consider adding OWNERS files and enabling tide / approval and merge automation like kubernetes etc. so we can smooth out PRs to this repo.

If any of the maintainers need a hand configuring the automation, please let me know or file a bug against test-infra.

Also, on a related note, bumping https://github.com/kubernetes/release/issues/559 regarding SECURITY_CONTACTS which should probably have some relation to the top level OWNERS..

**Comment by BenTheElder** [comment]
this repo does have a prow presubmit to make sure push-build.sh can stage a working cluster, and LGTM / size labeling, but merge automation and OWNERS seem to be missing.

**Comment by calebamiles** [comment]
We should just turn up the automation here. If you don't get around to it before next week I'll start this then
/assign

**Comment by BenTheElder** [comment]
I can turn up the automation, but we'll need appropriate `OWNERS` files first, which are currently lacking, and I don't know who should be in them.

**Comment by jagosan** [comment]
Suggest sig leads. Maybe the current and last 2 release team leads is also interesting idea?

**Comment by ixdy** [comment]
maybe also recent branch managers, since they are the ones who usually end up running the scripts from this repo?

**Comment by BenTheElder** [comment]
OWNERS is done, enabling automation in https://github.com/kubernetes/test-infra/pull/8682

**Comment by justaugustus** [comment]
Looks likes this is done per Ben's comment.
/close
