### ISSUE TITLE
cherrypick-bot should add milestone

### ISSUE THREAD

**Issue by jberkus** [kubernetes/release#571]
Currently, automated cherry-picks do not set the Milestone field for PRs. Example: #62679.
It would be nice to set this so that the milestone is correctly reflected in searches and summary reports.

**Comment by idealhack** [comment]
Currently, we use the [script](https://github.com/kubernetes/kubernetes/blob/master/hack/cherry_pick_pull.sh) calling `hub` which support `--milestone=<NAME>` to create a cherrypick PR. But for most cherrypick PR authors, they don't have the power to set a milestone. So this sounds like a Prow plugin to me, I'm not sure if we have anything related to mapping the `release-1.y` to milestone `v1.y` though.

**Comment by nikhita** [comment]
> So this sounds like a Prow plugin to me, I'm not sure if we have anything related to mapping the release-1.y to milestone v1.y though.

If we need a prow plugin for this, I think the right place would be to add to the `cherrypickunapprove` plugin. We can look at the baseBranch, and if it is `release-1.y`, then we can add the milestone as `v1.y`, while _also_ commenting that this PR is not approved.

Kinda related: the branches to be treated as cherry-picks are a config option:

https://github.com/kubernetes/test-infra/blob/38bfb6c3fa5824ec1c14d7dc9c4a301b69b2ee25/prow/plugins/config.go#L677-L679

(maybe a good place to discuss this is in the test-infra repo?)

cc @spiffxp @BenTheElder

**Comment by BenTheElder** [comment]
cherry pick PR management tooling has been somewhat controversial IIRC .... cc @cblecker

**Comment by nikhita** [comment]
cc @tpepper @aleksandra-malinowska

**Comment by tpepper** [comment]
I feel like our methods of tracking new inbound, known pending, rejected, and merged cherry picks is lossy.  Would love to figure out something better.  I'm not sure milestone is the answer, but I also am not sure it would hurt if auto-applied.

**Comment by cpanato** [comment]
What is the decision here? I can help on that, need some guidance since i'm a newbie :)

**Comment by nikhita** [comment]
This is already in progress here: https://github.com/kubernetes/test-infra/pull/12968 :grimacing: 

Going to remove help wanted on this, sorry @cpanato :see_no_evil: 

/remove-help

**Comment by spiffxp** [comment]
/milestone v1.16
to reflect when this work is expected to land

**Comment by idealhack** [comment]
I suppose we can close this since it's implemented now.

/close
