### ISSUE TITLE
make `mock` flag required

### ISSUE THREAD

**Issue by mbohlool** [kubernetes/release#574]
The mock flag is default when you run any anago or gcbmgr command. You may realize this much later when you ready to release an staged build and realized staged build was a mock. Also it is unclear when there is a default if you can release with --nomock when you ran stage with no flag (that means mock), which you cannot.

If we make `mock` flag required, all of these confusions and mistakes will go away. On staging, when it is required, user of the script knows there is a different between mock and nomock for staging. On release, the user will reminded to pass the same mock/nomock from the staging step.

**Comment by mbohlool** [comment]
@david-mcmahon WDYT?

**Comment by david-mcmahon** [comment]
The idea behind an explicit `--nomock` is to allow the running of the tooling by default in a non-destructive way.  I would assert that if the user is unaware of the consequences of mock vs. nomock, then the default is serving its intended purpose.  I understand that it takes greater contextual understanding, planning and forethought to generate an actual release and this really is WAI.  

`gcbmgr` produces output/reporting that shows what is available for release.  Discoverability could possibly be improved here and better warnings/notifications.  It's always worth exploring new ideas if the current workflow is confusing in any way.

**Comment by mbohlool** [comment]
> I would assert that if the user is unaware of the consequences of mock vs. nomock, then the default is serving its intended purpose.

I totally agree. What I am trying to solve here is as you mentioned later, making the process more clear. Problem is not being unaware of consequences of mock vs nomock but to remove human error here (forgetting to set nomock flag). Making both flags required with no default value will make the release manager to specify it and be aware of which one is running.

This is specially important with `gcbmgr` as most of those warning/notifications will be buried under many line of logs in a cloud running service.
