### ISSUE TITLE
kubelet rpm build incorrect location for systemd unit file

### ISSUE THREAD

**Issue by davemac30** [kubernetes/release#576]
According to systemd(1):
> Packages that want to install unit files shall place them in the directory returned by `pkg-config systemd --variable=systemdsystemunitdir`

On RHEL/CentOS 7 (presumably on most RPM-based systems), this is `/usr/lib/systemd/system`. The kubelet RPM, however, installs its unit file in `/etc/systemd/system`.

Looking at rpm/kubelet.spec there's this:

> `install -p -m 755 -t %{buildroot}%{_sysconfdir}/systemd/system/ kubelet.service`

I suspect that it ought to be changed to this:

> `install -p -m 755 -t %{buildroot}%{_unitdir}/ kubelet.service`

**Comment by idealhack** [comment]
@davemac30 Hi, could you confirm that this is still relevant? Feel free to submit a PR if so.

/remove-lifecycle stale
/kind cleanup

**Comment by idealhack** [comment]
/remove-lifecycle stale
/kind cleanup

@davemac30 Hi, could you confirm that this is still relevant? Feel free to open a PR if so :)
