### ISSUE TITLE
gcrmgr container push caused k8s 1.8.15 release to fail

### ISSUE THREAD

**Issue by jpbetz** [kubernetes/release#579]
Marking this as a P2 since a second attempt to release was successful.

Steps taken:

```
$./gcbmgr stage release-1.8 --nomock --official
$./gcbmgr tail b123dd6f-54c4-4324-9246-f67beb24cc96
$./gcbmgr release --nomock --official release-1.8 --buildversion=v1.8.15-beta.0.33+c2bd642c70b362

Failed with error: "Pushing staging-k8s.gcr.io/cloud-controller-manager:v1.8.15: .....FAILED"

$ ./gcbmgr release --nomock --official release-1.8 --buildversion=v1.8.15-beta.0.33+c2bd642c70b362
$./gcbmgr tail 05b1db46-8b32-483a-b893-d853dfcfee93

...output indicated that if I run "gsutil -m rm -r gs://kubernetes-release/release/v1.8.15" I should be able to reattempt the release.

$ gsutil -m rm -r gs://kubernetes-release/release/v1.8.15

<successful>

./gcbmgr release --nomock --official release-1.8 --buildversion=v1.8.15-beta.0.33+c2bd642c70b362
$./gcbmgr tail 402f24fa-c7b3-48bf-ac37-841e7bfdff79

...release successful
```

/cc @listx @ixdy @david-mcmahon

**Comment by david-mcmahon** [comment]
These failed pushes are usually due to an out of date gcloud binary.  We don't really have a good story on updating the `k8s-cloud-builder` image on a regular basis.  

Update it by running https://github.com/kubernetes/release/blob/master/build/build-k8s-cloud-builder-container.

**Comment by jpbetz** [comment]
Also encountered by @foxish  for 1.11.1 - https://gist.github.com/foxish/f0c98aa2a7d832851cbdcc9ea7107f4c

**Comment by MaciekPytel** [comment]
Is there something I can do to avoid this issue? Should I just run https://github.com/kubernetes/release/blob/master/build/build-k8s-cloud-builder-container every time before trying to cut release?

**Comment by david-mcmahon** [comment]
@MaciekPytel That doesn't seem unreasonable, though certainly less than ideal.  Having some CI engine doing that work would be best.  It also appears that the underlying ubuntu base image used to create that image changed somehow and the Dockerfile no longer builds, so that needs some attention as well.

**Comment by dims** [comment]
@dougm did you run into this issue?

**Comment by dougm** [comment]
@dims no, I haven't run into this.
