### ISSUE TITLE
improve handling of cri-tools dependency version

### ISSUE THREAD

**Issue by chuckha** [kubernetes/release#583]
We hardcode cri-tools >=v1.11.0 as a dependency to kubeadm but because the versioning of cri-tools will match that of kubernetes we will need to make this value dynamic. Example: >=1.12.0 for k8s 1.12.

**Comment by luxas** [comment]
Is this an actual version requirement from cri-tools @Random-Liu @feiskyer or what version skew is supported?

**Comment by feiskyer** [comment]
@chuckha @luxas I think we can close this now?
