### ISSUE TITLE
Packages for Ubuntu 18.04

### ISSUE THREAD

**Issue by dawidmalina** [kubernetes/release#589]
Ubuntu 18.04 is available for a while but kubernetes packages are not available. When we can expect those packages?

**Comment by evanrich** [comment]
was wondering the same thing myself.

**Comment by dawidmalina** [comment]
Any updates on this? CC @ixdy @mikedanese

**Comment by ixdy** [comment]
this is kinda a dupe of https://github.com/kubernetes/release/issues/589

**Comment by ixdy** [comment]
this is kind of a dupe of https://github.com/kubernetes/kubernetes/issues/66300

**Comment by ixdy** [comment]
also a dupe of #589.
/close
