### ISSUE TITLE
RFC: Check in RPM spec file updates for patch versions

### ISSUE THREAD

**Issue by ncdc** [kubernetes/release#591]
Back in December 2017 I was asking how RPMs were built for Kubernetes 1.9.x. The Slack thread is here: 
https://kubernetes.slack.com/conversation/C2C40FMNF/p1513780901000151.

I was specifically curious about the RPM spec file, as it has hard-coded values for the major, minor, and patch versions of Kubernetes, and these were out of date at the time (they were for 1.8.x).

@enisoc wrote there are some Google-internal scripts that modify the spec file to update the versions, but for patch releases, those updates are not checked in. Looking at recent history, the spec file jumped from 1.9.0 to 1.11.0, which highlights a gap.

I would like to see these updates checked in if possible, so the community can see the exact spec files used to create the RPMs.

It would also be nice if we come up with a strategy to make it easy to see spec files for different versions (1.10.x vs 1.11.x ...). This could be done with branches/tags in this repository, or with multiple copies of the spec (1 per minor version). I think branches/tags probably makes more sense, but we should keep all the options on the table and discuss.

**Comment by tpepper** [comment]
Same occurs it seems for deb's.

**Comment by tpepper** [comment]
/cc @ixdy @spiffxp 

Is there any info we can get from Google on thoughts/plans here for improving the build/publish process?  And is there somebody to whom we could assign this issue?

Kubeadm and SIG-Cluster-Lifecycle are fielding a lot of issues here lately and they're really just a consumer of the build/publish process.

**Comment by ixdy** [comment]
cc @filbranden

**Comment by tpepper** [comment]
See also https://github.com/kubernetes/release/issues/631

**Comment by tpepper** [comment]
see PR #693

**Comment by justaugustus** [comment]
Closing in favor of the [kubepkg umbrella issue](https://github.com/kubernetes/release/issues/1027).
/close
