### ISSUE TITLE
branchff and ectd

### ISSUE THREAD

**Issue by tpepper** [kubernetes/release#610]
Yes "ectd":
```
logecho -n "Ensure ectd is up to date: "
logrun -s hack/install-etcd.sh
```

At a minimum this is a typo.  But is the install etcd script truly needed in order to fast forward a release branch?

**Comment by ixdy** [comment]
`hack/update-openapi-spec.sh` (specified here) https://github.com/kubernetes/release/blob/dcfd042493c5456bf7b36995aa047593d14f8a95/branchff#L194 requires `etcd`.
