### ISSUE TITLE
remove experimental docker feature enabling

### ISSUE THREAD

**Issue by tpepper** [kubernetes/release#628]
To enable multiarch manifest support, a sadly still experimental feature needed enabled.

https://github.com/kubernetes/release/pull/622
https://github.com/kubernetes/release/pull/627

We need to understand how/when this goes stable and then revert the addition of the environment variable so we're not inadvertently enabling all manner of experimental docker things.

**Comment by dims** [comment]
yep, once this merges - https://github.com/docker/cli/pull/1355

**Comment by tpepper** [comment]
I glanced in on this and it appears docker/cli upstream still has this marked experimental and it would seem their long term preferred direction is https://github.com/moby/moby/issues/38043 and not moving anywhere at the moment.

**Comment by justaugustus** [comment]
Docker commands like `docker manifest` and `docker buildx` continue to require experimental features to be enabled (even though they've been available and widely in use for quite some time).

I'd say let's opt to no longer track this, until something changes upstream and we have a reason to revisit.
/close

**Comment by tpepper** [comment]
I'm concerned about not tracking this.  It brings in un-scoped risk.  Across time we've gone from one instance of DOCKER_CLI_EXPERIMENTAL exported to eleven instances in k/release and eight in k/k, none of which are labeled in code with a FIXME or indication of the flag being risky.  Only 7 of those 19 today indicate which docker feature the flag is meant to be enabling in that usage instance, or how/when to remove it.  The first instance of this flag in the project core was vigorously objected to, but accepted as short term inevitable and ok IF we had an issue open so we didn't forget to get it removed.  We're sliding deeper into tech debt here.

**Comment by saschagrunert** [comment]
Upcoming releases of docker will enable experimental features per default: https://github.com/docker/cli/pull/2774

**Comment by saschagrunert** [comment]
Closing because of my previous comment. I do not see a way right now to solve this.
/close
