### ISSUE TITLE
Signing releases with GPG keys

### ISSUE THREAD

**Issue by dims** [kubernetes/release#636]
I'd like us to sign release artifacts using GPG keys. Here's how other foundations do it:

- https://www.apache.org/dev/release-signing.html
- https://docs.openstack.org/infra/system-config/signing.html
- https://wiki.openstack.org/wiki/OpenPGP_Web_of_Trust
- https://releases.openstack.org/#cryptographic-signatures

Ideally we would build a web of trust including the patch/branch managers and use keys when building the artifacts at the same time as we generate the md5 and sha1/512 manifests. We could have a signing party at kubecon to kick off the web of trust too!

Thanks,
Dims

**Comment by philips** [comment]
Also related @ajeddeloh has been working on a YubiKey HSM backed signing server: https://github.com/coreos/fero

**Comment by ajeddeloh** [comment]
Credit where it's due: @csssuf did the implementation, I just got it set up and deployed. It requires a pair of servers with a yubiHSM loaded with the secrets. If there's interest in using it, I can help with setup. It allows for setting thresholds such that you can specify "You need 100 points of signatures" where different users can have different weights for different secrets. I.e. you can set it up so you need 3 people to sign a release.

**Comment by philips** [comment]
@dims what is signing the apt package releases? https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl

**Comment by dims** [comment]
@philips 

The Google Cloud Packages Automatic Signing Key id  is`ba07f4fb` and belongs to email id (gc-team@google.com), So i think it's setup in the Anago/GCB release harness that we cannot see. (part of the stuff we need to bring out from behind the screen when we move to CNCF)

Thanks,
Dims

**Comment by dims** [comment]
This issue was moved to kubernetes/kubernetes#70132
