### ISSUE TITLE
FIx github auth for all the tooling

### ISSUE THREAD

**Issue by david-mcmahon** [kubernetes/release#65]
The handling of github authentication is much like the rest of the tooling prereqs in this repo.  It should be a no-assumed-knowledge, guided process that handholds the user to getting their auth set up correct so they can get on with their lives (the running of the tool).

We make a few attempts to get auth set up correctly.
- https://github.com/kubernetes/release/blob/master/lib/gitlib.sh#L118
- https://github.com/kubernetes/release/blob/master/anago#L905

Additional things we should be doing:
- Guide users using typical workflows and authentication methods and integrate those workflows into tooling here (using the man pages and/or messages that come with auth errors).
- Look into the long running TODO to get an auth state earlier in the execution flow.

**Comment by mattymo** [comment]
What would you like to see improved? Open a browser automatically to https://github.com/settings/tokens if there is no token set?
If it's set and doesn't work, advise the user to ensure there is a token created the current set of information?

This process can't be automated internally without the user actually logging in.

**Comment by david-mcmahon** [comment]
`anago` and other tools run via the command-line.  We need to:

* Understand the different auth mechanisms github uses
* Figure out which ones are used most commonly
* Have a check (as early in the script/process as possible) that validates all the necessary auth pathways (mostly push to various branches).
* The workflow should assume zero knowledge of github auth mechanisms and the user should simply pass the auth check or the auth check should produce a detailed set of steps to achieve the auth required for the operation with instructions on how to continue.

**Comment by david-mcmahon** [comment]
Release process eventually moving to container builder, the issues raised here are no longer relevant/pressing.
