### ISSUE TITLE
the debian job fails due to timeout (trying to build ~750 packages)

### ISSUE THREAD

**Issue by chuckha** [kubernetes/release#651]
[This job](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-release/kubernetes-builds.yaml#L89) has been failing since as [far back as gubernator will show me](https://gubernator.k8s.io/builds/kubernetes-jenkins/logs/ci-kubernetes-build-debian-unstable?before=3835).

One temporary solution here is to increase the timeout and maybe bump the periodic interval. Another solution is to disable this job as it provides no signal for us anyway.

I think the main problem is [this logic](https://github.com/kubernetes/release/blob/master/debian/build.go#L198). This builds 5 architectures * 5 packages * 10 distros * 3 versions (stable,unstable,nightly) which is 750 debian packages every time this job runs. It's actually a little bit less than 750 but it's close enough.

We should restrict this to one kube version (latest), one distro (xenial?) and one or two architectures amd64 and arm64?

**Comment by ixdy** [comment]
This job is at least not timing out anymore, thanks to @dims for https://github.com/kubernetes/test-infra/pull/10750 and https://github.com/kubernetes/test-infra/pull/10763.

**Comment by chuckha** [comment]
woohoo!
