### ISSUE TITLE
kube-conformance image is not being released as part of the release process

### ISSUE THREAD

**Issue by chuckha** [kubernetes/release#655]
As stated in the kube-conformance readme [this image](https://github.com/kubernetes/kubernetes/tree/master/cluster/images/conformance#conformance) should be released during every release. It did not happen with the 1.13 release.

**Comment by chuckha** [comment]
Image does exist. Initial report was not made when the issue was discovered, but it's resolved now. It may or may not be an issue for the next release.

**Comment by idealhack** [comment]
FWIW, I don't think we have any changes in the image releasing part between 1.12 and 1.13

**Comment by dims** [comment]
Looks like we are good - https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/conformance?gcrImageListsize=30
