### ISSUE TITLE
Bazel build fails when trying to build release-notes manually

### ISSUE THREAD

**Issue by onyiny-ang** [kubernetes/release#677]
I am getting the following error when trying to build the release-notes tool from source with bazel. I tried running `dep ensure` to make sure the vendored packages were up to date but it hasn't helped. I am still able to get the release-notes tool through `go get` and am able to build it with `go build` so this is a fairly low priority issue.

```
bazel build //cmd/release-notes
ERROR: $GOPATH/src/k8s.io/release/cmd/release-notes/BUILD.bazel:3:1: no such package 'vendor/golang.org/x/oauth2': BUILD file not found on package path and referenced by '//cmd/release-notes:go_default_library'
ERROR: Analysis of target '//cmd/release-notes:release-notes' failed; build aborted: no such package 'vendor/golang.org/x/oauth2': BUILD file not found on package path
INFO: Elapsed time: 0.264s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 1 target configured)
    currently loading: @io_bazel_rules_go//go/private
```

@marpaia

**Comment by marpaia** [comment]
@onyiny-ang I spent some time debugging this today and I noticed that I was able to reproduce your issue when the repo was checked out to `~/somewhere/release`, but not when it was checked out in my `$GOPATH` at `~/GOPATH/src/k8s.io/release`.  Can you confirm that behavior (that `bazel build //cmd/release-notes` works in `$GOPATH`, but not outside of it?

**Comment by ixdy** [comment]
bazel shouldn't care about `GOPATH`, so that's curious...

**Comment by ixdy** [comment]
oh, I can reproduce this easily. gazelle is configured to use "external" vendoring (i.e. the `vendor/` directory), but that's not how dependencies are vendored in this repo. easy fix incoming.

**Comment by ixdy** [comment]
alternately, maybe @marpaia has a `vendor/` directory which hasn't been checked in?
