### ISSUE TITLE
Minor release notes formatting issue for code blocks

### ISSUE THREAD

**Issue by hoegaarden** [kubernetes/release#681]
When cutting [v1.14.0-beta.2][i], the release notes showed a minor formatting issue for the PR https://github.com/kubernetes/kubernetes/pull/74140.

It seems for a release note like

`````
```release-note
        # Apply resources from a directory containing kustomization.yaml
        kubectl apply -k dir

        # Delete resources from a directory containing kustomization.yaml.
        kubectl delete -k dir

        # List resources from a directory containing kustomization.yaml
        kubectl get -k dir
```
`````

the first line's `#` is interpreted as a markdown heading command, despite the fact that the whole release note is indented and should probably be treated as a code block.

/sig release
/area release-eng

----

Screenshot of the [notification email][n] in my gmail:

> ![image](https://user-images.githubusercontent.com/1401333/54232534-c04c7c80-4502-11e9-87ba-39727cf7a5aa.png)

[i]: https://github.com/kubernetes/sig-release/issues/530
[n]: https://groups.google.com/d/msg/kubernetes-dev/ds7b-nsX0vw/wCXfTQR7CQAJ

**Comment by tpepper** [comment]
See also PR https://github.com/kubernetes/kubernetes/pull/75543
