### ISSUE TITLE
kubernetes yum repository using remote paths with ../../pool and odd filenames

### ISSUE THREAD

**Issue by andyanfieldroad** [kubernetes/release#689]
Hi community,

I seem to be having issues with mirroring the kubernetes yum repository.  My yum repo looks like:

[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
       https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

When I use reposync to download I use the command:
reposync -l --repoid=kubernetes --download_path=/var/mrepo/kubernetes-el7-x86_64/

However that fails with:
WARNING: skipping package kubernetes-cni-0.5.1-0.x86_64: remote path "../../pool/e7a4403227dd24036f3b0615663a371c4e07a95be5fee53505e647fd8ae58aa6-kubernetes-cni-0.5.1-0.x86_64.rpm" not within repodir, unsafe to mirror locally

Firstly, why has the download path specified been ignored?  This behaviour isn't occuring with any other repos I am syncing.  Secondly, whats with the hash at the beginning of the filename?

Thanks
Andy

**Comment by pswica** [comment]
Taking a look at: 

https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/primary.xml

I think you are getting those errors because many location parameters in this xml are relative (../..) which is usually considered unsafe because of potential path traversal attacks.

The location of the file is different than the name of the rpm, which on the .xml is ```kubernetes-cni```

I think the next step would be change the location href="..." tags to point to absolute, rather than relative paths.

**Comment by patsevanton** [comment]
Same issue

**Comment by shai** [comment]
+1

**Comment by zpavlig** [comment]
+1

**Comment by patsevanton** [comment]
Please don`t close issue

**Comment by justaugustus** [comment]
For future state, we'll move to different repos w/o this config issue, but there are quite a few things to do before we get to that stage.
You can track that work here:
- [Establish Kubernetes build/stage/release process on k8s-infra](https://github.com/kubernetes/release/issues/911)
- [Umbrella issue for a job that signs artifacts and uploads them to a GCS bucket](https://github.com/kubernetes/release/issues/913)

In the meantime, @kubernetes/release-engineering, is anyone with experience here interested in chasing this down?

**Comment by xmudrii** [comment]
@justaugustus Should we move this issue away from the v1.18 milestone?

**Comment by justaugustus** [comment]
We're still chasing moving the release process to K8s Infra, which is higher priority (ref: https://github.com/kubernetes/release/issues/689#issuecomment-563039890).

If someone picks this up, then we're happy to add this back to the milestone, but for now:
/milestone clear

**Comment by patsevanton** [comment]
is this bug fixed?

**Comment by patsevanton** [comment]
is this bug fixed?
