### ISSUE TITLE
Fix `release-notes` tests

### ISSUE THREAD

**Issue by jeefy** [kubernetes/release#697]
Currently one of the tests called in `pkg/notes/` is failing because changes were made and the tests weren't updated. This is a failing on two parts.

1) The tests weren't updated. That's :(
2) The tests for `pkg/notes/` aren't run. So I'm going to revisit this and likely add an additional prowjob to run tests for `pkg/` (don't quote me on that till I do more research)

/assign

**Comment by saschagrunert** [comment]
I think the additional prow job is needed here, how to add it?

**Comment by alvaroaleman** [comment]
You would have to add it here: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/release/release-config.yaml#L3

**Comment by saschagrunert** [comment]
> You would have to add it here: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/release/release-config.yaml#L3

Thanks for the hint, I will come up with a PR.

**Comment by saschagrunert** [comment]
@alvaroaleman I would like to verify if the merged PR works as intended, so I opened up a small fix in https://github.com/kubernetes/release/pull/708. The new job does not seem to run there, is there a special synchronization between prow and the config reop?

**Comment by saschagrunert** [comment]
@jeefy The issue should be resolved and can be closed.

**Comment by alvaroaleman** [comment]
@saschagrunert Thanks!

/close
