### ISSUE TITLE
relnotes can't determine a last release on a new branch

### ISSUE THREAD

**Issue by david-mcmahon** [kubernetes/release#70]
It has to do with the github::last_releases() and how github's release page is our canonical source for releases.  We currently treat a branch event as a non-release event, so github's release page won't show a new branch beta tag as a release.  We either need to treat beta.0's as releases (probably best) or workaround the fact beta.0 is not a release.

cc @pwittrock @ixdy

**Comment by pwittrock** [comment]
Betas as releases makes sense to me since we are doing that for alphas.
