### ISSUE TITLE
releaselib.sh assumes testgrid's config.yaml is authoritative, but it is not

### ISSUE THREAD

**Issue by Katharine** [kubernetes/release#709]
releaselib.sh assumes that testgrid's config.yaml file is an authoritative source on testgrid's setup, but in reality config.yaml is just an input into another tool that then produces the actual output.

In practice, this is going to break soon (this week in principle, except we'll probably block on this repo being fixed first) because the releases-blocking tests defined for testgrid are going to move out of config.yaml and in to other files.

The correct approach is to fetch `https://storage.googleapis.com/k8s-testgrid/config`, which is the testgrid config proto as defined by [config.proto](https://github.com/kubernetes/test-infra/blob/master/testgrid/config/config.proto). Parsing that file will probably require adding new non-bash tooling into the image.

/priority important-soon
/area release-eng

**Comment by tpepper** [comment]
FWIW I just noticed relnotes includes a call out to this stuff also via releaselib.sh's check on 'testgrid/config/config.yaml' so the pre-announce of coming release and cherry pick deadline like at https://groups.google.com/d/topic/kubernetes-dev-announce/HpasA0aV3yI/discussion includes:

```
Details
find_green_build: BEGIN main on tpepper-fedora-pet Thu May 30 12:47:42 PDT 2019

Checking for a valid github API token: OK
Checking required system packages: OK
Checking required PIP packages: OK
Checking/setting cloud tools: OK

FAILED: Curl to testgrid/config/config.yaml
No sig-release-1.14-blocking list found in the testgrid config.yaml!

find_green_build: DONE main on tpepper-fedora-pet Thu May 30 12:47:44 PDT 2019 in 2s
```

**Comment by hoegaarden** [comment]
Current status:
- The main change is implemented (https://github.com/kubernetes/release/pull/715) we are picking up the correct config file.
- We don't pick up the changes in test-infra in an automated fashion.
  - There is a check being ran as part of the build process which gives an overview of which of our dependencies are outdated.
  - If there are changes which we don't pick up, our builds and `find_green_build` might fail.
  - AFAIK there is no way in prow to trigger on multiple repos, so if we automatically want to pick up changes not only from k/release but also from k/test-infra, we might need to duplicate the job.

I will check on updating our deps and report back here or maybe close this issue and create a new one re: (auto-) update deps.

**Comment by saschagrunert** [comment]
This can be closed since we do not use testgrids config.yaml any more.
