### ISSUE TITLE
[anago] publishing-bot issue creation is noisy

### ISSUE THREAD

**Issue by hoegaarden** [kubernetes/release#712]
When a new branch is created (when cutting a `.beta.0`), an issue for the publishing-bot is created (see https://github.com/kubernetes/release/pull/676).

It seems that the API response for creating the issue is dumped to StdOut. This is overly noisy and should probably be changed (e.g.: only the issue # or a link to the issue should be printed).

Examples of the output can be found here:
- gcb logs: https://console.cloud.google.com/cloud-build/builds/658507ec-2039-4ca5-ba25-310afaad7ca9?project=kubernetes-release-test
- screenshot: ![image](https://user-images.githubusercontent.com/1401333/57715923-b6183d00-766f-11e9-87de-c0ca5e5b5065.png)

/area release-eng
/kind cleanup

**Comment by pswica** [comment]
@hoegaarden 
This should be resolved now. Let me know if it's good to close

**Comment by idealhack** [comment]
/remove-lifecycle stale

since the change of linked PR got reverted later after its merge.
