### ISSUE TITLE
[anago] publishing-bot issue does not assign correctly

### ISSUE THREAD

**Issue by hoegaarden** [kubernetes/release#713]
The publishing bot should *assign* the created issue to all team members of @kubernetes/publishing-bot-reviewers because GH does not allow to assign to a team.

This currently does not seem to work, as we don't see those assignments in the body of https://github.com/kubernetes/kubernetes/issues/77871 (we should see some `/assign someuser ...` instead of `<!-- no assignments -->`)

/area release-eng
/kind cleanup

----

The code which should add those assignments (for actual releases, not for mock releases) can be found at: 

https://github.com/kubernetes/release/blob/f591e2bcea45e8de3a25d9d443300787c515a91b/lib/gitlib.sh#L350-L363

The code for getting the member list for a team is here:

https://github.com/kubernetes/release/blob/f591e2bcea45e8de3a25d9d443300787c515a91b/lib/gitlib.sh#L384-L424

**Comment by hoegaarden** [comment]
This is still the case, even after https://github.com/kubernetes/release/pull/751 merged.

See https://github.com/kubernetes/kubernetes/issues/81354: it still shows `<!-- no assignments -->` where the `/assign ...` stanza should be ...

**Comment by nikhita** [comment]
> The publishing bot should assign the created issue to all team members of @kubernetes/publishing-bot-reviewers because GH does not allow to assign to a team.

Side note: IMO it should be fine even if everyone was not assigned. The team is being cc'd anyway. I guess that's good enough.

The person from the team taking the task of creating the PR can assign themselves when they take it up. Wdyt?

**Comment by hoegaarden** [comment]
1. Happy that is useful to you, even if the assignments currently don't work
1. I will keep the thing open for now and mark it as not-so-critical ... maybe we find on some other refactorings what the issue is ...

/label priority/important-longterm

**Comment by justaugustus** [comment]
@nikhita @hoegaarden -- Are there still things we need to do here?
/remove-lifecycle stale

**Comment by nikhita** [comment]
@justaugustus The original issue that folks are not assigned to the publishing-bot issue still remains. Though the publishing-bot-reviewers team is cc'd on the issue, so this isn't super critical (https://github.com/kubernetes/kubernetes/issues/84532).

**Comment by justaugustus** [comment]
@nikhita -- Has that been sufficient to get attention on those issues? If so, I say we close this out.

**Comment by nikhita** [comment]
> @nikhita -- Has that been sufficient to get attention on those issues?

Yes, IMO we can close this :+1:  but I'd wait for @hoegaarden to confirm as well (based on https://github.com/kubernetes/release/issues/713#issuecomment-520894246).

**Comment by hoegaarden** [comment]
I think we should do one of:

1. close this issues if publishing-bot-reviewers team is happy enough with the current state (mention only, no assignment)
    - the but also create an issue or PR to remove the the whole code which does not work anyway, so we don't bother 1.) porting that code path to `krel` or somewhere else 2.) just don't have that broken code in `k/release`
1. keep it open to track that we still want to implement the assignment somewhen somewhere

I don't have a strong opinion, the above conversation seems to suggest that people lean towards 1.).
