### ISSUE TITLE
branchff assumed dependencies 

### ISSUE THREAD

**Issue by idealhack** [kubernetes/release#721]
There are a few tools that [`branchff`](https://github.com/kubernetes/release/blob/9713cfe10469e64bc3c7ab5adb24115c13c9b826/branchff) currently requires but not necessarily provided in a fresh Linux environment:

- git
- go (recent version, different in release cycles)
- jq
- make

This is something like the [write access to `/usr/local` and sudo permission](https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/branch-manager/README.md#pre-requirements) but not documented. It better be checked at first in the script and exit if not found.

/area release-eng
/kind cleanup
/help
/good-first-issue

**Comment by pswica** [comment]
Can I try taking this on?
