### ISSUE TITLE
Shellcheck bash scripts

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#726]
The release repo has several bash scripts that could likely do with some linting.
Let's:
- Create a hack directory
- Copy in a `verify-shellcheck` script e.g.,
  - https://github.com/kubernetes/kubernetes/blob/master/hack/verify-shellcheck.sh
  - https://github.com/kubernetes/kubeadm/blob/master/kinder/hack/verify-shellcheck.sh
- Create a presubmit job, which can optionally be triggered
- Update scripts based on shellcheck results
- Set shellcheck presubmit to always run

/sig release
/area release-team
/help
/good-first-issue
/kind cleanup
/priority important-longterm

**Comment by pswica** [comment]
I would love to help with this, if that would be okay. I might need some additional guidance as I'm still fairly new to the release architecture.

**Comment by justaugustus** [comment]
@pswica -- sounds good! I'll put some additional pointers on this issue when I have a moment.

**Comment by pswica** [comment]
Cool thank you so much for taking the time to do that. I'll read over your notes, and keep reading the source code, and then start on this. Thanks again

**Comment by pswica** [comment]
Thanks again for letting me work on this and being open to providing guidance. I think looking around I'm starting to understand the scope of this--the release process is so cool! Please let me know if I'm on the right track.

Points 1&2: Easy (just mkdir and copy file over)
Point 3: Add a job here: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/release/release-config.yaml. Provide this job with a tag we can use. This script will just be a simple bash script that runs shellcheck on all the .sh files here.
Point 4: I guess here I may need some guidance. What type of updating should I do (totally rewrite all the scripts based on shellchecker's results)? 
Point 5. Have the job contain always_run: true

Can you let me know what else I'm missing?

**Comment by pswica** [comment]
I gave this another look after doing some contributions to sig-cli and getting the hang of contributing. I think I can do this now

**Comment by justaugustus** [comment]
With #740 merged, we're well on our way with this!
Assigning to @pswica, as he's made some excellent progress here and is now an org member :)

/assign @pswica 
/milestone v1.16

**Comment by pswica** [comment]
My first assignment !

**Comment by pswica** [comment]
That should be all of them. After these get finalized, reviewed, merged, etc. I'll make one last PR for any left (if needed) and then I will make a PR to make verify always-run that closes this issue.

**Comment by hoegaarden** [comment]
/remove-lifecycle stale

While this is IMHO not a pressing issue, making our shell scripts better should be a long term prio.

**Comment by justaugustus** [comment]
Obsoleted by https://github.com/kubernetes/release/issues/918.
/close
