### ISSUE TITLE
Support for Debian Buster

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#728]
A request was made to add support for Debian Buster: https://github.com/kubernetes/release/pull/720#discussion_r288733156

Buster is scheduled to be released around the same time as Kubernetes 1.15, so this will have to happen during the 1.16 release cycle instead.

/kind feature
/priority important-longterm
/milestone v1.16
/help
/sig release
/area release-eng

**Comment by justaugustus** [comment]
/milestone v1.16
cc: @praseodym

**Comment by praseodym** [comment]
Thanks! Creating an issue for this was still on my todo list :slightly_smiling_face:

**Comment by rkojedzinszky** [comment]
Hi All,

I am also waiting for Buster support. One thing I've found, that kubelet repeatedly inserts an iptables rule, which was not the case on debian stretch. I think, https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_network_linux.go#L64 is responsible for this rule being inserted several times, but I had no time to dig deeper.

Keep up with the great job!

**Comment by johscheuer** [comment]
@rkojedzinszky you probably stepped into this bug: https://github.com/kubernetes/kubernetes/issues/71305

**Comment by justaugustus** [comment]
This is kind of a confusing case due to naming.
During the release process, we publish all debs to the following repository: apt.kubernetes.io --> https://packages.cloud.google.com/apt/dists/kubernetes-xenial

In installation instructions like [kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl), you will see references to `kubernetes-xenial`, though the packages contained therein are known to work for distributor-supported versions of Debian/Ubuntu.

I'll assign myself here to document that idiosyncrasy.

Eventually, we'll move to repositories that are more _aptly_-named (pun intended), but there are quite a few things to do before we get to that stage.
You can track that work here:
- [Establish Kubernetes build/stage/release process on k8s-infra](https://github.com/kubernetes/release/issues/911)
- [Umbrella issue for a job that signs artifacts and uploads them to a GCS bucket](https://github.com/kubernetes/release/issues/913)

/remove-help
/assign
/milestone v1.18

**Comment by xmudrii** [comment]
@justaugustus Is there any update on this issue? Can we reassign it? I believe that we should move it away from the 1.18 milestone, but I don't have permission to do so.

**Comment by JulyIghor** [comment]
Is it going to happen?

**Comment by DaDummy** [comment]
Does that mean that Kubernetes dropped support for Debian?

**Comment by praseodym** [comment]
> Does that mean that Kubernetes dropped support for Debian?

No, the [installation instructions](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/) are still fine.

**Comment by DaDummy** [comment]
So support will be dropped once Debian Stretch is EOL or what does it mean that this issue was closed seemingly without a fix?

**Comment by praseodym** [comment]
> So support will be dropped once Debian Stretch is EOL or what does it mean that this issue was closed seemingly without a fix?

I'm not sure if there's anything left to do, Kubernetes works fine on Debian Buster.
