### ISSUE TITLE
cri-tools debs/rpms are not being published

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#739]
After taking a look at #737, I discovered a tangential problem, namely, we have not been publishing debs/rpms for `cri-tools` since v1.12.0:

### debs
```
$ apt-cache show cri-tools
Package: cri-tools
Version: 1.12.0-00
Installed-Size: 27665
Maintainer: Kubernetes Authors <kubernetes-dev@googlegroups.com>
Architecture: amd64
Description: Container Runtime Interface Tools
 Binaries that interact with the container runtime through the container runtime interface
Description-md5: c5a3d1c1edf49aa0775171c95e117e05
Homepage: https://kubernetes.io
Filename: pool/cri-tools_1.12.0-00_amd64_2d9f048a50a9dfeceebd84635f1322955aca6381d9c05b4d60b3da1edb7d856c.deb
Priority: optional
SHA256: 2d9f048a50a9dfeceebd84635f1322955aca6381d9c05b4d60b3da1edb7d856c
Section: misc
Size: 5342588

Package: cri-tools
Version: 1.11.1-00
Installed-Size: 27816
Maintainer: Kubernetes Authors <kubernetes-dev@googlegroups.com>
Architecture: amd64
Description: Container Runtime Interface Tools
 Binaries that interact with the container runtime through the container runtime interface
Description-md5: c5a3d1c1edf49aa0775171c95e117e05
Homepage: https://kubernetes.io
Filename: pool/cri-tools_1.11.1-00_amd64_e6300f0f4ec2fb5d6967533416580e1a22be90277944370ceb2551b04d7bc1a3.deb
Priority: optional
SHA256: e6300f0f4ec2fb5d6967533416580e1a22be90277944370ceb2551b04d7bc1a3
Section: misc
Size: 5319986

Package: cri-tools
Version: 1.11.0-00
Installed-Size: 27712
Maintainer: Kubernetes Authors <kubernetes-dev@googlegroups.com>
Architecture: amd64
Description: Container Runtime Interface Tools
 Binaries that interact with the container runtime through the container runtime interface
Description-md5: c5a3d1c1edf49aa0775171c95e117e05
Homepage: https://kubernetes.io
Filename: pool/cri-tools_1.11.0-00_amd64_768e5551f9badfde12b10c42c88afb45c412c1bf307a5985a4b29f4499d341bd.deb
Priority: optional
SHA256: 768e5551f9badfde12b10c42c88afb45c412c1bf307a5985a4b29f4499d341bd
Section: misc
Size: 5309448

Package: cri-tools
Version: 1.0.0-beta.1-00
Installed-Size: 26067
Maintainer: Kubernetes Authors <kubernetes-dev@googlegroups.com>
Architecture: amd64
Description: Container Runtime Interface Tools
 Binaries that interact with the container runtime through the container runtime interface
Description-md5: c5a3d1c1edf49aa0775171c95e117e05
Homepage: https://kubernetes.io
Filename: pool/cri-tools_1.0.0-beta.1-00_amd64_68880f674e9bf5959744d2cde7389a1a57b857e3fb769051ae0c506b19269ff0.deb
Priority: optional
SHA256: 68880f674e9bf5959744d2cde7389a1a57b857e3fb769051ae0c506b19269ff0
Section: misc
Size: 5069050
```

### rpms

```
# yum list cri-tools --show-duplicates
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: ewr.edge.kernel.org
 * extras: mirror.jaleco.com
 * updates: mirror.jaleco.com
Available Packages
cri-tools.x86_64                                                                                             1.0.0_beta.1-0                                                                                             kubernetes
cri-tools.x86_64                                                                                             1.11.0-0                                                                                                   kubernetes
cri-tools.x86_64                                                                                             1.11.1-0                                                                                                   kubernetes
cri-tools.x86_64                                                                                             1.12.0-0                                                                                                   kubernetes
```

Our current release tooling maps versions of cri-tools (>= 1.12.0) to the rest of the release packages.

This raises a set of questions...
- As we have not been publishing cri-tools debs/rpms, does that imply that release versions of cri-tools do not need to map (semver) to Kubernetes release semver? ref: https://github.com/kubernetes-sigs/cri-tools/issues/297
- Who are the set of maintainers for cri-tools?
- What is the release process for cri-tools? Is there an order of operations i.e., does it need to be released before/after the corresponding Kubernetes version?
- Have we not been requesting cri-tools packages be pushed to the deb/rpm repos OR does the tooling we currently utilize not support that/has something changed in the tooling to prevent this (during, say, the post-1.12.0 timeframe)? ref: https://github.com/kubernetes-sigs/cri-tools/issues/422
- How do we catch this in the future? k/k currently consumes the tarballs of cri-tools (https://github.com/kubernetes/kubernetes/pull/75658), so we're missing coverage here.

**Comment by BenTheElder** [comment]
> Who are the set of maintainers for cri-tools?

bump @Random-Liu

**Comment by cpointner** [comment]
Any news on this issue?

**Comment by justaugustus** [comment]
I'm working on a tool, `kubepkg`, which will make it easier to produce the packages. I'll continue work on this for 1.18.
/milestone v1.18

**Comment by feiskyer** [comment]
@justaugustus  any progress on this?

**Comment by saschagrunert** [comment]
A quick summary from my side as discussed yesterday in the release engineering meeting:

- We switched from release branches to master-based releases of cri-tools, which should theoretically allow us to use crictl v1.18.0 with Kubernetes v1.16.0 (just an example).
- I had some issues in the past with some incompatibles between different gRPC versions (regarding dial context). I think we can explicitly mention that in the cri-tools release notes if that happens in the future.

This should be fine, right?

Some parts of the story are already done, should I take it over @justaugustus? (I think https://github.com/kubernetes/kubernetes/issues/88408 needs to be fixed first, too)

**Comment by saschagrunert** [comment]
Probably related, we could publish the binary in the same way on the bucket to avoid "too many requests" failures when downloading from GitHub: https://github.com/kubernetes/kubernetes/pull/91239

**Comment by saschagrunert** [comment]
I think this can be closed, right? We now manually update the releases by pushing the artifacts to GCS and then change it in k/k on our side.

**Comment by saschagrunert** [comment]
/close

Feel free to reopen if I miss anything.

**Comment by paulcostinean** [comment]
Can this be reopened? 
Neither [stable](https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/filelists.xml) or [unstable](https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64-unstable/repodata/filelists.xml) seem to include cri-tools past the 1.13 release.
