### ISSUE TITLE
Got 403 when trying to get a release for release-1.4

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/release#74]
07800600576: Preparing
Post https://gcr.io/v2/kubernetes-release-test/hyperkube-arm64/blobs/uploads/: token auth attempt for registry: https://gcr.io/v2/token?
account=oauth2accesstoken&scope=repository%3Akubernetes-release-test%2Fhyperkube-arm64%3Apush%2Cpull&service=gcr.io request failed with 
status: 403 Forbidden
anago::logrun(): .
anago::release::docker::release(): /usr/local/google-cloud-sdk/bin/gcloud docker push gcr.io/kubernetes-release-test/hyperkube-arm64:v1.
4.0-beta.1

**Comment by david-mcmahon** [comment]
Can you attach a full log?

**Comment by pwittrock** [comment]
Yes I will do that.  I will need to scp them from my machine this afternoon.

**Comment by pwittrock** [comment]
[anago.log](https://github.com/kubernetes/release/files/465538/anago.txt)

**Comment by pwittrock** [comment]
Looks like the issue is pushing to gcr.io.  If I run the script as the production user then it tells me to switch to my personal gcloud user, but then it fails to push to gcr.  Is this because I am running in mock mode?

** /usr/local/google-cloud-sdk/bin/gcloud docker push gcr.io/kubernetes-release-test/kube-proxy:v1.4.0-beta.1**
The push refers to a repository [gcr.io/kubernetes-release-test/kube-proxy] (len: 1)
91dc026257fb: Preparing
Post https://gcr.io/v2/kubernetes-release-test/kube-proxy/blobs/uploads/: token auth attempt for registry: https://gcr.io/v2/token?account=oauth2accesstoken&scope=repository%3Akubernetes-release-test%2Fkube-proxy%3Apush%2Cpull&service=gcr.io request failed with status: 403 Forbidden

**Comment by pwittrock** [comment]
It looks like the production user only gets activated when running in nomock, and I do not have permissions to write to the mock registry

```sh
[[ "$registry" =~ gcr.io/ ]] && docker_push_cmd=("$GCLOUD" "docker")

  # Activate credentials for the k8s.production.user@gmail.com
  [[ "$registry" == "gcr.io/google_containers" ]] \
   && logrun $GCLOUD config set account k8s.production.user@gmail.com

  logecho
  logecho "Send docker containers to $registry..."
```

Log Line

>
anago::release::docker::release(): Send docker containers to gcr.io/kubernetes-release-test...

So it is just trying to push as me.  I am going to try to run in nomock mode to see if solves the problem.

**Comment by pwittrock** [comment]
I tried updating the script to always change the user and pushing the images still fails...

**Comment by david-mcmahon** [comment]
Looks like you need permission to gcr.io/kubernetes-release-test.
There's also a bug that this isn't checked in the prereqs.

**Comment by pwittrock** [comment]
How do I get that :P

**Comment by david-mcmahon** [comment]
Auth issue, worked out at the time.
Since then a check has been added to validate access to kubernetes-release-test as well.
