### ISSUE TITLE
Add check to verify-boilerplate

### ISSUE THREAD

**Issue by hoegaarden** [kubernetes/release#777]
... like we do in other repos as part of `make verify`

We can copy the things from `k/k` or use some shared thing, e.g. from `k/repo-infra` (... but there is already [a discussion](https://github.com/kubernetes/repo-infra/issues/97) going on how and if we want to do that ...)

/cc @pswica @kubernetes/release-engineering @kubernetes/licensing

**Comment by nikhita** [comment]
> . from k/repo-infra (... but there is already a discussion going on how and if we want to do that ...)

would prefer this long-term, but I don't see us consuming repo-infra anytime soon (even if the related PR gets merged). :(

IMO it's fine to copy things over from k/k...

**Comment by saschagrunert** [comment]
This seems done from my point of view, we now check verify boilerplate.
/close

**Comment by justaugustus** [comment]
Added in https://github.com/kubernetes/release/pull/889, https://github.com/kubernetes/release/pull/890, and https://github.com/kubernetes/release/pull/892.
