### ISSUE TITLE
Add tests for shellscripts

### ISSUE THREAD

**Issue by hoegaarden** [kubernetes/release#779]
Proposal:
- add a make target `test`
- add the following to that target:
  - `go test ./...`
  - `bazel test //lib/*`
  - ... potentially others
- change `pull-release-unit` to run `make test` instead of `go test ./...`

Alternatively:
- add a make target `test-sh-unit` (or similar)
- add `bazel test //lib:*` to that target
- add a separate prow job to run that

What do you all think?

/cc @kubernetes/release-engineering @pswica

**Comment by pswica** [comment]
BIG +1
I like the first approach, myself, since I feel like the bazel tests will be mostly unit tests as well. I can help with this when I'm done with my shellcheck project.

**Comment by hoegaarden** [comment]
I think that we can close this (feel free to reopen, ofc), because:

[msh]: https://github.com/kubernetes/release/blob/a14a3aee6459ab329d782c7b99e67d68b7726b24/Makefile#L58
[mgo]: https://github.com/kubernetes/release/blob/a14a3aee6459ab329d782c7b99e67d68b7726b24/Makefile#L54
[mtest]: https://github.com/kubernetes/release/blob/a14a3aee6459ab329d782c7b99e67d68b7726b24/Makefile#L51
[prowjob]: https://github.com/kubernetes/test-infra/blob/d04b70c118e93ac49961cac74b31c362f15c123d/config/jobs/kubernetes/release/release-config.yaml#L41-L56
[spyglass]: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/release/883/pull-release-unit/1178732880600240130
[mhelp]: https://github.com/kubernetes/release/blob/a14a3aee6459ab329d782c7b99e67d68b7726b24/Makefile#L78-L92
[mdefault]: https://github.com/kubernetes/release/blob/a14a3aee6459ab329d782c7b99e67d68b7726b24/Makefile#L18

- we have make targets:
  - [`test-sh`][msh] for shell script tests
  - [`test-go`][mgo] for go tests
  - [`test`][mtest] which runs the the above two targets
- `make test` [runs on prow][prowjob] and we see the [results in spyglass][spyglass]
- we have documented that with [`make help`][mhelp], which [is also the default make target][mdefault]

/close
