### ISSUE TITLE
Token should be regenerated without newlines

### ISSUE THREAD

**Issue by hoegaarden** [kubernetes/release#811]
In https://github.com/kubernetes/release/pull/801 a new token was generated and added to the GCB config. It seems that this token was added with a newline at the the end. Presumably the encrypted token was generated with

```
echo "$GITHUB_TOKEN" | gcloud kms encrypt ...
```
instead of (note the `-n`!)
```
echo -n "$GITHUB_TOKEN" | gcloud kms encrypt ...
```

When we have fixed all the other issues with k/release we should add the trimmed version of the token (or of a new token) to our GCB config.

gcb docs: https://cloud.google.com/cloud-build/docs/securing-builds/use-encrypted-secrets-credentials#encrypting_an_environment_variable_using_the_cryptokey

ref: https://github.com/kubernetes/release/pull/810

/assign @justaugustus @calebamiles

**Comment by hoegaarden** [comment]
/remove-lifecycle rotten
/lifecycle stale

I think it does not hurt either way to rotate this secret once in a while.

**Comment by hoegaarden** [comment]
/remove-lifecycle stale
/lifecycle frozen

I think it does not hurt either way to rotate this secret once in a while.

**Comment by justaugustus** [comment]
We've moved the GitHub token to the prod releng project (`k8s-releng-prod`) in https://github.com/kubernetes/release/pull/1163 and generated it as follows:

```shell
gcloud kms encrypt --location global --keyring <keyring> \
  --key <key> --ciphertext-file=- --plaintext-file=<(echo -n '<github-token>') \
  | base64 -w 0
```

/remove-lifecycle stale
/close
