### ISSUE TITLE
move push-build to kubernetes/kubernetes

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/release#829]
This is one of the only reasons lots of CI jobs need to check out this repo, if we move this over we can prevent changes to this repo from instantly breaking most of CI :-)

discussed in sig-release today, cc @justaugustus

**Comment by javier-b-perez** [comment]
if we move push-build into k8s/k8s meas we can could docker manifests at the same time we do are building the tar files.
+1

**Comment by justaugustus** [comment]
As an update, we're working on [rewriting the shell tools in this repo in Go](https://github.com/kubernetes/release/issues/918).
Daniel is in the process of [porting push-build](https://github.com/kubernetes/release/pull/941), so assigning him here.

/assign @hasheddan 
/priority important-longterm
/remove-lifecycle rotten

**Comment by justaugustus** [comment]
@hasheddan -- status update?

**Comment by hasheddan** [comment]
@justaugustus this fell down my queue a few times but I have reprioritized and hope to have progress soon!

**Comment by saschagrunert** [comment]
I think push-build would be one of the next big krel commands to be used in anago. Do you need help on the implementation @hasheddan?

**Comment by hasheddan** [comment]
@saschagrunert agreed! I have really fallen behind on implementing this, but the stub is already present in `krel`: https://github.com/kubernetes/release/blob/master/cmd/krel/cmd/push.go

If you have bandwidth I would be happy for you to pick this up :)

**Comment by saschagrunert** [comment]
@hasheddan I don't think that this is still relevant for us, right? Moving to krel seems already work in progress.

**Comment by hasheddan** [comment]
@saschagrunert correct :)

/close
