### ISSUE TITLE
RFC -- testgrid screenshotting

### ISSUE THREAD

**Issue by hoegaarden** [kubernetes/release#831]
# RFC -- testgrid screenshotting

Some people use https://gist.github.com/hoegaarden/0e9aab9d29885074a0f60f8398880397 for adding screenshots to the "cutting issue", something like [that](https://github.com/kubernetes/sig-release/issues/714#issuecomment-509130796).

We could automate that, so we have a consistent way to do add this data to the "cutting issue" and have it better integrated in our workflow.

I can think of two ways how to implement that:

#### create a prow plugin that does that

if you do something like ...
```yaml
# getting the release from the milestone, getting the default (blocking & informing, or just blocking)
/testgrid screenshot
# not only failing boards, but also flaking ones
/testgrid screenshot flaky,failing
# specifically specify, which boards and which states we are interested in
/testgrid screenshot faling release-1.13-blocking,release-1.13-informing
```
... a prow plugin could got off, gather the screenshots, and add that comment automatically.

#### integrate into anago

`anago` could also, automatically, go and search for an issue with the matching release number, gather the screenshots and ad a comment to the issue. We could also think about `anago` auto-creating that issue if it cannot find one.

Potential implementation and even-further-in-future things we could think about:
- the actual implementation can be done in go and be [compiled](https://github.com/kubernetes/release/blob/master/gcb/stage.yaml#L16-L22) and used similar to [blocking-testgrid-tests](https://github.com/kubernetes/release/tree/master/cmd/blocking-testgrid-tests)
- `anago` could use that (auto-created) issue to track some metrics (how long things took, where the artifacts can be found, ...) by itself

/cc @kubernetes/release-managers 
/cc @kubernetes/release-engineering 
/area release-eng
/kind feature
/shrug

**Comment by cpanato** [comment]
a prow plugin will be nice

**Comment by hoegaarden** [comment]
https://github.com/kubernetes/release/pull/845

**Comment by hoegaarden** [comment]
[`testgridshot`][tgs] has been merged into `k/release` and is part of the release process now, so we can
/close this.

[tgs]: /kubernetes/release/blob/master/testgridshot
