### ISSUE TITLE
Analyze current release tooling

### ISSUE THREAD

**Issue by bartsmykla** [kubernetes/release#837]
Hi,

As we discussed on today's release team meeting I should create this issue earlier. Sorry about that. I'm working on analyzing current release tooling/scripting, and want to create good, as a result I want to create a document with list of dependencies between tools, and a logical flow, which can help in future rewriting.

Currently I'm working on flow charts like this one: https://cdn.saco.pl/anago/index.html which can be helpful for everyone (for me they definitely are).

I'm open to any suggestion or critique. If you would like to get anything else from that koind of document, please feel free to write about it. I'll do my best. :-)

**Comment by idealhack** [comment]
@bartsmykla awesome, thanks a ton for this!

cc @kubernetes/release-engineering 
/area release-eng

**Comment by bartsmykla** [comment]
flow chart for `branchff`: https://cdn.smykla.blog/branchff/index.html

**Comment by bartsmykla** [comment]
Temporary description:
| Element | What Represents |
| ------- | --------------|
| yellow background | function call |
| yellow background with opacity 50% | logs |
| yellow background with red border | function call which breaks execution |
| teal background | variable (re)declaration |
| pink/purple background | function declaration |
| green background | source ... |
| purple dashed border | loop |

**Comment by bartsmykla** [comment]
flow chart for `changelog-update`: https://cdn.smykla.blog/changelog-update/index.html

**Comment by bartsmykla** [comment]
flow chart for `prin`: https://cdn.smykla.blog/prin/index.html

**Comment by bartsmykla** [comment]
flow chart for `gcbmgr`: https://cdn.smykla.blog/gcbmgr/index.html

**Comment by bartsmykla** [comment]
flow chart for `compile-release-tools`: https://cdn.smykla.blog/compile-release-tools/index.html

**Comment by bartsmykla** [comment]
flow chart for `find_green_build`: https://cdn.smykla.blog/find_green_build/index.html

**Comment by bartsmykla** [comment]
Ahh, My domain expired. Let me move it to some other one.
