### ISSUE TITLE
release notes generator does not pick up edits to PRs

### ISSUE THREAD

**Issue by tpepper** [kubernetes/release#838]
release-notify for 1.15.2, 1.14.5, and 1.13.9 did not pick up the edited PRs release note content after the embargo was lifted and we were publishing info on the releases.  This feels like a fairly normal workflow.  The notes do come via the GitHub API.  Probably additional code is needed to handle pulling a release note stanza from a stack of edited PR descriptions?

**Comment by tpepper** [comment]
/sig release
/area release-eng

@kubernetes/patch-release-team

**Comment by saschagrunert** [comment]
Hey @tpepper, may I ask you for a reproducer of this? I had a look into the generator sources and it seems to pick always the latest PR version via the GitHub API. The internal de-duplication cache works based on the text (the content) of the note, so this should not fail as well.

**Comment by idealhack** [comment]
note: this happened again for pre-release notifications in Nov. https://kubernetes.slack.com/archives/CJH2GBF7Y/p1573233887162900

**Comment by saschagrunert** [comment]
I suggest to continue there https://github.com/kubernetes/release/issues/918 due to the fact that we want to replace the script with the golang based version.

**Comment by saschagrunert** [comment]
This should be fixed when using `krel changelog` for patch releases (not yet implemented)

/remove-lifecycle stale

**Comment by saschagrunert** [comment]
@hoegaarden do you think we are ready to merge the code paths for patch release announcements and minor releases?

**Comment by saschagrunert** [comment]
This should be fixed, the old release notes scripts do not exist any more on the master branch.

/close
