### ISSUE TITLE
build scripts README.md

### ISSUE THREAD

**Issue by tpepper** [kubernetes/release#846]
The https://github.com/kubernetes/release/tree/master/build subdirectory of scripts needs a README.md describing the tools, example invocations, expected outputs, tests.

**Comment by hoegaarden** [comment]
https://github.com/kubernetes/release/pull/825 would address parts of it, by moving all the image related stuff into a separate directory

**Comment by justaugustus** [comment]
@kubernetes/release-engineering -- This is a good one for someone to pick up.

/lifecycle frozen
/unassign
/help

**Comment by hariz22** [comment]
end sha

**Comment by hariz22** [comment]
delete

**Comment by justaugustus** [comment]
Let's make sure the usage docs go in `docs/krel/<tool>.md`

**Comment by justaugustus** [comment]
First pass PR is here: https://github.com/kubernetes/release/pull/1201
