### ISSUE TITLE
Safe templating of json in bash scripts

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#853]
There are a few places in our scripts where we template JSON directly in bash e.g., https://github.com/kubernetes/release/blob/c32c094ff025d4d61fc27e575b489a174090c630/anago#L1131-L1138

As @hoegaarden [mentions](https://github.com/kubernetes/release/pull/849#discussion_r315283633), it'd be nicer/less scary to handle this in a safer way via jq, like this: https://github.com/kubernetes/release/blob/c32c094ff025d4d61fc27e575b489a174090c630/lib/gitlib.sh#L341-L352

This is another good one for a Release Manager Associate to take up.

/help
cc: @kubernetes/release-engineering 
/area release-eng
/priority important-longterm
/kind cleanup

**Comment by hasheddan** [comment]
@justaugustus I am happy to take this one!

/assign @hasheddan
