### ISSUE TITLE
missing images for the ci/latest.txt label

### ISSUE THREAD

**Issue by neolit123** [kubernetes/release#854]
currently, it appears that the ci/latest.txt label points to images that are missing:

```
curl -L https://dl.k8s.io/ci/latest.txt
v1.17.0-alpha.0.400+b8e8130a9195d5
```

missing `400` tagged image for a control-plane component:
https://console.cloud.google.com/gcr/images/kubernetes-ci-images/GLOBAL/kube-apiserver?gcrImageListsize=30

at the time of writing this report the latest one is at `398`
![screenshot](https://user-images.githubusercontent.com/331852/63442630-1ae7ee00-c43c-11e9-8460-8eb619c87963.png)

ci-cross on the other hand returns `398`:
```
curl -L https://dl.k8s.io/ci-cross/latest.txt
v1.17.0-alpha.0.398+bfb69dbb8f0105
```

slack conversation:
https://kubernetes.slack.com/archives/C2C40FMNF/p1566398444348500

/kind bug
/priority critical-urgent

**Comment by neolit123** [comment]
btw, it will be nice to add an e2e that makes sure that these labels point to actual images.
possibly under: https://k8s-testgrid.appspot.com/sig-release-misc
?

**Comment by justaugustus** [comment]
Investigating and confirming that the `ci-cross` image version trails the `ci` version number:

```shell
$ curl -L https://dl.k8s.io/ci/latest.txt
v1.17.0-alpha.0.423+1a53325550f6d5
$ curl -L https://dl.k8s.io/ci-cross/latest.txt
v1.17.0-alpha.0.421+bad4d0ee963a71
```

**Comment by justaugustus** [comment]
Detailed write-up on this in https://github.com/kubernetes/test-infra/pull/14030

**Comment by justaugustus** [comment]
@neolit123 -- Closed via https://github.com/kubernetes/test-infra/pull/14030
Please use https://dl.k8s.io/ci/ markers moving forward instead of https://dl.k8s.io/ci-cross/.

/close

**Comment by neolit123** [comment]
@justaugustus 
thanks, let's see if someone (outside of kubeadm users) complains about this.
hopefully not.
