### ISSUE TITLE
Testing bash scripts: PR feedback

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#855]
@hoegaarden made some good points in a [recent PR](https://github.com/kubernetes/release/pull/849) that we should investigate...

> Also, can we maybe get some tests in place? E.g. when we introduce new files, I'd expect a test to check if a file was created on disk or a test that check if (a mock) curl has been called for those files.

> I am not sure if we want to do that: When I have a trap already set up, and "blindly" use that function it would override (= remove) my trap.
I think, the least we should do is document that behaviour.
I guess, we could also return the tmp_dir and leave it to the caller to do whatever with that?
We could also have test_main setup a tmp_dir for each test case it runs and export that as TMPDIR or pass in to the TEST_... function? test_main could just set a exit trap to remove the dir in the subshell it runs the test in ...

> we don't have any test in place which actually tests if the shasum files would be uploaded when they exist, which I believe is the interesting bit
I don't want to block on all that, esp. because I believe testing update_github_release will be a bit painful. But I guess it will force us to refactor that func into something that is easier to test and easier to reason about.
In general, we (esp. myself) could do a better job on documenting the test cases by at least stating what we are intending to test and why.

This is a good issue for a Release Manager Associate to run with.

/help
/priority important-longterm
/kind test cleanup
cc: @kubernetes/release-engineering

**Comment by girikuncoro** [comment]
@justaugustus I'm an associate and interested to pick this up, will need pointer on which files/scripts should I start looking at? Do we have test somewhere or we want to start introducing test by investigating this issue? Looking at the issue description seems there are tons of cases that we want to test, I think we should break it down and prioritize.

**Comment by justaugustus** [comment]
Removing the rotten label so this doesn't pop up again in sweeps.
/remove-lifecycle rotten

I'm fine with this staying closed as we should prioritize moving away from the shell-based tools and  over to go --> https://github.com/kubernetes/release/issues/918
