### ISSUE TITLE
branchff fails depending on the way git remotes are configured

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#856]
Running `branchff` today fails when I do not specify `RELEASE_TOOL_REPO`.
I think this has to do with the way my remotes are set up.

```shell
$ ./branchff release-1.16
branchff: BEGIN main on auggievmw01 Wed Aug 21 10:17:56 EDT 2019

fatal: 'origin
up' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Checking /home/augustus/go/src/k8s.io/release state: FAILED

/home/augustus/go/src/k8s.io/release is not up to date.
$ git pull

branchff: DONE main on auggievmw01 Wed Aug 21 10:17:56 EDT 2019 in 0s
```

My remotes:
```shell
$ git remote -v
a	git@github.com:justaugustus/release.git (fetch)
a	git@github.com:justaugustus/release.git (push)
a-http	https://github.com/justaugustus/release.git (fetch)
a-http	https://github.com/justaugustus/release.git (push)
origin	https://github.com/kubernetes/release (fetch)
origin	https://github.com/kubernetes/release (push)
up	git@github.com:kubernetes/release.git (fetch)
up	git@github.com:kubernetes/release.git (push)
```

I can run `branchff` successfully when issuing the following:
```shell
RELEASE_TOOL_REPO="https://github.com/kubernetes/release" ./branchff release-1.16
```

This is a good one for a Release Manager Associate to pick up.

/help
/priority important-soon
/milestone v1.16
/kind bug
cc: @kubernetes/release-engineering

**Comment by tpepper** [comment]
Interesting that `RELEASE_TOOL_REPO="https://github.com/kubernetes/release"` makes it run.

Could @nikhita 's https://github.com/kubernetes/release/commit/5a3469695dd4bc0653ab818efcdc83734c26c113 be in play?

Can you share your .gitconfig?

We do have multiple places where tools tend to expect an upstream/downstream forked GitHub workflow where remote "origin" is your repo fork (as an ssh url) and remote "upstream" is the k/* repo (as an https url, ideally with the push_url set to something invalid).  This is partly documented for example in the cherry pick developer guide, but it is not in the branch or patch manager role handbook.

If whoever tackles this issue does cleaning up beyond documentation, I'd like to request the code be opinionated:
1. default to the above described layout
1. complain to the user if the above layout is not what is encountered in the local config
1. optionally allow overriding with a non-standard remote get-url and name

**Comment by tpepper** [comment]
I think most people do something like:

```
$ git remote -v
origin	git@github.com:tpepper/release.git (fetch)
origin	git@github.com:tpepper/release.git (push)
upstream	https://github.com/kubernetes/release.git (fetch)
upstream	no_push (push)
```

and parts of that are definitely encoded in tooling.

**Comment by justaugustus** [comment]
Yep. Tim's layout is what the standard should look like.

I'd personally love to see some fuzzy match where I can be lazy and say `RELEASE_TOOL_REPO="kubernetes/release"` instead of `RELEASE_TOOL_REPO="https://github.com/kubernetes/release"` and it'll know that I either mean `https://github.com/kubernetes/release.git` or `git@github.com:kubernetes/release.git`.

Here's my `.gitconfig`:
```
[user]
    name = Stephen Augustus
    email = <snip>
    signingkey = 8006EEE82E82A6A6
[alias]
    co = checkout
    st = status

    # log with short SHA, description, history graph of latest 20 commits
    l = log --pretty=oneline -n 20 --graph --abbrev-commit

    # View the current working tree status using the short format
    s = status -s

    # Show verbose list of tags, branches, and remotes
    tags = tag -l
    branches = branch -a
    remotes = remote -v

    # List commiters with number of commits
    contributors = shortlog --summary --numbered
[core]
    editor = vim
    excludesfile = ~/.gitignore
[color]
    ui = true
[gpg]
	program = gpg2
[credential]
    helper = cache
```

**Comment by justaugustus** [comment]
I fixed my particular issue in https://github.com/kubernetes/release/pull/915, but I'd still like to see what @tpepper mentioned addressed, if anyone is interested in taking this:

> If whoever tackles this issue does cleaning up beyond documentation, I'd like to request the code be opinionated:
> 
> 1. default to the above described layout
> 2. complain to the user if the above layout is not what is encountered in the local config
> 3. optionally allow overriding with a non-standard remote get-url and name

**Comment by justaugustus** [comment]
branchff is deprecated, so this issue is obsolete.

/remove-lifecyle rotten
/close
