### ISSUE TITLE
Don't install CNI plugins to /opt

### ISSUE THREAD

**Issue by Silvanoc** [kubernetes/release#862]
**What would you like to be added**:

Let RPM and DEB packages install CNI plugins under `/usr/lib/cni`, `/usr/lib/cni-plugins` or similar.

**Why is this needed**:

Current installation path for CNI plugins (`/opt/cni`) is not aligned with Debian and Fedora packaging best practices (even possibly policies).

In the case of *Fedora*, [previous versions](https://pagure.io/packaging-committee/blob/93d6d1cdac29c51b336e992e0546a1a936680d02/f/Packaging:Guidelines.mw#_248) of their packaging guidelines were explicitly stating that packages shouldn't install any files under `/opt`. For a [documented reason](https://pagure.io/packaging-committee/issue/451) that I cannot fully understand, they [reformulated it 4 years ago](https://pagure.io/packaging-committee/c/3aa092465b5474a43552f35c4102507a8df366b6) in a way that IMHO made a bit [unclearer](https://docs.fedoraproject.org/en-US/packaging-guidelines/#_limited_usage_of_opt_etcopt_and_varopt), but the essence remains the same: *Fedora packages shouldn't install files under `/opt`*.

In the case of *Debian* there are [no clear/explicit policies](https://www.debian.org/doc/debian-policy/ch-opersys.html) forbidding it, but the standard linter for Debian packages ([lintian](https://packages.debian.org/search?keywords=lintian)) reports it as an [error in the package](https://lintian.debian.org/tags/dir-or-file-in-opt.html).

**Comment by Silvanoc** [comment]
> you should file this issue against https://github.com/kubernetes/release for better visibility, currently releases use the specs there. that repo also has much lower volume of interaction than this one sweat_smile

@BenTheElder thanks for the information. Thankfully @justaugustus already did so.

**Comment by Silvanoc** [comment]
> I think that those guidelines only apply to the distribution packages, i.e. the ones that each distribution package and consider part of its distribution.
> In this case, IIUIC, these are `kubernetes` packages. Most of the distros follow the FHS https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard, and based on that seem that the `/opt` folder seems to be a good place based on the content.
> 
> > /opt is reserved for the installation of add-on application software packages.
> 
> > A package to be installed in /opt must locate its static files in a separate /opt/ or /opt/ directory tree, where  is a name that describes the software package and  is the provider's LANANA registered name.
> 
> https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html#optAddonApplicationSoftwarePackages

The FHS documentation is a bit too unclear, therefore the distributions are implementing it differently. In the case of Debian, the package linter (_lintian_) would report it as an issue.

Fedora used to have a policy similar to that of Debian, but they changed it and [now it's allowed](https://docs.fedoraproject.org/en-US/packaging-guidelines/#_limited_usage_of_opt_etcopt_and_varopt).

@aojea you appear to be working for SuSE. Don't you have similar policies to those of Debian or Fedora?

Anyway, even if K8s doesn't care for the distribution policies, some consistency would be desirable and installing some things to `/opt` and some others to `/usr/bin` is not consistent.

**Comment by aojea** [comment]
> @aojea you appear to be working for SuSE. Don't you have similar policies to those of Debian or Fedora?

yeah, but those policies are for the packages that are part of the distribution, this is an external package that works with that distribution, but is not released as part of it. Per example, if you have a bug with this package in a specific distro, you can't open a bug in that distro, right? They really don't know who is packaging this or who is the maintainer.

These are distribution kubernetes packages:

https://build.opensuse.org/package/show/devel:kubic/kubernetes
https://apps.fedoraproject.org/packages/kubernetes

If you want to include a new package in a distribution you have to follow a process and, of course, obey the policies. 

Ref:
https://www.debian.org/doc/manuals/developers-reference/ch05.en.html#newpackage
https://en.opensuse.org/openSUSE:How_to_contribute_to_Factory
https://fedoraproject.org/wiki/New_package_process_for_existing_contributors

> Anyway, even if K8s doesn't care for the distribution policies, some consistency would be desirable and installing some things to /opt and some others to /usr/bin is not consistent.

Don't get me wrong, I'm not saying we should not care about consistency and best practices, just wanted to point out the difference between a distribution package and a third party package :)

**Comment by Silvanoc** [comment]
> yeah, but those policies are for the packages that are part of the distribution, this is an external package that works with that distribution, but is not released as part of it. Per example, if you have a bug with this package in a specific distro, you can't open a bug in that distro, right? They really don't know who is packaging this or who is the maintainer.

Fully agree if thinking on OpenSuSE or Fedora. But in Debian there's not a big difference between distribution packages and _properly debianized_ external packages (you would use `lintian` in both cases). In fact the packages typically first get created as external packages and then move into the distribution. Therefore properly debianized packages are expected to be in a shape that can be taken over by the distribution and therefore it raises the probability of directly getting them distribution supported.

Of course, SuSE and RedHat are investing resources on K8s, therefore I can understand that the `/opt` installation has more backing. Debian will then have to care itself for "distribution packaging", what will take much longer. In any case, if you decide for the `/opt` way, then I'd at least move everything there for consistency.

> Don't get me wrong, I'm not saying we should not care about consistency and best practices, just wanted to point out the difference between a distribution package and a third party package :)

I didn't get you wrong, I just oversaw that Debian is probably the distribution handling it a bit differently here and you are right WRT OpenSuSE and Fedora.

BTW, if installing to `/opt`, according to the FSH and since there's no LANANA provider registered for K8s, then `/opt/<package>` should be used. Or K8s gets registered as provider in LANANA. The last option is simply ignoring the standard and using things like `/opt/kubernetes`, `/opt/cni`, ...

**Comment by justaugustus** [comment]
Closing as I agree with @BenTheElder's [assessment](https://github.com/kubernetes/release/issues/862#issuecomment-525408804).

See here to track the deprecation of `kubernetes-cni` deb/rpm packages: https://github.com/kubernetes/release/issues/885

/close
