### ISSUE TITLE
jobResultsCache.json is deprecated

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/release#873]
This code reads `jobResultsCache.json` from prowjob GCS results. https://github.com/kubernetes/release/blob/master/lib/releaselib.sh#L42

... only `bootstrap.py` publishes this https://github.com/kubernetes/test-infra/search?q=jobResultsCache&unscoped_q=jobResultsCache

bootstrap.py has been deprecated for around a year. the pod-utils don't write anything like this as far as I know.

this code should either be removed or move to something else

**Comment by justaugustus** [comment]
I haven't had time to work on this, but we should try and figure this out soon.
@kubernetes/release-engineering -- Any takers?

/remove-lifecycle stale
/lifecycle frozen
/milestone v1.18
/unassign
/help

**Comment by cpanato** [comment]
I can try that, just need the entrypoint @BenTheElder @justaugustus 
/assign
/remove-help

**Comment by hoegaarden** [comment]
@cpanato My guess is, this is part of the `find_green_build` and all that business. All that is super weird & unreadable. If we'd find a way to refactor that and figure out what we **actually want and need** that'd be great. I am not convinced that the `find_green_builds` is actually doing the right and useful thing right now.

**Comment by cpanato** [comment]
made a comment [here](https://kubernetes.slack.com/archives/CJH2GBF7Y/p1576057678417100)
don't know if remove or replace if replace the finished.json is the best one? but that does not have the buildnumber, do we need that? or can use the commit hash?

**Comment by cpanato** [comment]
pinging again @BenTheElder @justaugustus when have time can look in the slack post? 😄 
i can open a PR as well  removing that and we discuss there 😬

**Comment by BenTheElder** [comment]
I don't really remember the details of the metadata formats but they should be documented in test-infra. If not that's a prow bug for sure.

**Comment by justaugustus** [comment]
@cpanato -- Can provide some pointers next week. I'm still burning down the post-holiday queue.

**Comment by saschagrunert** [comment]
That's done, we do not use the job results cache any more inside this repository. 
/close
