### ISSUE TITLE
ci/latest.txt should be updated after this version's artifacts are uploaded

### ISSUE THREAD

**Issue by neolit123** [kubernetes/release#897]
in this slack comment:
https://kubernetes.slack.com/archives/C2C40FMNF/p1570666879009900

i've mentioned that the `ci/latest.txt` marker can end up pointing to a version that still does not have all the artifacts uploaded to the GCS bucket:
https://console.cloud.google.com/storage/browser/kubernetes-release-dev/ci/?pli=1

since this failure can be seen in the kubeadm CI:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-upgrade-1-16-master
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-upgrade-1-16-master/1182765664260067329/artifacts/task-01-add-kubernetes-versions-log.txt

> HTTP GET https://storage.googleapis.com/kubernetes-release-dev/ci/v1.17.0-alpha.1.365+a8478746554769/bin/linux/amd64/kubelet failed: 404 Not Found

i wanted to reproduce it, and i did with a bash script that ran for a while.

the following gist contains further details:
https://gist.github.com/neolit123/dc159e43b93b835c5e3a73e1bba092d1

please escalate the priority if needed.
we are probably going to move the kubeadm e2e to `latest-bazel.txt`, but to my knowledge there might be more test jobs that use `latest.txt`.

cc @justaugustus @dims @fabriziopandini @alejandrox1  @guineveresaenger 
/sig release testing
/priority important-longterm
/kind flake

**Comment by saschagrunert** [comment]
For what I can see is that the release lib generates the file pointers here: https://github.com/kubernetes/release/blob/a15442f0d30c7578a79bdc79e3fe706ba8d09bc4/lib/releaselib.sh#L780-L834

There is no file-based validation inside this function, but we could add one like this:

```bash
#!/usr/bin/env bash
set -euo pipefail

RELEASE=v1.19.0-alpha.0.779+84dc7046797aad
PATHPREFIX=/go/src/k8s.io/kubernetes/_output/gcs-stage/$RELEASE/
SUMS=$(gsutil cat gs://kubernetes-release-dev/ci/$RELEASE/SHA256SUMS)
FILES=$(echo "$SUMS" | awk '{print $2}')

ARTIFACTS=(
    extra/gce/master.yaml
    extra/gce/configure.sh
    extra/gce/shutdown.sh
    extra/gce/windows/k8s-node-setup.psm1
    extra/gce/windows/configure.ps1
    extra/gce/windows/common.psm1
    extra/gce/windows/user-profile.psm1
    extra/gce/windows/install-ssh.psm1
    extra/gce/node.yaml
    kubernetes-test-portable.tar.gz
    kubernetes-test-linux-amd64.tar.gz
    kubernetes-src.tar.gz
    kubernetes.tar.gz
    bin/linux/amd64/kube-proxy.docker_tag
    bin/linux/amd64/kubectl
    bin/linux/amd64/kube-controller-manager.docker_tag
    bin/linux/amd64/kube-controller-manager
    bin/linux/amd64/kube-controller-manager.tar
    bin/linux/amd64/kube-proxy
    bin/linux/amd64/kubelet
    bin/linux/amd64/kube-scheduler
    bin/linux/amd64/apiextensions-apiserver
    bin/linux/amd64/kube-proxy.tar
    bin/linux/amd64/kube-apiserver
    bin/linux/amd64/mounter
    bin/linux/amd64/kube-apiserver.docker_tag
    bin/linux/amd64/kube-scheduler.tar
    bin/linux/amd64/kube-scheduler.docker_tag
    bin/linux/amd64/kubeadm
    bin/linux/amd64/kube-apiserver.tar
    kubernetes-node-linux-amd64.tar.gz
    kubernetes-manifests.tar.gz
    kubernetes-server-linux-amd64.tar.gz
    kubernetes-client-linux-amd64.tar.gz
)

for ARTIFACT in "${ARTIFACTS[@]}"; do
    FOUND=
    for FILE in $FILES; do
        STRIPPED_FILE="${FILE#"$PATHPREFIX"}"
        if [[ "$ARTIFACT" == "$STRIPPED_FILE" ]]; then
            echo "Found $STRIPPED_FILE"
            FOUND=true
            break
        fi
    done
    if [[ -z $FOUND ]]; then
        echo "Artifact $ARTIFACT not found on bucket"
        exit 1
    fi
done
```
A drawback is the hard-coded list of expected `$ARTIFACTS`, which can change over time and this will releases fail. @neolit123 do you know any better way how to validate which artifacts are expected on the bucket?

**Comment by neolit123** [comment]
i have not seen this issue recently in the kubeadm / kinder jobs that use ci/latest
wondering if something is masking it or whether it was resolved at some point.

**Comment by justaugustus** [comment]
The marker gets written after artifact pushes, so any missing artifacts would've happened on an incomplete build.

https://github.com/kubernetes/release/pull/1457 also switches some ordering, so that GH releases don't publish without a successful artifact push.

Should all be fixed now, but feel free to reopen if you notice any issues.

/remove-lifecycle stale
/close
