### ISSUE TITLE
relnotes: cherry-pick note should supersede parent PR's NONE

### ISSUE THREAD

**Issue by tpepper** [kubernetes/release#899]
The changelog for 1.16.1 at:
https://github.com/kubernetes/kubernetes/commit/0960c74c3788b1724bd7e7b9933bc49c7e5b5afa#diff-7ce0da8ad6adf39c0d46fc012603d6aaR163

is missing four notes:

 * https://github.com/kubernetes/kubernetes/pull/82857
 * https://github.com/kubernetes/kubernetes/pull/82618
 * https://github.com/kubernetes/kubernetes/pull/83025
 * https://github.com/kubernetes/kubernetes/pull/83034

Each of these is marked in the cherry-pick as having a release note.  But each has a parent PR on master marked as `release-note-none`.

If a cherry pick has a release note added (eg: newer information, newer context, newer impact), compared to what was done on master (eg: likely before full awareness of impact and making a choice to cherry pick), then the cherry pick's non-NONE release note must supersede that of the parent PR.

**Comment by saschagrunert** [comment]
Should be fixed with https://github.com/kubernetes/release/pull/902
