### ISSUE TITLE
Prow deployer account needs permission to set storage object ACLs on k8s-staging-release-test GCP

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#904]
The `ci-kubernetes-prototype-build` ([prow run](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-prototype-build/1186940260093792257), [prow build log](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-prototype-build/1186940260093792257/artifacts/build-ci.log), [GCB log](https://console.cloud.google.com/gcr/builds/f1779809-3170-443b-b2e3-2d87c2d3c45a?project=634027639865)) job fails as the prow deployer account (`deployer@k8s-prow.iam.gserviceaccount.com`) does not have permission to set ACLs on storage objects within the `k8s-staging-release-test` project:

```
Step #4: Publish official pointer text files to k8s-staging-release-test...
Step #4: Test v1.17.0-alpha.3.41+5f03d33fc938e7 > ci/latest.txt (published): OK
Step #4: * v1.17.0-alpha.3.41+5f03d33fc938e7 > v1.17.0-alpha.3.41+5f03d33fc938e7 (published),
Step #4: updating
Step #4: 
Step #4: push-build.sh::release::gcs::publish(): mkdir -p /workspace/go/src/k8s.io/kubernetes/_output/release-stage/upload
Step #4: 
Step #4: push-build.sh::release::gcs::publish(): /opt/google/google-cloud-sdk/bin/gsutil -m -h Content-Type:text/plain -h Cache-Control:private, max-age=0, no-transform cp /workspace/go/src/k8s.io/kubernetes/_output/release-stage/upload/latest gs://k8s-staging-release-test/ci/latest.txt
Step #4: Copying file:///workspace/go/src/k8s.io/kubernetes/_output/release-stage/upload/latest [Content-Type=text/plain]...
Step #4: / [0/1 files][    0.0 B/   34.0 B]   0% Done                                    
/ [1/1 files][   34.0 B/   34.0 B] 100% Done                                    
Step #4: Operation completed over 1 objects/34.0 B.                                       
Step #4: Making uploaded version file public: 
Step #4: push-build.sh::release::gcs::publish(): /opt/google/google-cloud-sdk/bin/gsutil acl ch -R -g all:R gs://k8s-staging-release-test/ci/latest.txt
ERROR: (gcloud.builds.submit) build f1779809-3170-443b-b2e3-2d87c2d3c45a completed with status "FAILURE"
Step #4: CommandException: Failed to set acl for gs://k8s-staging-release-test/ci/latest.txt. Please ensure you have OWNER-role access to this resource.
Step #4: FAILED
Step #4: 
Step #4: 
Step #4: Signal ERR caught!
Step #4: 
Step #4: Traceback (line function script):
Step #4: 233 main ../release/push-build.sh
Step #4: 
Step #4: Exiting...
Step #4: 
Step #4: 
Step #4: push-build.sh: DONE main on 6a0eaff8b026 Wed Oct 23 10:31:43 UTC 2019 in 11m36s
Finished Step #4
ERROR
ERROR: build step 4 "gcr.io/k8s-staging-release-test/k8s-cloud-builder" failed: exit status 2
```

The function that sets the object ACL can be found here: https://github.com/kubernetes/release/blob/3998cb9d66d2b2e535716b26871485e91eee9ffa/lib/releaselib.sh#L920-L922

/assign
/area release-eng
/sig-release
/milestone v1.17
/priority important-soon

**Comment by justaugustus** [comment]
Dims, can you help out with this since you've got owner on the `k8s-staging-release-test` project?
/assign @dims

**Comment by thockin** [comment]
The bucket is already world-readable and we have explicitly enabled "bucket-only ACLs", so you can't set per-object perms.   We figured that non-public should be the exception, rather than the rule, for max transparency, and in fact, if I run that gsutil myself, I get the same error (not super helpful either).

 So you can either remove that `acl ch` command or first check whether the file is readable or something.

```
$ gsutil acl get -R -g all:R gs://k8s-staging-release-test/ci/latest.txt
BadRequestException: 400 Cannot get legacy ACL for an object when Bucket Policy Only is enabled. Read more at https://cloud.google.com/storage/docs/bucket-policy-only.
```
