### ISSUE TITLE
Relnotes: Add some basic content linting

### ISSUE THREAD

**Issue by jeefy** [kubernetes/release#910]
Build a linter to check basic misspeillings, backticking of dash dash command line parameters, probably many many other things the rel note wrangler regularly manually does

Copied from https://github.com/kubernetes/community/issues/1971

/cc @tpepper

**Comment by saschagrunert** [comment]
Nobody started working on this after 1 year. I'm closing, we probably have to re-evaluate what we can improve at a later point.
/close
