### ISSUE TITLE
Signing releases with GPG keys

### ISSUE THREAD

**Issue by dims** [kubernetes/release#914]
_From @dims on September 21, 2018 20:58_

I'd like us to sign release artifacts using GPG keys. Here's how other foundations do it:

- https://www.apache.org/dev/release-signing.html
- https://docs.openstack.org/infra/system-config/signing.html
- https://wiki.openstack.org/wiki/OpenPGP_Web_of_Trust
- https://releases.openstack.org/#cryptographic-signatures

Ideally we would build a web of trust including the patch/branch managers and use keys when building the artifacts at the same time as we generate the md5 and sha1/512 manifests. We could have a signing party at kubecon to kick off the web of trust too!

Thanks,
Dims

_Copied from original issue: kubernetes/release#636_

**Comment by justaugustus** [comment]
Migrated to k/release. 
@josiahbjorgaard -- You can drop this from your tracking sheet.

/sig release
/area release-eng
/milestone v1.17
/priority important-soon
/kind feature

**Comment by julianvmodesto** [comment]
As an alternative/option to PGP infra, OpenBSD uses Signify/Minify:

https://www.openbsd.org/papers/bsdcan-signify.html

**Comment by trishankatdatadog** [comment]
Hi everyone,

Out of curiosity, how are k8s release artifacts signed now?

Also, an open-source alternative is [The Update Framework (TUF)](https://theupdateframework.io/) and [in-toto](https://in-toto.io/), which are other CNCF projects. I'm involved in both, and am happy to discuss how to integrate them with k8s. The [Datadog Agent integrations](https://www.datadoghq.com/blog/engineering/secure-publication-of-datadog-agent-integrations-with-tuf-and-in-toto/) uses both to make sure that attacks anywhere between developers and end-users can be detected.

Cc @SantiagoTorres

**Comment by SantiagoTorres** [comment]
big +1, @trishankatdatadog. I think at least signing the release tags on the `kubernetes/kubernetes` repo would be low-hanging fruit to bump the security stance of the releng process:

```
santiago at .../kubernetes ✗ git tag --verify v1.17.2
object 59603c6e503c87169aea6106f57b9f242f64df89
type commit
tag v1.17.2
tagger Anago GCB <nobody@k8s.io> 1579389703 +0000

Kubernetes official release v1.17.2
error: no signature found
````

**Comment by SantiagoTorres** [comment]
So, I take it this is not a concern?

**Comment by trishankatdatadog** [comment]
As mentioned [earlier](https://github.com/kubernetes/release/issues/914#issuecomment-582478954), @SantiagoTorres and I are happy to consult on how to use the TUF and in-toto CNCF sibling projects to secure the building and distribution of k8s binaries...

**Comment by xmudrii** [comment]
@justaugustus Is there any update on this issue? Can we reassign it? I believe that we should move it away from the 1.18 milestone, but I don't have permission to do so.

/remove-lifecycle stale

**Comment by justaugustus** [comment]
We should be able to make some incremental progress in 1.19.
@SantiagoTorres and @trishankatdatadog -- will follow up with you later in the cycle.

> So, I take it this is not a concern?

Santiago, to answer your question, this is absolutely a concern to us, but there are only so many hours in the day.
Our primary focus for the past few cycles has been refactoring the release tooling (https://github.com/kubernetes/release/issues/918, https://github.com/kubernetes/release/issues/852) (to enable further improvements) and migrating to community-owned infrastructure (https://github.com/kubernetes/release/issues/911, https://github.com/kubernetes/release/issues/270).

/milestone v1.19

**Comment by trishankatdatadog** [comment]
> @SantiagoTorres and @trishankatdatadog -- will follow up with you later in the cycle.

Understood: these things take time. We are happy to help, just let us know when you are ready.

Also, we are working with @joshuagl at VMware to [sign all Python packages on PyPI with TUF](https://www.python.org/dev/peps/pep-0458/) 🙂

**Comment by xmudrii** [comment]
This still seems relevant.
/remove-lifecycle stale

**Comment by MarcoR83** [comment]
yes please , fetching all hashes for new releases is a pita. also who tells me that they are correct?

**Comment by trishankatdatadog** [comment]
We're probably gonna go sigstore, no? @dlorenc @justaugustus

**Comment by justaugustus** [comment]
> We're probably gonna go sigstore, no? @dlorenc @justaugustus

Quite possibly! Would love if you and Dan had some time to pop by a RelEng meeting to discuss :)

cc: @kubernetes/release-engineering

**Comment by trishankatdatadog** [comment]
> Quite possibly! Would love if you and Dan had some time to pop by a RelEng meeting to discuss :)

Happy to join anytime, although Dan and @lukehinds can advise better here :)

**Comment by lukehinds** [comment]
I am more than happy to jump on, is the topic marked for discussion on any particular date?

**Comment by saschagrunert** [comment]
The initial draft of the sining KEP is proposed in https://github.com/kubernetes/enhancements/pull/3061

**Comment by justaugustus** [comment]
Closing in favor of https://github.com/kubernetes/enhancements/issues/3031 and https://github.com/kubernetes/release/issues/2227.
/close
