### ISSUE TITLE
[krel] Refactor existing bash scripts into go tools

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/release#918]
The main target is to port the existing bash scripts into golang based versions on top of the existing `krel` command line tool. The scripts should be added as subcommands to `krel` whereas common utilities should be re-used over the whole package.

#### Things to be done
- [x] (@justaugustus) Create initial skeleton of `krel` and `krel ff` (port of `branchff`) - https://github.com/kubernetes/release/pull/869
- [x] (@justaugustus, @saschagrunert ) resolve all `TODO`s in `cmd/krel/ff.go`
  - #938, #939
- [x] (@saschagrunert, @hasheddan) migrate relates notes git package (`pkg/notes/git.go`) into the `pkg/util/git.go` package
    - #920, #936, #937, #942
- [x] refactor utils to contain a dedicated command package (https://github.com/kubernetes/release/pull/922)
- [ ] migrate the bash scripts
    - [x] make a plan in which order the scripts should be ported
    - [ ] `push-build.sh` → `cmd/krel/cmd/push.go`
        - #941, #1105
    - [x] `compile-release-tools`
      - [x] (https://github.com/kubernetes/release/pull/1047) Compile all release tools in `compile-release-tools`
    - [ ] `find_green_build`
        - #1078
    - [x] (@justaugustus - https://github.com/kubernetes/release/pull/1081) drop `gcbmgr` in favor of the [`builder`](https://github.com/kubernetes/test-infra/blob/master/images/builder/main.go) tool
    - [x] `release-notify`
        - #1323, #1315, #1173
    - [x] `changelog-update`
        - #983
    - [x] `relnotes` - use Go implementation from @saschagrunert et al
        - #940, #982, #980, #978, #975, #987, #991, #992, #1003, #1005, #1014, #1023, #1043, #1042, #1044, #1040, #1068, #1075, #1074, #1073, #1072, #1071, #1070, #1069
    - [ ] (@justaugustus / @kubernetes/patch-release-team to supervise) `anago`
        - #1106
- [x] Add integration tests to verify the tooling from a use-case perspective (see https://github.com/kubernetes/release/pull/939#issuecomment-557830439)

Related: https://github.com/kubernetes/release/issues/834, https://github.com/kubernetes/release/issues/959

/cc @justaugustus @hasheddan

**Comment by justaugustus** [comment]
Thanks for opening this! I'm going to come back and shift some things around later as well as drop notes on our [#release-management Slack discussion](https://kubernetes.slack.com/archives/CJH2GBF7Y/p1572605765115500) (ref: https://github.com/kubernetes/release/pull/869#issuecomment-548755283)

/cc @saschagrunert @justaugustus @hasheddan
/milestone v1.18
/priority important-longterm
/kind feature cleanup
/sig release
/area release-eng

**Comment by justaugustus** [comment]
@saschagrunert @hasheddan -- Please work on reconciling `pkg/notes/git.go` into the `pkg/util/git.go` and `krel push` first. Feel free to break up the work however you see fit.

I'll be working on `krel ff`.

**Comment by hasheddan** [comment]
Small nitpick: I am of the opinion that we should try to avoid putting things into a `util` package as it has potential to grow and become bloated with functionality. Currently, the functions in `common.go` seems like a fair candidate to be part of a `util` package (although maybe they could go into a `cli` package or something), but I think the functionality in `pkg/notes/git.go` should likely go into a `pkg/git` package which feels more descriptive. My feelings on this are pretty accurately captured here: https://dave.cheney.net/2019/01/08/avoid-package-names-like-base-util-or-common

**Comment by saschagrunert** [comment]
> Small nitpick: I am of the opinion that we should try to avoid putting things into a `util` package as it has potential to grow and become bloated with functionality. Currently, the functions in `common.go` seems like a fair candidate to be part of a `util` package (although maybe they could go into a `cli` package or something), but I think the functionality in `pkg/notes/git.go` should likely go into a `pkg/git` package which feels more descriptive. My feelings on this are pretty accurately captured here: https://dave.cheney.net/2019/01/08/avoid-package-names-like-base-util-or-common

We have the same mind, please take a look at https://github.com/kubernetes/release/pull/920

**Comment by justaugustus** [comment]
Perfect! This was going to be part of my notes :)

**Comment by saschagrunert** [comment]
What would be the next steps to move forward here? I suggest in finishing the git refactoring (and branch ff adaptions) before porting other scripts. WDYT? Is anyone already working on the git side? (If not, I could)

**Comment by saschagrunert** [comment]
@hoegaarden regarding the release notes tool we could add another `--discover` mode like introduced here: https://github.com/kubernetes/release/commit/532f7dfc5a275ffd2719c3d290e83fae385fa264

**Comment by saschagrunert** [comment]
I think the git package is fine for now, so we can continue to work on `ff.go` where I expect that more methods from there could go into the `git` package.

**Comment by justaugustus** [comment]
Sascha and Dan have this well in hand, so I'm unassigning myself.
Please still tag me for reviews on these PRs though.
/unassign

**Comment by justaugustus** [comment]
anago deprecation announced on k-dev: https://groups.google.com/d/topic/kubernetes-dev/Mhpx-loSBns/discussion

**Comment by saschagrunert** [comment]
> anago deprecation announced on k-dev: https://groups.google.com/d/topic/kubernetes-dev/Mhpx-loSBns/discussion

Alright we should probably start converting anago itself into a krel subcommand. Something like `krel run`? Then krel could call the internal subcommand functions directly...

**Comment by justaugustus** [comment]
> Alright we should probably start converting anago itself into a krel subcommand. Something like `krel run`? Then krel could call the internal subcommand functions directly...

@saschagrunert -- Yep. I'm planning on taking the first pass on the `anago` rewrite before handing it off to y'all for optimizations.

I've begun work on `krel gcbmgr` here: https://github.com/kubernetes/release/pull/1081

**Comment by saschagrunert** [comment]
Update, the `release-notify` part is done with https://github.com/kubernetes/release/pull/1323

**Comment by justaugustus** [comment]
Great progress team!

**Comment by saschagrunert** [comment]
We're pretty far. I created new issues for the rest of the migration:
- https://github.com/kubernetes/release/issues/1445
- https://github.com/kubernetes/release/issues/1446
- https://github.com/kubernetes/release/issues/1452
- https://github.com/kubernetes/release/issues/1459
- https://github.com/kubernetes/release/issues/1460
- https://github.com/kubernetes/release/issues/1461

Let's close this one since it has been open for quite a while and we can split-up the work better
/close
