### ISSUE TITLE
gcbmgr release using python 2.7

### ISSUE THREAD

**Issue by tpepper** [kubernetes/release#932]
I noted the following goes by during our release process using gcbmgr:

```
Step #1: DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
```

We need to move off of python 2.7.

**Comment by hoegaarden** [comment]
- [ ] bump python in our base image (`k8s.gcr.io/kube-cross:v1.13.4-1` currently)
- [ ] ensure we only have python 3 in our image (maybe serverspec, container-structure-test, ... ?)
- [ ] check which python tools we run as part of the release process and if they are python3 compatible
- [ ] run at least one mock staging / release run

**Comment by hoegaarden** [comment]
Currently every debian version's (`sid`, `bullseye`, `buster`, `stretch`) `mercurial` package has a hard dependency on python 2:

```console
sid:       Depends: mercurial-common (= 5.2-1), ucf (>= 2.0020), python2 (<< 2.8), python2 (>= 2.7~), python2:any (<< 2.8), python2:any (>= 2.7~), python:any, libc6 (>= 2.14)
bullseye:  Depends: mercurial-common (= 5.2-1), ucf (>= 2.0020), python2 (<< 2.8), python2 (>= 2.7~), python2:any (<< 2.8), python2:any (>= 2.7~), python:any, libc6 (>= 2.14)
buster:    Depends: mercurial-common (= 4.8.2-1+deb10u1), ucf (>= 2.0020), python (<< 2.8), python (>= 2.7~), python:any (<< 2.8), python:any (>= 2.7~), libc6 (>= 2.14)
stretch:   Depends: libc6 (>= 2.14), python (<< 2.8), python (>= 2.7~), python:any (<< 2.8), python:any (>= 2.7~), ucf (>= 2.0020), mercurial-common (= 4.0-1+deb9u1)
```

However, `mercurial` can be installed on a python3-only system, eg. via `pip3 install mercurial`.

My assumption are:
- that the only (potential) reason we even need `mercurial` is `go get`
- `go get ...` would probably also work with a `pip3 install`ed version of `mercurial`

Therefore, at least for the `mercurial`¹⁾ case, we could just purge all python2 packages and install `mercurial` with `pip3`.


¹⁾ the gcloud sdk and potentially others still need to be checked if they work with python3 only.

**Comment by justaugustus** [comment]
Approach seems sounds. Thanks for tackling this, @hoegaarden!

**Comment by justaugustus** [comment]
Closed via https://github.com/kubernetes/release/pull/934.
/close
