### ISSUE TITLE
gcbmgr release frequently fails at "push git objects"

### ISSUE THREAD

**Issue by tpepper** [kubernetes/release#933]
Lately on patch releases we've had as high maybe 5-30% failure rate in "gcbmgr release" at the "push git objects" step.  Eg:

Today's run of:
```
gcbmgr release --nomock --official release-1.14 --buildversion=v1.14.9-beta.0.44+500f5aba80d712
```

Failed with:
```
Step #1: ================================================================================
Step #1: PUSH GIT OBJECTS  (11/14)
Step #1: ================================================================================
Step #1:
Step #1: Checkout master branch to push objects: OK
Step #1: Pushing tags
Step #1: * v1.14.9: OK
Step #1: * v1.14.10-beta.0: OK
Step #1: Pushing release-1.14 branch: OK
Step #1: Checkout master branch to push objects: OK
Step #1: Rebase master branch: OK
Step #1: Pushing master branch: FAILED
Step #1: [2019-Nov-13 17:50:09 UTC] push_git_objects in 26s
Step #1: FAILED in push_git_objects.
Step #1:
Step #1: RELEASE INCOMPLETE! Exiting...
```

Frequently this does not reproduce.  A second run of the exact same 'gcbmgr release' command usually will succeed, and this was the case for this 1.14 failure above.

Today we also had the 1.16 'gcbmgr release' fail and refuse to continue, noting the v1.16.3 and v1.16.4-beta.0 tags already existed.  This contradicts the above run for 1.14 which failed initially, had pushed tags, yet succeed on re-run despite the existing tags.

Running:
```
git push --delete upstream v1.16.3
git push --delete upstream v1.16.4-beta.0
```
and then re-running the same 'gcbmgr release' command for the 1.16 release then succeeded.

This feels like a race or incomplete error handling, perhaps in GCB, gcbmgr, or maybe even in GitHub API accesses?

**Comment by justaugustus** [comment]
Removing the rotten label so this doesn't pop up again in sweeps.
/remove-lifecycle rotten

I _think_ I'm fine w/ this staying closed.
I believe intermittent failures in accessing GitHub can cause this. We saw something similar in https://github.com/kubernetes/release/pull/1302 / https://kubernetes.slack.com/archives/CJH2GBF7Y/p1589889924258900

**Comment by tpepper** [comment]
I wonder if it's the same root cause as whatever causes a notable amount of cherry picks to not have labels correctly applied?  Eg: I infer some throttling or limit in API usage.

**Comment by tpepper** [comment]
The frequency of this failure has decreased, but now given how we add commits and tags and push them, it is relatively fatal for a build workflow.  See https://github.com/kubernetes/release/pull/1358 and https://github.com/kubernetes/sig-release/issues/1119

**Comment by tpepper** [comment]
And https://github.com/kubernetes/release/pull/1360

**Comment by tpepper** [comment]
SIG decision is to no refactor anago/gcbmgr internals, which means this issue is a dup of https://github.com/kubernetes/release/issues/918
