### ISSUE TITLE
Unify release notes tooling

### ISSUE THREAD

**Issue by hoegaarden** [kubernetes/release#954]
We have a couple of different release notes tools around. Each does slightly different things and some have issues we should fix.

Current tools:
1. https://github.com/kubernetes/release/blob/master/relnotes
    - used in anago, when announcing the patch releases
    - bash, tightly coupled and integrated in k/release bash scripts
    - has some issues
      - `TODO(hoegaarden)`
1. https://github.com/kubernetes/release/tree/master/pkg/notes
    - used in ??? `TODO(hoegaarden)`
    - golang, vendorable(?)
1. https://github.com/kubernetes-sigs/release-notes
    - used for https://relnotes.k8s.io/
    - uses output from 2.)
    - seems to be "only" the frontend, but maybe there's still something useful for us there

Things we need to answer (no particular order):
- Is there an external / existing tool we can leverage?
- What's the difference between 1.) and 2.)? What does the one tool provide that the other one doesn't?
- Can we implement the missing features of 1.) in 2.)?
- Can we switch the release tooling / the patch release announcement to 2.) then?
- Can we make it easy to integrate things with `krel`?

cc: @saschagrunert @justaugustus 
/kind cleanup
/milestone v1.18
/priority important-soon
/area release-eng

**Comment by saschagrunert** [comment]
Hey @hoegaarden, thank you for the detailed summary. Let me try to answer some of the questions:

> * What's the difference between 1.) and 2.)? What does the one tool provide that the other one doesn't?

The second (golang based) implementation is the version which should replace 1.) historically. The tool is actually maintained and is used by the release notes team to manually generate the input for the website (3) and the markdown based release notes draft during the release cycle.

This tool contains fixes like the correct tracking of the PRs on cherry-picked release notes.

> * Can we implement the missing features of 1.) in 2.)?

I already started working on this in https://github.com/kubernetes/release/pull/940. A follow up step would be the right mangling of the markdown documents for a particular release.

> * Can we switch the release tooling / the patch release announcement to 2.) then?

I really hope so :pray: 

Relates to: https://github.com/kubernetes/release/issues/918, https://github.com/kubernetes/release/issues/834
