### ISSUE TITLE
Consider adapting krel ff for docs release workflow

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/release#956]
The docs release team is considering updating their workflow.
As part of the release cycle the docs team will merge master -> into the current dev-vX.Y branch. This action is done by hand by the current release team docs lead and is very similar to the workflow done by `krel ff`. 

The other alternative being looked into is instead switching to a rebase based workflow with the changes slated for 1.17 being rebased on top of master closer to the end of the release cycle.

Either way, it'd be worth having a discussion about a workflow improvement 👍 

/area release-eng
/kind feature
/priority important-longterm

**Comment by justaugustus** [comment]
@mrbobbytables -- Thanks for following up on our convo so quickly!

Adding SIG Docs Chairs, so they can add comments and stay abreast:
cc: @zacharysarah @Bradamant3 @jimangel

**Comment by zacharysarah** [comment]
@mrbobbytables This sounds excellent. Anything that reduces release cycle pain is a welcome improvement.

**Comment by justaugustus** [comment]
Do y'all want to come to the Release Engineering meeting this Monday, 11am US ET and we can kick around the idea a little?

cc: @kubernetes/release-engineering for visibility

**Comment by zacharysarah** [comment]
I'm happy to. Can we please get invitations for myself and @jimangel @Bradamant3 @bradtopol  @kbarnard10?

**Comment by jimangel** [comment]
This release (1.17) has had some unlucky snags. It sounds like this would improve the process! +1 Thanks @mrbobbytables!

**Comment by justaugustus** [comment]
> I'm happy to. Can we please get invitations for myself and @jimangel @Bradamant3 @bradtopol @kbarnard10?

@zacharysarah -- Sent and added to the [Releng agenda](http://bit.ly/k8s-releng-meeting) for 12/9!

**Comment by bradtopol** [comment]
Thanks! Looking forward to it!
 
--Brad
  
Brad Topol, Ph.D.IBM Distinguished Engineer 
Open Technology & Developer AdvocacyKubernetes Contributor and Conformance Workgroup Member(919) 543-0646Internet: btopol@us.ibm.comAssistant: Andrea Retana (404) 527-8260 x8615 
 
 
----- Original message -----From: Stephen Augustus <notifications@github.com>To: kubernetes/release <release@noreply.github.com>Cc: Brad Topol <btopol@us.ibm.com>, Mention <mention@noreply.github.com>Subject: [EXTERNAL] Re: [kubernetes/release] Consider adapting krel ff for docs release workflow (#956)Date: Fri, Dec 6, 2019 9:02 PM 
I'm happy to. Can we please get invitations for myself and @jimangel @Bradamant3 @bradtopol @kbarnard10?
@zacharysarah -- Sent and added to the Releng agenda for 12/9!

**Comment by saschagrunert** [comment]
Sounds generally good to me, do we have a short abstract of the workflow written down somewhere?

Is it all about this: https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/docs#middle-steps-weeks-3-8 (_Maintain the current and upcoming dev / release branches_)? 

If so, we could create a dedicated subcommand `krel docs ...` to not overlap features to much.

**Comment by irvifa** [comment]
Hi @mrbobbytables is this still WIP or there's already a tools that can be used to sync up the current dev-1.8? If it's not ready when is the ETA for this automation? Best.

**Comment by jimangel** [comment]
Hey @irvifa, we chatted on slack but wanted to comment here too. It's a WIP with the goal of completing this release cycle.

**Comment by zacharysarah** [comment]
Any update on this? 🤞

**Comment by jimangel** [comment]
I have chatted offline with a few folks. I'm going to move this issue to [another one](https://github.com/kubernetes/release/issues/1204) for tracking with a larger scope.

/close
