### ISSUE TITLE
Add a --print command for release-notify

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#958]
Using [release-notify](https://github.com/kubernetes/release/blob/3dc0ff39a4a1989b24a37c2f407dbfec435c59ff/release-notify) currently requires [`sendmail` to be configured on the computer/image a Release Manager is using to cut a release](https://github.com/kubernetes/sig-release/blob/c0fe6a291e21f07dcae77a4d08f962d5bd75f8df/release-engineering/role-handbooks/branch-manager.md).

I personally don't use `sendmail`, nor do I think it should be a requirement to configure.
Instead, I grab the HTML and subject for the announcement and send it directly from my email account (Gmail).

Without fail, I forget exactly where these are located and spend a few minutes digging around in GCS buckets to find them.
Here's an example of each:
- Subject: https://gcsweb.k8s.io/gcs/kubernetes-release/archive/anago-v1.17.0-rc.2/announcement-subject.txt
- Announcement: https://gcsweb.k8s.io/gcs/kubernetes-release/archive/anago-v1.17.0-rc.2/announcement.html

It'd be great if `release-notify` supported a `--print` command, which did two things:
1. Display the locations on GCS of the announcement subject and body
2. Output the content of each, so I can easily copy and paste it into an email

/help @kubernetes/release-engineering 
/sig release
/area release-eng
/kind feature
/priority important-soon
/milestone v1.18

**Comment by hoegaarden** [comment]
> I personally don't use `sendmail`, nor do I think it should be a requirement to configure.

Agreed!
I think https://github.com/kubernetes/release/issues/959#issuecomment-563234388 is also helpful in this context.

I think adding a `--print` option or so would be fine, as long as we agree that that's not the end goal. Also, it should be fairly easy (where easy has sometimes special meaning in the context of `k/release` 😏) to introduce such a thing.

----

Some side-notes:
- you don't necessarily need "the `sendmail`", any "standard MTA" should do.
- I use a container image to run all the release things in. This container comes with `ssmtp` which is configured to send through my company's mail servers. Works well. 🤷‍♂

**Comment by justaugustus** [comment]
> as long as we agree that that's not the end goal

Absolutely! This is simply meant to be a convenience function.

As for your container image, could you add it to the repo? I've opened https://github.com/kubernetes/release/issues/960 for that.
