### ISSUE TITLE
Should release-notify script send from GCB?

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/release#959]
(Follow-up item from https://github.com/kubernetes/sig-release/issues/696)
ref: https://github.com/kubernetes/sig-release/pull/666#discussion_r296540312

cc: @hoegaarden @tpepper @kubernetes/patch-release-team 

/help
/sig release
/area release-eng
/milestone v1.18
/priority important-longterm
/kind feature

**Comment by hoegaarden** [comment]
> Should release-notify script send from GCB?

Yes, I think it should.

Directly sending does not work, however sending mails via sendgrid works (other services will most probably work too, but that's what I have been using eg. in #949).

From what I can see, things we'd need to make this a reality:
- a sendgrid account
- a sendgrid secret in GCB (similar to the already existing one for the GitHub token)
- changes to the notify script to run on GCB and not locally

**Comment by justaugustus** [comment]
@hoegaarden -- Since you've already been working on this, I'm assigning you. Let's see if we have time in the releng meeting today to discuss.

/assign @hoegaarden 
/remove-help

**Comment by hoegaarden** [comment]
To add some context here:
Sending mails is not directly possible from a GCP instance because the default smtp port is blocked. There are some workarounds and alternatives. Using a service like sendgrid seems to be the easiest.

See also:
- https://cloud.google.com/compute/docs/tutorials/sending-mail/
- https://cloud.google.com/cloud-build/docs/configure-third-party-notifications

**Comment by justaugustus** [comment]
I signed up for a Sendgrid account for this a while back, but it hasn't been high-priority.
Will try to close the loop on this this cycle.

/assign

**Comment by saschagrunert** [comment]
@justaugustus is this still relevant to us? Manually announcing the release seems a legit step to me.

**Comment by saschagrunert** [comment]
Closing because I guess the process we're using right now is a great fit. I do not see a necessity to announce directly from krel.
/close
