### ISSUE TITLE
Running `make test-go` fails on Darwin

### ISSUE THREAD

**Issue by hoegaarden** [kubernetes/release#961]
This is the error I get:

```gotest
=== RUN   TestFailurePipeWrongArgument
2019/12/10 10:30:23 Running command: /bin/echo -n hi | /bin/cat --wrong
2019/12/10 10:30:23 unable to copy command stderr
--- FAIL: TestFailurePipeWrongArgument (0.01s)
    command_test.go:58:
                Error Trace:    command_test.go:58
                Error:          "" does not contain "unrecognized option"
                Test:           TestFailurePipeWrongArgument
```

Related: https://github.com/kubernetes/release/pull/942#issuecomment-558707516

/assign @saschagrunert 
/priority important-longterm

**Comment by saschagrunert** [comment]
Interesting, does this happen every time? It looks like that the pipe copy failed with `unable to copy command stderr`.

**Comment by hoegaarden** [comment]
1. Happens (in one of the forms outlined further down) all the time
1. BSD `cat` behaves differently than GNU `cat`, see further down. This hits here, because this is not an isolated test, it depends on the outside world.
1. I consistently see slightly different behaviour in running `make test-go` & plain `go test ./...`, which I guess is good because it means the make target finds more or different issues than plain `go test ./...`. (In the make target we in the end run `GO111MODULE=on go test -v -race -count=1 ./...` from the root of the repo)
1. Why do we need `Pipe` method in the command package anyway? Do we have a use-case for that? Do we really want to implement and maintain that ourselves? Do we really want to diverge that far from `exec`?
I totally get that this is an interesting problem to tackle, but is it worth it doing that in `k/release`?
To be honest, it is still not really clear to me why we need the `command` package at all / in that form, why we introduce different & incompatible types to the types in `exec` and ones which behave quite differently then the `exec.Cmd` (e.g. by default wiring StdIO). Please don't get me wrong, if you think there is a use-case or some benefit for that, by all means, go ahead! Chances are good I am just do blind to  see those. 🤷‍♂I just wanted to call out that I have troubles understanding what we are up to here.

----

```shell
→ cat --wrong # running the BSD cat that ships with MacOS
cat: illegal option -- -
usage: cat [-benstuv] [file ...]

→ gcat --wrong # running a brew-installed GNU cat
gcat: unrecognized option '--wrong'
Try 'gcat --help' for more information.

→
```

----

```shell
→ make test-go 2>&1 | sed -n '/=== RUN   TestFailurePipeWrongArgument/,/=== RUN/p'
=== RUN   TestFailurePipeWrongArgument
2019/12/10 11:25:19 unable to copy command stderr
2019/12/10 11:25:19 Running command: /bin/echo -n hi | /bin/cat --wrong
2019/12/10 11:25:19 unable to copy command stderr
--- FAIL: TestFailurePipeWrongArgument (0.00s)
    command_test.go:58:
                Error Trace:    command_test.go:58
                Error:          "" does not contain "unrecognized option"
                Test:           TestFailurePipeWrongArgument
=== RUN   TestSuccessWithWorkingDir

→ go test -v ./... 2>&1 | sed -n '/=== RUN   TestFailurePipeWrongArgument/,/=== RUN/p'
=== RUN   TestFailurePipeWrongArgument
2019/12/10 11:25:32 unable to copy command stdout
2019/12/10 11:25:32 unable to copy command stderr
2019/12/10 11:25:32 Running command: /bin/echo -n hi | /bin/cat --wrong
cat: illegal option -- -
usage: cat [-benstuv] [file ...]
2019/12/10 11:25:32 unable to copy command stderr
--- FAIL: TestFailurePipeWrongArgument (0.00s)
    command_test.go:58:
                Error Trace:    command_test.go:58
                Error:          "cat: illegal option -- -
                                usage: cat [-benstuv] [file ...]
                                " does not contain "unrecognized option"
                Test:           TestFailurePipeWrongArgument
=== RUN   TestSuccessWithWorkingDir

→ go test -v -test.parallel=1 ./... 2>&1 | sed -n '/=== RUN   TestFailurePipeWrongArgument/,/=== RUN/p'
=== RUN   TestFailurePipeWrongArgument
2019/12/10 11:28:55 Running command: /bin/echo -n hi | /bin/cat --wrong
cat: illegal option -- -
usage: cat [-benstuv] [file ...]
--- FAIL: TestFailurePipeWrongArgument (0.00s)
    command_test.go:58:
                Error Trace:    command_test.go:58
                Error:          "cat: illegal option -- -
                                usage: cat [-benstuv] [file ...]
                                " does not contain "unrecognized option"
                Test:           TestFailurePipeWrongArgument
=== RUN   TestSuccessWithWorkingDir

→ go test -v -race -test.parallel=1 ./... 2>&1 | sed -n '/=== RUN   TestFailurePipeWrongArgument/,/=== RUN/p'
=== RUN   TestFailurePipeWrongArgument
2019/12/10 11:29:40 unable to copy command stderr
2019/12/10 11:29:40 Running command: /bin/echo -n hi | /bin/cat --wrong
2019/12/10 11:29:40 unable to copy command stderr
--- FAIL: TestFailurePipeWrongArgument (0.01s)
    command_test.go:58:
                Error Trace:    command_test.go:58
                Error:          "" does not contain "unrecognized option"
                Test:           TestFailurePipeWrongArgument
=== RUN   TestSuccessWithWorkingDir

→
```

**Comment by saschagrunert** [comment]
> 1. Happens (in one of the forms outlined further down) all the time
> 2. BSD `cat` behaves differently than GNU `cat`, see further down. This hits here, because this is not an isolated test, it depends on the outside world.

Yeah, depends on how far we wanna go here. We could provide our own little golang binary and use it for testing. Then we pre-build it and have expected output on every machine, WDYT? (I could follow-up with that).

> 4. Why do we need `Pipe` method in the command package anyway? Do we have a use-case for that? Do we really want to implement and maintain that ourselves? Do we really want to diverge that far from `exec`?
>    I totally get that this is an interesting problem to tackle, but is it worth it doing that in `k/release`?
>    To be honest, it is still not really clear to me why we need the `command` package at all / in that form, why we introduce different & incompatible types to the types in `exec` and ones which behave quite differently then the `exec.Cmd` (e.g. by default wiring StdIO). Please don't get me wrong, if you think there is a use-case or some benefit for that, by all means, go ahead! Chances are good I am just do blind to  see those. man_shruggingI just wanted to call out that I have troubles understanding what we are up to here.

From my point of view golang is not very good in abstraction, which means if we remove the command package we would have a lot of repeating overhead in files like `ff.go`. I think we should provide an easy to use interface for people who want to add functionality on top of krel, without distracting them by things like _pipes_.

**Comment by hoegaarden** [comment]
> Yeah, depends on how far we wanna go here. We could provide our own little golang binary and use it for testing. Then we pre-build it and have expected output on every machine, WDYT? (I could follow-up with that).

Let's not spend too much time on that and over-engineer it. I don't consider that critical right now.

However, maybe in future, if we'd want isolated tests, one way we could do that is:
- Trust that stuff in `exec` does the right thing, don't test that, test the interaction with `exec`
- In the production code, use something like `k8s.io/utils/exec` instead of the stuff from `exec` (e.g. use `k8s.io/utils/exec/Cmd` instead of `exec.Cmd`). In order words, use an executor that is an interface and not a concrete type.
- In the tests fake out all `Exec`s, `Cmd`s and related things. Either use stuff from `k8s.io/utils/exec/testing` or use your favourite test fakes generator (e.g. counterfeiter)
- In the tests do assertions on which things have been passed into the fake by calling it's methods or fake out things the fake returns when it's called

**Comment by justaugustus** [comment]
> Let's not spend too much time on that and over-engineer it. I don't consider that critical right now.

+1. This is low-priority in the grand scheme of things.

**Comment by saschagrunert** [comment]
Can we close this issue? The darwin unit test fix should be done. :)
