### ISSUE TITLE
[testgridshot] Print comment, even if no failing dashboards where found?

### ISSUE THREAD

**Issue by hoegaarden** [kubernetes/release#965]
When `testgridshot` does not find any failing dashboard it just prints
```shell
# ./testgridshot 1.14
2019-12-11 14:28:34+0000 No screenshots captured for 1.14 ... ‾\_(ツ)_/‾
#
```
but does not generate a c&p-able issue comment.

Questions:
- Should we still print the issue comment but with a message like `NO FAILING BOARDS`, to signal & capture that we've ran the tool and actually didn't find any failing tests? (see: https://github.com/kubernetes/sig-release/issues/888#issuecomment-564460178)
- Should we fallback to searching for `FLAKY` boards in case no `FAILING` boards are found? This might be weird when users run the tool with specific states they are interested in (`STATES='...' ./testgridshot 1.14`) 

/kind design
/priority important-longterm

**Comment by justaugustus** [comment]
I'm fine with something like "NO FAILING BOARDS".
