### ISSUE TITLE
swagger.json for patch releases 1.16.4, 1.15.7, 1.14.10 has the wrong verison

### ISSUE THREAD

**Issue by rtheis** [kubernetes/release#968]
`api/openapi-spec/swagger.json` in patch releases 1.16.4, 1.15.7, 1.14.10 has the wrong verison.

- 1.16.4 uses version 1.16.5: https://github.com/kubernetes/kubernetes/commit/224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba
- 1.15.7 uses version 1.15.8: https://github.com/kubernetes/kubernetes/commit/6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4
- 1.14.10 uses version 1.14.11: https://github.com/kubernetes/kubernetes/commit/575467a0eaf3ca1f20eb86215b3bde40a5ae617a

**Comment by rtheis** [comment]
@justaugustus

**Comment by justaugustus** [comment]
/priority important-soon
/kind bug
/milestone v1.18

ref: https://github.com/kubernetes/kubernetes/pull/84654

**Comment by justaugustus** [comment]
cc: @tpepper @liggitt 
Slack thread: https://kubernetes.slack.com/archives/C2C40FMNF/p1576091971464500

**Comment by tpepper** [comment]
Looking for example at release-1.16 build logs for Nov. and Dec. patch releases v1.16.3 and v1.16.4 respectively there is a difference.

This error did not happen in the Nov. 2019 patch release v1.16.3 which shows in `./gcbmgr tail 17f4383a-cbac-4fa1-913a-548da949693c`:
```
Step #2: ================================================================================
Step #2: PREPARE AND TAG TREE official (5/6)
Step #2: ================================================================================
Step #2:
Step #2: Checking out release-1.16 (release-1.16): OK
Step #2: Tagging Kubernetes official release v1.16.3 on release-1.16: OK
Step #2: [2019-Nov-13 10:48:54 UTC] prepare_tree in 2s
Step #2:
Step #2: ================================================================================
Step #2: TAG/BUILD LOCAL KUBE CROSS  (6/6)
Step #2: ================================================================================
Step #2:
Step #2: Checking if k8s.gcr.io/kube-cross:v1.12.12-1 exists locally: OK
Step #2: Tagging docker image k8s.gcr.io/kube-cross:v1.12.12-1 as k8s.gcr.io/kube-cross:local: OK
Step #2: [2019-Nov-13 10:48:54 UTC] local_kube_cross in 0s
Step #2:
Step #2: ================================================================================
Step #2: PREPARE AND TAG TREE beta (5/6)
Step #2: ================================================================================
Step #2:
Step #2: Checking out release-1.16 (release-1.16): OK
Step #2: Skipping federation/apis/openapi-spec/swagger.json...
Step #2: Committing openapi-spec versioned files: OK
Step #2: Tagging Kubernetes beta release v1.16.4-beta.0 on release-1.16: OK
```

That is:

 * tag v1.16.3
 * commit openapi-spec versioned files
 * tag v1.16.4-beta.0

The error did happen in today's Dec. 2019 patch release v1.16.4 which shows in `./gcbmgr tail 8eba3568-d17a-4f81-9388-ea1d3b5cb3d0`:
```
Step #2: ================================================================================
Step #2: PREPARE AND TAG TREE beta (5/6)
Step #2: ================================================================================
Step #2:
Step #2: Checking out release-1.16 (release-1.16): OK
Step #2: Skipping federation/apis/openapi-spec/swagger.json...
Step #2: Committing openapi-spec versioned files: OK
Step #2: Tagging Kubernetes beta release v1.16.5-beta.0 on release-1.16: OK
Step #2: [2019-Dec-11 12:11:07 UTC] prepare_tree in 2s
Step #2:
Step #2: ================================================================================
Step #2: TAG/BUILD LOCAL KUBE CROSS  (6/6)
Step #2: ================================================================================
Step #2:
Step #2: Checking if k8s.gcr.io/kube-cross:v1.12.12-1 exists locally: OK
Step #2: Tagging docker image k8s.gcr.io/kube-cross:v1.12.12-1 as k8s.gcr.io/kube-cross:local: OK
Step #2: [2019-Dec-11 12:11:07 UTC] local_kube_cross in 0s
Step #2:
Step #2: ================================================================================
Step #2: PREPARE AND TAG TREE official (5/6)
Step #2: ================================================================================
Step #2:
Step #2: Checking out release-1.16 (release-1.16): OK
Step #2: Tagging Kubernetes official release v1.16.4 on release-1.16: OK
```

That is:

 * commit openapi-spec versioned files
 * tag v1.16.4-beta.0
 * tag v1.16.3
 
This is out of order.

I'm not seeing any changes in the past month on k/release that touch any of this gcbmgr, LAST_RELEASE, gitlib::last_releases, anago, rev_openapi_versions, or VER_REGEX code.

**Comment by tpepper** [comment]
prepare_tree() at https://github.com/kubernetes/release/blob/9faaf9c7678f711ab9c3b52919937b9ac889087a/anago#L646 today is overly complex.  The stateful, reentrant functions hold so many varying behaviors depending on the state of the global variables and arguments and prior calls to the functions that it's not obvious what's happening.  This function in the past did a mix of applying multiple tags and multiple different commits.

We really need to cleanly automate the desired branch management and patch release workflows instead of having those workflows attempting to run a script which does something different than today's intended workflow, and via what has become overly complex bash relative to required functionality.
