### ISSUE TITLE
Release notes generator conflicts with GitHub API abuse detection

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/release#979]
GitHub blacklisted me during development because the gatherer implementation seems to trigger the GitHub API abuse detection:

```
> go run cmd/release-notes/main.go --branch release-1.17 --start-rev v1.16.0 --end-rev v1.17.0
...
INFO starting to process commit 254 of 2682 (9.47%): c213196f0a8ab8b997d145db8a50c00cd4ec211c
INFO starting to process commit 255 of 2682 (9.51%): e24f5ab4e45e120158f64ee6b0e489577fba915a
INFO starting to process commit 256 of 2682 (9.55%): 19b4017b5d5c5695403a9804f5ea3de11a436c04
INFO starting to process commit 257 of 2682 (9.58%): e434d2dbab16288782af369e5891e671095af491
FATA retrieving release notes: listing release notes: GET https://api.github.com/repos/kubernetes/kubernetes/commits/796faba4ac96db07194c4811585abe52fd682064/pulls?page=1&per_page=100&state=closed: 403 You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.
exit status 1
```

@hoegaarden do you think we can somehow limit the gatherer usage? I'm not sure what the limits are.

**Comment by hoegaarden** [comment]
Thanks for the report, @saschagrunert!
I looked at the implementation of the github package superficially and thought it would handle the rate limit responses and hold requests if they'd hit the thresholds. Obviously I was wrong on that. I also hit the API quite hard while testing and never had an issue.
Anyway, I will check asap on that!

**Comment by hoegaarden** [comment]
- A first quick fix has been implemented in #984 
- I am still checking on a better long-term solution (see also the comments/discussion in #984)

**Comment by justaugustus** [comment]
/assign @saschagrunert 
(to add details and close out)

**Comment by saschagrunert** [comment]
@hoegaarden I think we're fine with our current solution. I did a more detailed research and think we should keep the current implementation, because: If we would know the exact limits for the API rates, what would be the resulting action? We would still have to wait and retry… :man_shrugging: 

Closing, feel free to reopen if I missed anything.
